### ISSUE TITLE
Safari overlapping images

### ISSUE THREAD

**Issue by stephenstroud** [desandro/masonry#1001]
Google Chrome works nicely however Safari is over lapping. Source code used: 

<script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>
<script src="https://unpkg.com/imagesloaded@4/imagesloaded.pkgd.min.js"></script>

<script>
    var grid = document.querySelector('.js-masonry-grid');
    $('#js-masonry-grid').imagesLoaded()
         .always(function (instance) {
          //   console.log('all images loaded');
         })
         .done(function (instance) {
                       var msnry = new Masonry(grid, {
                             itemSelector: '.js-masonry-grid-item',
                             percentPosition: true
                         });
         })
         .fail(function () {
             //console.log('all images loaded, at least one is broken');
         })
         .progress(function (instance, image) {
             var result = image.isLoaded ? 'loaded' : 'broken';
          //   console.log('image is ' + result + ' for ' + image.img.src);
         });

</script>

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues).

**Comment by joshcanhelp** [comment]
I was seeing this issue on Chrome, Safari, and IE but intermittently. It only happened on the first load and when I resized it would correct itself. Different images each time, when it happened. I noticed that the overlapped images were a specific height each time, figured that Masonry was called before the images loaded. 

Added a timeout like:

```javascript

setTimeout( function () {
            $( '.gallery' ).masonry( {
                itemSelector : '.gallery-item',
                columnWidth : '.gallery-item',
                percentPosition : true,
                gutter : 10
            } );
        }, 1000 );

```

... and not seeing this issue anymore. Our galleries are typically down the page a bit so not a big impact on experience.

**Comment by desandro** [comment]
My recommended solution is to use imagesLoaded then trigger layout again on window load.

``` js
var $grid = $('.grid').masonry({
  // options...
});

// trigger after images loaded
$grid.imagesLoaded( function() {
  $grid.masonry();
});

// trigger on window load
$( window ).load( function() {
  $grid.masonry();
});
```

**Comment by joshcanhelp** [comment]
@desandro - Works like a charm, thank you!
