### ISSUE TITLE
Sorting and searching, 2 in 1, maybe?

### ISSUE THREAD

**Issue by evstun** [desandro/masonry#1002]
Good day! And you can combine filter and search at the same time? What you could first filter, and then to use search?

I did, but maybe something is not right! If I press the sort button and then use the search field, nothing happens. Refreshes the page, use the search and the search works!

Conversely, if I first use the search box, and then click the sort button, the sorting comes from just the content and not the filtered search!

Tell me, is there any way to fix it?

sincerely, Alexander

**Comment by desandro** [comment]
See [Search & filter buttons demo](https://codepen.io/desandro/pen/mCdbD) for Isotope.
