### ISSUE TITLE
2 Stamps and responsive not working on stamp-2

### ISSUE THREAD

**Issue by p-drolima** [desandro/masonry#1003]
Hi,

I hope you can help resolve this issue. Thanks in advanced.

Steps to replicate:

320px width, refresh and stamp 2 won't push down the first grid-item.

**Test case:** http://staging.punktastic.com/the-pickup/

**Comment by desandro** [comment]
It looks like you may have an issue with [unloaded images](https://masonry.desandro.com/layout.html#imagesloaded)
