### ISSUE TITLE
Issue with responsive grid layout on chrome and edge

### ISSUE THREAD

**Issue by NMorgana** [desandro/masonry#1005]
I'm trying to apply the masonry plugin (vanilla js) in the correct way and facing an issue where elements are stacking on top of each other. The masonry grid looks fine on Firefox, but not in Google Chrome nor Edge. I've tried to init the script by placing it directly into the document with window onload function, but the problem still persists. Changing the size of the elements width did not make a difference neither. The function gets initiated together with the scrollReveal.

link where problem reproduce: http://mandalaviajes.cl/testimonios

Above all, thank you for this great script!

**Comment by 1-2-1** [comment]
Hello,
I was just searching to resolve an issue with elements disappearing after about being displayed for 10 minutes (disappearance is rather random as to which and how many elements vanish),... but anyway, I saw this post (below) which may help solve your issue.


https://masonry.desandro.com/layout.html#imagesloaded


Regards

**Comment by NMorgana** [comment]
Thanks! but it seem that I have already solved the issue. The problem appeared to be my in my CSS stylesheet where I had the margin at "0 auto" under the *, which caused the grid to stack up. By adding "margin: 0" to the gutter, the problem got resolved.

**Comment by 1-2-1** [comment]
Awesome to hear! :-)
