### ISSUE TITLE
Download link doesn't download

### ISSUE THREAD

**Issue by Matthew-McDonald** [desandro/masonry#1007]
Maybe I am doing something wrong, but the download links for masonry.pkgd.min.js and masonry.pkgd.js on the https://masonry.desandro.com/ site just open up the source code in another tab instead of downloading a file. Am I supposed to copy the source code into my own file?

**Test case:** http://codepen.io/desandro/pen/osFxj

**Comment by desandro** [comment]
Thanks for reporting this issue. I realize this a little bit confusing. In my experience, I prefer opening the source code. This provides two options: you can either save the file via your browser, or you can copy/paste the URL to use for CDN.
