### ISSUE TITLE
Masonry container height - need to set to auto on infinite scroll

### ISSUE THREAD

**Issue by ianmoise** [desandro/masonry#1009]
I am sorry I am not submitting a reduced test case - I'm not sure how to modify your code pens to include infinite scroll, which is part of my problem. I am describing the bug here and hope you are intrigued to figure it out. If not, no worries and thanks for your time. 

You can see the issue in action on our production site (kuttlefish.com/default/editorspicks) - I know you advised against providing production links but I want you to see what I describe - by reducing the screen width to less than 500px and triggering the infinite scroll several times. This is easy to do if you are viewing the site on your mobile phone.  Here is the description:

I have a bunch of tiles I am displaying in a masonry container with infinite scroll. It all works fine and the infinite scroll triggers when I get to the bottom. HOWEVER, when I reduce my screen width to less than 500px, the width of the tiles start to reduce; consequently, I use CSS to reduce the height of the tiles as well to maintain proportion. The problem is that the masonry container uses the original tile height for its calculation of the height of the container. The result: after triggering 1 or 2 infinite scrolls, there is a large white space at the bottom. And then you have to scroll through the entire white space before the infinite scroll will trigger again.

Thanks for any help.

**Comment by desandro** [comment]
I can't open that page. Sorry, I don't think I'll be able to help here.
