### ISSUE TITLE
Resize Problems

### ISSUE THREAD

**Issue by dhruvangg** [desandro/masonry#1012]
In Touch Devices, On Screen Rotate, It shows some Issues, In Vertical Screen there are 3 grid columns, and In Horizontal, it is 2. So When i rotate screen Horizontal to vertical it remains 2 column and right side is blank

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues).
