### ISSUE TITLE
Footer issue Internet Explorer

### ISSUE THREAD

**Issue by agostinijoerg** [desandro/masonry#1013]
Hi there
First and foremost, thanks a lot for your awesome tool!

I tried to recreate my issue with codepen, but didn't get far (bit of a newbie).
Anyway, my problem is regarding a rendering issue in Explorer 11 (and lower). I'm using your imageloader to get the images preloaded before masonry js gets activated. It all works fine in any other browser, but in Explorer after masonry js get activated my footer moves to the top and underneath my masonry posts. 

https://ridershotel.com/agenda/

It would be great if you would be able to point me in the right direction.
Thanks a lot
Joerg

**Comment by desandro** [comment]
Sorry, I won't be able to provide support on this issue.
