### ISSUE TITLE
Grid Breaks with new Chrome Version 62.0.3202.94

### ISSUE THREAD

**Issue by mnoesel** [desandro/masonry#1014]
With the latest version of Chrome the masonry grid breaks on certain browser widths!

Watch here (with Chrome v62):
http://wp11052791.server-he.de/mnoesel/

How can I fix this????? Any advice?

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues).
