### ISSUE TITLE
Arranging Issues

### ISSUE THREAD

**Issue by sumanthsrao** [desandro/masonry#1015]
The arrangement is not working for some of cases. Can you please look into this and let me know the issues on how to use.

**Test case:** https://codepen.io/ssrao/pen/WXaJoL

Also my requirement is I am having n fixed containers. I need to move the fitting pieces into different containers effectively. All the elements from One base container to move to multiple fixed width, height containers dynamically.

Appreciate your response...

**Comment by desandro** [comment]
Sounds like you want to use [Packery, which fills gaps that Masonry may leave open](https://packery.metafizzy.co). See demo https://codepen.io/desandro/pen/052c5dba79945444d9cbc0d708f53980/
