### ISSUE TITLE
col-xs-6 columns are not in 1 row

### ISSUE THREAD

**Issue by meijdenmedia** [desandro/masonry#1017]
I already posted this issue on Stackoverflow a couple of days ago but didn't get any response. I hope one of you guys can help me out.

There are 3 columns: 1 x `col-md-6 col-sm-12`, 2 x `col-sm-6`. When I make my window smaller the two `col-sm-6` columns are placed under the `col-sm-12` column. But instead of displaying them next to each other they are displayed underneath each other.The issue appears `< 992px` wide screen.

**Test case:** https://codepen.io/joost-developer/pen/jaQOMG

**Comment by desandro** [comment]
Thanks for reporting this issue.

So there are two column widths we need to account for: 1/3 size, and 1/2 size. Masonry's `columnWidth` needs to fit both, which would be 1/6. So I changed the `sm` class to `col-sm-2`.

See demo https://codepen.io/desandro/pen/3d5bf74c0af70499056faf42463d07d2/?editors=1000
