### ISSUE TITLE
Masonry not initialized

### ISSUE THREAD

**Issue by federicovilla** [desandro/masonry#1019]
In my project (Admin image panel) I need to add and remove images using AJAX from a server using a Masonry page
Using the code in the Test case I get an error when I add an image, the error is:"masonry not initialized", even if the image is uploaded into the server and appended to Masonry.
I tried to modify the following line in JS
`jQuery(".masonry").append($content).masonry( 'appended', $content );`
into
`jQuery(".masonry").append($content);`
Doing so the error has gone and the image is correctly uploaded into the server and appended to the Masonry; so I'm wondering what could be the issue removing 
`.masonry( 'appended', $content );` 
from the code.

I tried to fix the issue initializating masonry by jQuery, using:
`$('.masonry').masonry({
  itemSelector: '.masonry-item',
  columnWidth: '.masonry-item',
  percentPosition: true
});`

but in the case above Maosnry page looks totally messed up, no Masonry effects on images.

Thanks for any help to figure out the best way to add/remove image from Masonry by AJAX 

**Test case:** https://codepen.io/Vespa/pen/dZxrby

**Comment by desandro** [comment]
Were you able to resolve this issue?

**Comment by federicovilla** [comment]
Thanks for feedback desandro and sorry if I didn't close before the post. Yep..fixed.
