### ISSUE TITLE
Masonry items overlap

### ISSUE THREAD

**Issue by sharifzadesina** [desandro/masonry#1022]
It some times fails like this:
![screenshot from 2017-12-22 23-06-18](https://user-images.githubusercontent.com/15300551/34310469-fd808b04-e76c-11e7-88dd-f6701b9b81b8.png)
But it always should be like this:
![screenshot from 2017-12-22 23-07-00](https://user-images.githubusercontent.com/15300551/34310482-0bb8d14a-e76d-11e7-9fe5-f391f25a62e9.png)

My script:

```js
window.imagesLoaded = require('imagesloaded');
window.Masonry = require('masonry-layout');
window.InfiniteScroll = require('infinite-scroll');

InfiniteScroll.imagesLoaded = imagesLoaded;
```

```js
var msnry = new Masonry('.posts-grid', {
    itemSelector: '.posts-grid-item',
    originLeft: false
});
var infScroll = new InfiniteScroll('.posts-grid', {
    path: '.pagination__next',
    hideNav: '.pagination',
    append: '.posts-grid-item',
    status: '.posts-scroller-status',
    history: false,
    outlayer: msnry,
    elementScroll: 'main'
});
```

**Comment by sharifzadesina** [comment]
It seems this is cause of a bug in `imagesloaded` package or `infinite-scroll`.
I've fixed it by this code:
```js
infScroll.on('append', function(response, path, items) {
    imagesLoaded('.posts-grid', function() {
        msnry.layout();
    });
});
```

**Comment by StErMi** [comment]
It's happening also to me but I'm not using imagesloaded nor infinite-scroll

**Comment by desandro** [comment]
@StErMi You likely need to use imagesLoaded. See https://masonry.desandro.com/faq.html#how-do-i-fix-overlapping-item-elements
