### ISSUE TITLE
a problem with the height of the parent node!

### ISSUE THREAD

**Issue by FengHaiSheng** [desandro/masonry#1023]
when I append a new DOM which has a "img src='***'".There is a problem with the height of the parent node

**Test case:** https://codepen.io/wubber/pen/vpgRrL

**Comment by FengHaiSheng** [comment]
I recomputed the height， the code:
`
this.$grid = $('.js-wall-container').masonry({
      itemSelector: '.js-wall-stu-info',
      percentPosition: true,
      transitionDuration: '0.5s',
      resize: true,
    });

function addNewItem($html) {
    $html.find('img').load(function() {
      const $childs = $(this.$grid).find('.js-wall-stu-info');
      let maxDistance = 0;

      [].map.call($childs, item => {
        let $item = $(item);
        let top = parseInt($item.css('top'));
        let height = parseInt($item.css('height'));
        let distance = top + height;

         maxDistance = distance > maxDistance ? distance : maxDistance;
      });

      this.$grid.css('height', maxDistance + 'px');
    });

    if(index > -1) {
      this.$grid.append($html).masonry('prepended', $html);
    }
}
`

**Comment by desandro** [comment]
This sounds like an [imagesLoaded](https://masonry.desandro.com/layout.html#imagesloaded) problem. Take a look at [imagesLoaded API](https://imagesloaded.desandro.com/#jquery) on how to use it.

**Comment by FengHaiSheng** [comment]
thanks!
