### ISSUE TITLE
alter timing of $item.show();

### ISSUE THREAD

**Issue by timholz** [desandro/masonry#1025]
Hi – Thanks for the plugin.
I tried the example below and it works well.
https://codepen.io/desandro/pen/kipBG?selected_tag=masonry-docs&
When i alter the time value for:
`$item.show();` to `$item.show(600);`
i get four columns of images stacked on top of each other.
I also tried:
`setTimeout(function() { $item.show(); }, 500);`
This results in one column with all the elements stacked on top of each other.

How can i fine tune the timing of the elements that are appended one after another?
Thanks again for your work.
regards theo

**Comment by desandro** [comment]
Thanks for reporting this issue. Can you elaborate what behavior you're trying to achieve? How do you want to hide/show the items? You can fork that demo to better explain.

**Comment by timholz** [comment]
Basically i try to have timing control of how the items come on the screen. Only show the next item when the animation of the previous is completed. As it is, the time interval between the items is quite short. I tried to have a longer time interval. Animation is always about timing. For instance other animation events like rotation could be applied if the time was sufficient. It tried several ways to alter the timing but the masonry function somehow does not wait for that. I'll try to post a demo later. Thanks a lot for your interest.

**Comment by desandro** [comment]
In that case you can use [`stagger` option for Masonry](https://masonry.desandro.com/options.html#stagger)

See demo https://codepen.io/desandro/pen/d96ac0c1f1309d9289e63902712c8917/

**Comment by timholz** [comment]
@desandro – Thank you very much for your response and the hint with option «stagger». I appreciate your work a lot. Very useful script. All the best to you
