### ISSUE TITLE
masonry gets applied to items that are not defined in the options

### ISSUE THREAD

**Issue by timholz** [desandro/masonry#1026]
Hi – i successfully applied masonry to a wordpress site. It works well. Then i noticed that masonry adds inline style to elements in the footer that i did not specify in the options and which i also do not want to behave as masonry. I tried to prevent masonry to happen on that element:

``` js
$('.flexible-widget-area').masonry({
  initLayout: false,
});
```

But i didn't help.
I also tried to remove all inline styles:

``` js
$(".site-footer .flexible-widget-area, .site-footer .flexible-widget-area aside").removeAttr("style");
```

No luck, the items «aside» keep dashing aroung.
Why is that happening?
Here is how i call the function:

``` js
jQuery.fn.masonryImagesReveal = function( $items ) {
     "use strict";// JavaScript Document
     var msnry = this.data('masonry');
    //var itemSelector = msnry.options.itemSelector;
    // hide by default
    $items.hide();
    // append to container
    this.append( $items );
    $items.imagesLoaded( function() {
    // un-hide items
    $items.show();
    // reveal all of them
    msnry.appended( $items );
  });
  
  return this;
};
```

Thanks for your interest.
theo

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues).

**Comment by timholz** [comment]
@desandro – Thanks for responding. Sorry for the duplicate. I must have done something wrong when submitting my question. I apologize. I will try to mimic the behaviour this weekend and keep you informed. Thanks a lot for your care. regards, theo

**Comment by timholz** [comment]
@desandro – I figuered it out. It was a wordpress-theme oriented issue. No need to mimic this on codepen. Sorry for the trouble. All the best to you…
