### ISSUE TITLE
Another Animation Test

### ISSUE THREAD

**Issue by timholz** [desandro/masonry#1029]
Hi – With this test i tried to generate a random rotation angle for each item.
https://codepen.io/timholz/full/GyYvNb/
I also tried to make the items rotate on resize, but i could not find a solution. Hints are welcome.
regards

**Comment by desandro** [comment]
Thanks for submitting this issue.

Sorry, but I am not available for personal support. If you have found a bug with Masonry, I can take a look. Otherwise, I'll leave it up to you to find a solution.
