### ISSUE TITLE
Use CSS Grids

### ISSUE THREAD

**Issue by rugk** [desandro/masonry#1032]
What about using [CSS grids](https://cssgrid.io/) for the modern browsers at least? And offer the current way as a fallback?

See also this presentation: https://potch.github.io/grid-talk/#1

**Comment by desandro** [comment]
Good question!

You can create a Masonry effect with CSS Grid. [See maCSSonry grid layout by @kseso  demo on CodePen](https://codepen.io/Kseso/pen/ZJbEMe). Wes Bos also has a Grid Image Gallery section  on [cssgrid.io](https://cssgrid.io/).

But actually using CSS Grid with Masonry will not work. Masonry uses `position: absolute` to position element. When you set `position: absolute` you remove that element from the CSS Grid flow. So the two systems are incompatible, sadly.

**Comment by krazyjakee** [comment]
@rugk @desandro I would imagine the moving animations would be impossible too as there is no JS API for grid events to figure out what has changed or what moves where.

Some use cases may benefit more from using css grid over masonry, for example where you know the size of the elements that will be in the grid will be consistent and don't require animation or events.
