### ISSUE TITLE
Slow scroll in Chrome

### ISSUE THREAD

**Issue by Solybum** [desandro/masonry#1034]
Hello!
First of all thank you for such an amazing library.

Due to a client's request I used Masonry, everything works as expected except that in Chrome, scrolling through the page is quite slow.
The issue seems to be specific to Chrome because it does not happen in IE, Safari or Firefox.

As you can see in the test case, I am using very large images (3000x4000), reducing the image size helps a lot with the slow down but again, even with such large images scrolling is pretty fast and smooth in IE.
For now I can work with resizing the images I display in the grid but ultimately the images used won't be in my control.

I don't know if it is of any help but in my (small) research I came across "composition layers".

Chrome version: Version 64.0.3282.167 (Official Build) (64-bit)
**Test case:** https://codepen.io/Solybum/pen/xYXjjx

**Comment by desandro** [comment]
Thanks for reporting this issue. Yeah, this looks to be caused by big images. I'm sorry, but there's not a good solution. Masonry isn't doing anything other than positioning the items on the screen.

**Comment by Solybum** [comment]
Yeah, after all is not present on other browsers so it's more likely to be an issue with Chrome desktop specifically (it doesn't even affect Chrome for Android, it seems).

I was tempted to use another library along with masonry (infinity.js I think, is advertised on the website) but I instead resized my images and we'll tell the client to be careful on which images he puts in the grid.

I guess the issue can be closed since there isn't really much that can be done on your side, but at least people can be aware of the problem with big images.

Thanks!

**Comment by khalwat** [comment]
So I'm adding this here for any fellow traveler who may find it. We had similar issues to what @Solybum noted. Adding the following to the `<img` tag did the trick:

```
     style="will-change: transform; transform: translateZ(0);"
```
As per: https://developers.google.com/web/fundamentals/performance/rendering/stick-to-compositor-only-properties-and-manage-layer-count

This allowed us to nicely use Masonry with lazily loaded `srcset` images via [LazySizes](https://github.com/aFarkas/lazysizes):

```
	// masonry grid
	var $grid = $('.grid');
	$grid.masonry({
		itemSelector: '.grid-item',
		// use element for option
		columnWidth: '.grid-sizer',
		
	});
	$(document).on('lazyloaded', function(e){
		$grid.masonry('layout');
	});
```

**Comment by khalwat** [comment]
@Solybum I added the properties to your codepen example CSS:

```
.item-image {
  width: 100%;
  height: 100%;
  background-size: cover;
  background-position: center;
  will-change: transform;
  transform: translateZ(0);
}
```

...and it scrolls as smooth as butter in Chrome now.

**Comment by Solybum** [comment]
@khalwat Thanks a lot for looking into it.
I'll give this a try on our site.
