### ISSUE TITLE
Masonry Javascript plugin causes page earthquake

### ISSUE THREAD

**Issue by cryptodescriptor** [desandro/masonry#1035]
If you look at the title in this codepen you will see that when the cards are loaded into the page, the title shakes/gets displaced. This also happens to the search bar when I am not using codepen and causes the glyph search addon to become unattached in Internet Explorer.
               
https://codepen.io/cryptodescriptor/pen/MQBWLL

Forgot to mention, it happens to the footer text usually aswell.

**Comment by desandro** [comment]
Could this be resolved by adding a scroll bar?

``` css
html { overflow-y: scroll; }
```

**Comment by cryptodescriptor** [comment]
Perfect! Love your work by the way.

**Comment by cryptodescriptor** [comment]
Also, If you know how to batch add masonry items for smoother loading let me know :) 👍
