### ISSUE TITLE
How to import Masonry in angular/typescript application ?

### ISSUE THREAD

**Issue by Anthony-Breneliere** [desandro/masonry#1037]
Hello,

I use successfully Masonry in dev environement, importing it like this:

```
import Masonry = require( 'masonry-layout/masonry' );

...
            this.grid = new Masonry( '.masonry_grid', {
                itemSelector: 'section',
                columnWidth: 10,
                containerStyle: { position: 'relative' }
              });
```

...but I cannot build it. The command :

> ng build

.. returns:

> ERROR in src/app/intervention/details/intervention.details.ts(51,1): error TS1202: Import assignment cannot be used when targeting ECMAScript modules.
> Consider using 'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead.

...but I cannot use those forms of import.

I installed @types/Masonry for typescript.

In the masonry.js.. I see 
> var Masonry = Outlayer.create('masonry');

But how do I import it ?

**Comment by desandro** [comment]
Thanks for reporting this issue. See possible solutions over in #839
