### ISSUE TITLE
Masonry Safari Responsive Design Mode issue

### ISSUE THREAD

**Issue by makingthingswork** [desandro/masonry#1038]
This occurs on sites I have masonry installed from unpkg but only when the user agent is set to iOS iPhone. It only occurs in Safari's (11.0.3) Responsive Design mode but interestingly not on Safari Technology Preview.

Anyone else encountered this? Its more annoying than anything else.

[Error] Failed to load resource: the server responded with a status of 403 (HTTP/2.0 403) (imagesloaded.pkgd.min.js, line 0)
[Error] Failed to load resource: the server responded with a status of 403 (HTTP/2.0 403) (masonry.pkgd.min.js, line 0)
[Error] Did not load script at 'https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js' because non script MIME types are not allowed when 'X-Content-Type: nosniff' is given.
[Error] Did not load script at 'https://unpkg.com/imagesloaded@4/imagesloaded.pkgd.min.js' because non script MIME types are not allowed when 'X-Content-Type: nosniff' is given.
![screen shot 2018-03-15 at 20 57 24](https://user-images.githubusercontent.com/998619/37490881-e7ab171e-2893-11e8-85d4-0af41e9a056f.png)

**Comment by desandro** [comment]
Thanks for reporting this issue. It's the first I've heard of this issue.

**Comment by sbiefeni** [comment]
I'm also having this exact problem using resposive design mode

**Comment by desandro** [comment]
This looks to be an issue with unpkg CDN. I've opened unpkg/unpkg#107 to track the issue.

In the mean time, you can use JS files from another CDN, like cdnjs

```
https://cdnjs.cloudflare.com/ajax/libs/masonry/4.2.1/masonry.pkgd.min.js
https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js
```

**Comment by desandro** [comment]
unpkg/unpkg.com#107 has been resolved.
