### ISSUE TITLE
Why first image loading seems to fly in from the left?

### ISSUE THREAD

**Issue by skunkbad** [desandro/masonry#1039]
I know this example is not good, but I didn't want to show code that I wasn't using:

**Test case:** https://codepen.io/anon/pen/PRGyzx

First images loaded seem to fly in from the left, but later when using appended they "pop" right where they are supposed to be?

Real demo: https://suvovu.com/portfolio.php

I want to clarify what this is about. I figured out how to load the initial set of images with appended, so that the animation is always the same. Why does the first set animation differ from that of appended? Shouldn't they be the same? Maybe the animation types could be more easily configured.

**Comment by makingthingswork** [comment]
https://masonry.desandro.com/options.html#transitionduration
// no transitions
transitionDuration: 0

You could set the transition duration to zero and then implement something else.

**Comment by desandro** [comment]
See demo https://codepen.io/desandro/pen/kwsJb from https://github.com/desandro/masonry/issues/501#issuecomment-34583942

**Comment by skunkbad** [comment]
I don't know if you're interested, but I got it working the way I wanted. While I don't have a codepen demo, if you're interested you could check it out on my website: [Portfolio](https://brianswebdesign.com/portfolio)

**Comment by desandro** [comment]
Thanks for following up!
