### ISSUE TITLE
Problem with layout update

### ISSUE THREAD

**Issue by jmperezcalcco** [desandro/masonry#1040]
Trigger "appended event" dont work correctly when elemens are perecentuals, and container not have childrens on init masonry.

The container dont redo his height, and the elements are not positionated correctly.

If i trigger "reload" it works but i dont want to reposition all elements on container, only new one.
Reload doesnt matter if there are a few childrens but it is slow if i have 1000 elements.

ORIGINAL EXAMPLE:
https://codepen.io/desandro/pen/kwALv    (with fixed dimensions and initial childs - WORK)
MODIFIED ORIGINAL
https://codepen.io/jmperezcalcco/pen/wmJQyV   (with fixed dimensions and NO initial childs - WORK)

PERCENTUAL
https://codepen.io/jmperezcalcco/pen/VXpVbx   (with percentual dimensions and initial childs - WORK)

PERCENTUAL FAILS
https://codepen.io/jmperezcalcco/pen/pLeQpg  **(with percentual dimensions and NO initial childs - DONT WORKS)**

**Comment by desandro** [comment]
If you're going to use element sizing for `columnWidth`, then I recommend you use an element that's not a grid element. The issue is that `columnWidth` is looking for a `grid-item` to measure size, but isn't able to find any.

See demo https://codepen.io/desandro/pen/8e867989cbb2598009703f7b605eddb9/

**Comment by desandro** [comment]
Thanks for following up.

> I believed that the width of the element for columnWidth would be calculated each time the layout is rendered 

Masonry already has this behavior. It does not, however, update the element used for `columnWidth` with every `layout`. I'd like to keep the behavior as is. Thanks!
