### ISSUE TITLE
Using Masonry with paroller.js

### ISSUE THREAD

**Issue by Ceyar** [desandro/masonry#1041]
Hello, I'm trying to use Masonry and the parallax plugin paroller.js.

But I get a problem using them together. Here is a test case:
**Test case:** https://codepen.io/Ceyar/pen/dmVdVr

I think it's due to the transform: translateY value who's changed by the paroller.js plugin and make masonry don't know the specific height of the elements. S my footer is overlayed by my elements.

Any ideas how to resolve this? I'm still trying but don't know how to resolve this issue.
Here is an image from the main site.
<img width="975" alt="capture d ecran 2018-03-26 a 08 53 10" src="https://user-images.githubusercontent.com/1465346/37894006-f9c7e778-30dc-11e8-8372-6d7a3ea6e277.png">

Thank you in advance.

Best regards
Dan

**Comment by desandro** [comment]
Masonry does not work with flex box. Similar to https://github.com/desandro/masonry/issues/1032#issuecomment-365932988

> But actually using CSS Grid with Masonry will not work. Masonry uses position: absolute to position element. When you set position: absolute you remove that element from the CSS Grid flow. So the two systems are incompatible, sadly.

**Comment by Ceyar** [comment]
-_-' Ok, thank you for your answer.

Do you have maybe an idea of wich parallax plugin could work with masonry to get the demo effects?

Thank you so much for taking time.

**Comment by desandro** [comment]
Sorry I don't have a recommendation.

**Comment by Ceyar** [comment]
Ok, thank you for your time and your plugin.

Best regards
Dan
