### ISSUE TITLE
Lazy Load

### ISSUE THREAD

**Issue by anarchoi** [desandro/masonry#1042]
How can i add Lazy-loading feature to this script?
I'm getting a lot of errors in Google Lighthouse due to the images from not being optimized for lazy loading
Chrome says my website could load 3.5seconds faster by doing this

"Consider lazy-loading offscreen images to improve page load speed and time to interactive"
https://developers.google.com/web/tools/lighthouse/audits/offscreen-images

Thanks for this awesome script!

**Comment by desandro** [comment]
You can use lazy-loading with Masonry. But you'll need to trigger [`layout`](https://masonry.desandro.com/methods.html#layout-masonry) after images have loaded in case their sizes affect the layout.  Your jQuery may look like:

``` js
$grid.on( 'load', function() {
  $grid.masonry('layout');
});
```
```

**Comment by anarchoi** [comment]
Thanks for the reply,

I tested your solution, but as soon as I activate mod_pagespeed LazyLoad, here's the result: http://prntscr.com/j2di30

This is the code I use

```
<script src='/js/modernizr.custom.js'></script>
<script src='/js/masonry.pkgd.min.js'></script>
<script src='/js/imagesloaded.js'></script>
<script src='/js/AnimOnScroll.js'></script>
<link rel='stylesheet' type='text/css' href='/css/default.css' />
<link rel='stylesheet' type='text/css' href='/css/facebook_album_gallery.css'  />

<!-- classie.js -->
<script>!function(s){\"use strict\";function e(s){return new RegExp(\"(^|\\s+)\"+s+\"(\\s+|$)\")}function n(s,e){var n=t(s,e)?c:a;n(s,e)}var t,a,c;\"classList\"in document.documentElement?(t=function(s,e){return s.classList.contains(e)},a=function(s,e){s.classList.add(e)},c=function(s,e){s.classList.remove(e)}):(t=function(s,n){return e(n).test(s.className)},a=function(s,e){t(s,e)||(s.className=s.className+\" \"+e)},c=function(s,n){s.className=s.className.replace(e(n),\" \")});var o={hasClass:t,addClass:a,removeClass:c,toggleClass:n,has:t,add:a,remove:c,toggle:n};\"function\"==typeof define&&define.amd?define(o):\"object\"==typeof exports?module.exports=o:s.classie=o}(window);</script>

<script>
    new AnimOnScroll( document.getElementById( 'fbgrid' ), {
      minDuration : 0.3,
      maxDuration : 0.5,
      viewportFactor : 0.2
	} );
</script>

<script>
fbgrid.on( 'load', function() {
	fbgrid.masonry('layout');
  });
</script>
```

**Comment by Postnov** [comment]
I am sorry for maybe stupid question and written not where it should be, but how to call a method masonry layout after change css of the block  from 'display: none' to 'display: block' in native js? I have a problems work with content of tabs.

Code example is simplified.

```
.grid {
   display: none;
}
```

```
elem.addEventListener('click', function() {
   grid.style.display = 'block';
   //here method masonry for layout
})
```

Almost like this, just on native javascript
```
$grid.on( 'load', function() {
  $grid.masonry('layout');
});
```

Thanks and sorry for my english, i am just begin.

**Comment by desandro** [comment]
@Postnov see #1045

**Comment by ZoeFken** [comment]
Hello i seem to be having the same issue. When I use a lazyload and the extra images get loaded in they don't correctly load in. I tried your solution but i seem to be having a issue getting the $grid.masonry() to instanciate and execute.

When i do however resize my window everything jumps into place. So if i can just trigger the event it would be golden.

This is the lazy load i am trying to use
https://github.com/verlok/lazyload
var lazyLoadInstance = new LazyLoad({
  elements_selector: ".lazy"
});

window.addEventListener('LazyLoad::Initialized', function (event) {	
  window.lazyLoadInstance = event.detail.instance;	
}, false);

**Comment by Zebra447** [comment]
> Hello i seem to be having the same issue. When I use a lazyload and the extra images get loaded in they don't correctly load in. I tried your solution but i seem to be having a issue getting the $grid.masonry() to instanciate and execute.
> 
> When i do however resize my window everything jumps into place. So if i can just trigger the event it would be golden.
> 
> This is the lazy load i am trying to use https://github.com/verlok/lazyload var lazyLoadInstance = new LazyLoad({ elements_selector: ".lazy" });
> 
> window.addEventListener('LazyLoad::Initialized', function (event) { window.lazyLoadInstance = event.detail.instance; }, false);

did you find a solution?
