### ISSUE TITLE
Center the gallery

### ISSUE THREAD

**Issue by Gas75** [desandro/masonry#1043]
**Test case:** http://codepen.io/desandro/pen/osFxj
Hi there, I am using Masonry but I'd like the columns will appear centered in the box, but via CSS the margin-left: auto and margin-right: auto; looks ignored.

**Comment by desandro** [comment]
[Use `fitWidth`](https://masonry.desandro.com/options.html#fitwidth)

**Comment by Gas75** [comment]
Sorry it's not what I mean... :( Please see my layout draft below
![layout_home_page](https://user-images.githubusercontent.com/34484003/38620125-00634c58-3d9e-11e8-8980-ad9fda496326.png)
Masonry works on the light blue box: right column should collapse with left one in a single column when width is not enough, letting the orange box alive to right until the screen is bigger than a smartphone portrait: I can manage this.
Masonry works good without the fitWidth. But I need the single column is centered into the light blue box (as margin-left: auto and margin-right: auto shoud do normally). I hope problem has been explained, English is not my native language...

**Comment by desandro** [comment]
If you're looking to position a non masonry item within a Masonry grid, you can use [stamp.](https://masonry.desandro.com/options.html#stamp) You'll have to play around with the demo to figure out how to stamp it in the middle

**Comment by Gas75** [comment]
I need to use _a mansory grid_ (the light blue box) _into a non mansory layout_: my right div keeps the same width as I want, but resizing screen the div containing mansory grid does not reduces the width of its div box, so the right div goes down as CSS's float rules says... How can I let mansory grid to "feel" the div at its right?
And I still have to center the mansory grid into its box when it is on a single column,

**Comment by desandro** [comment]
Sorry Masonry may not be the right solution for you.

**Comment by Gas75** [comment]
Ok, I'll change layout...
Thanks.
