### ISSUE TITLE
Masonry + Infinite scroll: masonry error.

### ISSUE THREAD

**Issue by ieraora** [desandro/masonry#1044]
Hi, If I launch this https://codepen.io/ieraora/pen/xWomYj for first time (debug mode, for example), masonry don't work fine. Why? Thanks
![screenshot 2018-04-16 08 54 24](https://user-images.githubusercontent.com/22258422/38794008-d4c41294-4153-11e8-9c10-cb4a3cf6637e.png)

**Comment by fennecthemes** [comment]
Hello, I tested and it's working, maybe because of your browser (delete the cache)

**Comment by ieraora** [comment]
Isn't a problem of cache. I tested it also with  an anonymous window

**Comment by ieraora** [comment]
If I add  gutter, I haven't problem (https://codepen.io/ieraora/pen/rdXMjy). But I need gutter= 0.

**Comment by ieraora** [comment]
If I assign gutter=0, in preview of [codepen](https://codepen.io/ieraora/pen/rdXMjy) is correct, but if you CHANGE VIEW in DEBUG MODE, this is my view
![screenshot 2018-04-16 11 12 03](https://user-images.githubusercontent.com/22258422/38800229-06ead7b8-4167-11e8-9cb0-c6540efcbce8.png)

**Comment by desandro** [comment]
Could this be caused by the scroll bar? Try adding `html { overflow-y: scroll; }` to your CSS.

**Comment by ieraora** [comment]
now it's OK. Thanks
