### ISSUE TITLE
An error in the safari on Windows

### ISSUE THREAD

**Issue by serkrush** [desandro/masonry#1047]
If you open your site (https://masonry.desandro.com) in a safari, we get an error
TypeError: 'undefined' is not a function (evaluating 'e.getAttribute(a)')
Is there a solution to this problem?

**Comment by desandro** [comment]
Masonry v4 does not support the older version of Safari (v6?) on Windows, last supported in 2012. You can try downgrading to [Masonry v3](https://masonry.desandro.com/v3) or [Masonry v2](https://masonry.desandro.com/v2)
