### ISSUE TITLE
Corner stamp - fixing a separate element to the opposite corner

### ISSUE THREAD

**Issue by desandro** [desandro/masonry#105]
Setting `cornerStampSelector` specifies that Masonry saves space for the selected element

``` javascript
$('#container').masonry({
  itemSelector: '.box',
  columnWidth: 100,
  cornerStampSelector: '.corner-stamp'
});
```

**See http://jsfiddle.net/desandro/M8EYn/embedded/result/**

This feature was original built way back for [Pattern Tap Alpha](http://alpha.patterntap.org). Just today I received another request for it.

Speak up if you like to see this feature merged into the master branch.

**Comment by denseflux** [comment]
Looks like this mod has now been moved to: http://desandro.github.io/masonry/demos/corner-stamp.html

**Comment by desandro** [comment]
This feature has been implemented as the [`stamp` option in Masonry v3](http://masonry.desandro.com/options.html#stamp)
