### ISSUE TITLE
IE back button: layout not firing

### ISSUE THREAD

**Issue by josephkohlmaier** [desandro/masonry#1050]
This seems to be a known issue, but in recent IE releases, using the back button doesn't fire some essential js required to layout isotope masonry. ImagesLoaded does not improve the situation, nor does using pageshow etc. Wanting to avoid (window).load – and I am not sure if that would even work – has there been a recent solution to this issue? You can see a video of the effect here.
https://www.dropbox.com/s/ivykp72nukxex4j/IMG_7931.MOV?dl=0

**Comment by desandro** [comment]
Thanks for reporting this issue. Not sure if there's anything I can do here, as this sounds like a browser issue. I'll leave this issue open in case others find it useful.
