### ISSUE TITLE
How to display a certain number of items. 

### ISSUE THREAD

**Issue by nikomaxia** [desandro/masonry#1052]
Hi Desandro, 
I have build a bootstrap-4 page with a big number of cards. 
I have create a jquery script with .slice method to display only 6 cards on page load. Below the cards is a button. Every time you click the button another 6 items displayed... 
The problem is when I import masonry.js the whole number of cards are displayed on page load and the button is not working at all. 
Is there a way via masonry.js to display only 6 cards on page load and use the button to display another 6 cards every time is clicked? 
I'm trying to understand the appended method on your website but I cannot make it.

Thanks in advanced.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues).
