### ISSUE TITLE
Multi-column content with floating center image

### ISSUE THREAD

**Issue by andremacola** [desandro/masonry#1054]
Is it possible to do this with Masonry?I am already using CSS Multi-column to make the paragraphs in columns but I need to fit a floating image around the text.

It's not possible to break the content in multiple grid-like solutions. The post need to work like a magazine or printable newspaper when editing in softwares like Indesign.

Example:

![captura_de_tela_2018-07-10_as_11 52 04](https://user-images.githubusercontent.com/3408809/42540166-b7c1dcfe-8473-11e8-9ace-2c9b9255a18e.png)

**Comment by desandro** [comment]
[Yes, use stamp](https://masonry.desandro.com/options.html#stamp)
