### ISSUE TITLE
Outer Height not calculating properly!

### ISSUE THREAD

**Issue by Jishnuparakkat** [desandro/masonry#1061]
@desandro 

Height of parent 'div' is not calculating properly!

here i'm attaching the image

![issue](https://user-images.githubusercontent.com/26666571/43311810-158d16a4-91a9-11e8-8da0-30b9006910cf.jpg)

**Comment by desandro** [comment]
[Looks like you need imagesLoaded](https://masonry.desandro.com/layout.html#imagesloaded)
