### ISSUE TITLE
Is Horisontal line layout possible in masonry?

### ISSUE THREAD

**Issue by nerminba** [desandro/masonry#1062]
This is not really an issue, it's kinda feature request if this is not already possible in masonry.

It this kind of layout possible with it:
http://app.moptym.com/vue-waterfall/demo/horizontal-line.html

I know that it supports this kind of layout: 
http://app.moptym.com/vue-waterfall/demo/vertical-line.html

But the first example is what I am after. Please let me know.

**Comment by desandro** [comment]
Sorry, no Masonry does offer an 'image wall' layout. You'll have to find another solution.
