### ISSUE TITLE
Masonry overlapping problem

### ISSUE THREAD

**Issue by engharb** [desandro/masonry#1067]
Hello,

initial loading of html entities <div> is succeeded, but every few seconds I used to remove some of those children <div> and append new ones then I call ```masonry('layout');```.

later on I noticed that some <div> are overlapping: this means the elements css positions are the same (same features) and I do not exactly how to fix that?

Any ideas?

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues).

**Comment by engharb** [comment]
I'm not sure if what I did is correct: https://codepen.io/anon/pen/EeGagE?selected_tag=masonry-docs

I want to delete some element and then append new ones, the new elements are template of html code and in the example it is like:
```
<div class="item clickAd" style="min-height: 320px; min-width: 300px;">
    <a class="catshadow adshelper" href="javascript:void(0)" url="http://www.google.com">
            <img class="image" src="" title="test click" alt="test click">
    </a>
  </div>
</div>
```

**Comment by desandro** [comment]
See [appended docs](https://masonry.desandro.com/methods.html#appended) and [demo](https://codepen.io/desandro/pen/kwALv)

**Comment by engharb** [comment]
I followed exactly what is written in the tutorial.
