### ISSUE TITLE
Massonary grid issues on ajax loading

### ISSUE THREAD

**Issue by amitsarkerr** [desandro/masonry#1068]
Hello,

I am using your scripts on my wordpress theme for post massonary layout http://prntscr.com/l14jh7.
When I click load more button, it's overlapping on the grids http://prntscr.com/l14kbl

My js codes
`$("#load-more-posts").on('click', function (e) {
			var nexturl = $(this).attr('href');

			$.get(nexturl, {}, function (data) {
				var posts = $(data).find(".lorepostsgrids").html();
				//console.log(posts);
				$(".lorepostsgrids").append(posts);

				var postgrids = $('.lorepostsgrids');
				imagesLoaded($postgrids,function(){
					$postgrids.masonry('appended',items);
					$postgrids.masonry({
						itemSelector: '.grid-item'
					});

				});

				var newpagelink = $(data).find("#load-more-posts").attr("href");
				if(newpagelink){
					$("#load-more-posts").attr('href', newpagelink);
				}
				else{
					$("#load-more-posts").hide('slow');
				}
			});
			return false;
		});

		var newpagelink = $("#load-more-posts").attr("href");
		if(!newpagelink){
			$("#load-more-posts").hide('slow');
		}`

Solution please

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues).

**Comment by amitsarkerr** [comment]
Finally, I fixed it
