### ISSUE TITLE
Masonry only layouts some elements

### ISSUE THREAD

**Issue by TheNeikos** [desandro/masonry#1069]
Heya! Thanks for this great library!
Unluckily I seem to have struck a form of edge case, and I am not sure how to reproduce it on its own.

The problem is that masonry only layouts some of the elements and doesn't seem to touch the others at all.

![image](https://user-images.githubusercontent.com/1631166/47241234-426cc500-d3eb-11e8-9f30-2d3c3008b2bc.png)

 However this only happens when the images are cached, on first load it works fine:

![image](https://user-images.githubusercontent.com/1631166/47241341-9677a980-d3eb-11e8-895c-9239aca68182.png)

This made me thing that maybe I was calling 'layout' too fast, but testing in a codepen wasn't fruitful.

However, I do not understand how they get _no_ positioning assigned, which makes me think that maybe it could be a bug?

I have been trying the past hours to reproduce this on its own, but to no avail. Have you seen something like this happen before? I'd be happy about pointers to resolve this.

Thanks!

------
Some more context that could be helpful:

- The html content looks roughly like this:

```html
<div class="columns">
    <div class="column is-full-mobile is-half-tablet is-one-third-widescreen" style="position: absolute; left: 0%; top: 0px;">
      <!-- Non zero-height and width, with an image with varying height for each column -->
    </div>
</div>
```

- The HTML already exists on load, and Masonry is being used to augment the layout.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues).
