### ISSUE TITLE
Hide items on small devices

### ISSUE THREAD

**Issue by AlessandroVecchi** [desandro/masonry#1071]
I want to show only the first three items on small devices.
I tried with a css selector but it doesn't work properly
```
@media (max-width: 767px) {
  .grid-item:nth-child(n+4) {
    display: none;
  }
}
```
is there another way?

**Comment by AlessandroVecchi** [comment]
Can i disable masonry at a specific screen size?

**Comment by desandro** [comment]
You can initialize Masonry conditionally with 

``` js
if ( matchMedia("(min-width: 720px)").matches ) {
  $('.grid').masonry(...);
}
```

**Comment by AlessandroVecchi** [comment]
Thanks!
Maybe it works....
But i have to count "grid-sizer" too (i dont't understand why)
