### ISSUE TITLE
Masonry creating long gaps between the top and the grid container

### ISSUE THREAD

**Issue by ableslayer** [desandro/masonry#1073]
I followed the codepen called [Iteratively reveal items](http://jsfiddle.net/chickberger/eVaMF/4/) and inserted the new masonry codes [v4.2.2](https://unpkg.com/masonry-layout@4.2.2/dist/masonry.pkgd.js) and now there's a gap between the container and the very top of my html. 

and here's the test case:
https://codepen.io/ableslayer/full/RqqGzX/

How can I remove this gap?
![gap](https://user-images.githubusercontent.com/15151552/49215677-46d1c800-f404-11e8-85c4-cbcdfd6556d3.jpg)

**Comment by desandro** [comment]
See demo https://codepen.io/desandro/pen/wQQyMW

The trick is that you need to set an initial `itemSelector` to select no items, this way, those initial items are not added and loaded as Masonry items. Then reset `itemSelector` after init to select proper `.grid-item`.

``` js
      var $grid = $('#grid').masonry({
        // init with no items
        itemSelector: 'NONE',
        percentPosition: true,
        columnWidth: '.grid-sizer',
        gutter: '.gutter-sizer'
      });

      // reset itemSelector to load grid-item
      $grid.masonry( 'option', {
        itemSelector: '.grid-item',
      })
      
      $grid.masonryImagesReveal( $('#grid').find('.grid-item') ); });
```

related to original issue #501

**Comment by vanduzled** [comment]
Thank you, I understand now. This is perfect!

**Comment by ableslayer** [comment]
Thank you. I understand now. This is perfect!
