### ISSUE TITLE
Issue with <details>

### ISSUE THREAD

**Issue by GenieTim** [desandro/masonry#1076]
**Test case:** https://codepen.io/BernhardWebstudio/pen/YdNLKa

With a `<details>` element in place, Masonry fails to realign on extension of the `details`-element. Might be a no-fix, in which case I would like to request a documentation adjustment.

**Comment by desandro** [comment]
Thanks for reporting this issue and providing a test case! If you make a change to the size of an item element, like expanding a `details` element, you'll have to trigger [`layout`](https://masonry.desandro.com/methods.html#layout-masonry) on the [details `toggle` event](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details#Events)

``` js
$grid.find('details').on( 'toggle', function() {
  $grid.masonry();
});
```

See demo https://codepen.io/desandro/pen/4fcade9e0d20b359b74a8d78e05e1cf7

**Comment by GenieTim** [comment]
Alright, thanks!
