### ISSUE TITLE
How to redesign mansory using getting async data as a div

### ISSUE THREAD

**Issue by emreordukaya** [desandro/masonry#1080]
Hi I get async data, I use webmethod and jquery. then I show data in divs on web page via mansory as 3 columns. But I have only last 3 columns have height, other divs have 0 height because of async data. 
I have to redesing all divs again after all page loaded. 
I tried 
$('.grid').masonry().reloadItems();
$('.grid').masonry().layout();
but I have 3 columns and all columns the last div have heiht again. How can I redisign mansory.
If I miniaturize and maximize the browser as a manuel, All divs have heigt greatly. I want to run via code this func (miniaturize and maximize the browser as a manuel).

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues).
