### ISSUE TITLE
Masonry gallery not working fine with 4 columns

### ISSUE THREAD

**Issue by MalikZohaib** [desandro/masonry#1082]
**Test case:** https://codepen.io/anon/pen/yZEBXQ?selected_tag=masonry&

**Comment by merefield** [comment]
Your calculation for width is incorrect, Use 30px (for 3 x gutters ie n-1), instead of 20px, so:
```
  width: calc((100% - 30px)/4);
```

**Comment by MalikZohaib** [comment]
yes its working fine now.. Thanks for the correction.

**Comment by merefield** [comment]
np, happy tiling :)
