### ISSUE TITLE
Question: can masonry handle pinterest -like grid with expanding cards ?

### ISSUE THREAD

**Issue by Aarbel** [desandro/masonry#1083]
Hi @desandro,

I'm working on this use case :
**When a user clicks on a card**, the card expands `from 20% to 80% width` and `to a bigger height`, and pushes the other cards on the sides and bellow.
Is there a way to do it with this library ? (I've spent many hours to find similar example, … without success).

Thanks a lot for your help !

![image](https://user-images.githubusercontent.com/25119847/52942758-e8194c00-336b-11e9-8100-866d4e39c0a3.png)

![image](https://user-images.githubusercontent.com/25119847/52942778-f10a1d80-336b-11e9-8538-9b31e73896bd.png)

**Comment by desandro** [comment]
Take a look at the [layout demo](https://masonry.desandro.com/methods.html#layout-masonry) or the  [animating item sizes demos](https://masonry.desandro.com/extras.html#animating-item-size)
