### ISSUE TITLE
horizontalOrder doesn't seem to do anything

### ISSUE THREAD

**Issue by YCMitch** [desandro/masonry#1086]
Before I spend ages trying to get this all into a CodePen, has anyone successfully gotten horizontalOrder to work?

It makes no difference at all in my code - are there any extra settings or required parameters that haven't been documented? 

The only relevant JS is the below, and I've only got some very basic typography CSS being used. Totally ignores the order. 

```
        var masonryGrid = $('.videos-list').masonry({
            horizontalOrder: true,
            itemSelector: '.videos-list .list-item',
            columnWidth: '.grid-sizer',
            gutter: 40,
        })
```

If everyone else is using it okay I'll try get mine into a CodePen, just thought I'd check first.

**Comment by desandro** [comment]
Try disabling and re-enabling `horizontalOrder` with this CodePen: https://codepen.io/desandro/pen/EmKWdr
