### ISSUE TITLE
Problem with my JS in Masonry

### ISSUE THREAD

**Issue by TasioC** [desandro/masonry#1087]
Hello!
First to say it's super fun Mansonry, good job.

I have made my css and my html prepared but I can not do well my JS to see it, I do not know where the problem lies. I appreciate if you could help me, I do not think it is very difficult.
THANK YOU VERY VERY MUCH :) 

https://codepen.io/ta_io/pen/MxqjpV (THIS IS WHAT I HAVE )

**Comment by desandro** [comment]
Take a look at the Masonry CodePen: https://codepen.io/desandro/pen/osFxj
