### ISSUE TITLE
How i can put my div float left 

### ISSUE THREAD

**Issue by TasioC** [desandro/masonry#1088]
i put float:left on my divs but when i add Masonry and Imagesloaded all of my divs they do not adjust. I dont know where can be the problem, thanks :)

https://codepen.io/ta_io/pen/KEbQxo

**Comment by desandro** [comment]
Looks like your demo was missing `x1` on `masonry-column-sizer`.

See  https://codepen.io/desandro/pen/2634413eb9bc75c5f0a4980614258bf9
