### ISSUE TITLE
IE throwing error with attempted local masonry.pkgd.js copy

### ISSUE THREAD

**Issue by luxcreativity** [desandro/masonry#1092]
I'm totally new to jquery and I downloaded the pen example (https://codepen.io/desandro/pen/osFxj) and attempted to change hosted masonry.pkgd.js to a local copy stored in the js folder.

It works fine in Chrome but is throwing an error in Microsoft Edge in index.js:

SCRIPT438: Object doesn't support property or method 'masonry'

And doesn't work in Internet Explorer whilst not throwing any error.

Is there an example using a locally stored version I could take a look at?

**Comment by desandro** [comment]
You can download the docs site and run that locally. Click **download these docs** https://masonry.desandro.com/
