### ISSUE TITLE
Load image after another

### ISSUE THREAD

**Issue by e-anima** [desandro/masonry#1097]
Hi,
i have just a simple question because i could not find anything. 
Is it possible to start loading the images one after another right in the moment the dom is loaded?

I guess it is not possible because mansory does not know the sizes for the grid until all images are loaded?

Thank you

**Comment by desandro** [comment]
See demo https://codepen.io/desandro/pen/kwsJb and explanation in https://github.com/desandro/masonry/issues/501#issuecomment-34583942

**Comment by e-anima** [comment]
Thank you very much. I will check that.

**Comment by e-anima** [comment]
Am i right that you can NOT use this with a fluid layout when using 
width: 20% on ".item" and option "percentPosition: true,"

**Comment by desandro** [comment]
This technique will work with fluid sizing.
