### ISSUE TITLE
No gutters after append elements

### ISSUE THREAD

**Issue by LuQK9** [desandro/masonry#1098]
Hello,

I use masonry.js on my WordPress project. Everything works correctly except AJAX. My AJAX object "success" method has this code:

**$(".blog-posts.grid").masonry().append(arr).masonry("appended", arr, true);**

All posts are loaded correctly, but they don't contain gutters. How to fix it?

Thanks in advance for any help!

**Comment by desandro** [comment]
Double check that `arr` is either an Array of Elements or a jQuery Object, and NOT an HTML string. If it is an HTML string, convert it to a jQuery Object

``` js
var $arr = $( arr );
$(".blog-posts.grid").masonry().append( $arr ).masonry("appended", $arr);
```
