### ISSUE TITLE
item load Animation Not working in angular build with prod mode

### ISSUE THREAD

**Issue by contact2mayurkukadiya** [desandro/masonry#1099]
I am using masonry-layout  in angular project. all animation and item are load perfect in running project in local environment. But when I try to deploy my project by using following command :

ng build --prod

then my build is successfully generate but when I run that build, masonry item load animation not working proper. 
Is there any solution for this kind of behavior .
Please help me.

**Comment by desandro** [comment]
Sorry, I am not available for personal support for this issue.
