### ISSUE TITLE
Pin elements or specify column

### ISSUE THREAD

**Issue by skjnldsv** [desandro/masonry#1140]
Hi, I'd like to specify some items to be set at the very last column.
So whatever the reflow would be, they would always be in the last wolumn.

I searched a bit around, but couldn't fien anything related.
Is it possible? IS it what stamps are all about?

Thanks a lot! And thanks for this awesome library!

**Comment by desandro** [comment]
Use [stamp](https://masonry.desandro.com/options.html#stamp)
