### ISSUE TITLE
Rotate not working

### ISSUE THREAD

**Issue by borjaprueba** [desandro/masonry#1142]
**Test case:** http://codepen.io/desandro/pen/osFxj

It doesn´t work properly when i rotate in my mobile from vertical to horizontal and my photos overlapped.

Here is the example:

https://tinyurl.com/y5nb3zwsv

if you enter in one of the fist gallery you can see the problem when rotating. but what can be wrong?

**Comment by desandro** [comment]
True, any `transform` set on grid item elements will be removed as Masonry sets `translate`. You can, however, set `transform` on a child element of the item elements. See demo https://codepen.io/desandro/pen/gOwZjxg

<img width="661" alt="image" src="https://user-images.githubusercontent.com/85566/104816443-38fc7e00-57e9-11eb-9137-2ed9711c434b.png">
