### ISSUE TITLE
Site Not Found

### ISSUE THREAD

**Issue by mrleblanc101** [desandro/masonry#1192]
![Screenshot 2023-10-20 at 3 45 45 PM](https://github.com/desandro/masonry/assets/17392251/85820342-0695-4a78-9800-367ac9e16660)

**Comment by desandro** [comment]
Yes, this indeed an issue. Netlify has spuriously banned my account, which has taken down a dozen of my sites. I am now working to move hosting provider. This will likely take another couple days to resolve.

Sorry for the hassle everyone

More drama detail in case you're curious:

Netlify has completely banned my account for "fraudulent behavior." I have literally no idea in reference to what. Uncertain what recourse I have with them. I may need to re-deploy a dozen sites elsewhere. I am absolutely furious

1. I took 72 hours through a support thread for them to reveal the ban.
2. This is the first mention about fraudulent behavior. No previous correspondence about it
3. Most recent successful payment was Oct 6th

**Comment by desandro** [comment]
The site is back up: masonry.desandro.com . I've moved to Vercel. There may be some more bits of downtime as part of migrating off of Netlify.

**Comment by mrleblanc101** [comment]
Just curious, why not use GitHub Pages ? It's free and gets the job done
