### ISSUE TITLE
`display: none` of a brick is ignored

### ISSUE THREAD

**Issue by apfelbox** [desandro/masonry#126]
Hi,

please see the jsFiddle example: http://jsfiddle.net/DNPLg/

The brick with `display: none` is still shown as an "invisible element" (i.e. the following element does not take it's place).

I think this is a bug, since in all other display methods (plain CSS etc) the elements with `display: none` are completely removed from the element flow.

There is indeed a workaround: not only remove the element via `display: none` but also remove the class via CSS, but it is still a bug. ;-)

Cheers
apfelbox

**Comment by brianfgonzalez** [comment]
I am receiving the following error.  Can anyone assist me?

Uncaught SyntaxError: Failed to execute 'matches' on 'Element': ':visible' is not a valid selector.

here is my site: fortmillkids.com

and here is my masony call:

function reloadMasonry() {
    $('.results').masonry({
       itemSelector: ':visible',
    }).imagesLoaded(function() {
        $(this).masonry('reload');
    });
}

Thanks in advance!

/Brian
