### ISSUE TITLE
How do I avoid showing "jumping" bricks on page load

### ISSUE THREAD

**Issue by jayd3e** [desandro/masonry#275]
I currently load jquery.masonry() on DOM ready.  During the second or so that it takes the browser to display the content, the individual bricks can be seen jumping to the location that jquery.masonry() gives them.  I can best illustrate this with the following screenshots.  

This is my site immediately after pageload:

![pageload](http://f.cl.ly/items/1G1J2e10041n2L351O2E/Screen%20Shot%202013-01-08%20at%205.09.01%20PM.png)

Then after a split-second of loading.  Jquery.masonry() does it's thing, resulting in this:

![after](http://f.cl.ly/items/1b0j1s1V0d1q393B0I3P/Screen%20Shot%202013-01-08%20at%205.14.47%20PM.png)

As you can see, for a split-second, the bricks can be seen "jumping" to a new location.  This is incredibly annoying, and I'm curious as to what measures I can take to fix it.  The first thing that came to mind was that I would hide the bricks by default, call Jquery.masonry(), and then show the bricks again.  This way the bricks are not shown until they arranged.  The problem with this is that when the bricks are hidden, jquery.masonry() cannot calculated their height correctly.  This results in lots of overlapping.  Any ideas?

**Comment by squarecandy** [comment]
This is great. I had to add the .masonry class manually. I also added a nice little fade in using css opacity transition:

js

    	// init Masonry
	var $grid = $('.grid').masonry({
		columnWidth: '.grid-sizer',
		itemSelector: '.grid-item',
		percentPosition: true,
		gutter: 10,
	});

	// layout Masonry after each image loads
	$grid.imagesLoaded().progress( function() {
		$grid.masonry('layout');
		$grid.addClass('masonry'); // add the class here, after images are loaded...
	});

css

	.grid {
		opacity: 0;
		transition: opacity 500ms;
	}
	.grid.masonry {
		opacity: 1;
	}
