### ISSUE TITLE
How can I keep the items in its original order?

### ISSUE THREAD

**Issue by Antonel1** [desandro/masonry#331]
I am using jQuery Masonary for a basic dynamic grid layout. It seems to be working pretty well. Thank you!

Ben Foster who posted this question on stackoverflow explains our problem very well:

"The plugin appears to calculate the "next available space" based on the height of elements on the previous row.

View example here: http://i.stack.imgur.com/0EXrx.png

In this example item number 6 goes to the far right because the height of number 4 is less than the height of number 2 (where I want it to go).

The layout I would like to achieve is more similar to left-floating elements:

View example here: http://i.stack.imgur.com/ElUDG.png

Are there options on Masonary to achieve this layout?

I've been trying for awhile to get this to work but with no success. Your help would be greatly appreciated!!

**Comment by desandro** [comment]
See #873
