### ISSUE TITLE
Disable animation on window resize

### ISSUE THREAD

**Issue by michaelnie** [desandro/masonry#353]
Is it possible to remove the animation on window resize?

**Comment by sandroweb** [comment]
But `transitionDuration: 0` command disable the animation, or only change the animation time to 0?

**Comment by desandro** [comment]
Technically, `transitionDuration: 0` disables the CSS transition completely. So CSS is immediately set, rather than set with a CSS transition.

**Comment by mukulsoftwap** [comment]
transitionDuration: 0 is not work for me
