### ISSUE TITLE
Masonry breaks all javascript in IE7

### ISSUE THREAD

**Issue by pwkip** [desandro/masonry#356]
I understand you don't support IE7 anymore, I have absolutely no problem with that, but your plugin fails in such a way in IE7 that all other javascript is not even executed. Just loading the masonry.js file is enough to completely disable all javascript for that browser.

You can check out a live example on your own website, http://masonry.desandro.com/. Just make sure to watch it in IE and view it in IE7 mode.

This is the error you will see in the console window:

SCRIPT5009: 'Element' is undefined 
masonry-docs.min.js, line 1 character 9877

**Comment by desandro** [comment]
I'm closing this issue as a **won't fix**. I feel most JS will break in IE7, so you'll likely need a wider solution aside from just handling Masonry v3 to resolve supporting IE7.  I'll leave that up to you.
