### ISSUE TITLE
Masonry breaks in Chrome

### ISSUE THREAD

**Issue by matt25** [desandro/masonry#362]
Hi, I am building a new site at frictionmultimedia.com and I am using the masonry script for the first time.

It works fine in Firefox and IE but in chrome all the boxes overlap and I cannot work out why. 

As Requested I have stripped the site down to the bare minimum but I cannot seem to work it out still. The stripped down version is at http://frictionmultimedia.com/masonry/

I am using Chrome version 27.0.1453.116 m

As I say, I have tried everything I can think of but I cannot work it out, Please can you give me some suggestions?

Any help is much appreciated.

Thanks, Matt

**Comment by jbonpland** [comment]
@desandro how are you? where should i put the code you mention ?
 `jQuery( document ).ready( function( $ ) {
  var $container = $('#hWr').masonry({
    columnWidth: 1
  });
  $container.imagesLoaded( function() {
    $container.masonry();
  });
});`

i'm having an issue that when i go to one section it loads one of the images full size, then i hit f12 on chrome and that action does the trick and show the masonry layout perfectly fine. I dont why.
