### ISSUE TITLE
IE8 issue on line 1124 and Masonry stop to work

### ISSUE THREAD

**Issue by saymonkent** [desandro/masonry#365]
Hi, I love this masonry app, I know the las version V3 does not support IE7, but it is not working on IE8 neither.

I followed the steps on http://masonry.desandro.com/#getting-started but when I run on IE8 I get this error:

SCRIPT87: Argumento no válido. 
masonry.pkgd.js, Línea 1124 Carácter 5

When I go to this line, this is the piece of code that I see on that line:

Item.prototype.css = function( style ) {
  var elemStyle = this.element.style;

  for ( var prop in style ) {
    // use vendor property if available
    var supportedProp = vendorProperties[ prop ] || prop;
    elemStyle[ supportedProp ] = style[ prop ];
  }
};

and this it the code that I use to initialize the masonry:

var container = document.querySelector('#content');
var msnry = new Masonry( container, {
  // options
  itemSelector: '.box'
});

am I doing something wrong?

**Comment by mattstein** [comment]
I've also hit this problem in IE8, after injecting ajax-loaded cards into a percentage-based layout and calling the plugin's layout method.

I can tack on `style[ prop ] != 'NaN%'` to avoid the resulting error in IE8, but the cards are absolute-positioned on top of each other in a stack. If I explicitly set the column width in the plugin options (ignoring my percentage-based layout), the problem goes away and cards are positioned as expected. Seeing if I can narrow further.

**Comment by desandro** [comment]
@mattstein Thanks for the heads up. Any chance you can put together a [reduced test case](http://masonry.desandro.com/appendix.html#reduced-test-cases)? I'd like to investigate this if possible.

**Comment by mattstein** [comment]
@desandro I should be able to. Figured out that my problem has to do with the timing of layout calls, only in IE8. Will reduce and post if I can whittle it down to the essentials.

**Comment by mattstein** [comment]
@desandro I didn't use CodePen, but I put together this simple test to illustrate the problem: http://masonry-test.wrkbkt.com/

This is a stripped-down version of what I experienced on a development site: the user chooses to load more cards, and the existing ones are removed before new ones are loaded into the DOM from some asynchronous JSON—randomized here just so the display changes.

To witness the problem:

1. Load IE8 in IE8 standards mode, visit the demo page, and choose _Load More_.
2. Confirm the _Invalid argument_ JavaScript error that blocks any further script action on the page.

To bypass the problem and get IE8 working fully with no effect in real browsers:

1. Switch to my patched `/js/jquery-masonry-custom.js` instead, which throws in another conditional to avoid having the `NaN%` value throw an error in IE8.
2. Reload the page and confirm that the Masonry layout works as expected in IE8.

To reproduce the (probably related) stacking problem in IE8:

1. Use the patched version of Masonry from above.
2. Remove line 115 from index.html, which is a call to Masonry's `layout` method immediately after appending grid items.
3. Confirm that Masonry's layout seems to work fine in real browsers, yet stacks cards on top of each other in IE8.

Here's a ZIP package of my test setup—I've left comments in index.html that may help clarify: http://wrkcpt.co/9332f5dbd9bc6ac50c02e4288ee3
