### ISSUE TITLE
After AJAX div reload masonry loads images over each other.

### ISSUE THREAD

**Issue by steverob** [desandro/masonry#369]
I am using ajax to refresh a div containing images. I use masonry to add layout initially.

Then the ajax call returns a js that refreshes the div using the html() method. Now after it completes I am calling masonry('reloadItems'). But masonry loads all images onto one another. After a page resize it works. I tried manually triggering the page resize with jquery but it doesnt make masonry make the adjustments.

JS:

``` javascript
$('#timerange-select, #category_select').bind('change', function() {
    form=$('#images-filter-form');
    $.get(form.action, form.serialize(),function(){
      var $container = $('#images_conta');
      $container.imagesLoaded(function(){$container.masonry('reloadItems');});
      $(window).trigger('resize');
    }, 'script');
 });
```

![Image](http://i.stack.imgur.com/4SOen.png)

This is actually 10 images loaded on each other.

See http://stackoverflow.com/questions/17697223/masonry-images-overlapping-above-each-other/17697495?noredirect=1#17697495 for css and html.

Please help me with this.

**Comment by Mustafaoeztuerk** [comment]
@steverob  I have the same issue If you fixed that problem can you tell me how ? http://stackoverflow.com/questions/28874932/masonry-items-not-reloaded-when-cliking-ajax-load-more-button

**Comment by HabedyOmid** [comment]
i have been having hard time with same problem in last 2 days. 

the following is my javascript code which gets the images and data from AJAX.PHP from DB.
Ajax and scroll loading part is working just fine, before i use ajax to pull data from DB Masonry was working perfectly.  after i decide to implement the infinite scroll loading Masonry broke and its not working no more.

I have been searching alot and read all other problems and Masonry documentation applied many solution but it seems its not working for me.

Any Help would be highly appreciated.


   $(document).ready(function() {
            
            var track_load = 0; //total loaded record group(s)
            var loading  = false; //to prevents multipal ajax loads
            var total_groups = <?=$total_groups;?>; //total record group(s)

            $('.imgWrapper').load("ajax.php", 
                               {'group_no':track_load}, 
                               function() {track_load++;}); //load first group

            $(window).scroll(function() { //detect page scroll

                //user scrolled to bottom of the page?
                if($(window).scrollTop() + $(window).height() == $(document).height()){

                    //there's more data to load
                    if(track_load <= total_groups && loading == false) {

                        loading = true; //prevent further ajax loading
                        $('.overlay').show(); //show loading image

                        
                        //load data from the server using a HTTP POST request
                        $.post('ajax.php',
                               {'group_no': track_load}, 
                                function(data){ 

                                $(".imgWrapper").append(data); //append received data into the element

                                //hide loading image
                                $('.overlay').hide(); //hide loading image once data is received

                                track_load++; //loaded group increment
                                loading = false; 
                            
                                jQuery('.imgWrapper').masonry( 'appended', data );

                                });

                    }
                }
                
            });

        });
