### ISSUE TITLE
Appending via AJAX and using jQuery

### ISSUE THREAD

**Issue by drewbaker** [desandro/masonry#374]
Big time fan of your work. I use it all the time.

I've been trying to get my head around the new Masonry. I'd like to stick to a jQuery way of appending new bricks to an existing Masonry instance. 

I've followed the Docs as close as I can, and I'm getting a "TypeError: t[a] is not a function" error when trying to use the 'appended' method.

Here is a link to my reduced test case:
http://labs.funkhausdesign.com/examples/masonry/appended.html

But my guess is there is something wrong with this code:

```
// Start Masonry
jQuery('#container').masonry({
    columnWidth: 150,
    itemSelector: '.block',
    gutter: 20,
    isFitWidth: true
});

// Get some more blocks
jQuery('#more').click(function(){
    jQuery.get('http://labs.funkhausdesign.com/examples/masonry/blocks.html', function(data) {

        // Append new blocks
        jQuery('#container').append(data);

        // Have Masonry position new blocks
        jQuery('#container').masonry( 'appended', data );

    });                     
});
```

Once I have this solved, I will leave up my example page and go through Stackoverflow and answer a lot of these questions people are having:
http://stackoverflow.com/search?q=masonry+appended

**Comment by zaeem** [comment]
Thanks

**Comment by X9DESIGN** [comment]
Why this does not work now?
http://codepen.io/desandro/pen/evLkD

Loaded blocks do not match.
