### ISSUE TITLE
masonry v3.0.0 IE8

### ISSUE THREAD

**Issue by kzahirag** [desandro/masonry#377]
Bug with iE8:

elemStyle[ supportedProp ] = style[ prop ];

masonry.pkgd.js, line1127 char 5

Solution:
if(style[ prop ] != 'NaNpx') {
    elemStyle[ supportedProp ] = style[ prop ];
}

**Comment by joeylin** [comment]
can Masonry support IE 8 ?

**Comment by desandro** [comment]
@joeylin [yes](http://masonry.desandro.com/faq.html#what-is-masonry-s-browser-support).
