### ISSUE TITLE
masonry('remove', items) when items is empty throws critcal error

### ISSUE THREAD

**Issue by drewbaker** [desandro/masonry#381]
If you try to run masonry('remove', items) when items is empty, you will get a "TypeError: t is undefined" error.

See test case here:
http://labs.funkhausdesign.com/examples/masonry/remove_and_appended.html

Click "Just 'remove' all blocks!" twice.

**Comment by wanidulf** [comment]
Desandro, how are you? I used this fix but it is not working on firefox. In my case, It works on chrome but doesn't on firefox.
