### ISSUE TITLE
percentage width, pixel gutter

### ISSUE THREAD

**Issue by mauriciocgpereira** [desandro/masonry#393]
How can I do this?
(html, css and jquery)

Thanks,
Maurício

![screen3](https://f.cloud.github.com/assets/2078204/1012099/7e39562a-0b69-11e3-9c98-856de19ee95f.jpg)
![screen2](https://f.cloud.github.com/assets/2078204/1012100/82bb0bf8-0b69-11e3-8bc4-d6cb27d21fbb.jpg)
![screen1](https://f.cloud.github.com/assets/2078204/1012102/873330d4-0b69-11e3-95b5-7d8b215e8b2e.jpg)

**Comment by squarecandy** [comment]
Thank you the code pen linked is exactly what I was looking for - specifically:

` width:  calc( ( 100% - 6px ) / 3 );`

as in:

`$gutter_size = 3px;
$number_of_columns = 3;
$total_gutter_space = ( $number_of_columns - 1 ) * $gutter_size;

width: calc( ( 100% - $total_gutter_space ) /  $number_of_columns );`

if that makes any sense...
