### ISSUE TITLE
Elements flickering in Chrome

### ISSUE THREAD

**Issue by bildlich** [desandro/masonry#394]
I am loading a couple of `<li>` elements on a page with jQuery's `.ajax()` and stack them on top of each other. The user can then
- drag individual elements around (I used jQuery UI's `.draggable()` for this)
- click on "pile" to rebuild the stack
- click on "spread" to spread elements out with masonry

The problem: When spreading out the items, the elements go to their designated position in the grid as they should and then **flash for a little moment back to their original position.**

See a video here: [Video](https://dl.dropboxusercontent.com/u/18268/jquery-flickr/jquery-flickr.mov) (Quicktime .mov)<br>Reduced test case here: [Demo](http://mgieselmann.com/k/kd202/index.htm)

The problem only occurs about 50% of the time, not every time I spread the items. For instance, in the video above it only happens the second and the last time I click on "spread". I have not been able to tell what exactly causes the bug to occur.
The problem occurs in Chrome 29.0.1547.57 on a Mac. Firefox 22 and Safari 6.0.5 are not affected. I haven't tried any other browsers yet.

When the spread link is clicked .masonry() is called this way:

```
    $('.content').masonry({
        columnWidth: 180,
        gutter: 20,
        itemSelector: 'li',
        isResizeBound: false,
        isLayoutInstant: false
    });
```

**Comment by aktorebeket1** [comment]
Hey I have the same problem in windows 10 Chrome
