### ISSUE TITLE
Masonry triggered only after window resize

### ISSUE THREAD

**Issue by clearvis** [desandro/masonry#396]
I have my elements inside a hidden container that appears when a click event is fired. Masonry stacks the elements at left 0 until I re-size the browser window. After that it works fine when opening and closing the hidden div.

I've used Masonry several time without problems. Thanks, I love it.

Jim

**Comment by alihut** [comment]
My container is not hidden and i have the same problem. Triggering _layout()_ didn't solve my problem. Can anybody help me?
