### ISSUE TITLE
Responsive margin-bottom?

### ISSUE THREAD

**Issue by Nettsentrisk** [desandro/masonry#417]
I've come across a problem that affects only certain browsers. If you set margin-bottom with a responsive unit, such as %, on the elements you're laying out using Masonry, it won't always work correctly.

In IE9+, Chrome, Firefox, and Opera, it applies the %-based margin correctly. In IE8, Safari iOS and the Android browser, the margin-bottom gets set to a few pixels and ignores the % in the CSS. Setting margin-bottom with px in the CSS works fine.

I'm puzzled by the fact that IE8, Safari iOS and Android browser exhibit this problem, it seems like there would be nothing these three should have in common to produce this error. I'm assuming there's a hole somewhere in the calculation of px from % when it comes to the margin bottom/top properties.

Here's a demonstration of a Masonry layout set up with % for margin-bottom, IE8 on the left and IE10 on the right:
![image](https://f.cloud.github.com/assets/1027492/1307194/7afa5b44-31bb-11e3-8b1a-c2f0508e4190.png)

**Comment by NoahWilcox** [comment]
Hey @desandro where could I get this? I can't seem to figure out how to get vertical gutters to work with %'s either.
