### ISSUE TITLE
Broken resize when width changes.

### ISSUE THREAD

**Issue by ldwg** [desandro/masonry#427]
Thanks for Masonry!

I experience the following problem: With responsive layouts, the height of containers changes _after_ masonry positions them.

When I resize the browser-window:
First, the containers are repositioned depending on their current height.
Secondly, the viewport dependent css is applied, which may cause a new height. 
Result: There is a gap below the now-smaller element.

An example: Imagine a container in a grid-layout that holds some text. When the browser window is narrowed down, the grid gets linearized and the containers width therefore increases. The container will be repositioned first, then the new width is applied, and therefore the height decreases at the same time. This results in a gap below the now lower element.

Not sure, this is this considered a bug, but I thought I let you know?! What would be an elegant solution? Thanks, again.

**Comment by desandro** [comment]
Closing as an edge case.
