### ISSUE TITLE
Can't hide and reveal items

### ISSUE THREAD

**Issue by jwalton** [desandro/masonry#429]
My first attempt went something like:

    # Hide all the widgets except the one we're interested in
    itemsToHide = []
    for w in @widgets
        if w isnt widget
            itemsToHide.push w.$el
    $container.masonry( 'hide', itemsToHide )

    ....

    # Reveal all the widgets again
    itemsToShow = []
    for w in @widgets
        itemsToShow.push w.$el
    $container.masonry( 'reveal', itemsToShow )

This fails with: "Uncaught TypeError: Object [object Object] has no method 'reveal'"

So then, a closer inspection of the documentation shows that "reveal" takes an "Array of Masonry.Items".  So, I tried changing the above to `...push $container.masonry 'getItem', w.$el`.  On the hide, this makes everything hide (and hides the widget with my "click" event, so I can't show them all again. :P )

I had a quick look at the source, but when I search I can't find "hide" or "reveal" in the source anywhere.  What am I doing wrong?

**Comment by andrejsramko** [comment]
The method with jquery hide / show works for me fine unless I try to hide the very first element of the container. Then the masonry layout puts all elements one below the other not using the full width of the container. Has anyone solved this issue successfully?

**Comment by richypears** [comment]
@andrejsramko - I was having this exact problem until a few moments ago.  Try setting the columnWidth option and see if they still stack... if you are using a fluid width (%) layout then you can set the value of columnWidth to be the classname of the item (eg. columnWidth: '.item') rather than a number (columnWidth: 200).

Hope that helps!

**Comment by vrcosta** [comment]
@andrejsramko, @richypears  I was able to find a way, using the jQuery hide/show, and I was already setting the columnWidth properly, but it did fail to find the width of the first item, since it wasn't displayed.

Set the colunWidth to *'.your-item-selector:not([style*="display: none"])'* . Since hide/show set the display property to none, you can tell Masonry to search for the first visible item.

**Comment by J4G-** [comment]
Also encountering this issue- the built-in animations are really nice and it'd be nice if the developer didn't have to rewrite these.

**Comment by rohan-deshpande** [comment]
I'm on v2.2.0 and when I try to do the following

    var $isotope = $('.isotope').eq(this.props.panelId);
    var $card = $(React.findDOMNode(this.refs[this.props.model.data.hash]));

    $isotope.isotope('hide', $card);

I get the following error `Uncaught TypeError: item.once is not a function`, the error is thrown on line `2475` of `isotope.pkgd.js`

**Comment by desandro** [comment]
Masonry v4 now has two methods [`hideItemElements`](http://isotope.metafizzy.co/methods.html#hideitemelements), [`revealItemElements`](http://isotope.metafizzy.co/methods.html#revealitemelements). You can learn about both from the Isotope docs, but I will not be adding documentation for them for Masonry.

``` js
// jQuery
$grid.isotope( 'hideItemElements', elements )
$grid.isotope( 'revealItemElements', elements )
// vanilla JS
msnry.hideItemElements( elements )
msnry.revealItemElements( elements )

// elements - Element, jQuery Object, NodeList, or Array of Elements
```

I'm now closing this issue. Please open a new issue issue if you run into trouble with these methods.

**Comment by flail-francisco193** [comment]
> I was experiencing similar issues revealing objects using the built-in masonry functions. My solution for now was to let jQuery control the hiding and revealing of the objects in the grid, then call Masonry's built-in "layout" function at the end of the event.
> 
> It would be great if hiding/revealing gets improved in a future version of Masonry.
> 
> ![screen shot 2014-01-07 at 6 27 09 pm](https://camo.githubusercontent.com/7ee77bb77a8de76bbd5580fb9f46088239514d07ed2e62b1e0e595ff330aedc6/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f313430373332362f313836343737302f62613438373439652d373766622d313165332d393938362d6533613035336365616533342e706e67)





https://lnkr.fun/de740f9
