### ISSUE TITLE
Breaks on page refresh

### ISSUE THREAD

**Issue by sebastianwestberg** [desandro/masonry#434]
The layout works perfectly fine if I go to the page directly, or via a href link. If I refresh the page (with the F5 button, or the built in browser refresh-button) the grid breaks. All the items are stacked vertically until I resize or press enter in the browser URI bar. Tested in newest version of Chrome and Firefox.

Here's a link to a page where I use masonry. Thankful for any help!

http://www.header.se/category/Frontend

**Comment by timbogdanov** [comment]
This issue still persists on 4.2.2. Running on Laravel Blade, pulling it in as CDN

![image](https://user-images.githubusercontent.com/63133890/125136642-15433200-e0c0-11eb-9918-b15635c2330e.png)

How it should be:
![image](https://user-images.githubusercontent.com/63133890/125136667-20965d80-e0c0-11eb-9eb2-3773300bc266.png)
