### ISSUE TITLE
Masonry doesn't work after appending items dynamically!

### ISSUE THREAD

**Issue by jeremyrajan** [desandro/masonry#441]
Hi Guys,
I am in bit of dilemma here, I am trying to append elements to masonry container and re-initliaze but doesn't seem to work. I tried as mentioned on the site and stuffs on Stackoverflow as well. Nothing seems to work, this is a snippet from the code:

<pre>
jQuery.noConflict();
        var limit = 6;
    jQuery(document).ready(function(){
        var container = jQuery('#shoots_wrap').masonry({
                    itemSelector : '.shoot_item',
                    isFitWidth : true,
                    isAnimated: true
                });
                jQuery(document).scroll(function() {
        if (jQuery(window).scrollTop() + jQuery(window).height() == jQuery(document).height()) {
                    limit += 6;
                    jQuery.post("/ajax/loaditems.php",
                    {
                        limit: limit
                    },
                    function(data,status){
                         var obj = jQuery.parseJSON(data);
                         jQuery.each(obj, function() {
                             jQuery.post("/ajax/loadcover.php",
                             {
                                 id: this['id']
                             },
                             function(data,status){
                                  var src = jQuery.parseJSON(data);
                                  jQuery.each(src, function() {
                                    var img_src = this['filename'];
                                    var html = "<div class='shoot_item'><img src='"+img_src+"'/></div>";
                                    container.append(html);
                                    container.imagesLoaded(function() {
                    container.masonry();
                    container.masonry('appended', html);
                                    });
                                });
                            });
                         });
                    });
                        
                }
            });
    });
</pre>

The code appends items to shoots_wrap container, when someone gets to the end of the webpage. I can successfully append it but masonry doesn't seem to be reinitialise.

Any help will be really appreciated and thanks in advance.

**Comment by Leylou85** [comment]
After having searched a solution to implement Masonry, infinite scroll and Java JEE/JSP all together since yesterday, here's a whole solution which works fine !

In the body of the JSP showimg content :
<pre>
<code>
			<div id="container">  				
  				 <jsp:include page="more.jsp" />
			</div>

<script>
	var container = document.querySelector('#container');
	
	// initialize Masonry
	var msnry = new Masonry( container, {
		itemSelector: '.item'
	});	
</script>

<script src="js/main.js"></script>

</code>
</pre>

In the JSP more.jsp :
<pre>
<code>
<%@ page language="java" pageEncoding="ISO-8859-1"%>
<%@ page import="java.util.*"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<jsp:useBean id="fc" class="org.independants.metier.Fiche"
	scope="page"></jsp:useBean>	

<c:if test="${ empty param.o }">
<c:set var="offset" value="0" />
</c:if>	
<c:if test="${ !empty param.o }">
<c:set var="offset" value="${ param.o }" />
</c:if>	

<c:set target="${fc}" property="offset" value="${ offset }"/>

<c:forEach var="fiche" items="${ fc.listeLastUpdate }">
	<div class="item">
		<div class="titled-polaroid">	
			<a href="fiche.jsp?fcid=<c:out value="${ fiche.fcid }"/>">				  
				<img src="images/<c:out value="${ fiche.uid }"/>_<c:out value="${ fiche.tags }"/>/<c:out value="${ fiche.image_principale }"/>">
			</a>
		  
			<p class="text-center"><c:out value="${ fiche.titre }"/></p> 
		</div>
	</div>		
</c:forEach>
</code>
</pre>

In the main.js :
<pre>
<code>
	var offset = 20;
	var dOffset = 20;

	// on initialise ajaxready à true au premier chargement de la fonction
	$(window).data('ajaxready', true);
	
	var deviceAgent = navigator.userAgent.toLowerCase();
	var agentID = deviceAgent.match(/(iphone|ipod|ipad)/);
	$(window)
			.scroll(
					function() {
						// On teste si ajaxready vaut false, auquel cas on
						// stoppe la fonction
						if ($(window).data('ajaxready') == false)
							return;
						if (($(window).scrollTop() + $(window).height()) == $(
								document).height()
								|| agentID
								&& ($(window).scrollTop() + $(window).height()) + 150 > $(
										document).height()) {
							// lorsqu'on commence un traitement, on met
							// ajaxready à false
							$(window).data('ajaxready', false);
							
							$.get('more.jsp?o=' + offset, 						
							
							function(newElements) {
								// hide new items while they are loading
								var $newElems = jQuery(newElements).css({ opacity: 0 });
								
								$('#container').append($newElems);
								offset += dOffset;
								$(window).data('ajaxready', true);
								$newElems.animate({ opacity: 1 });
								msnry.appended( $newElems )
						    });
						}
					});

</code>
</pre>

And finally, in the class Fiche.java :
<pre>
<code>
public class Fiche {
	private int fcid; // id of the fiche
	private int uid; // id of the creator of the fiche
	private String titre;
	private String image_principale; // image of the fiche
		
	private int offset;
	private List<Fiche> listeLastUpdate; // For JSTL to work

	...

	public void setOffset(int offset) {
		this.offset = offset;
	}

	...

	public List<Fiche> getListeLastUpdate() throws ClassNotFoundException,
			SQLException {
		List<Fiche> liste = new ArrayList<Fiche>();

		DAO dao = DAO.getInstance();
		
		
		ResultSet rs = dao
				.execSQL(
						"SELECT * FROM FICHE ORDER BY DATE_UPDATE DESC LIMIT 20 OFFSET " + offset);
		Fiche fiche;
		Utilisateur util;

		while (rs.next()) {
			util = new Utilisateur(rs.getInt("UID"));
			fiche = new Fiche(rs.getInt("FCID"), rs.getInt("UID"),
					rs.getString("TITRE"), rs.getString("TEXTE_PRESENTATION"),
					rs.getString("IMAGE_PRINCIPALE"), "", util.getNomUtilisateur(), true, null, null);
			liste.add(fiche);			
		}
		return liste;
	}
}
</code>
</pre>

Hope it helps !
