### ISSUE TITLE
Problem with page refresh and not only

### ISSUE THREAD

**Issue by alexa-a** [desandro/masonry#443]
I have an overlapping problem with Masonry.
On my website there is three pages that use Masonry for blocks of different heights that contain pictures.
In Opera, Firefox and IE there is no problem, everything works fine and steadily. Thank you very much!!!
In Chrome and Safari (last versions both) there is a problem:
when I refresh the page the blocks overlap each other, as a rule, not every time but very often.
As a rule, when I go to the page directly or via a href link all work well, but sometimes I have such problem in this situation also.

I already used imagesLoaded, as you recommended on your site, but there is no effect.

Please help me, could you tell me how I can fix this problem?

**Comment by php11i5** [comment]
I meet the same...
