### ISSUE TITLE
imagesLoaded does not work on my second div container

### ISSUE THREAD

**Issue by smooth08** [desandro/masonry#445]
masonry.pkgd.min.js
imagesloaded.pkgd.min.js

and 

$(window).load(function() { $(function() { var $container = $('#container'); $container.imagesLoaded(function() { $container.masonry({ itemSelector : '.item', }); }); }); }); 

div id="container" class="masonry js-masonry
   div class="item" IMAGE div
   div class="item" IMAGE div
   div class="item" IMAGE div
  div class="item" IMAGE div
div

div id="container" class="masonry js-masonry
   div class="item" IMAGE div
   div class="item" IMAGE div
   div class="item" IMAGE div
  div class="item" IMAGE div
div

```
but images on the second div container overlap.
imagesloaded works only on the first container div
```

   Any solutions? ANY HELP WILL BE APRECIATED
  thanks.

**Comment by ghost** [comment]
This works for me:

```javascript
$(document).ready( function() {
    window.addEventListener('load', (event) => {
        $('.grid').masonry({
            itemSelector: '.grid-item',
        });
    });
});
```
