### ISSUE TITLE
Masonry is not working on the second tab , please help

### ISSUE THREAD

**Issue by mase857** [desandro/masonry#451]
.. So I am using masonry to show content in different tabs , but the thing is that it will work for the very first one , but the other ones won't work ..they're originally hidden with the hide() function.  I would like masonry to be able to work on the following tabs as well .. I can't use visibility:hidden because that will show all the tabs and their content .. How can I fix this ?  Below is my code

[CODE]
jQuery(document).ready(function() {
      $('#tabs > div').hide();
            $('#tabs div:first').fadeIn('slow');
            $('#tabs ul li:first').addClass('active');
            $('#tabs > ul li a').click(function(){
                    $('#tabs ul li.active').removeClass('active');  // <== Only what you need
                    $(this).parent().addClass('active');
                    var selectedTab=$(this).attr('href');
                    $('#tabs > div').fadeOut('fast', function() {       // <== Use a callback
                        $(selectedTab).delay(10).fadeIn('fast');          // <== add a delay
                      });  
                    return false;
                  });

```
       $('.panel').masonry({
       columnWidth: 951,
       itemSelector: '.tweet_box'
      });
  });
```

HTML

```
<div id="tabs">
              <ul>
                  <li><a href="#tabs-1">First panel</a></li>
                  <li><a href="#tabs-2"> Second panel </a></li>
                </ul>
<div id="tabs-1">
  <div class="panel js-masonry">
      <div class ="tweet_box">
       <div class="item"></div>
       <div class="item w2 h2"></div>
       <div class="item h3"></div>
      </div>
   </div>
</div>
<div id="tabs-2">
    <div class="panel js-masonry">
       <div class ="tweet_box">
       <div class="item"></div>
       <div class="item w2 h2"></div>
       <div class="item h3"></div>
     </div>
</div>
</div>
</div>
```

[/CODE]

**Comment by d0ublezer0** [comment]
Here is solution: http://www.sitepoint.com/bootstrap-tabs-play-nice-with-masonry/
