### ISSUE TITLE
Need an event triggered after container is resized

### ISSUE THREAD

**Issue by theeluwin** [desandro/masonry#466]
Hello. I'm trying to make some website like pinterest.
In pinterest, you can see that header's width is calculated after all content elements are some kinda 'masonry'-ed whenever the window is resized.
I've tried to make it same, but I had some issue here:
When resizing the window, the items are re-aligned but the container's client width is not updated right away. When transition duration is positive value, it doesn't really matter since the layoutComplete event is raised twice: once right after re-aligned (width is not updated), and then another event with width updated.
I think this problem is related to transition duration, not sure though. I'll tried to find exact problem.
If possible, I'll make a demo page.

**Comment by desandro** [comment]
Not enough interest in the feature here so I'm closing this ticket.

**Comment by mbeauv** [comment]
My timing is truly awful.  I just realized that my problem is exactly what you describe here.  Too bad about the feature not being implemented... still your solution works very well.  Thanks.

**Comment by BornToDoStuff** [comment]
Shame this was never implemented, but I appreciate the shim code @theeluwin, I just used it and it did exactly what I needed it to.
