### ISSUE TITLE
Slow performance with lots of items with infinite scroll

### ISSUE THREAD

**Issue by MennaEllithey** [desandro/masonry#474]
hi, @desandro 

in my page i used masonry and infnite scroll, and the masonry blocks contains buttons that expand/minimize the block, so when it loads a large amount of blocks and i click on those buttons it takes so much time to execute the event and relayout masonry.

is there any way to relayout blocks in sequance way or something?

Note:

layoutItems Method doesn't work for me.
$container.masonry( 'layoutItems', items, isStill )
here was my code:

```
        var blockItems = $('#main_body').masonry('getItemElements');
        $("#main_body").masonry('layoutItems', blockItems , true);
```

*Uncaught TypeError: Object #<HTMLDivElement> has no method 'on' 

and i tried this also:

```
       var arr = new Array();
       $(".main_items").each(function () {
            var blockItems = $('#main_body').masonry('getItem', $(this));
            arr.push(blockItems);
       });
      $("#main_body").masonry('layoutItems', arr , true);
```

*Uncaught TypeError: Object [object Object] has no method 'getSize' 

thanks a lot..

**Comment by desandro** [comment]
[Infinite Scroll v3](https://infinite-scroll.com) has been released with a brand new rewrite including tight [Masonry support](https://infinite-scroll.com/options.html#outlayer). Please try upgrading to the Infinite Scroll v3.

Please open a new issue if you continue to run into this issue.
