### ISSUE TITLE
items overlapping with Infinite Scroll

### ISSUE THREAD

**Issue by ghost** [desandro/masonry#476]
Hi Desandro,
I dont know why, suddenly my masonry dont work well with infinite scroll plugin.. worked well until now...

here is the website:
http://realdeal.co.il

scroll down and hit the down arrows to load more posts.. they stuck on each other..

is there anything wrong with my script? configuration?

Thank you very much,

Amit.

**Comment by Hastig** [comment]
Another option to try, put this in the InfiniteScroll Wordpress plugins *Callback* field..

    (function($) {
    var $container = $('.masonry-container'); // this is the content selector
    $container.imagesLoaded( function() {
    $container.masonry({
    itemSelector: '.block-wrapper' // this is the item selector
    });
    });
    })(jQuery);


adjust your selectors as needed.

make sure Masonry/Isotope is selected in *Behaviour*

thanks to this gent..
https://wordpress.org/support/topic/infinite-scrollmasonry-overlapping-issue
