### ISSUE TITLE
CommonJS compatibility

### ISSUE THREAD

**Issue by MoOx** [desandro/masonry#480]
It's currently a pain in the ass to use masonry (so outlayer & friends) in a commonsjs environnement (in my case browserify).
You should take a look to UMD (eventually [this part](https://github.com/umdjs/umd/blob/master/returnExports.js#L17-L37)) to handle the 3 styles CommonJS, AMD & oldschool way.

**Comment by kopax** [comment]
From changelog.md : + imagesLoaded no longer included 

Why ?
It does not longer work with gamma, which I made compatible browserify too

**Comment by desandro** [comment]
@kopax imagesLoaded is a separate project that solves a separate problem, for this reason, it should be kept separate.

**Comment by bonfish** [comment]
Hi!

There is still one build method that's not working for Masonry: using browserify with standalone scripts (not installed via npm and thus with no node-modules dependencies, but just stored in folders). E.g. the structure like this:

```
app.js                                  // this file has require's in it and is browserified
|--- libs/                              // scripts from this folder are being required
|------ masonry.pkgd.js
|------ someOtherLib.js
...
```

All other libraries/plugins I've met so far, both designed with module.exports ans without it, could be made working this way. 

I understand, this might not be of any priority; just thought it would be fair noticing.

**Comment by desandro** [comment]
@bonfish Thanks for reporting this issue. As you have guessed, I don't feel this is a common use case. If you're using browserify, then you should be installing Masonry with npm. `masonry.pkgd.js` is designed for users who do not use package management, and just want the plop the file in `<script />`.

**Comment by achord** [comment]
Trying to figure this out. I'm using masonry 4.0 running gulp. I keep running into the same error:

[Error running Gulp] Error: module "./item" not found

**Comment by desandro** [comment]
@achord Please open a new issue, thanks!
