### ISSUE TITLE
Issues with Print Stylesheet

### ISSUE THREAD

**Issue by iversoncreative** [desandro/masonry#481]
When I print, I get some vertical overlap, and some bleeding off the right side of the page. 

The tops of subsequent items are floating on top of the bottoms of items above them. And the last column's items are bleeding about 1/4" off the right side of the paper. 

![1](https://f.cloud.github.com/assets/3998792/1979625/fa83466a-83b3-11e3-9497-a58cb5079e0e.jpg)
![2](https://f.cloud.github.com/assets/3998792/1979626/fa8425c6-83b3-11e3-82b7-7d44e78fc86d.jpg)

Any insights?

**Comment by desandro** [comment]
No one else has chimed in so I'm gonna close this ticket due to inactivity.
