### ISSUE TITLE
Please add support to Composer

### ISSUE THREAD

**Issue by marcemira** [desandro/masonry#508]
Something like:

// composer.json
{
  "name": "desandro/masonry",
  "description": "Masonry works by placing elements in optimal position based on available vertical space, sort of like a mason fitting stones in a wall. You’ve probably seen it in use all over the Internet.",
  "keywords": ["masonry", "jquery","grid"],
  "homepage": "http://masonry.desandro.com/",
  "authors": [
    {
      "name": "David DeSandro",
      "email": "contact@desandro.com"
    },
  "license": "MIT",
  "extra": {
    "branch-alias": {
      "dev-master": "3.1.x-dev"
    }
  }
}

**Comment by desandro** [comment]
After 11 months, I don't feel there's enough interest to pursue adding Composer support. Sorry Composer :fried_shrimp:

**Comment by Donjohn** [comment]
well no composer = no solution to include it properly in a professional project with Symfony. At least give us a direct link to a compiled version so we can declare a custom package.

**Comment by codekipple** [comment]
@Donjohn composer is for PHP packages. I use Symfony2, for frontend packages I use Bower or NPM within my Symfony2 project as package managers. Using composer is definitely not the way to go for frontend things.
