### ISSUE TITLE
measureColumns using first item even if hidden

### ISSUE THREAD

**Issue by mikethedarv** [desandro/masonry#511]
I implemented a small plugin for my site that incorporated filtering functionality using masonry's built in "ignore", "unignore", "hide" and "reveal" functions.  The problem is, in the Masonry.prototype.measureColumns function, it is pulling the first item from the list to use in the columnWidth calculation whether or not it was hidden (and ignored).  I've updated the code to:

Masonry.prototype.measureColumns = function () {

...

var firstItem;

for (var i = 0, len = this.items.length; i < len; i++) {
    if (!this.items[i].isIgnored) {
        firstItem = this.items[i];
        break;
    }
}

if (!firstItem) {
    firstItem = this.items[0];
}

...

Calling "layout" now correctly positions all the elements.  Not sure if this should be pulled into the main branch, but seems to me like a bug as ignored columns are not considered in the "getItemsForLayout" method call, so probably should be used for the columnWidth either.

**Comment by desandro** [comment]
Closing this request as it didn't get enough activity.

**Comment by ferromariano** [comment]
nottt ferromariano@ff493ff
