### ISSUE TITLE
Chrome Acts strangely at 90% Zoom on Masonry Homepage 

### ISSUE THREAD

**Issue by merlihan** [desandro/masonry#514]
Hi,

I am having an issue in Chrome version 33.0.1750.146m (latest). If i zoom out then refresh the page OR arrive at the page while zoomed out, the layout breaks. I am using the prescribed columnWidth solution with no avail:

var $container = $('#masonry-list');
$container.imagesLoaded( function(){
	 $container.masonry({
		  itemSelector: '.item',
		  columnWidth: 235
	 });
});

To verify this, i am able to replicate it on the Masonry Homepage. See before and after refresh images attached (zoomed at 90%).
![90 zoom-beforerefresh](https://f.cloud.github.com/assets/4990374/2360894/95927d68-a62a-11e3-878b-bab57bc88880.jpg)
![90 zoom-afterrefresh](https://f.cloud.github.com/assets/4990374/2360908/a5399260-a62a-11e3-8184-970dec974239.jpg)

**Comment by desandro** [comment]
Closing as an edge case.
