### ISSUE TITLE
Items are overlapping on initial page load

### ISSUE THREAD

**Issue by Seb-Thiroux** [desandro/masonry#515]
Hello Desandro,

First, thank you for the work you put into this.
I'm working on a site redesign, and I'm trying to use masonry as it is the best solution I found to stack articles/items that have different heights. I have used it before and never had a problem with it.
This time, it's almost working the way I want, except that the items are not loading properly when loading the page. The items are either overlapping one another or the spaces between them are uneven. Yet when you resize the browser window to a smaller or bigger break point, the layout start acting like it should. I tried to figure out what the problem is on my own for more than a week now, and I'm sure I'm missing something, but I don't see it. Can you please tell me what it is that I'm doing wrong?
Here is the temporary test site where you can see the issue: http://stereovisual.com

Thanks.

Sebastien

**Comment by roncarino** [comment]
Hi Desandro, thanks for your work.
I know this issue has been closed in 2014 but I am having the same problem. It is quite weird. I am facing the same problem of @Seb-Thiroux. At first load of the page, few images, are overlapping. If I try to refresh the page everything seems ok. Same if I try to resize the screen, images are re-ordering properly by themselves.

EDIT: Yes, a combination of jQueryBridget and imagesLoaded seems to have solved the problem. Sorry for this.
Thanks, Loris

<img width="1079" alt="Screen Shot 2020-02-24 at 10 52 57 am" src="https://user-images.githubusercontent.com/13092188/75122648-f7a44100-56f3-11ea-9727-3b4b8955dce6.png">

<img width="1068" alt="Screen Shot 2020-02-24 at 10 51 37 am" src="https://user-images.githubusercontent.com/13092188/75122643-e9eebb80-56f3-11ea-8512-cfa0a09f10d1.png">


@Seb-Thiroux in your case "imagesLoaded" solved the problem?

Cheers, Loris

**Comment by roncarino** [comment]
Yes, a combination of jQueryBridget and imagesLoaded seems to have solved the problem. 
Thanks, Loris
