### ISSUE TITLE
Stagger transition

### ISSUE THREAD

**Issue by desandro** [desandro/masonry#540]
Several people have requested animation that is staggered. Similar to [MixItUp](https://mixitup.kunkalabs.com).

Requested in desandro/masonry#493, desandro/isotope#339

**Comment by djskinner** [comment]
I think I'm going to have to implement this functionality (in Outlayer probably - I'm using a custom Outlayer layout rather than Masonry). Any pointers on where to start?

**Comment by desandro** [comment]
I'd create a generalized method to handle the staggering. Take an array of items, use transition delay, or setTimeout, set item element style. Currently Outlayer doesn't have this kind of group-change functionality, outside of layoutItems

**Comment by desandro** [comment]
Masonry added the [stagger option](https://masonry.desandro.com/options.html#stagger) in [v4.1.0](https://github.com/desandro/masonry/releases/tag/v4.1.0). Closing as fixed! 🍍
