### ISSUE TITLE
Reload Masonry after display:none is added to item

### ISSUE THREAD

**Issue by jmogera** [desandro/masonry#545]
I have a situation where certain item panel get display:none when a specific action is performed. i.e. Check a checbox and certain item disappear. 

Here is an example of a item getting display:none. (note: the masonry control doesn't reset the layout)
http://jsfiddle.net/jmogera/6tm4d/

I have also added the error in stackoverflow, but no response: http://stackoverflow.com/questions/21537281/reload-layout-in-masonry

I am not sure how to reset the layout after display:none is added to items? Please help!

**Comment by Pramoddeokar** [comment]
I am getting same issue.
Items get overlapped, when i disable some of items.
Other Items got style attribute set to left:0
Tried triggering .masonry(), layout().
