### ISSUE TITLE
Safari Desktop & Mobile problem //  images stuck on Top 

### ISSUE THREAD

**Issue by dennishelbig** [desandro/masonry#555]
Hello, sorry for my bad english in advance.

I tried to adept the masonry tool in a website and got problems with safari for desktop and mobile on ipad. the images I try to arrange are all stuck on the top of each other. Just when I resize the browser window by hand, they arrange in the right way.

I read a lot in the issue part, but couldn't find something that helps me. Also tried the imagesloader, but unfortunately without success, because then the order of the items is not right and it seams like the "grid-sizer is getting in the layout. Also reduced the page to the max.

Does anybody got an idea and can help me?

https://dl.dropboxusercontent.com/u/4716494/20140421/without_imageloader.html
https://dl.dropboxusercontent.com/u/4716494/20140421/with_imageloader.html

**Comment by GeorgeTodea** [comment]
I solve this by putting the initializing in the jQuery(window).load function instead of jQuery(window).ready. In this way the plugin will be activated when the page finishes to load and has time to initialize it.
