### ISSUE TITLE
cannot call methods on masonry prior to initialization; attempted to call method 'on' 

### ISSUE THREAD

**Issue by pedronmo** [desandro/masonry#556]
Hi, can you help me with a problem please?
What I'm trying to do is reload the masonry after it finishes loading.

I have the following code:

$(document).ready(function() {
    var $container = $('.obrasMasonry .listarticles ul');
    $container.imagesLoaded( function() {
        $container.masonry({
            itemSelector: 'li'
        });
    });

```
$container.masonry('on','layoutComplete', function() {
    $container.masonry("reload");
});

//Need this when resiing browser - reloading the organization of masonry tiles
$(window).resize(function() {
    $container.masonry("reload");
});
```

});

And it's always giving me  the error of cannot call methods on masonry prior to initialization; attempted to call method 'on'

**Comment by sim045** [comment]
hi, i have the same error, i'am using masonry on a result page with a filter function like most recent, highest price... etc, the filter uses JavaScript so the page is not reloading and when i click on a filter i lose the masonary effect.
the link of the filter is looking like this:
`<a onclick='sort_directory("<?php echo esc_attr($adminURL); ?>", "<?php echo esc_attr($themeURL); ?>", "recent", this)' href="javascript:void(0)"><?php _e('Most Recent', 'directory'); ?></a></li>`
is there any way to initialize masonary on the click action or something else, sorry i dont know a lot about javascript
