### ISSUE TITLE
IE8 invalid argument

### ISSUE THREAD

**Issue by luzhang** [desandro/masonry#562]
Hi recently I am using the latest version of masonry 3.1.5, it says 'invalid argument', I debugged the error and found this is where the error comes from:
line 15653: elemStyle[supportedProp] = style[prop],  when the prop = top, style[top] = NAN. I think it is because IE8 does not support that 'top' attribute, do we have a fix for that? Thanks!

**Comment by desandro** [comment]
I believe this was a duplicate of desandro/get-size#10. Closing here
