### ISSUE TITLE
Center items

### ISSUE THREAD

**Issue by ghost** [desandro/masonry#565]
There should me an option to center the items.

**Comment by morenoh149** [comment]
I am currently using `isFitWidth` would be nice to be able to provide an additional param so I can get items centered within their calculated columns. I see the items are absolutely positioned.

Example, I'm on mobile. Currently the items are left justified. And as they are absolutely positioned there is no way to center utilizing margins. The `left` option should be non-zero and calculated dynamically.

Let me know if I can assist.
