### ISSUE TITLE
Masonry - reloadItems method not working.

### ISSUE THREAD

**Issue by rajeshgehlawat** [desandro/masonry#566]
I am trying to put content in container by an ajax request and it the image are messed up. I am trying to reload the container elements in ajax success but it doesn't work and above it "Destroy" method is working perfectly fine which not required. Please help. Below is my code:

I only have one div tag on my HTML page with ID container:

And calling below function on document.ready

function list_data(){
    var site_url = siteUrl+'images/ajax_img_data';
    if(data_count == ''){
        $.ajax({
            type: "POST",
            url: site_url,
            async: false,
            data:{page_number:number_of_page},
            dataType: 'html',
            error: function(a,b,c) {
                //overlay_cover("show");
            },
success: function (data) {
                    $('#container').append(data); 
                    $('#container').masonry().masonry('reloadItems');
            }
        });
    }
}

As you see site_url  in above code I am calling an other page(ajax_img_data) and putting its content inside container div and after that calling reloadItems method, but it doesn't seems to be working. And it works when I change the window size. Please see the screen shot below.

![fotoapp - google chrome_2014-06-03_21-19-47](https://cloud.githubusercontent.com/assets/7782782/3162597/eb1e72fe-eb36-11e3-9254-0b56ad28504e.png)

Thanks in advance for your help.

Looking forward for a solution.

Thanks
Rajesh

**Comment by vtmx** [comment]
I have problem with tag video. Today exist any solution?
