### ISSUE TITLE
Refresh masonry container after a change.

### ISSUE THREAD

**Issue by alucardu** [desandro/masonry#568]
I'm using masonry with a drag and drop system. But when I drag a .item out of the masonry container it creates a gap because everything is position absolute. So I was thinking off a way to refresh the content of the div after a change. I've got a small demo here: http://no-illusions.nl/demo/dragdrop/

**Comment by erinmester** [comment]
Hi Desandro,

I love masonry.. thanks for creating it and giving a further explanation above for how to make it work with draggable items.. Could this also be modified to move items around within the container? For example if I had images in my container and I wanted to swap the images into different spots within the container.. I can imagine dragging one image over the location where another image is and they swap places.. This would give the user more control over how the images are arranged within the container so wanted to see if this is possible.

Thanks in advance for your help.

Erin

**Comment by desandro** [comment]
@erinmester See [Packery for drag-and-drop with masonry layouts](http://packeryjs.com).
