### ISSUE TITLE
Responsive design: Option for left positioning to be output as a percentage?

### ISSUE THREAD

**Issue by tbredin** [desandro/masonry#574]
Firstly - I've used masonry quite a lot in the past - wonderful tool! Thanks heaps.

I have something of a feature request - in responsive design, the debounce on the resize event that positions the elements has always bugged me (or rather, more often than not, made our clients unhappy!). 

However, in a fluid responsive grid we usually work in percentages. If there was an option to output masonry 'left' positions as percentages, this issue would almost completely disappear.

**Comment by perry** [comment]
+1

**Comment by ram-you** [comment]
<b>+1</b>

**Comment by Tuckie** [comment]
+1

**Comment by desandro** [comment]
Masonry `v3.3.0` adds [`percentPosition` option](http://masonry.desandro.com/options.html#percentposition) to position percent-width items fluidly. No more re-adjust transitions. :balloon:  Demo: http://codepen.io/desandro/pen/JFpeg

Try it out! If you run into any problems, please open a new issue.
