### ISSUE TITLE
retain masonry effect with Angular JS sorting and filtering

### ISSUE THREAD

**Issue by rdikshit** [desandro/masonry#581]
Please take a look at the fiddle which has Angular JS with Jquery masonry layout. I want to use angular sorting and searching as well. The transitions are not very smooth and also the masonry layout does not seem to be fully functional.

Is there a suggestion on how I can achieve a masonry type affect and include angular with sorting/filtering etc. http://jsfiddle.net/rdikshit/AMbF5/embedded/result/
If there are any custom directives etc that will help me achieve this easily, please suggest. I tried Passy's directive however when I add the sorting and filtering to it, the masonry layout breaks.

**Comment by klihelp** [comment]
check this project https://github.com/passy/angular-masonry
