### ISSUE TITLE
changing to latest masonry from  a very old version causes divs overlapping

### ISSUE THREAD

**Issue by shangsunset** [desandro/masonry#595]
Hi,
this is not really a issue of masonry.
im trying to use this [Gamma gallery](http://tympanus.net/codrops/2012/11/06/gamma-gallery-a-responsive-image-gallery-experiment/) on my site. the version of Masonry this gallery is using is quite old(from 2012 i think, when imagesLoaded was included in masonry) so i changed to the lasted masonry and added imagesLoaded. however, after the change of version, images of my demo are overlapping. so im wondering what could be causing this from migrating to the latest version.

it inits masonry like this:

``` javascript
            Gamma.gallery.imagesLoaded( function() {

                Gamma.gallery.masonry( {
                    itemSelector : 'li',
                    columnWidth : function( containerWidth ) {
                        return containerWidth / Gamma.columns;
                    }
                } );

                if( callback ) {

                    callback.call();

                }

            } );
```

thanks!

**Comment by sydekumf** [comment]
Hi, I have the same exact problem. Your link directs to 404. Can you help me out here?

**Comment by desandro** [comment]
Masonry v2-v3 shim has been moved to https://raw.githubusercontent.com/desandro/masonry-v2-3-shim/master/masonry-v2-3-shim.js
