### ISSUE TITLE
nth-child margin error

### ISSUE THREAD

**Issue by JulianKingman** [desandro/masonry#598]
I was having trouble setting up a responsive fluid masonry blog grid, and narrowed the issue down to where the nth item doesn't have a left margin. The boxes reflow incorrectly. See here:
http://codepen.io/anon/pen/rjqAd

**Comment by desandro** [comment]
Masonry will not work with `nth-child` as Masonry's layout logic rearranges the order of the items.

Instead, use [`gutter`](http://masonry.desandro.com/options.html#gutter).
