### ISSUE TITLE
Masonry not working properly in IE 11

### ISSUE THREAD

**Issue by pgrm** [desandro/masonry#616]
Hi,

in IE 11 (and probably previous versions) masonry not always renders the tiles properly. Specifically what I've seen is that it somehow doesn't take the padding into account. When I changed padding to margin, it worked. The error only shows up when you first visit a page with IE where masonry is downloaded but not used. When you afterwards visit a page where it is used, you get the mentioned wrong rendering.

I've submitted already a [question on stackoverflow](http://stackoverflow.com/questions/26564195/ie-11-doesnt-render-masonry-js-properly) and managed to create a test case: http://server.grman.at/ie11-intro.html

This is the smallest I could get it to reproduce the error. I'm not able to publish it in codepen or similar because of the type of the error, but the referenced files are all static. If you want I can publish it as a github page. 

I'm still not sure if it is a bug in masonry or IE, because all other browsers work smoothly. Also I've created a second intro page: http://server.grman.at/ie11-intro2.html - which doesn't load the masonry library. If you use this, you will see that IE renders everything properly.

PS: For the test cases to be reproducible it might be necessary to clear the cache - I was using private browsing - and don't reload the page with F5, ... Then usually IE starts working properly

**Comment by desandro** [comment]
Closing this issue as the test case URL is no longer working. If you have a live test case I can take another look.

**Comment by pgrm** [comment]
ah yes, that problem was solved in a new masonry version few months ago. Everything is working now, just forgot about this reported issue

**Comment by vbauer** [comment]
I have the same problem with my site (http://android-arsenal.com) on the last version of Masonry (4.1.0):
1 Everything works fine when I open site in browser in the first time.
2. Everything works fine when I refresh page using "Ctrl+R".
3. Padding does not work when I try to navigate on site (click on "Next/Previous" links). In this case, page should be  reloaded and layout should be the same (as in the 1st & 2nd cases), but it is not.

Could you please help me?
