### ISSUE TITLE
How to call masonry reload onClick?

### ISSUE THREAD

**Issue by mmehrle** [desandro/masonry#628]
Pretty simple question - I am using a masonry style layout and need to call upon masonry to refit everything after a 'read more' event which changes the height of one of the divs in my sidebar. This is what happens:
1. I click on a 'read more' link which unhides some text in a div.
2. The containing masonry-brick resizes to accommodate the new text.
3. Unfortunately the bricks below do not push further down as their position and height has been set by masonry.
4. When I slightly resize the window everything moves into the right place.

Therefore the easiest way to trigger this event would be by calling a masonry reload with that click. This is what I have in my page's header right now:

```
<script type='text/javascript'>
$(document).ready(function(){
  $("a.read_more").click(function(){
    alert("Clicked");
    $rootScope.$broadcast('masonry.reload');
    $('#content').masonry('reload');
  });
});
</script>
```

The clicked alert pops up, so I'm sure the function has been bound properly. However no reload of masonry is being triggered. Any help/pointers/suggestions would be very welcome.

Thanks in advance!! :-)

**Comment by manu3021** [comment]
same problem happen with me

var $content = $('#block-views-ideas-block > .view-ideas > .view-content');
	  $("#wg-shw-mr").click(function(){
	  	alert ("hello");
		  $rootScope.$broadcast('masonry.reload');
		  $content.masonry();
	  });

but this code is not work for me can us suggest.
How i can solve this problem

thanks

**Comment by northoutIshan** [comment]
I have tried the same but not working in pagination case. Please suggest what should I do?
