### ISSUE TITLE
Vertical positioning not calculating correctly in Safari

### ISSUE THREAD

**Issue by webgurus** [desandro/masonry#629]
I've set up a masonry grid with bootstrap 3. The elements are positioned beautifully with one exception:

Safari ignores bottom padding/margin of the elements, thus overlapping the elements vertically. The thing is, the overlap is not 100%, somehow it is only disregarding the bottom padding/margin in the height calculation.

Chrome preview:
![chrome_masonry](https://cloud.githubusercontent.com/assets/1938503/5279754/c33b2120-7af0-11e4-803d-3de9e864b6c9.PNG)

Safari masonry
![safari_masonry](https://cloud.githubusercontent.com/assets/1938503/5279755/c33c8e7a-7af0-11e4-8e34-cad34c7cef6c.PNG)

Safari masonry element
![safari_masonry2](https://cloud.githubusercontent.com/assets/1938503/5279756/c33dda00-7af0-11e4-9a18-001dec712c7f.png)

**Comment by desandro** [comment]
Closing as no test case was provided.
