### ISSUE TITLE
Ajax issue: when I load items after a post, I got a mess

### ISSUE THREAD

**Issue by viniciusottoni** [desandro/masonry#630]
I have the following code in the first load of the page:

    if ($(window).width() > 992) {
        $('#masonry').masonry({
            itemSelector: '.col-masonry'
        });
    }

Everything is fine with my items. The problem is when I load the items with a post:

    $.post(loadDealsPost, { idTag: idTag }, function (deals) {
        $('#content').fadeTo(0, 0);
        $("#masonry").empty();

        if ($(window).width() > 992) {
            $data = jQuery(deals).filter('a');
            $("#content").append($data).masonry('appended', $data, true);
            //$('#masonry').masonry({
            //    itemSelector: '.col-masonry',
            //    transitionDuration: 0
            //});
        }

        $("#content").fadeTo(500, 1);
    });

Now I got a mess with the items. (I tried the code that is commented, but nothing works).

**Comment by patrikengborg** [comment]
Try to wrap the masonry call in a setTimeout with a 100 ms delay, solves the issue for me.

**Comment by viniciusottoni** [comment]
patrikengborg

Depending the internet speed this solution won't works. The problem is with
the imgs load, that solve using imagesloaded (
http://imagesloaded.desandro.com/).
ᐧ

2015-01-06 15:25 GMT-03:00 patrikengborg <notifications@github.com>:

> Try to wrap the masonry call in a setTimeout with a 100 ms delay, solves
> the issue for me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/desandro/masonry/issues/630#issuecomment-68908137>.
>



-- 
@INFRAERO/TIVIT - Analista de Sistemas Pleno
@IFPE -  Graduado em Análise e Desenvolvimento de Sistemas
@MCP - Windows Azure (70-583)
@MCTS - ADO.NET (70-516)
@MCTS - WCF (70-513)
@MCPD - Windows Azure

**Comment by patrikengborg** [comment]
@viniciusottoni i'm using imagesLoaded as well, setTimeout is run after that. I don't know why it works, but it does.

**Comment by viniciusottoni** [comment]
@patrikengborg

Depending on your internet connection speed and the number of elements (containing images) won't work the delay.  

So, my code that works is here:

     $('#content').fadeTo(100, 0);
     $.post('/Home/LoadDeals', { idTag: idTag }, function (deals) {
            $("#masonry").masonry('destroy');
            $("#masonry").html($(deals));
            if ($(window).width() > 992) {
                imagesLoaded(document.querySelector('#masonry'), function (instance) {
                    $('#masonry').masonry({
                        itemSelector: '.col-masonry'
                    });
                    $("#content").fadeTo(500, 1);
                });
            }
            else
            {
                $("#content").fadeTo(500, 1);
            }
        });

**Comment by desandro** [comment]
Without a **reduced test case**, we don't have a good way to debug your code. Sorry, but I'll have to close this issue.
