### ISSUE TITLE
gutterHeight ? 

### ISSUE THREAD

**Issue by justnorris** [desandro/masonry#631]
Hi Davis,
Fluid gutterWidths are cool, but I have to add manual `margin-bottom` in pixels if I want vertical spacing. It becomes a problem with fluid gutters using `.gutter-size`. Gutters are fluid horizontally, but not vertically, which isn't esthetically pleasing on some screens. 

Any hope to seeing gutterHeight option that would automatically add the same spacing to heights that widths already have ? If you're too busy - can you point me in the right direction and I can come up with a pull request ?

**Comment by van-nguyen** [comment]
Thanks @desandro, I think this should be included in the main codebase as it helps with calculations for the tiles above and below, CSS cannot do this and the margins don't work quite well.

**Comment by desandro** [comment]
Closing this feature request as it hasn't gotten much interest :whale:
