### ISSUE TITLE
Trouble with multiple masonry containers and imagesLoaded (example provided)

### ISSUE THREAD

**Issue by seetheday** [desandro/masonry#636]
Hi,
Thanks for the great plugin.  I'm having some trouble getting multiple containers to work correctly.
I'm in an environment that makes using jQuery difficult, so I've done everything in regular JS.

I can get everything to work correctly, except imageLoaded.

Here is an example of everything working without imagesLoaded: http://jsfiddle.net/jat7bg17/5/

Here is the example with imagesLoaded (breaking things): http://jsfiddle.net/jat7bg17/4/

I feel like there is something very simple that I'm simply missing and I've been working on this for hours so I thought I'd ask.  Any help is appreciated.

**Comment by z-ax** [comment]
Hey, check here, with layout update after images are loaded: http://jsfiddle.net/jat7bg17/7/

**Comment by desandro** [comment]
Thanks for the example! I think you're running into a problem with using `imagesLoaded` in a loop. From JSHint:

> Function declarations should not be placed in blocks. Use a function expression or move the statement to the top of the outer function

I've refactored your example and it's working just fine: http://jsfiddle.net/jat7bg17/8/

``` js
var containers = document.querySelectorAll('.vrip-container');

for ( var i=0, len = containers.length; i < len; i++ ) {
  var container = containers[i];
  initMasonry( container );
}

function initMasonry( container ) {
  imagesLoaded( container, function() {
    new Masonry( container, {
      itemSelector: '.item'
    });
  });
}
```

**Comment by seetheday** [comment]
Works perfectly.  Thank you very much.
