### ISSUE TITLE
swipebox with masonry

### ISSUE THREAD

**Issue by lironrichkid** [desandro/masonry#637]
hi everyone i tried to put together masonry with swipebox.
but it didnt work till yet (only the first image is opened),
i also want to make the masonry gallery responsive.
how?
http://www.reading3.co.il/he/company/a/gallery/?ContentID=268
you can see the error i get when click in console.

**Comment by desandro** [comment]
1. Looks like you're using an old version of Masonry, v2. I recommend upgrading to [Masonry v3](http://masonry.desandro.com/)
2. I appreciate you providing a live URL, but I won't be able to debug your site. Can you try putting together a  **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by lironrichkid** [comment]
the gallery: in real time it is with photos from server(asp.net)
    <div id="container" class="clearfix rtl centered" >
        <%foreach (PhotoItem p in Photos)
          { %>
          <div class="item">
          <div class="innerItem">
               <a href="<%=p.src%>" class="swipebox">
               <img src='<%=p.src%>' title='<%=p.PhotoTitle%>' />
               </a>
                </div>
          </div>
        <%} %>
    </div>

the code for masonry:
 $(function () {

                    // or with jQuery
                    // initialize Masonry
                    var $container = $('#container');
                    // layout Masonry again after all images have loaded
                    $container.imagesLoaded(function () {
                        $container.masonry({
                            itemSelector: '.item',
                            isRTL: true,
                            isFitWidth: true
                        });

                    });
            
the code for swipebox:
<script type="text/javascript">
;( function( $ ) {

	$( '.swipebox' ).swipebox();

} )( jQuery );
</script>

and the problem as i said only the first image is loaded in the swipebox.

**Comment by lironrichkid** [comment]
???

**Comment by desandro** [comment]
Sorry, but I will not be able to debug your site.
