### ISSUE TITLE
jumping page

### ISSUE THREAD

**Issue by loincom** [desandro/masonry#638]
Hello,

I love your plugin and I am inches to getting it how I'd like. However, when the page loads the boxes are off the screen. When I resize the window the go correctly into place. Is it possible for them to be in correct place before resizing the screen?

http://kilrain.com/version_kl/

Happy new year

**Comment by loincom** [comment]
I figured it out! Turns out that my loader files (main.js) was calling the primary-container. I removed the '$('body').addClass('primary-content');' and it's fine.

I feel so nerdy now!

$(document).ready(function() {
	
	setTimeout(function(){
		$('body').addClass('loaded');
		$('body').addClass('primary-content');
		$('h1').css('color','#222222');
	}, 2000);
	
});

**Comment by desandro** [comment]
Thanks for following up.
