### ISSUE TITLE
Masonry not working for infinite scrolling in Ember

### ISSUE THREAD

**Issue by changeweb** [desandro/masonry#640]
Please check this out [Masonry not working for infinite scrolling in Ember](http://stackoverflow.com/q/27824906/2429040) in Stackoverflow. I really need this to work.

I don't know. Either it is a wrong way of implementing Masonry in Ember with infinite scroll or it is a bug of Masonry. Please help.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by changeweb** [comment]
Here is a **reduced test case**. Please try to scroll to bottom **three** times to see the effect of infinite scroll in **Codepen** & **jsbin**.

+ http://codepen.io/anon/pen/xbgYEN
+  http://emberjs.jsbin.com/zitatizafa/1/edit?output

**Comment by desandro** [comment]
Thanks for that! What's happening is the new items need to be recognized to the Masonry instance. One way to do this is with [`reloadItems`](http://masonry.desandro.com/methods.html#reloaditems). Then, I trigger [`layout`](http://masonry.desandro.com/methods.html#layout) to lay out all items.

``` js
  applyMasonry: function(){
    var $galleryContainer = $('#galleryContainer');
    $galleryContainer.imagesLoaded(function() {
        // check if masonry is initialized
        var msnry = $galleryContainer.data('masonry');
        if ( msnry ) {
          msnry.reloadItems();
          // disable transition
          var transitionDuration = msnry.options.transitionDuration;
          msnry.options.transitionDuration = 0;
          msnry.layout();
          // reset transition
          msnry.options.transitionDuration = transitionDuration;
        } else {
          // init masonry
          $galleryContainer.masonry({
            itemSelector: '.item',
            columnWidth: 150
          });
        }
    });
  },
```

There also some code to disable transition, so items aren't transitioned into place.

**Comment by changeweb** [comment]
Thanks for your help & quick response :smile:. I should have read Masonry Docs properly.

I think you can add something like this in Masonry Doc as example to use Masonry in Ember. I'm going to add this as answer in Stackoverflow.
