### ISSUE TITLE
Empty space between masonry items after using imagesloaded

### ISSUE THREAD

**Issue by bedakb** [desandro/masonry#641]
I had issue with overlapping items, so I find solution - using imagesLoaded plugin.

I follow instructions and It works  - but not fully.Here is URL, so you can see where is problem http://developer.bedakbelmin.com/ .As you see there is a empty space between masonry items.

This is masonry setup:
http://pastebin.com/ytFkVePB

Best,

Belmin

**Comment by desandro** [comment]
Looks like Masonry is not initialized on that page. There's an extra `);` that needs to be removed. Try this code:

``` js
jQuery( document ).ready( function( $ ) {
  var $container = $('#masonry-container');
  $container.imagesLoaded( function() {
  $container.masonry({
    itemSelector: '.brick',
    columnWidth: function(containerWidth) {
      return containerWidth/2;
    }
  });
});
```

**Comment by bedakb** [comment]
Oh I'm sorry on my mistake.

Thank you.
