### ISSUE TITLE
isHorizontal setting just like in packery

### ISSUE THREAD

**Issue by bastienJS** [desandro/masonry#642]
I have looked at all samples from masonry but I could not find any option in masonry which would support an initial layout just like with packery and the isHorizontal:true setting.

We can not use the packery because of its drag/drop behavior because we need to do custom logic when an item is dragged and then dropped e.g. the percentage width of the dragged item must switch to the percentage width of the dropped item (to have a static layout only - only content changes- ) and of course THEN both items must take the other`s item position.

I would be great if you could give me a hint here as its for a commercial application and I have pressure ;-)

**Comment by desandro** [comment]
Isotope has a [masonryHorizontal layout mode](http://isotope.metafizzy.co/layout-modes/masonryhorizontal.html). Have you tried that?
