### ISSUE TITLE
combine container and children percentage width with fixed gutter

### ISSUE THREAD

**Issue by opatry** [desandro/masonry#643]
Hi,

I have a problem similar to the #482 one. I wish my gutters can adapt their width to container to make first and last column stick respectively to left and right.

I tried various combination of `columnWidth` +/- `gutter` +/- `isFitWidth` without success.
The suggested solution based on `max-width` on container seems to be not applicable to me AFAIK (I expect the first and last column to stick on their side).

I might achieve my goal if masonry tell me what items are on first and/or last column through a CSS class  (relates to #271 too but v3 doesn't seems to solve anything for me :disappointed:).
By doing so, I should apply the gutters myself through CSS on child elements of the layed out ones except the last (or first) one.
(to avoid % width combined with px margins on same element).

http://codepen.io/opatry/pen/XJRRgY?editors=110

**Comment by desandro** [comment]
From http://masonry.desandro.com/options.html#isfitwidth

> `isFitWidth` does not work with element sizing with percentage width. 

Sorry, but Masonry cannot support your use case. For `isFitWidth` to work, it requires an explicit set width size of columns. I appreciate you giving this a shot, but it's impossible to do.

**Comment by opatry** [comment]
Yes, that's what I understood.

But what about telling the user which items are the first and last of the current line?

**Comment by desandro** [comment]
This is tricky as Masonry has no concept of 'current line.' All items can be staggered.

Your best shot would be to write custom JS that iterates over item elements and measures their position and width to determine if they are along the left or right edge. I'll leave that up to you.

**Comment by opatry** [comment]
Agreed. I've come to the same conclusion :) I already did that for a specific 2 column use case and I was expecting to use Masonry to generalize this for multi column adaptive and responsive.

I'll try to extend my own solution to multiple column. Thanks for your time.
