### ISSUE TITLE
add ajax on photos load

### ISSUE THREAD

**Issue by lironrichkid** [desandro/masonry#645]
hi im usign masonry in my site and want to add ajax onphotosload
now it looks not very nice:
http://www.reading3.co.il/he/company/a/gallery/?ContentID=268

i want it to look like:
http://haimafriat.com/gallery/events-2/

thanks

**Comment by desandro** [comment]
I recommend looking at this solution:  https://github.com/desandro/masonry/issues/501#issuecomment-34583942

I'm sorry to see you're having trouble with Masonry. I'd be better able to help you if you provided a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by lironrichkid** [comment]
<html>
<head>


  <link rel="stylesheet" href="../css/style.css" />
  <link rel="stylesheet" href="../swipebox-master/src/css/swipebox.css">
  
  
<script src="http://code.jquery.com/jquery-1.8.0.min.js"></script>

<script src="../jquery.masonry.js"></script>
<script src="../swipebox-master/src/js/jquery.swipebox.js"></script>
<script>
$( function() {

  
  var $container = $('#container');
  // hide initial items
  var $initialItems = $container.find('.item').hide();
  
  var $container = $container.masonry({
      // do not select initial items
      itemSelector: 'none',
      columnWidth: 200
    })
    // set option
    .masonry( 'option', { itemSelector: '.item' } )
    .masonryImagesReveal( $initialItems );

  $('#load-images').click( function() {
    var $items = getItems();
    $container.masonryImagesReveal( $items );
  });
  
});

// reveals items iteratively
// after each item has loaded its images
$.fn.masonryImagesReveal = function( $items ) {
  var msnry = this.data('masonry');
  var itemSelector = msnry.options.itemSelector;
  // hide by default
  $items.hide();
  // append to container
  this.append( $items );
  $items.imagesLoaded().progress( function( imgLoad, image ) {
    // get item
    // image is imagesLoaded class, not <img>, <img> is image.img
    var $item = $( image.img ).parents( itemSelector );
    // un-hide item
    $item.show();
    // masonry does its thing
    msnry.appended( $item );
  });
  
  return this;
};

function randomInt( min, max ) {
  return Math.floor( Math.random() * max + min );
}

function getItem() {
  var width = randomInt( 150, 400 );
  var height = randomInt( 150, 250 );
  var item = '<div class="item">'+
    '<img src="http://lorempixel.com/' + 
      width + '/' + height + '/nature" /></div>';
  return item;
}

function getItems() {
  var items = '';
  for ( var i=0; i < 12; i++ ) {
    items += getItem();
  }
  // return jQuery object
  return $( items );
}
</script>
</head>
<body style="width:980px; margin-right:auto;margin-left:auto;">
<div id="container">
  
  <div class="item"><img src="http://lorempixel.com/326/204/nature"></div>
  <div class="item"><img src="http://lorempixel.com/160/254/nature"></div>
  <div class="item"><img src="http://lorempixel.com/277/362/nature"></div>
  <div class="item"><img src="http://lorempixel.com/380/222/nature"></div>
  <div class="item"><img src="http://lorempixel.com/321/237/nature"></div>
  <div class="item"><img src="http://lorempixel.com/154/175/nature"></div>
  <div class="item"><img src="http://lorempixel.com/277/194/nature"></div>
  <div class="item"><img src="http://lorempixel.com/339/177/nature"></div>
  <div class="item"><img src="http://lorempixel.com/438/259/nature"></div>
  <div class="item"><img src="http://lorempixel.com/394/291/nature"></div>
  <div class="item"><img src="http://lorempixel.com/284/292/nature"></div>
  <div class="item"><img src="http://lorempixel.com/193/253/nature"></div>
</div>


</body>
</html>
imagesloaded is undefined
not working it console

**Comment by desandro** [comment]
Sounds like you need to install [imagesLoaded](http://imagesloaded.desandro.com/).

Sorry, but I will not be able to debug this support request.

**Comment by lironrichkid** [comment]
but desandro the example you gave me isnt working with a href 
means:
<div id="container" style="margin-right: auto;margin-left: auto;">
  
  <div class="item"><a href="http://lorempixel.com/326/204/nature"><img src="http://lorempixel.com/326/204/nature"></a></div>
    
  <div class="item"><a href="http://lorempixel.com/326/204/nature"><img src="http://lorempixel.com/326/204/nature"></a></div>
    
  <div class="item"><a href="http://lorempixel.com/326/204/nature"><img src="http://lorempixel.com/326/204/nature"></a></div>
    
  <div class="item"><a href="http://lorempixel.com/326/204/nature"><img src="http://lorempixel.com/326/204/nature"></a></div>
    
  
  <div class="item"><a href="http://lorempixel.com/326/204/nature"><img src="http://lorempixel.com/326/204/nature"></a></div>
    
  <div class="item"><a href="http://lorempixel.com/326/204/nature"><img src="http://lorempixel.com/326/204/nature"></a></div>
    
  <div class="item"><a href="http://lorempixel.com/326/204/nature"><img src="http://lorempixel.com/326/204/nature"></a></div>
  <div class="item"><a href="http://lorempixel.com/326/204/nature"><img src="http://lorempixel.com/326/204/nature"></a></div>
</div>
