### ISSUE TITLE
Do we have a "Disable change position animation" option?

### ISSUE THREAD

**Issue by lmhung** [desandro/masonry#646]
Is there an option to disable elements change position transition? `transitionDuration: 0` disable all transitions, but I want to keep hide and reveal effect.

**Comment by desandro** [comment]
This sounds like an Isotope issue, not quite Masonry. Closing here. Follow along at metafizzy/isotope#855

The same solution does work for Masonry. Add this code

``` js
// disable position transition
Masonry.prototype._positionItem = function( item, x, y ) {
  item.goTo( x, y );
};
```

See example http://codepen.io/desandro/pen/RNgBbN
