### ISSUE TITLE
Tumblr blog: Images overlap with Masonry and Infinite Scroll

### ISSUE THREAD

**Issue by vavvo966** [desandro/masonry#647]
I can't get to work properly Masonry with Infinite Scroll. The problem is that when i scroll down my Tumblr to the last posts, the last images are overlapped. When you refresh the page, the problem is gone. 
This is the code i am using at the moment. Please help me with another code i am completely newbie.

<script type="text/javascript" src="http://static.tumblr.com/imovwvl/dJWl20ley/jqueryformasonry.js"></script>
    <script type="text/javascript" src="http://static.tumblr.com/imovwvl/rSGl20lfv/masonry.js">
    </script>
    <script src="http://static.tumblr.com/df28qmy/SHUlh3i7s/jquery.infinitescroll.js"></script>
    <script src="http://static.tumblr.com/thpaaos/lLwkowcqm/jquery.masonry.js"></script>
    <script type="text/javascript">
     
 
    $(window).load(function () {
    $('.posts').masonry(),
    $('.masonryWrap').infinitescroll({
    navSelector : "div#navigation",
    // selector for the paged navigation (it will be hidden)
    nextSelector : "div#navigation a#nextPage",
    // selector for the NEXT link (to page 2)
    itemSelector : ".entry",
    // selector for all items you'll retrieve
    bufferPx : 10000,
    extraScrollPx: 11000,
    loadingImg : "",
    loadingText : "<em></em>",
    },
    // call masonry as a callback.
    function() { $('.posts').masonry({ appendedContent: $(this) }); }
    );
    });
    </script>
    <script type="text/javascript">$(window).load(function(){$("p").remove(":contains('Source:')");});</script>

**Comment by desandro** [comment]
Sorry, but I won't be able to debug this support request. See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).
