### ISSUE TITLE
Add option to horizontally position bricks based on index

### ISSUE THREAD

**Issue by perry** [desandro/masonry#648]
#### Problem
By default the bricks are packed in to the shortest column, so the horizontal position of the brick is determined by the height of other bricks. This can cause problems with bricks that have dynamic content, bricks may move around the page when the height of other bricks change. It would be nice to position the bricks horizontally based on the index in the list, rather than the the index of the shortest column.

#### Solution

I've created two examples [here](http://jsfiddle.net/Lbqj9fk6/4/), which explains the problem and my solution. Notice the index of bricks in both examples, where the modification reads sequentially row by row. The code modification is on L28-32.

**Comment by desandro** [comment]
Sounds like you're looking for [masonry ordered](http://masonry-ordered.tasuki.org/)

**Comment by perry** [comment]
Thank you @desandro. I was unable to use that plugin as it does not work with masonry `3.x`, or without jQuery.

**Comment by desandro** [comment]
I've opened a new issue to track this feature request. See #873
