### ISSUE TITLE
Refresh masonry while slideDown animation (and not reorder)

### ISSUE THREAD

**Issue by jdmoliner** [desandro/masonry#649]
Hi,

First thank you for this awesome plugin.

I'm need to refresh masonry position while slideDown animation with jQuery. It's possible?. 

I have this example. Yo can see how the ".hide" div hides behind the below ".item"

http://jsfiddle.net/kurtko/t5zcatrx/3/

Also the ".item" order changes after $container.masonry(); , you can see in the example how when click on first item the below item goes to right position. I need the below item to be pushed down.

Thanks.

**Comment by desandro** [comment]
This feature is not available in Masonry. It is available in a custom [layout mode for Isotope v1: masonryColumnShift](http://isotope.metafizzy.co/v1/custom-layout-modes/masonry-column-shift.html).

See metafizzy/isotope#582 If you would like to see this feature be added to Isotope v2.

**Comment by jdmoliner** [comment]
That's just what I wanted. thanks
