### ISSUE TITLE
After filtering wrong position

### ISSUE THREAD

**Issue by levipadre** [desandro/masonry#650]
Hi,

Thank you for the plugin, it's really cool.
I have a question about filtering. The filter function is working good, some elements disappear properly, but the others have wrong position (vertical, not horizontal).
I use this code:
```
var container = $(".boxes");
container.masonry({
    itemSelector: ".box"
});

$('.filter').on( 'click', function() {
    var category = $(this).attr("data-filter");
    $(".box").each(function(){
       if(!$(this).hasClass(category)){
           $(this).hide();
       }
    });
    $(".box."+category).show();
    container.masonry("layout").masonry();
});
```
Do you have any idea, what's wrong with the code?

Thanks,
L

**Comment by levipadre** [comment]
Hi,

I just switched to isotope, and it's working perfectly.

But thank you anyway!

**Comment by domialex** [comment]
I also have this problem. Some items get all positioned vertically.
