### ISSUE TITLE
Problem with masonry with infinite scroll

### ISSUE THREAD

**Issue by vavvo966** [desandro/masonry#651]
Please my post got deleted before, i don't know why. I am a complete newbie but i need this problem fixed cause it's driving me insane.

I have a tumblr blog, and i am using Masonry with Infinite Scroll. The problem is that, when i scroll down to the end of the page, the last images always overlapped. This is the code i am using at the moment
Please help me

<script type="text/javascript">
$(window).load(function () {
$('.posts').masonry(),
$('.masonryWrap').infinitescroll({
navSelector : "div#navigation",
// selector for the paged navigation (it will be hidden)
nextSelector : "div#navigation a#nextPage",
// selector for the NEXT link (to page 2)
itemSelector : ".entry",
// selector for all items you'll retrieve
bufferPx : 10000,
extraScrollPx: 11000,
loadingImg : "",
loadingText : "<em></em>",
 },
// call masonry as a callback.
function() { $('.posts').masonry({ appendedContent: $(this) }); }
 );
 });
 </script>
 <script type="text/javascript">$(window).load(function(){$("p").remove(":contains('Source:')");});</script>

**Comment by desandro** [comment]
Sorry, but I won't be able to debug this support request. See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).
