### ISSUE TITLE
Masony image animation on page load and click: bugs and differents animations

### ISSUE THREAD

**Issue by jdmoliner** [desandro/masonry#652]
Hi,

I'm trying to get same effect like masony home page: when page is loaded the images has an animation. Also I need the same effect when click on button.

I have this code: (I do not know if it's the right way to do what I want)

http://jsfiddle.net/kurtko/u8pz8ytb/

I have the next problems:

1) You can see that the first animation is not equal to animations when I make click.
2) Randomly I get white spaces above and below images (in jsfiddle seems to works fine but in my page with same code not)

Thanks.

**Comment by desandro** [comment]
See https://github.com/desandro/masonry/issues/501#issuecomment-34583942

**Comment by jdmoliner** [comment]
Hi,

I've updated my script with your recomendation but now when I make click on button the items are not added to the top (items maintain the previous position):

http://jsfiddle.net/kurtko/qepv3xmo/7/

Thanks.
