### ISSUE TITLE
Issue with initial display in Chrome

### ISSUE THREAD

**Issue by a-r-taylor** [desandro/masonry#653]
Great product!

My issue happens when I open the page for the first time using Chrome. The tiles overlap vertically. If I refresh the page it displays correctly and stays correct until I shut the Chrome window/tab and then reopen. See the image below:

![chrome-first-load](https://cloud.githubusercontent.com/assets/5340875/5958882/57d3a654-a797-11e4-87ad-fe650c4996c0.png)

Once refreshed or if I open the page in FireFox I get the correct display:

![proper-display](https://cloud.githubusercontent.com/assets/5340875/5958929/b3128f08-a797-11e4-81af-eeaf598463bb.png)

**Comment by jdmoliner** [comment]
Have you used imagesLoaded ?? http://masonry.desandro.com/appendix.html

**Comment by a-r-taylor** [comment]
@jdmoliner - Thanks for the quick reply. I was not using imagesLoaded. I tried it but it created one long line of images instead of the masonry layout. I am sure it is my error. Here is my simple code. I would appreciate your help in properly using the imagesLoaded function.

    $(document).ready(function() {
      $('#masonry-container').masonry({
		columnWidth: 300,
		itemSelector: '.masonry-item',
		gutter: 10
      });	
    }); 

I tried this but got the single column result:

    $(document).ready(function() {
      var $container = $('#masonry-container');
      // initialize Masonry after all images have loaded  
      $container.imagesLoaded( function() {
        $container.masonry({
			columnWidth: 300,
			itemSelector: '.masonry-item',
			gutter: 10
        });
      });	
    }); 

Thanks.

**Comment by jdmoliner** [comment]
How is your css??

it's necessary:
.masonry-item{
 width:300px;
}

**Comment by a-r-taylor** [comment]
This is css I have:

    .masonry-item {
	width: 300px;
    }

	.masonry-item img {
		border: 1px solid rgb(209, 209, 209);
	}

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by a-r-taylor** [comment]
@desandro: thanks for a great library. 

I don't know how I would strip everything out to produce a reduced test case. The site is built using ProcessWire, Semantic-UI, etc. The problem is likely an interaction between Masonry and something else (maybe) so stripping out all the other stuff to create a reduced test case probably won't work. Is there another option?

Cheers,
Anthony

**Comment by desandro** [comment]
Sorry, but I won't be able to resolve this.

A reduced test case allows others to efficiently identify what could be problem. It not only helps others, but it will help you get the root of the problem.
