### ISSUE TITLE
Percentage Column Width + Pixel Gutter

### ISSUE THREAD

**Issue by themesociety** [desandro/masonry#654]
I really tried everything i can imagine at the moment thats why iam here at the source. :)

I try to set up a masonry container with a percentage column width (1 column = 8.3333%) in connection with a pixel gutter, is this even possible? Everytime the last column breaks and it looks like the gutter gets multiplied by the column width. Let's say (like in the example) i have an column width of 25% (3*8,3333%) it looks like that the 10px gutter is multiplied by 3.

Is there anything iam doing wrong here?

Here is a little jsfiddle:
http://jsfiddle.net/chickberger/4x6a033n/2/

----------------
In case that doesn't work, another question: My original plan was to do the gutter with the bootstrap 3 paddings (left and right padding, box-sizing set to border-box) but i think there is no chance to get rid of the leff and right padding for the first and the last item of a row? (left padding for the first, right padding for the last item) Normally this is done by a wrapper div with a negative margin but for my masonry container that doesnt have any effect.

Thanks a ton David!
Keep up the great work!

**Comment by andri** [comment]
+1 This is pretty much the standard in grid system these days. Percentage width and fixed gutters.

**Comment by rlam3** [comment]
+1 Is there a workaround? This is really annoying.

**Comment by desandro** [comment]
One way to accomplish this is by using `calc` values for the width of the items. See demo http://codepen.io/desandro/pen/RPxeKq

This demo has 4 columns, with 20px gutters.

``` css
.grid-sizer,
.grid-item {
  width: calc( ( 100% - 60px ) / 4 );
}

.grid-item--width2 {
  width: calc( ( 100% - 60px ) / 2 + 20px )
}
```

**Comment by rlam3** [comment]
this would require every single grid item to have a class of .grid-item--width2 right? Would it be better to have instead of 'columnWidth' to 'numberOfColumns'?

**Comment by desandro** [comment]
> this would require every single grid item to have a class of .grid-item--width2 right?

No. `.grid-item--width2` is for items that span 2 columns in that demo

> Would it be better to have instead of 'columnWidth' to 'numberOfColumns'?

Not a bad idea. But users might run into a snag with media queries, when a layout shifts from 4 columns to 2. Element sizing resolves this as it relies on CSS, without having to add extra configuration JS.
