### ISSUE TITLE
isOriginTop False an stamp together isn't working

### ISSUE THREAD

**Issue by ElHamster** [desandro/masonry#655]
Good Morning,

for an new Element on our Website we try to use Masonry.
The Problem is, when we try to use isOriginTop : false an stamp together the MS-Elements lying other the Stamp.

I think Masonry doesn't check the Top-value of the stamp, but maybe I have an bug on my Code: http://codepen.io/anon/pen/jEaBrZ

We use Masonry v.3.2.1 an jQuery 1.10.1

Thanks for your help!

**Comment by desandro** [comment]
Sorry to say, this is how stamps work. They need to be anchored to the origin side. For normal top-down Masonry, they need to be anchored to the top. For your use case, with `isOriginTop: false`, they need to be anchored to the `bottom`.
