### ISSUE TITLE
Weird issue with older iPad, masonry breaks on reload.

### ISSUE THREAD

**Issue by fschroiff** [desandro/masonry#656]
I have an iPad 3 (retina, iOS 8). Masonry does a weird thing: 
- on first load items are laid out correctly
- reloading the page items are still layed out just fine
- go to another page and click a link back to the page with masonry and all items stack up on each other. 

Inspecting Safari on the iPad shows that Masonry does its work, the offsets are correctly added and the container is correctly sized. Only in the "computed" column it shows 0px for top and left. There is nothing in the CSS that would override Masonry. 
![screen shot 2015-02-07 at 15 10 58](https://cloud.githubusercontent.com/assets/660010/6092450/d3637b4c-aedf-11e4-8f34-9f59e47f06cd.png)

No reduced test case, but a production site, sorry... http://resultaten.pvda.nl/

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. I appreciate you providing a link to the live site, but I will not be able to debug you production site. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by fschroiff** [comment]
I believe this is related to aggressive caching / CDN. When I test locally there are no issues. Can't create a test case, sorry. I'll just remove the CDN from the site. Feel free to close.

**Comment by desandro** [comment]
Thanks for following up!

**Comment by fschroiff** [comment]
What seems to have solved this for me ultimately was moving the masonry call outside of `$(document).ready` and into `$(window).load`.

**Comment by fschroiff** [comment]
Wrong. What seems to have "solved" this for me ultimately was checking the referrer and switching the link back to the masonry page with a history back link, which works but feels a bit hacky. 

I still have no idea what was going wrong here. Masonry works correctly, it could be a browser bug, related to caching, or to the headers sent by the CDN. I am not able to get to the cause of this. When I have time I'll create a reduced test case and let smarter people look at it.
