### ISSUE TITLE
How to reload Masonry, when adding new items with AJAX?

### ISSUE THREAD

**Issue by userium** [desandro/masonry#657]
I'm using the Masonry Rails gem, which works well at first, my site looks like this: 

![screen shot 2015-02-12 at 09 29 32](https://cloud.githubusercontent.com/assets/3704631/6167834/34d06002-b2c8-11e4-845d-76740e145e29.png)

But on each AJAX request it breaks; it ends up looking like this, with all the divs stacked on top of each other:

![screen shot 2015-02-12 at 15 01 59](https://cloud.githubusercontent.com/assets/3704631/6167841/448c7080-b2c8-11e4-96df-77bc17c70f8b.png)

Here is my application.js:

        $(function(){
             $('#masonry-container').masonry({
                  itemSelector: '.box',
         });
       });

When adding new items with AJAX, they aren't getting the masonry applied. 

I found similar questions online, but I'm not sure if I should use 'reload', 'reloadItems' or 'appended' on masonry, and if so, where should I place the code?

I tried e.g., which didn't work for me:

       $(function(){
               $('#masonry-container').masonry({
                    itemSelector: '.box',
             }).masonry('reloadItems')};
         });

How could I get it to work when I add new items with AJAX?

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by userium** [comment]
Thanks for your reply! I managed to solve it with the following (source: http://stackoverflow.com/questions/16987782/how-to-trigger-reload-masonry-plugin-on-click/23085476#23085476):

    $(function(){
        $('#container').masonry({
            // options
            itemSelector : '.item',
            columnWidth : 260
       });
    });

    var masonryUpdate = function() {
        setTimeout(function() {
            $('#container').masonry();
        }, 0);
    }
    $(document).on('click', masonryUpdate);
    $(document).ajaxComplete(masonryUpdate);

Now it works, though I'm not sure how much it will slow down my page load..
