### ISSUE TITLE
Using with cleanslate

### ISSUE THREAD

**Issue by bvarga** [desandro/masonry#658]
Hello,

I'm trying to use masonry with [cleanslate](https://github.com/premasagar/cleanslate), which reset my css with !important, so every style I set had to suffixed with !important. 

As I see masonry put it's styles info into the element's *style* attribute, but for me every style property should be suffixed with !important.

I tried to suffix every style attribute with !important after the layout completed (in layoutComplete event), but it didn't worked.

any idea?
thanks

**Comment by desandro** [comment]
Hi there! Sorry to hear you're having trouble. I don't think Masonry is going to work with Cleanslate. Cleanslate is designed to override styles. Masonry sets its own styles. I recommend not using one or the other. (I advise not using Cleanslate as it is overly powerful and could lead to other problems, like the one you're experiencing here).
