### ISSUE TITLE
Loading list

### ISSUE THREAD

**Issue by bdadev** [desandro/masonry#659]
hey buddy!

Please help me with this [site](http://kodifik.com.br/web/clipping.php)
Charging parace be breaking.

Have I done something wrong?

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).
