### ISSUE TITLE
masonry and jquery draggable elements get bounded to container

### ISSUE THREAD

**Issue by zonnedauw** [desandro/masonry#661]
I have a drag and drop functionality for a website that is working fine. A can drag elements accross the page to any other box (div) and they stay visible outside that box.

However, when I apply jquery masonry to a div to stack the elements within this div the draggable elements are bounded to that div.
I can drag and drop them outside the box, but outside the box they disappear like they go behind all other elements on the page. When you drop them in an other box they appear again.

I have created two drag and drop test pages: one without masonry:
http://in-casting.com/2014/zzz_tesppage_drag_and_drop_without_masonry.asp

and one with masonry:
http://in-casting.com/2014/zzz_tesppage_drag_and_drop_with_masonry.asp

So you can see the difference.
Why are the draggable items after applying masonry bound to the div box?
And more important how can I resolve this?

I figured out that removing max-height and setting overflow to visible in the css resolves te problem. However, I realy don't want a extremly long div box to drag the items from...

**Comment by desandro** [comment]
I'm sorry to say that Masonry does not work with draggable UI. I recommend using [Packery](http://packery.metafizzy.co/), which was designed to be used with draggable UI.

**Comment by zonnedauw** [comment]
Hey desandro,
Thank uou for your answer and compliments on your work by the way great scripts!

I have seen packery also and tried it in this instance:

http://in-casting.com/2014/zzz_tesppage_drag_and_drop_with_packery.asp

However, the same problem occurs.
I can not figure out how to use the drag and drop functionality with stacking the results and using an overflow setting on the div box...
