### ISSUE TITLE
Multiple Masonry in the same page.

### ISSUE THREAD

**Issue by myuseringithub** [desandro/masonry#662]
How do I activate multiple independent Masonry divs in the same page ? 
Whenever I try adding another masonry only the first one shows up and the second is hidden. Does your  javascript supports multiple masonry working independently on the same page ?

Thanks you, other than that its a great tool.

**Comment by desandro** [comment]
Yes, multiple masonry instances work just fine. Consider all the [demos in the docs](http://masonry.desandro.com/options.html).

Here's a basic example with 3 instances that are initialized with HTML.

http://codepen.io/desandro/pen/VYXaYY

 Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by myuseringithub** [comment]
Thank you, after initializing masonry with class rather than id (var $masonry = $('.masonry'); in masonry loader .js), and adding 'masonry' class to the div instead of id, it worked perfectly. Maybe just one little problem is that the ajax loader is not hiding anymore when multiple masonry divs are called, but this is probably problem in my code.

**Comment by myuseringithub** [comment]
Fixed it. I did also add class to ajax loader and $('.ajax-loader').hide(); after masonry loads images.
Thanks.

**Comment by SirBirdy** [comment]
how can I update the layout of all with vanillaJS? msnry.layout() updates just my last one
