### ISSUE TITLE
Lazy loading as many boxes as screen height can handle?

### ISSUE THREAD

**Issue by Genesis-Software** [desandro/masonry#663]
Masonry still our choice of grid to use firstly. Q. Rather than loading in say ten images which on a mobile may take up 5 page scrolls or on a high resolution monitor may only take up one row leaving lots of blank space, is there a way to lazy load as many images as possible until the container holding the items is "full"? And then when the user scrolls down the page then it knows how many more images to load depending on container height? Many thanks. Olly.

**Comment by desandro** [comment]
Yes, what you are requesting is possible, but it would require developing a custom solution. This functionality is not build in to Masonry by default.

Looking [at the source](https://github.com/desandro/masonry/blob/v3.2.2/masonry.js#L153), after every set of items is laid out, Masonry calculates its height in `this.maxY`. You could keep adding items with `appended` method, similar to https://github.com/desandro/masonry/issues/501#issuecomment-34583942 Until `maxY` is greater than the value you set.

**Comment by Genesis-Software** [comment]
Many thanks for quick reply and i will indeed now look to use this.maxY in a custom solution and lazy load in the data. Appreciate your response.
