### ISSUE TITLE
Bootstrap + Masonry works not as expected with firefox

### ISSUE THREAD

**Issue by mantenie** [desandro/masonry#666]
Especially when I have a col-*-4. This is a 33% column.
Normally and in other browsers like Safari or Chrome masonry renders 3 columns. But in Firefox there are just two and one empty column.

**Comment by mantenie** [comment]
Ah, I see:
This behaviour should be solved in pull request: https://github.com/desandro/masonry/pull/580

**Comment by desandro** [comment]
Masonry v3.2.3 has shipped with a pixel rounding fix that should resolve this issue. [Try updating](http://masonry.desandro.com)! Closing here.
