### ISSUE TITLE
newbie question

### ISSUE THREAD

**Issue by zakriazubair** [desandro/masonry#667]
Hi

I am trying to make Masonry work on my website www.merekhayaal.com; have added the JS script and initialized it in header. Have created divs within a container and pointed the script to the id's I used in making them. The images are not moving / Masonry isnt working as intended. I know the answer is probably a very simple one but I am new to this.

many thanks!

**Comment by desandro** [comment]
If your layout has images, I recommend using imagesLoaded. See http://masonry.desandro.com/appendix.html#imagesloaded

You probably want to set `columnWidth` to a common multiple of the widths of the items. For example, if item widths are 200, 300, 400, set `columnWidth: 100`. Your items have widths of 296 and 466 don't  have a common multiple, but you could try `250`.

**Comment by zakriazubair** [comment]
Thanks. I cant figure out how to get imagesloaded to work with Masonry, I
ve read they came together a while ago.
