### ISSUE TITLE
When first masonry 'item' is hidden all remaining items form into a single column

### ISSUE THREAD

**Issue by jmclaren7** [desandro/masonry#668]
Using jquery to hide and show masonry items i found that the layout failed when the first item in the markup is hidden. I'm not that experienced with JS but i did a lot of testing and googling and i get the feeling this shouldn't be happening.

In the below codepen you can reproduce the result by pressing "Make" and then "Hide", if you remove class "special" from the first div then the layout works as it should. I reproduced this in latest Chrome, FF and IE

http://codepen.io/anon/pen/MYGOLw

**Comment by desandro** [comment]
Thanks for taking a look at this. To resolve this, set `columnWidth`. See http://codepen.io/desandro/pen/RNyyrY

The [docs state this is how `columnWidth` works](http://masonry.desandro.com/options.html#columnwidth). The docs also recommend setting `columnWidth`.

**Comment by jmclaren7** [comment]
Thanks, and thanks for the great work. I didn't even think of that but something i forgot to include in my example is that i was trying to use items with a dynamic width, which leaves me with the same problem as before and it doesn't look like columnWidth can accept a percentage. 

Perhaps it's an unusual use case or not intended, the pen below better demonstrates what i'm doing, however i did come up with a hack to make it work, i'm just curious if i missed something that would allow me to do this a little more proper:

http://codepen.io/anon/pen/gbzZmq

With an empty/offscreen div it works like a charm. When Masonry is performing layout and looks for the first item, couldn't it look for the first item with display not equal to none?

**Comment by desandro** [comment]
Use element sizing with a proxy element, like `.grid-sizer`. See [`columnWidth`](http://masonry.desandro.com/options.html#columnwidth) and demo  http://codepen.io/desandro/pen/JFpeg

**Comment by tehp** [comment]
`.grid-sizer` fix is perfect! Thank you @desandro :clinking_glasses:
