### ISSUE TITLE
How to initialize Imageloaded via HTML

### ISSUE THREAD

**Issue by zakriazubair** [desandro/masonry#669]
Hi, on my site www.merekhayaal.com I have initialized Masonry via html as i was having problems with jquery, but now since I am using images and need to implement ImagesLoaded, I cant seem to make it work. 

I have added following scripts to header:
<script src="/js/masonry.pkgd.min.js"></script>
<script src="/js/imagesloaded.pkgd.min.js"></script>

My code for the HTML is 
<//div id="container" class="js-masonry"
  data-masonry-options='{ "columnWidth": 320, "itemSelector": ".masonryitem" }'>
<//div class="masonryitem"><img alt="" src="image" /></div>
<//div class="masonryitem"><img alt="" src="image" /></div>
</div>

I tried adding the code from Appendix to header:
var container = document.querySelector('#container');
var msnry;
// initialize Masonry after all images have loaded
imagesLoaded( container, function() {
  msnry = new Masonry( container );
});

but imagesLoaded doesnt activate. Also if I tried increasing the width of parent container by then it stops being responsive when using width tag and nothing happnes when using max-width tag..Regards

**Comment by desandro** [comment]
Unfortunately, you cannot initialize imagesLoaded within HTML. Instead, initialize imagesLoaded and Masonry with jQuery.

``` js
$(document).ready( function() {

  var $container = $('#container').imagesLoaded( function() {
    $container.masonry({
      columnWidth: 320,
      itemSelector: '.masonryitem'
    });
  });

});
```

Be sure to remove `js-masonry` class from `#container`.
