### ISSUE TITLE
Safari-only problem: "left" position property always 0

### ISSUE THREAD

**Issue by Illyria** [desandro/masonry#67]
I'm having an issue getting masonry to work correctly in Safari: Masonry is loaded correctly but the elements are not put into two columns as in all other browsers (opera10.62, firefox 3.68, IE7+8). In Safari the plugin sets the "left" property of the masonified elements to 0 when it should be 360px as in the other browsers.
All images have widths and heights set. I also tried this without using any images and without embedded fonts - no change. Any help would be appreciated very much.

This is the page concerned: 'http://tangomitstil.de/news/'

Comments

lukeshumard about 15 hours ago | link 

maybe you could try setting the width of the masoned container, .content? try setting it's width to 900px just to try it out.

Illyria 4 minutes ago | link | edit | delete 

Thx for the quick reply. Tried giving .content a width and also the .wrapper element but didn't help. Could this be related to Safari loading stylesheets and scripts almost at the same time?

**Comment by GeorgeTodea** [comment]
I solve this by putting the initializing in the jQuery(window).load function instead of jQuery(window).ready. In this way the plugin will be activated when the page finishes to load and has time to initialize it.
