### ISSUE TITLE
Cannot find module './item' in '/bower_components/masonry/dist'

### ISSUE THREAD

**Issue by reggi** [desandro/masonry#670]
I'm using browserify with a shimmed version of `masonry.pkdg.js` from bower thats using `deamdify`, I know this use case isn't novel, but I found that 

I believe it's referring to "./item" here which doesn't exist in the directly.

https://github.com/desandro/masonry/blob/master/dist/masonry.pkgd.js#L2714-L2733

```
Error: Cannot find module './item' from '/Users/thomas/Desktop/holstee-browserify/bower_components/masonry/dist'
    at /Users/thomas/.nvm/v0.10.32/lib/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
    at load (/Users/thomas/.nvm/v0.10.32/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/thomas/.nvm/v0.10.32/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /Users/thomas/.nvm/v0.10.32/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at Object.oncomplete (fs.js:107:15)
```

**Comment by desandro** [comment]
If you're using Browserify, then I recommend installing masonry with npm and using the npm module

``` bash
npm install masonry-layout
```

See [Masonry - Browserify](http://masonry.desandro.com/appendix.html#browserify) docs.

`masonry.pkgd.js` is designed for people that want host and link a single `.js` file.

**Comment by reggi** [comment]
Thanks!
