### ISSUE TITLE
images overlapping after upgrade wordpress to 4.1.1

### ISSUE THREAD

**Issue by fotothink** [desandro/masonry#671]
hi,
my theme was working fine until i upgrade to wordpress 4.1.1.... so i build a new test responsive theme on localhost, the issue remains, overlapping images, have to resize the browser to make it worked... but it works perfect in html template instead... here s the snippet i use in functions.php

	//enqueue scripts and styles

	add_action('wp_enqueue_scripts', 'fotothink_theme');

	function fotothink_theme(){
	
		wp_enqueue_script( 'jquery-jquery');
		wp_enqueue_script( 'jquery-masonry');
		wp_enqueue_script( 'modernizr', get_template_directory_uri() . '/js/modernizr-transitions.js');
		
		wp_enqueue_style( 'main-style', get_template_directory_uri() . '/style.css');
		wp_enqueue_style( 'reset', get_template_directory_uri() . '/css/reset.css');
		wp_enqueue_style( 'mobile', get_template_directory_uri() . '/css/mobile.css');
	}

	if ( ! function_exists( 'my_theme' )) :
	function my_theme() { ?>
    <script type="text/javascript">
      $(function(){
				// initialize Masonry
				var $container = $('.container').masonry();
				// layout Masonry again after all images have loaded
				$container.imagesLoaded( function(){
					$container.masonry({
						itemSelector : '.box',
						columnWidth: 1,
						isAnimated: true
					});
				});
			});
    </script>
	<?php }
	//add to wp_footer
	add_action( 'wp_footer', 'my_theme' );
	endif; // ! my_theme exists

i ve been tried so many methods but no lucks, thanks for helps...

**Comment by desandro** [comment]
Sounds like you might be missing [imagesLoaded](http://imagesloaded.desandro.com/). Can you confirm you have [imagesloaded.pkgd.min.js](http://imagesloaded.desandro.com/imagesloaded.pkgd.min.js) on your page?

**Comment by fotothink** [comment]
thanx for ur reply man, i tried that but no luck either...
but i worked it out yesterday, weird thing is when i deactive the lazy load plugin, it works ok now. must be some conflicts with the new version of masonry, cuz this never happen to the v2 masonry before...

**Comment by desandro** [comment]
Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by fotothink** [comment]
how to do it? it works perfect in html template. mine s just conflict with the wordpress plugin lazy load. 
but here comes the new one: query_posts('orderby = rand') didnt work now.......
