### ISSUE TITLE
Layout broke with css padding bottom 

### ISSUE THREAD

**Issue by SuperstrongBE** [desandro/masonry#672]
On a grid with percent based width and padding-bottom height
The layout broke (some item is missplaced not completely broken! ! )on short range of resolution (will broke between 1052px to 1056px upper is ok until 1180 to 1191px )

This is a reduced test case.

With these css declaration
#content .grid-entry {

background-color:#E2E2E2;

}

    #content .w1 {
        width: 20%;
    }
    #content .w2 {
        width: 40%;
    }
    #content .w3 {
        width: 60%;
    }
    #content .w4 {
        width: 80%;
    }
    #content .w5 {
        width: 100%;
    }
    #content .h1 {
        padding-bottom: 20%; 
    }
    #content .h2 {
        padding-bottom: 40%; 
    }
    #content .h3 {
        padding-bottom: 60%; 
    }
    #content .h4 {
        padding-bottom: 80%; 
    }
    #content .h5 {
        padding-bottom: 100%; 
    }

and this JS

$grid.masonry ({
	columnWidth:'.w1'
	,gutter:0
	,itemSelector:'.grid-entry'
})

on this HTML

<div class="grid-entry w1 h1">
</div>

-- Right grid 
![capture d ecran 2015-02-26 14 17 40](https://cloud.githubusercontent.com/assets/1812457/6392601/96eb9fd6-bdc2-11e4-9df0-b7a193fc5f63.png)

-- With missplaced element
![image001](https://cloud.githubusercontent.com/assets/1812457/6392611/ad2e6896-bdc2-11e4-9319-2a318c30f13f.jpg)

Occurs en IE9 IE10 and IE11 FF latest and chrome 40.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by SuperstrongBE** [comment]
Thank for responding, it' no longer an issue.
