### ISSUE TITLE
'noop' is undefined, IE8

### ISSUE THREAD

**Issue by mikefrancis** [desandro/masonry#673]
I'm getting `'noop' is undefined` when testing a site in IE8 which stems from the masonry-layout package.

After doing some searching around, I noticed the [same bug had been fixed](https://github.com/metafizzy/isotope/issues/860) by yourself (@desandro) a couple of days ago on isotope.

I've tried updating masonry-layout with npm and I don't think this package has been updated yet.

Just wondering if this could be fixed on masonry too? Hopefully it's the same fix and it's simple to do.

**Comment by desandro** [comment]
Thanks for reporting this issue. I just installed `npm install masonry-layout`. Masonry v3.2.2 was installed,  and `masonry.pkgd.js` includes getSize v1.2.2, which has this fix. Can you confirm you're able to install Masonry v3.2.2?

**Comment by mikefrancis** [comment]
Ah, that's strange - `npm update` didn't seem to do anything, but a fresh install is indeed v3.2.2.

Thanks for your help, working fine now :smile:
