### ISSUE TITLE
Space available but it breaks anyway

### ISSUE THREAD

**Issue by Itrulia** [desandro/masonry#674]
In the example I have 3 columns with each 33.33% width. When the window is at 940px each column takes 313px. But masonry only displays 2 columns and breaks the third one down.

Demo: http://jsfiddle.net/1kdo3tdm/ (you have to resize the preview)

**Comment by desandro** [comment]
The grid CSS framework you are trying to use is designed for flexible boy layout (flex-box). This may not be compatible will with Masonry, which typically uses floats for fallback layout.

The problematic CSS is:

``` css
.grid {
  padding-right: 0.375rem;
  padding-left: 0.375rem; 
}
```

If you remove this CSS, Masonry works fine: http://codepen.io/desandro/pen/OPErEG/

What CSS framework is this? This could help other users to know.

**Comment by Itrulia** [comment]
Seems strange that this is happening. The grid works like a charm without masonry.
It is part of a framework i am writing for the rewrite of project of mine.

**Comment by desandro** [comment]
I'm closing this is an edge case. Please report back if do find a solution.
