### ISSUE TITLE
Masonry with BJ Lazy Load

### ISSUE THREAD

**Issue by GeorgeTodea** [desandro/masonry#676]
Hello, 

I am using Masonry with https://wordpress.org/plugins/bj-lazy-load/ and the problem is that on lower screens or even on normal (only sometimes), there is a gap after first element or before last element. A gap bigger than I am using between them. You can see a screenshot here: http://i.imgur.com/iRcLmC1.png. As you can see from ss, there is the gap I needed at the top, but before last element it shows that huge gap.

If I deactivate the bj lazy load, it works fine. I have also tried to put the masonry js and the loading in the footer.php, so it loads after bj lazy load. But still nothing. 

Do you have any idea how to solve this? Thank you.

**Comment by desandro** [comment]
Hi there! I'm sorry to see you're having trouble with Masonry.

What's likely happening is that BJ Lazy Load is adding one image with a different size, then replacing that image with another size. You need a hook to layout Masonry after images have been loaded. You could try using [imagesLoaded](http://masonry.desandro.com/appendix.html#imagesloaded).

**Comment by GeorgeTodea** [comment]
First of all, thank you for your response. 

I have downloaded from here http://imagesloaded.desandro.com/ the js, included it. Then in my custom.js tried this:

var container = jQuery('.blog .mason-container');
	container.imagesLoaded( function() {
		  container.masonry({
			itemSelector: '.blog-column',
			columnWidth: '.blog-column'
		});
	});

And still same thing. Am I doing something wrong?

**Comment by desandro** [comment]
Hmm, let's try this:

``` js
// use $ argument for jQuery
jQuery(document).ready( function( $ ) {
  var $container = $('.blog .mason-container').masonry({
    itemSelector: '.blog-column',
    columnWidth: '.blog-column'
  });

  $container.on( 'load', function( event ) {
    $container.masonry();
  });
});
```

**Comment by GeorgeTodea** [comment]
Nope, still the same. I will try to search for more information about this conflict. Thank you so much for answering and trying to help me.

**Comment by sarun007** [comment]
I have same problem I have added your given code 

```
jQuery(document).ready( function( $ ) {

  var $container = $('.masonry-wrapper').masonry({
    itemSelector: '.grid-item',
    columnWidth: '.grid-sizer',
      percentPosition: true
  });

  $container.on( 'load', function( event ) {
    $container.masonry();
  });

});
```

Its not working for me could you please provide solution for this issue ??
