### ISSUE TITLE
masonry reload issues after removing then adding items

### ISSUE THREAD

**Issue by longestdrive** [desandro/masonry#678]
I'm playing around with masonry.js for a gallery/album view.

I've succesfully used the script to display a thumbnail of albums. When the user clicks the thumbnail I want the album thumbnails to be removed and then replaced with the thumbnails of the images within the album.

The album images are passed to the script via ajax and are in html format

I can remove the items using this code $container is a jquery object of the masonry container:

    var obj = $('.item');
    $container.masonry('remove',obj);
    $container.masonry('reloadItems');
    $container.masonry('layout');

I then append the new thumbnails using this script - data is the html of the new elements.

    var $newItems = $(data);

    $container.append($newItems).masonry('appended', $newItems);

    $container.masonry('reloadItems');
    $container.masonry('layout');

This loads the new thumbnail elements and organises the layout. However because of the append it places them at the bottom of where the removed thumbnails were leaving whitespace above the new images

If I use prepend the images are placed at the top of the element as expected but I'm then left with loads of white space where the removed items were.

I've also tried html() to insert the new items - a layout is applied but the height of the container becomes inconsistent and some items overlap the bottom of the container.

So:

How can I remove items and clean up the layout - what is the correct order of applying methods
How can I add new items and clean up the layout - what is the correct order of applying methods

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by longestdrive** [comment]
Hi. I've created a reduced test case - http://codepen.io/longestdrive/pen/bNmjWe

I can replace the items once but repeating this corrupts the layout.
Click the 1st button then the 2nd button - then try the buttons again to see the corruption

**Comment by desandro** [comment]
Thanks for putting that together! Looks like you came across a bug with how remove works. This will be fixed in an upcoming release of [Outlayer](https://github.com/metafizzy/outlayer). Until then, you can resolve this by adding this code:

``` js
Outlayer.Item.prototype.removeElem = function() {
  this.element.parentNode.removeChild( this.element );
  // remove display: none
  this.css({ display: '' });
  this.emitEvent( 'remove', [ this ] );
};
```

See updated CodePen http://codepen.io/desandro/pen/bNmxEY

**Comment by longestdrive** [comment]
Thank you - ill give it a go. I just inspected the masonry data - in my script it appears to be retaining the items I removed for example I started with 4, removed them then added 4 new items = however there are now 8 items in the data - so assume it's not completely removing them.

**Comment by desandro** [comment]
This fix was implemented in Outlayer v1.4.0, Masonry v3.3.0, released last year. This issue should now be resolved.

**Comment by Ceyar** [comment]
Hello,
I have a similar issue. I'm trying to remove items and replace them by other new items got by ajax request.

My code is the same as the example:
**Jquery**

```
jQuery(window).load(function () {
    // My grid container
    var gridContainer = jQuery('#portfolio-container');

//    Starting masonry
    jQuery(gridContainer).masonry({
        itemSelector: '.grid-item',
        percentPosition: true,
        columnWidth: '.grid-sizer',
        gutter: 23
    });
    
    // Ajax call
    jQuery.post(
            ajaxurl,
            {
                'action': 'pomzed_load_portfolio'
            },
            function (response) { 
                
                jQuery('#test-button').click(function () {
                    
                    var itemGrid = jQuery('.grid-item');
                    
                    // Remove old items with masonry
                    gridContainer.masonry('remove', itemGrid);
                    gridContainer.masonry('reloadItems');
                    gridContainer.masonry('layout');
                    
                    // Add new items
                    gridContainer.prepend(response).masonry('prepended', response);
                    gridContainer.masonry('reloadItems');
                    gridContainer.masonry('layout');
                });
                var msnry = Masonry.data(jQuery(gridContainer)[0]);
                console.log(msnry);
            }
    );
});
```
**Html**
```
<!--My masonry Container-->
<div id="portfolio-container" class="grid" style="position: relative; height: 880.359px;">
    <div class="grid-sizer"></div>
    
    <!--My items-->
    <a href="#" class="permalink-single-portfolio grid-item">
        <img src="img" class="thumb-wall-portfolio wp-post-image" alt="Texte alternatif" >
        <img class="thumb-wall-portfolio" src="" alt=""> 
        <div class="title-article-wall-container color-design-graphique">
            <div class="sub-title-article-wall-container">
                <h2 class="title-article-wall">Testing Amazing guys</h2>
            </div>
        </div>
    </a>
    
    <!-- and here more items…  -->
    
</div>
```
link test to the website: [Website](http://dev.pomzeddesign.ch/portfolio/)
Click on the TEST button remove the old items and prepend the new items.

As you can see, the height of my container is big as like the olders items were always there. But if I move the windows size, the grid come again nice with the good height.

I console.log the masonry data, and they said there is more items than displayed.

I tried adding this piece of code but nothing was changing:

```
Outlayer.Item.prototype.removeElem = function() {
  this.element.parentNode.removeChild( this.element );
  // remove display: none
  this.css({ display: '' });
  this.emitEvent( 'remove', [ this ] );
};
```

What can I do to debug this?

I'm using the version 4.1 of masonry. 

Thank's in advance and best regards.

**Comment by desandro** [comment]
@Ceyar sorry, but I won't be able to debug this issue.
