### ISSUE TITLE
Get rid of the whitespace.

### ISSUE THREAD

**Issue by Jzarecta** [desandro/masonry#680]
I am new to the library, and I have an annoying issue, the tables don't seem to collapse creating big chunk of whitespace.

Currently I am using the isOriginLeft: false, and had also used columnWidth: 45% but seems to have little to no effect. 

Opposite to the examples, I have been using the nth-child(3n+4) selector to be able to push the items to the second row. 

You can see the site here: https://www.oooes.org/transpais/monterrey/
Here is a screenshot pointing to the whitespaces: http://i.imgur.com/092ttPx.png

Do I need to have multiple classes to define right vs left items like the samples?
Do I need to have CSS rules for each to avoid the whitespace?
IS there an option on the plugin to activate the collapse order?

**Comment by desandro** [comment]
Looks like Masonry is not being initialized. You most likely need to wrap your JS in `docReady`

``` html
<script>
docReady( function() {
  var mas = new Masonry( '.listing', {
    columnWidth: 45,
    itemSelector: '.destino'
  });
});
</script>
```
