### ISSUE TITLE
Center Masonry within Wrap Div

### ISSUE THREAD

**Issue by designnewb** [desandro/masonry#681]
Currently I am using wordpress to run a custom theme. It uses Masonry to run the portfolio.
However the masonry can't center within the Div. I have given my items a margin and a gutter, I'm not sure if that is the issue.

    // masonry code 
$(document).ready(function() {
  $('#post-area').masonry({
// options
itemSelector : '.post',
sResizable: true, 
// options...
isFitWidth: true,
columnWidth: function( containerWidth ) {
return containerWidth / 5;}
isAnimated: true,
animationOptions: {
duration: 400,
easing: 'linear',
 queue: false
}
  });
});

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).
