### ISSUE TITLE
Something wrong with elements positioning

### ISSUE THREAD

**Issue by anagami** [desandro/masonry#682]
http://codepen.io/anagami/pen/xbeENy
could you take a look, why first two elements are not positioned after big blocks? http://take.ms/ODSMj

**Comment by desandro** [comment]
This sounds related to #475. Good news is that Masonry v3.2.3 just shipped with a fix for these pixel rounding issues.

Also, the top two items should be in the top slot. If you add more items, they'll cascade into the empty areas. See http://codepen.io/desandro/pen/MYREbV
