### ISSUE TITLE
Have to reload page for masonry to display properly

### ISSUE THREAD

**Issue by levernemartin2011** [desandro/masonry#683]
Hello,

I must say that I love the Masonry Layout! It is beautiful and minimal and lets you display what you want easily. The only issue I am having is that when I click onto the page it doesn't load properly I tried putting the JQuery in the head to make the JQuery load faster but did not work. I am still new to JQuery so I wouldn't be surprised if it is a issue I am creating on my own but I thought I would ask any way here is my site page and a screen shot I would like to continue using this plugin but if I cannot figure out a fix I might have to find something else.

![masonry issue](https://cloud.githubusercontent.com/assets/7875432/6981710/598ba018-d9d4-11e4-86af-1e230c937d14.JPG)

http://design-w-el.com/mainsite/PublicationDesign.html

**Comment by desandro** [comment]
See http://masonry.desandro.com/appendix.html#imagesloaded
