### ISSUE TITLE
Image gaps in Masonry and general image set up 

### ISSUE THREAD

**Issue by ATrecha** [desandro/masonry#685]
Hello!

I've set up this test page - http://rantaconsulting.net/Client/PHR/masonry-test.html

It plays well above a viewport width of 1170px, but when reducing the window, there are gaps below extra wide/tall images.

Not sure what I'm missing here. It seems it's kinda tricky to set up when dealing strictly with images, unless I'm missing something obvious. 
Would be great if you have a demo on your site that dealt specifically with using images only.

I've seen examples online where images are featured with an effect similar to what I would like achieved, but I don't know enough to be able to reverse engineer it for my purposes.

Any help/point in the right direction would be appreciated.

Thanks!

**Comment by desandro** [comment]
If you remove the `min-height` styles from the items, things look pretty good. Does that help?
