### ISSUE TITLE
Masonry is NOT filling small GAPS

### ISSUE THREAD

**Issue by syedazampasha** [desandro/masonry#686]
Demo : http://jsfiddle.net/stanze/ahrzey3g/1/

Masonry is not filling small gaps even if there is space.

Example : Main Container width : 896px;

beside the first container with the orange background, there is a gap where Masonry could add one more container (Orange BG 2nd container), which is not happening. I'm not sure where I'm wrong. :-(

You need to maximize the window to see the issue.

StackOverflow : http://stackoverflow.com/questions/29555467/masonry-is-not-filling-small-gaps

**Comment by desandro** [comment]
Thanks for reporting this issue. This is how Masonry works. It may leave gaps. You should look at [Packery](http://packery.metafizzy.co/), which was specifically designed to fill gaps.

**Comment by syedazampasha** [comment]
@desandro  : Thanks for your reply..
