### ISSUE TITLE
Remove item from masonry without deleting DOM

### ISSUE THREAD

**Issue by J4G-** [desandro/masonry#688]
I've got a project in which I'd like to move an item temporarily out of Masonry's flow (while still visible). I can't find a method to accomplish this, however. I would try a hack with the .hide() method but it's been broken for a couple of years now. It seems like having "remove" take an element out of the DOM is a bit presumptuous. Can another method be added without this functionality?

**Comment by desandro** [comment]
Thanks for this feature request. To help me understand what you're trying for, could you put together a  **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by jrodrima** [comment]
Hi David, and thanks for creating such a great tool as Masonry!

Another case in which this feature would be useful is an image gallery with many images where pagination would be required. You could generate the html markup for all the images, but apply Masonry only to those in the first page and leaving the rest hidden and probably not loading those images yet, in a sort of lazy load. Then pressing a button, you would dynamically load items in "page 2" using 'appended', but before that you have to remove or hide the page 1 items. Hiding them does not seem the best option, but If they are deleted from Masonry and from the dom you cannot go back to page one, not without some ajax.

I hope this helps, or maybe I am missing an easier way to do this.
