### ISSUE TITLE
Bad masonry element: [object HTMLDivElement] ? I'm using document.querySelector not querySelectorAll

### ISSUE THREAD

**Issue by Nomia** [desandro/masonry#690]
Hi,

Thanks for all your awesome work.
Im using the masonry plugin recently, and did come into some headaches. Here is the code:

HTML:
<pre>
&lt;body>
    &lt;div id="img_container">
        &lt;div class="wrapper">
            &lt;div class="box">...&lt;/div>
            &lt;div class="box">...&lt;/div>
            &lt;div class="box">...&lt;/div>
                .......
        &lt;/div>
    &lt;/div>
&lt;/body>
</pre>
JS:
<pre>
var wrapper = document.querySelector('#img_container .wrapper'); (OR $('#img_container .wrapper').get(0))
new Masonry(wrapper,{
    columnWidth:300, 
    itemSelector: ".box"
});
</pre>

Simple as above, it keeps giving an error:
<pre>    Bad masonry element: [object HTMLDivElement]</pre>

I've tried a lot ways to invoke masonry. Sometime it will work, but it doesn't select the items which I specified(".box"), instead it select the whole container as the item, and give the columnWidth to the whole container.

Thanks

**Comment by Nomia** [comment]
More detail:
When I make two container, invoking masonry on each of them "separately", ".box" in the first container will work perfectly, but the second one will get into the situation I described above.

<pre>
&lt;body>
    &lt;div id="container">
        &lt;div class="wrapper">
            &lt;div class="box">...&lt;/div>
            &lt;div class="box">...&lt;/div>
            &lt;div class="box">...&lt;/div>
                .......
        &lt;/div>
    &lt;/div>
    &lt;div id="img_container">
        &lt;div class="wrapper">
            &lt;div class="box">...&lt;/div>
            &lt;div class="box">...&lt;/div>
            &lt;div class="box">...&lt;/div>
                .......
        &lt;/div>
    &lt;/div>
&lt;/body>
</pre>
When I make these ".box"es as the direct children of "#img_container"(remove the middle wrapper div), it starts to work. 

<pre>
&lt;div id="img_container">
    &lt;div class="box">&lt;/div>
    .....
    &lt;div class="box">&lt;/div>
&lt;/div>

new Masonry($("#img_container").get(0),{....})
</pre>
will work

<pre>
&lt;div id="img_container">
    &lt;div class="wrapper">
        &lt;div class="box">&lt;/div>
        .....
        &lt;div class="box">&lt;/div>
    &lt;/div>
&lt;/div>

new Masonry($("#img_container .wrapper").get(0),{....})
</pre>
will not work

**Comment by Nomia** [comment]
Problem solved. But might not be the best solution.
Kinda strange.
the ".wrapper" div was created dynamically using  
<pre>$("#img_container").append( $("&lt;div>",{"class":"wrapper"}) )</pre>
 and this is where the problem is.

If I create the "wrapper" div this way, it'll work with no error
<pre>$("#img_container").append("&lt;div class='wrapper'>&lt;/div>")</pre>

I haven't figured out what the problem is.
Hope this will help other friends get around this ... problem?

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).
