### ISSUE TITLE
Overlapping elements 

### ISSUE THREAD

**Issue by webdesign7** [desandro/masonry#691]
Hello, 

I wonder if you can help ? I am using masonry in my website ( thanks btw :) ) but for some reason I am getting a weird error and having a couple of days trying to fix but with no luck:

basically sometimes the masonry blocks appear with no bottom margin and therefore the blocks are  overlapping ( see image ) and sometimes some blocks overflow on the block below..   but when you do a refresh then this problem goes .. so its quite random, cant catch any logic. It more happens when you first access the website as after a few refreshes it gets back to normal.

the website is dir.lady.co.uk if you would like to have a look 

I'll appreciate your help

Thanks
Sergiu C.

![fireshot screen capture 068 - the lady directory - dir_lady_co_uk](https://cloud.githubusercontent.com/assets/2030016/7216287/f9509d8c-e5f1-11e4-8fba-dce4ab1a3e83.png)

**Comment by desandro** [comment]
See http://masonry.desandro.com/faq.html#how-do-i-fix-overlapping-item-elements

**Comment by webdesign7** [comment]
Thanks ! This has solved the issue ! :)
