### ISSUE TITLE
Stamp breaks layout with percent column width

### ISSUE THREAD

**Issue by dbismut** [desandro/masonry#692]
I've noticed that when using percentage with column width, the layout sometimes breaks with `stamped` elements.
Here's a fiddle to illustrate my point: http://jsfiddle.net/bhaqsdq6/

When you resize the viewport, you move from two types of behaviors:
![correct behavior](http://sidlee.d.pr/KGrb/7DJ7bYew+)

![wrong behavior](http://sidlee.d.pr/19Rbz/4vNDJdaU+)

It looks like when you change this line
https://github.com/desandro/masonry/blob/master/dist/masonry.pkgd.js#L3095

from:

```
    lastCol -= lastX % this.columnWidth ? 0 : 1;
```

to this:

```
    lastCol -= lastX % this.columnWidth > 0.05 ? 0 : 1;
```

corrects the issue in my case. However, I'm pretty sure there must be some other way...

**Comment by desandro** [comment]
Thanks for reporting the issue. I'll be looking in to this.

**Comment by manufaktor** [comment]
I'm having this same issue with the latest version. Are you successfully working with this fix, @dbismut

**Comment by desandro** [comment]
This issue has been quiet for a while. I'm closing as `wontfix`. Please chime in if you're running into this one.

**Comment by a-and-m** [comment]
This issue still exists and occured on the site I'm developing. It only seems to happen on firefox, see attached sceenshot:

![screenshot_2017-07-21_09-22-41](https://user-images.githubusercontent.com/25027175/28453132-3c82dbae-6df6-11e7-89ee-0d8a3b5bf03d.png)

The top right box is a "stamp"-box, which seems to push the middle-column down. On Chrome this is not the case.
