### ISSUE TITLE
Install question for masonry plugin - html template

### ISSUE THREAD

**Issue by Kirstenbr** [desandro/masonry#695]
Hi there,
I'm new to Github - I came here because I would like to use the desandro masonry (or packery) plugin and I'm stumped as to where I can ask a very basic question.  I followed the link from the developer's website....  Hopefully I can ask my question here?

The documentation here:  http://masonry.desandro.com/#install describes using a package manager to install this plugin - I have no idea how to do that!  I would like to use this plugin with an html template - don't I just need to put the files in the correct folder and write the code to include the script on the applicable page?  I read through all the documentation/FAQ but maybe this question is too basic - nevertheless I hope someone can help out with an answer.

The developer's page says he doesn't provide personal support - understandable - if this is not a correct place, is there is a developers forum somewhere to ask questions about how to implement/customize?

Thanks in advance!  BTW I would like to use this plugin to display a gallery of photos on the website I am creating.

**Comment by desandro** [comment]
You can use masonry by adding [masonry.pkgd.min.js](http://masonry.desandro.com/masonry.pkgd.min.js) to your site.

Masonry can be installed with Package managers, but it does not require package managers.
