### ISSUE TITLE
Is there any prerequisites for dom elements?

### ISSUE THREAD

**Issue by vko-online** [desandro/masonry#696]
Cannot make it work, tried js, jquery, html versions, but result. it just doesnt load it. So maybe there are some rules?

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).
