### ISSUE TITLE
Gaps below masonry items

### ISSUE THREAD

**Issue by radscheit** [desandro/masonry#697]
Hej, I'm in doubt if it is an general issue but I am facing problems with my masonry website: http://www.oliver-rath.com

Below each item there is a unintended black gap and I don't know how to get rid of this. Does anyone have an idea?

Thanks in advance!

http://stackoverflow.com/questions/30011326/black-stripes-below-masonry-items

**Comment by desandro** [comment]
[FAQ - How do I fix overlapping elements](http://masonry.desandro.com/faq.html#how-do-i-fix-overlapping-item-elements)

**Comment by radscheit** [comment]
Thanks, bit I did this already: 

var $container = $('#masonry');
// layout Masonry again after all images have loaded
$container.imagesLoaded( function() {
  $container.masonry({
   columnWidth: function(containerWidth){
                       return containerWidth / 3;
                   },
    isAnimated: false,
  });
});




$container.infinitescroll({
      debug: true,
      navSelector  : '.item-nav',
      nextSelector : '.older a',
      itemSelector : '.item',
      bufferPx: 200,
      extraScrollPX: 100,
      loadingText: '... loading more awesomess....',
      loading: {
          finishedMsg: 'Congrats. You have reached the end of the internet.',
          img: 'http://oliver-rath.com/wp-content/uploads/2015/05/15.png'
        }
      },
      function( newElements ) {
        var $newElems = $( newElements ).css({ opacity: 0 });
        zoomBilder();
        $newElems.imagesLoaded(function(){
          $newElems.animate({ opacity: 1 });
          $container.masonry( 'appended', $newElems, true );
        });
      }
    );

Is something wrong with my code?

Thanks in advance.
