### ISSUE TITLE
UITextFiled can not be on center

### ISSUE THREAD

**Issue by SANZOGENJO** [desandro/masonry#704]
when i end edit ，for
exmple there two uitextfiled，the first setTextAlignment:NSTextAlignmentCenter the second setTextAlignment:NSTextAlignmentLeft  when i click the second uitextfiled the first uitextfiled's label text change to left.but if i click the first uitextfiled ,it change to center

**Comment by desandro** [comment]
This sounds like an iOS problem. Can you verify this is related to Masonry?
