### ISSUE TITLE
Ajax load items overlaping

### ISSUE THREAD

**Issue by cocowool** [desandro/masonry#705]
Hi masonry is a great plugin, thank you very much.

when i use jQuery ajax load Items with image, the items overlaped with existed items

you can see my code on http://3.yueshi.sinaapp.com/article

my code like this:

	$(document).ready(function(){
		var $container = $('.ys_article_list .row');
		$container.imagesLoaded(function(){
			$container.masonry({
			  itemSelector: '.col-md-4',
			  isAnimated: true,
			  resizeable: true
			});
		});
    
                $('.ys_ajaxmore a').click(function(){
                       $.ajax({
                              'success':function(){
							var elements = [];
							$.each(result,function(k,v){
								elements.push('<DIV>XXXX</DIV>');
							});
							$container.append( elements ).imagesLoaded(function(){
								$container.masonry('appended', elements, 'reload');
								console.log($container.masonry({itemSelector:'.col-md-4'}));
							});

                               }
                       });
                }
        }

can you help to fix this problem, thank you very much.

**Comment by desandro** [comment]
The `appended` method needs elements. Your code has `elements` being an array of HTML strings.

Try this code:

``` js
success: function() {
  var elements = [];
  $.each( result, function(k,v){
    elements.push('<DIV>XXXX</DIV>');
  });
  // create jQuery object
  var $elements = $( elements );
  $container.append( $elements )
  $elements.imagesLoaded( function() {
    $container.masonry( 'appended', $elements );
  });
});
```

**Comment by cocowool** [comment]
Hi desandro:

glad to that you give me a solution, but i tried and it doesn't work

an error "TypeError: undefined is not an object (evaluating 'a.ownerDocument')" occured

do you know why thank you.
