### ISSUE TITLE
imagesLoaded to control multiple containers

### ISSUE THREAD

**Issue by timersys** [desandro/masonry#706]
Is possible with imagesLoaded control multiple containers? 

For example something like:

$(".div-classname"). imagesLoaded( function() {
  // images have loaded in all the divs with class "div-classname"
});
Thanks

**Comment by desandro** [comment]
Yes. imagesLoaded works by triggering a callback after all images have been loaded. With your example:

``` js
$('.container').imagesLoaded( function() {
  // all images in all .container elements have been loaded
});
```
