### ISSUE TITLE
Special change items position when someone item changed its height

### ISSUE THREAD

**Issue by zheoreh** [desandro/masonry#707]
How do I make to the underlying tile changed their position only in the vertical downward when the upper element of increased standing height? I do not want to adjacent tiles to change its position horizontally.

**Comment by desandro** [comment]
This kind of behavior is not supported by Masonry. You may want to look at Packery, with its [`fit` method](http://packery.metafizzy.co/methods.html#fit)

**Comment by zheoreh** [comment]
@desandro thanks
