### ISSUE TITLE
js masonry

### ISSUE THREAD

**Issue by Sue89** [desandro/masonry#708]
Firstly, thank you for the code!  I am new to js but I am trying to get masonry to work in Chrome .... and it isnt for me.  Could you help please:
I use brackets and codekit to compile using bootstrap (latest) and .less
I have a plugins.js file (complies to main.js) with both Masonry and ImagesLoaded min script
here is a little of my my html 
 <section id="portfolio">
        <h5>Views of some of my current work</h5>
      <div class="container">
        <div class="reviews js-masonry" data-masonry-options='{"itemSelector": ".hreview" }'>
          <div class="hreview review-item-1 thumbnail col-sm-6 col-md-4">
            <img src="img/port/JM-9600.jpg" alt="Earthstone form">
            <div class="caption">
              <blockquote class="description"><p>Earthstone form</p></blockquote>
            </div>
          </div>

also in my <body> I have the following scripts 
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.11.2.min.js"><\/script>')</script>
        <script src="js/plugins.js"></script>
        <script src="js/main.js"></script>

Could you help please?
Many thanks in advance

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).
