### ISSUE TITLE
Images overlapping on mobile devices

### ISSUE THREAD

**Issue by johnasp** [desandro/masonry#710]
Have used a Zurb foundation demo page to create a responsive masonry grid (complete with images and text in each box) and it all works fine on desktop pc and Mac.  However, when I view it on a mobile device the images overlap one another.  Another strange thing is the layout sometimes sorts itself out on page refresh?

Screenshot attached and link to live test page below:

![screenshot_2015-06-11-10-38-23](https://cloud.githubusercontent.com/assets/1118867/8104449/aa6a7010-1028-11e5-8b1a-0d726d868001.png)
 
http://johnasp.github.io/bst-html/masonry-demo/index.html

**Comment by desandro** [comment]
Have you checked http://masonry.desandro.com/faq.html#how-do-i-fix-overlapping-item-elements ?

**Comment by vleango** [comment]
Experiencing the same issue. Safari on iOS. Also a Rails with Twitter Bootstrap app.
The images loads correctly once or twice but the overlapping image piles up on one spot of the screen.

I have also tried imagesLoaded with $container.masonry() but no changes....
One thing I did notice is that, launching a twitter modal page when the bug occurs separates the images and layouts the grid correctly... I hope that information can be some sort of hint...

**Comment by vleango** [comment]
hmm.... I think I will take my comment back....
Didn't realize I was using an old version...
Anyways, updated and it seems to be working right now

**Comment by johnasp** [comment]
I also tried using the imagesLoaded and also it made no difference. vleango  - what version are you using to get it working?

**Comment by vleango** [comment]
@johnasp I was previously using the version from the [masonry-rails gem](https://github.com/kristianmandrup/masonry-rails) but removed it and added the latest today.

For my problem, it could have been an issue with the way rails loaded masonry, but I'm not sure.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).
