### ISSUE TITLE
IE8 doesn't work

### ISSUE THREAD

**Issue by shellka-roi** [desandro/masonry#711]
I have error: 'invalid argument' in Item.prototype.layoutPosition when applying top style.
It contains 'NaNpx'...
It can be simple fixed by adding
```
// clean up 'auto' or other non-integer values
  this.position.x = isNaN( this.position.x ) ? 0 : this.position.x;
  this.position.y = isNaN( this.position.y ) ? 0 : this.position.y;
```
inside 'Item.prototype.layoutPosition' method

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).
