### ISSUE TITLE
Adding gutter breaks percentage 

### ISSUE THREAD

**Issue by alvarotrigo** [desandro/masonry#712]
I want to have 4 columns so I set the `table` element to `width:25%` on my style sheet. 
Everything works as expected until I decide to add some margin for each column by using the `gutter` option.

Then, only 3 columns are displayed. 

Ideally masonry should be intelligent enough to rest the 10 pixels for each column and keep showing 4 columns.

[Reproduction of the issue](http://jsfiddle.net/zug093oa/2/).

**Comment by desandro** [comment]
Thanks for reporting this issue.

Adding a gutter will break layout when item width = 100%. With 4 columns and `gutter: 10`, the math looks like

```
4 * 25% + 10px * 3 = 100% + 30px
```

I cannot fit. One way to make this work is to use percent values for gutters, and change width of items so they all can fit. See demo: http://codepen.io/desandro/pen/BAJKn Another solution is to use `calc` values so items provide enough room for gutter.

``` css
.grid-item {  width: calc( ( 100% - 30px ) / 4 ); }
```

See http://codepen.io/desandro/pen/aOyKBP
