### ISSUE TITLE
masonry layout sometimes working and sometimes not working with the same code

### ISSUE THREAD

**Issue by tayoeu** [desandro/masonry#714]
Hey I'm new to the web development business and I'm having issues with my first ever project.
At first sorry for not providing a simplified version of my issue but I don't really know how to get it done in my case. But there is a live version on www.tayo.eu/tf

If you open the work slider you'll see preview pictures of each project. If you click on the first project (Palma) it'll open the project view and masonry is working just fine. (Loading time is quit long atm I'll fix that later).

But if you refresh the page and try to open the project "Berlin 4" All the pictures are just showing up on the left side of the page. Masonry only works for this project if you resize the window or if you reopen the same project a second time without refreshing the page. So always the same projects are working fine with masonry while some others never work and I seem to be to blind to find the systematic behind it.

I tried to exchange the pictures from a working project to a non working one - but no difference. I tried changing the order in json file, rename projects, emptying the cache. It just magically working in some cases and not in others.

Maybe it isn't even a masonry problem but I'm just so lost after 2 days of trying all kinds of stuff and I'm hoping to get some help here! :)

All tested with Chrome Version 43.0.2357.124 (64-bit)

So what I do is, I'm appending images to my DOM with the following code:

    $.getJSON("js/data.json", function(json){

             $.each(json.pictures, function () {

                if(this.Project_ID == projectID){

                    if(this.format == "w"){
                        $(".project-overview").append('<div  class="item w" data-picture_id="'+ this.ID +'" data-project_id="' + this.Project_ID + '" data-content= "' + this.Project +" "+ this.Year + '"><img src= ' + this.url + ' /></div>')
                    }else{
                        $(".project-overview").append('<div  class="item h" data-picture_id="'+ this.ID +'" data-project_id="' + this.Project_ID + '" data-content= "' + this.Project +" "+ this.Year + '"><img src= ' + this.url + ' /></div>')

                    }
                }
            });

after the images are appended,  I'm initializing masonry like this:

    $(".project-overview").imagesLoaded(function(){
              $('.project-overview').masonry({
                    itemSelector: '.item',
                    "columnWidth": '.grid-sizer',
                    "percentPosition": true,
                    "gutter": '.gutter-sizer-overview',
                    isResizeBound: true,
                    transitionDuration: '0.1s',
                    isAnimated: true
                });
                $(".item").fadeTo(400,1)
            })

All of the pictures are referenced in the json file like this:

    {
      "Project": "Palma",
      "Project_ID": "11",
      "ID": "2",
      "Title": "",
      "preview": false,
      "Year": "2015",
      "url": "projects/2015/palma/Palma_02.jpg",
      "format": "h"
    }

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry.

There are several issues going on.

1. Newly appended items are not being added to the Masonry instance. Use the [`appended` method](http://masonry.desandro.com/methods.html#appended)
2. I'm not sure how a user can switch between projects. One way would be to remove previous items from the `overview` elements before adding new ones.

My recommendation is to try and get this working without Masonry. After that's in place, go back and add Masonry back. One thing at a time.

**Comment by tayoeu** [comment]
Hey thanks for you response!

1. The items are being appended to the DOM and only after that, the Masonry instance is created. Which is indeed working.

2. That's exactly what is happening. If the user clicks on a new project or on the same project for that matter, the Masonry instance gets destroyed and all element expect of the gutter and grid sizer are being removed.

But I still get this wired behavior where the Masonry layout is done correctly with some projects and not with others.

I think it might have to do something with the browsers cache. Because it usually is working the first time after i empty the cache.

Of course I do understand, that this is not a place for general webdev advice but still I had to try. :)

Thank you so far!

**Comment by matek075** [comment]
Instead of innerHTML I gave append() and it worked 🚀 😄
