### ISSUE TITLE
Grid item order

### ISSUE THREAD

**Issue by nick281** [desandro/masonry#715]
Hello everybody,

i use mansonry for my website. 
The Script works good but in the responsive view i have a little Problem.
You can find on attachment a Screenshot. On the Screenshot you see on the left site the responsive view. I would like to the right view. Without gaps... It is possible? 
![screenshot1](https://cloud.githubusercontent.com/assets/12954357/8235496/9e8fb95c-15e2-11e5-9e39-96b9b9905908.jpg)

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by nick281** [comment]
Hello Desandro, thank you for your Message. I create a Screenshot from the html code and Script. Is That helpful?
![document](https://cloud.githubusercontent.com/assets/12954357/8240874/0b6653ce-1606-11e5-9f49-d9b73ea3e835.jpg)
