### ISSUE TITLE
The script can sort the blocks so that they got the most compact?

### ISSUE THREAD

**Issue by evgenyshev** [desandro/masonry#716]
![2015-06-27 21-34-17 sli -](https://cloud.githubusercontent.com/assets/12575690/8393387/73d3bbc0-1d15-11e5-92b1-beab283e8575.png)

**Comment by evgenyshev** [comment]
By the way, the latest version of the entity is here http://desandro.github.io/masonry/index.html

**Comment by desandro** [comment]
Use [Packery](http://packery.metafizzy.co/)! Packery was designed to fill gaps.
