### ISSUE TITLE
Scattered Grid Items in Safari Version 8.0.6 (10600.6.3)

### ISSUE THREAD

**Issue by conwilly88** [desandro/masonry#717]
See http://www.siteyak.com

I have no idea why this is happening, any pointers?

**Comment by desandro** [comment]
Looks to be a bug with transitionEnd triggering. I'll take a look.

**Comment by conwilly88** [comment]
I removed the transitions which appears to fix a lot of it but on initial load the grid items are still off. If you reload it after the initial load it fixes it.
