### ISSUE TITLE
How create fluid width animated masonry

### ISSUE THREAD

**Issue by dasi1va** [desandro/masonry#720]
How can make fluid width responsive masonry, animated?

**Comment by desandro** [comment]
See http://masonry.desandro.com/layout.html#responsive-layouts

**Comment by dasi1va** [comment]
Thanks I found way! but when set full window width and show hide scroll bar browser create some gap problems can be fixed this in some way?

thanks in advance!

**Comment by Tuckie** [comment]
`html { overflow-y: scroll }`
