### ISSUE TITLE
IsFitWidth breaking out of the container

### ISSUE THREAD

**Issue by douglasquintanilha** [desandro/masonry#722]
I'm trying to center  a Masonry grid container after setting the isfitwidth as true, following the documentation on the website, but even in the original codepen example, the grid items break out of the grid, and extends all the way to left. 

Is it a bug, or the documentation is outdated and there is a new way of doing it? 

Test Case that is on the website:
http://codepen.io/desandro/pen/nGLvx

**Comment by desandro** [comment]
Thanks for reporting this issue. What browsers are you seeing this bug in?

**Comment by douglasquintanilha** [comment]
I'm seeing in all the browsers.
Here is in Firefox Developer Edition 40.0a2 :
![image](https://cloud.githubusercontent.com/assets/3652509/8813486/4fcd94d0-2fda-11e5-90ee-754826416789.png)

And here is in Google Chrome 43.0.2357.134 m (64-bit):
![image](https://cloud.githubusercontent.com/assets/3652509/8813553/d8ee06f0-2fda-11e5-97fa-68258407e0fd.png)

And in Internet Explorer 11.0.9600.17842:
![image](https://cloud.githubusercontent.com/assets/3652509/8813619/4b46ab30-2fdb-11e5-8327-adb7a6e403b0.png)

**Comment by desandro** [comment]
Thanks for reporting this bug. Looks like the issue was `.grid { min-width: 1200px; }` in the CSS. I've updated the demo. http://codepen.io/desandro/pen/nGLvx
