### ISSUE TITLE
How about support an `infinite` function in Masorny?

### ISSUE THREAD

**Issue by sculove** [desandro/masonry#724]
I work for NAVER Corporation that is Korea Internet company.
Our company provides much information to people on Web Sites.

So, a page has so very many contents.
All this, as well as people wants to show grid-layout style like this.

http://m.shoppingw.naver.com/trendshop/home

I made `infiniteGird` using a masorny.
Scroll down to the bottom of the document continuously~!
The contents are increased continuously and the count of DOM is limited.
DOM is recycled.

Do you have a scheduled to add infinite function?

If the Masorny is a scheduled to add infinite function, I want to contribute it.
Can you give me a chance?

**Comment by klihelp** [comment]
hi sculove, proactively you can send a push request to the project, because it's easier to review.

**Comment by sculove** [comment]
@klihelp Thanks. I'll try it.

**Comment by desandro** [comment]
Thanks for getting in touch. Infinite scrolling is not built into Masonry. But you can use infinite scrolling with Masonry using its [methods like `appended`](http://masonry.desandro.com/methods.html#appended). Years ago, I would recommend [Infinite Scroll](https://github.com/infinite-scroll/infinite-scroll) (it's no longer supported, so beware).

If you wish to build an add-on to Masonry, I recommend you do as a separate project. You can add additional methods by adding to `Masonry.prototype`.

**Comment by sculove** [comment]
Ok. I got it. :)
