### ISSUE TITLE
bower.json has wrong reference to main file

### ISSUE THREAD

**Issue by pgrm** [desandro/masonry#725]
bower.json references `masonry.js` as it's main file, however it should be `dist/masonry.pkgd.js`

**Comment by desandro** [comment]
In bower/bower.json-spec#43 we resolved that `main` is for entry files, not for distribution files.

The Bower team is resolving the Wiredep use case in bower/bower.json-spec#47.

Until then you can resolve this by including an override in your wiredep config

``` js
  "overrides": {
    "outlayer": {
      "main": [
        "item.js",
        "outlayer.js"
      ]
    }
  }
```

**Comment by pgrm** [comment]
Thx for the update

**Comment by fjeddy** [comment]
This doesn't work

`TypeError: t.create is not a function. (In 't.create("masonry")', 't.create' is undefined)`
