### ISSUE TITLE
Wiredep TypeError: Cannot read property `Item` of undefined when using masonry with bower

### ISSUE THREAD

**Issue by pgrm** [desandro/masonry#727]
I've a setup, where my bower dependencies get included automatically via [wiredep](https://www.npmjs.com/package/wiredep) and I merge them afterwards with [useref](https://www.npmjs.com/package/gulp-useref).

This works fine for all dependencies, but masonry. I've tried moving masonry to the beginning as well as the end of those dependencies, but I'm always getting the same error. When I take out masonry and add an extra reference to your cdn link, it works. (Also all the other scripts work).

I've seen this issue: https://github.com/desandro/masonry/issues/618 and discovered that masonry's bower file is linking the wrong main file (https://github.com/desandro/masonry/issues/725) but even if I overwrote the main file to the correct one, I was still getting the same error. The cdn-file and bower files are identical, so probably the problem is somewhere in how wiredep is merging the files together?

Before that, I was already using masonry bundled together with [ASP.Net](http://www.asp.net/mvc/overview/performance/bundling-and-minification) and that worked fine. Any ideas what could be wrong here?

**Comment by desandro** [comment]
Have you tried using the override?

``` js
  "overrides": {
    "outlayer": {
      "main": [
        "item.js",
        "outlayer.js"
      ]
    }
  }
```

**Comment by pgrm** [comment]
Yes, this worked!
Thx

**Comment by brayan15** [comment]
ty, it's working
