### ISSUE TITLE
Overlapping blocks with divs that use scripts to display social feeds

### ISSUE THREAD

**Issue by leanda** [desandro/masonry#728]
Hi 

I have a small problem where two masonry blocks are overlapping on load. Both blocks contain empty divs that use scripts to add content. One is instafeed to display the latest instagram image and the other displays the latest tweet. If I resize the window then they stack nicely.

I've tried using .imagesLoaded method below but that doesn't change anything. And the tweet block is just text anyway.

    <script>
    $(document).ready( function() {

      var $container = $('#container').imagesLoaded( function() {
      $container.masonry({
     	"gutter": ".gutter-sizer",
			"itemSelector": ".item",
			"stamp": ".stamp"

        });
      });

    });
    </script> 

If I use the following this fixes it for all browsers except IE9:

    <script>
		    $(window).load(function(){
		    $('#container').masonry({
			    "gutter": ".gutter-sizer",
			    "itemSelector": ".item",
			    "stamp": ".stamp"
		    });
	    });
    </script>

I suspect it may have something to do with masonry loading before the other two scripts but I have no idea how to solve it.

Any help much appreciated!

**Comment by desandro** [comment]
You'll need to trigger `.masonry()` after contend has been loaded. I would look over the social feed widget API and see if there's an events that you could use

``` js
widget.on( 'feedLoad', function() {
  $container.masonry();
});
```

Otherwise, you'll have to find a hack for a solution.

**Comment by leanda** [comment]
Thanks! I looked of the API for instafeed and found an after: function so was able to use that to trigger masonry. Doesn't look like there is a way to do it with twitterFetcher script though.

**Comment by desandro** [comment]
Thanks for following up!
