### ISSUE TITLE
Filtering Wordpress

### ISSUE THREAD

**Issue by philnickel** [desandro/masonry#730]
Hi, 

I realy like your plugin but I make a site in wordpress for a client. I use isotope which includes mansonry and the filtering option from isotope. Is it possible to use mansonry and the filtering option? 

When I use only MANSONRY or only the FILTERING it works but together they don't work. 

Can anybody help me?

**Comment by desandro** [comment]
Masonry does not support filtering. [Use Isotope](http://isotope.metafizzy.co/).
