### ISSUE TITLE
masonry with seajs

### ISSUE THREAD

**Issue by blwoosky** [desandro/masonry#731]
i am using masonry with seajs ,
i just wrap an define(function(require, exports, module) {});

but a lot of js file not found:
js/lib/jquery.js
js/lib/desandro-get-style-property.js
js/lib/eventie.js
js/lib/doc-ready.js
js/lib/wolfy87-eventemitter.js
js/lib/desandro-matches-selector.js 
js/lib/get-size.js

**Comment by desandro** [comment]
Sorry, Masonry does not officially support seajs. After 6 months, no one else has voiced their interest in support either. Going to have to close this one.
