### ISSUE TITLE
Masonry container div height issue

### ISSUE THREAD

**Issue by paramsinghvc** [desandro/masonry#733]
http://stackoverflow.com/questions/31742158/masonry-container-grid-height-issue

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by francescostella** [comment]
I had the same issue, the fact that a grid item contains images affect the calculation of the position of the cards. Once the element is appended and the images are not loaded yet, the dimension got from the JS is wrong.
