### ISSUE TITLE
Bower RequireJS compatibility

### ISSUE THREAD

**Issue by adjohnson916** [desandro/masonry#734]
This module, at least in 3.3.1, has AMD requires that assume a RequireJS configuration that is incompatible with [yeoman/bower-requirejs](https://github.com/yeoman/bower-requirejs). Particularly, it assumes the dependencies are configured with paths relative to their base directories, rather than to their main files.
Any way we can change this to remove the deep path references in the require statements? Or do you have any tips besides manual configuration?

Looks like this issue applies transitively, e.g. `get-size` also makes the same assumption.

Refer to #296.

**Comment by desandro** [comment]
Thanks for reporting this issue. Masonry and its dependencies have their paths set relative to `bower_components`. See [Require + Bower example from the docs](http://masonry.desandro.com/appendix.html#requirejs)

``` js
requirejs.config({
  baseUrl: 'bower_components/',
  paths: {
    app: '../'
  }
});

requirejs( [
  'masonry/masonry',
  'app/my-component.js'
], function( Masonry, myComp ) {
  new Masonry( '.grid', {...});
});
```

As for bower-requirejs, this is the first I'm hearing of the incompatibility.  **+1 this issue** if you would like to see it resolved.

**Comment by mwcz** [comment]
:+1:

**Comment by mwcz** [comment]
bower-requirejs adds each installed bower package to RequireJS path config by its bower name and bower `"main"` filename.  Ie, `require(['get-size'])` will load `get-size.js`, as defined in get-size's bower.json file.  So masonry depending on "get-size/get-size" is making an assumption that isn't true for bower-requirejs users.  I'm not sure of a good solution though!  I'm going to try adding a bower-requirejs [override](https://github.com/yeoman/bower-requirejs#overriding-the-main-file-of-a-dependency).

Just an artifact of AMD not having enforced module names. :)

**Comment by mwcz** [comment]
This is a not-too-bad workaround.  Use bower-requirejs's [exclude option](https://github.com/yeoman/bower-requirejs/blob/master/readme.md#bowerrequirejsoptions-callback) to prevent the incorrect paths from being added to RequireJS config.  The same can be done for any module whose dependees attempt to load it relative to bower_components instead of by module name.

    options: {
        baseUrl: './j/bower_components/',
        exclude: ['outlayer', 'get-size', 'fizzy-ui-utils'] 
    }

**Comment by desandro** [comment]
Closing this feature request as it didn't get enough interest. :whale:
