### ISSUE TITLE
masonry don't support require.js

### ISSUE THREAD

**Issue by liuliangsir** [desandro/masonry#735]
![](https://cloud.githubusercontent.com/assets/8049878/9054682/88bcd0c6-3ab6-11e5-87d9-93e5b4712767.png)
![](https://cloud.githubusercontent.com/assets/8049878/9054693/a58b547a-3ab6-11e5-9142-acf9e8935873.png)

**Comment by desandro** [comment]
Have you looked at the [Require.js documentation for Masonry](http://masonry.desandro.com/appendix.html#requirejs) and [imagesLoaded](http://imagesloaded.desandro.com/#requirejs) ?

**Comment by liuliangsir** [comment]
thanks,I has looked at the documentation,by the way,I wonder how can you make so perfect plugin?

**Comment by imakin** [comment]
> Have you looked at the [Require.js documentation for Masonry](http://masonry.desandro.com/appendix.html#requirejs) and [imagesLoaded](http://imagesloaded.desandro.com/#requirejs) ?

hi, can i still read this somewhere? i still get the same issue with v4.2.2 today, and would try to make it work in my implementation.
but that link is dead http://masonry.desandro.com/appendix.html#requirejs
