### ISSUE TITLE
Inconsistent Initial Layout Using AJAX

### ISSUE THREAD

**Issue by AdamDenoon** [desandro/masonry#736]
My page loads elements using AJAX (I'm unable to do a reduced case test for this reason), and sometimes the elements overlap each other vertically, and sometimes they don't. Whenever I refresh, they always become aligned properly. Revisiting the page afterwards will return it to seemingly random behaviour as it regards vertical alignment (perhaps its parent isn't resizing its height properly sometimes).

My page is located at http://www.crossfireyouthministries.org/vidblog.html

Here is the relevant code:

    <head>
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/masonry/3.3.1/masonry.pkgd.min.js"></script>
    </head>

 ...

    <div class="postList">
        <script type="text/javascript">
		var $grid = $('.postList').masonry({
		    itemSelector: '.postItem',
		    columnWidth: 241,
		    gutter: 6
		});
	</script>
    
        // Get array of post IDs
        <?php getPosts($search, $criteria); ?>
    
        <script type="text/javascript">
		
		var postIds = [];
		var postsDrawn = 0;
    
               // Load array of IDs into Javascript for paging purposes
		<?php
			for ($i = 0; $i < count($arr_posts); $i++) {
		?>
		postIds.push("<?php echo $arr_posts[$i]; ?>");
		<?php	
			}
		?>
		
                // Get the first 6 posts						
		loadPosts(postIds, 0,6);
								
		// Get Posts via AJAX
		function loadPosts(arr_posts, start, count) {
			$.ajax({ method: "POST", url: "getVidPosts.php", data: {"posts_array[]" : arr_posts, "start" : start, "count" : count}}).done( function (response) {
				$grid.append(response);
				postsDrawn += count;
									
				if (postsDrawn >= arr_posts.length) {
					$("#loadMoreButton").remove();
				}
										
				// Layout new post items using Masonry
				$grid.masonry('appended', response);
				$grid.masonry('reloadItems');
				$grid.masonry();
			});
		}
        </script>
    </div>

**Comment by desandro** [comment]
Try using [imagesLoaded](http://masonry.desandro.com/layout.html#imagesloaded)

``` js
function loadPosts(arr_posts, start, count) {
    $.ajax({ method: "POST", url: "getVidPosts.php", data: {"posts_array[]" : arr_posts, "start" : start, "count" : count}}).done( function (response) {
        // hide new content
        var $response = $(response).hide();
        $grid.append($response);
        postsDrawn += count;

        if (postsDrawn >= arr_posts.length) {
            $("#loadMoreButton").remove();
        }

        $response.imagesLoaded( function() {
            // show when loaded
            $response.show();
            // Layout new post items using Masonry
            $grid.masonry('appended', $response);
        })
    });
}
```

**Comment by AdamDenoon** [comment]
That solved the vertical layout issue, but created a horizontal layout issue (the gutter has disappeared)

Using your code exactly: http://crossfireyouthministries.org/vidblog.html

**Comment by desandro** [comment]
Looks like you have a JS bug. The current code differs from my suggestion. All yours now!

**Comment by AdamDenoon** [comment]
The current code does not differ at all. In my first post on this thread, I omitted the code of the functions themselves, but still showed they being called. They just return straight html. Here's the current code, which is identical to what you gave me:

```javascript
<div class="postList">
    <script type="text/javascript">
    var $grid = $('.postList').masonry({
        itemSelector: '.postItem',
        columnWidth: 241,
        gutter: 6
    });
</script>

    // Get array of post IDs
    <?php getPosts($search, $criteria); ?>

    <script type="text/javascript">

    var postIds = [];
    var postsDrawn = 0;

           // Load array of IDs into Javascript for paging purposes
    <?php
        for ($i = 0; $i < count($arr_posts); $i++) {
    ?>
    postIds.push("<?php echo $arr_posts[$i]; ?>");
    <?php   
        }
    ?>

            // Get the first 6 posts                        
    loadPosts(postIds, 0,6);

    // Get Posts via AJAX
    function loadPosts(arr_posts, start, count) {
        $.ajax({ method: "POST", url: "getVidPosts.php", data: {"posts_array[]" : arr_posts, "start" : start, "count" : count}}).done( function (response) {
            $grid.append(response);
            postsDrawn += count;

            if (postsDrawn >= arr_posts.length) {
                $("#loadMoreButton").remove();
            }

          // Layout new post items using Masonry
	$response.imagesLoaded( function() {
	     // show when loaded
	     $response.show();
	     // Layout new post items using Masonry
	     $grid.masonry('appended', $response);
        });
    }
    </script>
</div>
```

Any help and support you can provide would be much appreciated. Again, the issue now is that the gutter disappears:

http://crossfireyouthministries.org/vidblog.html

**Comment by AdamDenoon** [comment]
This fixed it for me:

`<script type="text/javascript" src="js/imagesLoaded.min.js"></script>`

```javascript
var $response = $(response).hide();
$grid.append($response);
postsDrawn += count;
									
if (postsDrawn >= arr_posts.length) {
   $("#loadMoreButton").remove();
}
										
// Layout new post items using Masonry
imagesLoaded($response, function() {
   // show when loaded
   $response.show();
   // Layout new post items using Masonry
   $grid.masonry('appended', $response);
});
```

Thanks for your help!
