### ISSUE TITLE
How do I give a left and right margin to all items in the grid ?

### ISSUE THREAD

**Issue by codehandling** [desandro/masonry#737]
I tried to duplicate the CSS on your home page but the ".grid-sizer" is treated as an item on my end.

On your page - http://masonry.desandro.com/ the "hero-grid__grid-sizer" overlaps the first item somehow, which is what I need.

Have you modified the script for that ? How do I achieve this ?

**Comment by desandro** [comment]
> but the ".grid-sizer" is treated as an item on my end

Use an empty element for `.grid-sizer`, and set a separate `itemSelector` so it doesn't get use. Take a look at the [basic layout demos](http://masonry.desandro.com/layout.html).

Better yet, provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).
