### ISSUE TITLE
'layoutComplete' event not working

### ISSUE THREAD

**Issue by kirillbunin** [desandro/masonry#738]
According to http://masonry.desandro.com/events.html there should be event `layoutComplete`.
On the other hand http://desandro.github.io/masonry/index.html doesn't have any information on events.

Either way, `layoutComplete` doesn't trigger after completing the set-up.

How do i bind stuff on finish? :)

**Comment by Eric-Chiu** [comment]
I have the same problem

**Comment by desandro** [comment]
If you want to capture the initial layout event, you need to bind a listener before layout is initialized. You can do so with [isInitLayout](http://masonry.desandro.com/options.html#isinitlayout)

**Comment by brianjaikens** [comment]
Hi,
Can you put the information about the isInitLayout setting in the event docs so that this doesn't catch people out in the future.
Thank you.
