### ISSUE TITLE
Getting random bottom spacing on mobile after resizing

### ISSUE THREAD

**Issue by acurcione** [desandro/masonry#739]
Complete newbie with masonry so I may just be missing a setting somewhere, but I can't seem to figure this out. This is my first time ever using it and I'm integrating it into a Wordpress theme. 

Issue: On a responsive layout, using percentages for widths and media queries, everything is floating and positioning correctly at all sizes, but on occasion when going down to the smallest size (even on a desktop browser) I'll see one or more of the grid items have extra spacing at the bottom. If I refresh the browser the items slide into the proper position with my margin settings.

It seems to usually happen after on the iOS simulator when going from landscape to portrait OR when resizing the desktop browser down to the smallest size. When looking at the code inspector it isn't actually adding any extra padding or margin. It's like something is keeping the grid item from sliding into place.

This is how I'm initializing to help with images and typekit (and this might be wrong, but it's working):

<script>
var msnry;

function triggerMasonry() {
  // don't proceed if masonry has not been initialized
  if ( !msnry ) {
    return;
  }
  msnry.layout();
}
// initialize masonry on document ready
docReady( function() {
  var container = document.querySelector('#masonry-loop');
  imagesLoaded( container, function() {
        msnry = new Masonry( container, {
            itemSelector: '.masonry-entry',
            columnWidth: '.grid-sizer',
            gutter: '.gutter-sizer',
            percentPosition: true
        });
  });
});
// trigger masonry when fonts have loaded
Typekit.load({
  active: triggerMasonry,
  inactive: triggerMasonry
});
</script>

Gutter is set to 12px just to keep things even when resizing and margin bottom is set to 12px on the div holding the post. Again, it's all working except on resizing down to the smaller size. That's when the layout occasionally hiccups and I get a gap I can't explain.

Any ideas?

Thanks.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by acurcione** [comment]
I can certainly try to do that! I want to try one more thing to clear this up before I do though.

Also, did you have a look at my initialization script? Did I do that properly with the imagesLoaded portion? I didn’t see an example of it on your site that also included the typekit portion so I cobbled it together and have no idea if that’s the proper way to do it.

Thanks so much.

**Comment by acurcione** [comment]
And it looks like I fixed it and I simplified my media queries in the process. I ended up using fixed sizes instead of percentages and also isFitWidth so things would center. 

So you can that portion of this ticket, but please let me know if the way I’m initializing is the proper way to do it with imagesLoaded and typekit.

Thanks again.
