### ISSUE TITLE
use masonry meet a problem

### ISSUE THREAD

**Issue by liuliangsir** [desandro/masonry#740]
![image](https://cloud.githubusercontent.com/assets/8049878/9218105/eac837b4-4101-11e5-8f37-3d8e70e81792.png)
![image](https://cloud.githubusercontent.com/assets/8049878/9218138/394f0e94-4102-11e5-8765-537f8ef4bd5d.png)
![image](https://cloud.githubusercontent.com/assets/8049878/9218152/59112a32-4102-11e5-85c7-bff64fca16cf.png)
finally result is
![image](https://cloud.githubusercontent.com/assets/8049878/9218182/a235c45c-4102-11e5-93b9-8b27e4981c99.png)
[website url](http://myjs2015.sinaapp.com/)

**Comment by desandro** [comment]
I appreciate you providing a live URL, but I'm not able to debug it. Can you produce a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by liuliangsir** [comment]
sorry,My English is not fluent,so would you can tell me your google+ account? then we can talk about this problem.
