### ISSUE TITLE
grid boxes not optimising available space 

### ISSUE THREAD

**Issue by charlieapple** [desandro/masonry#741]
So sorry to bother you. I've followed all the instructions and tried different things but I can't get my boxes to take up the available space, they are just staying aligned in uniform vertical/horizontal grid.  Can anyone help with why this grid won't "masonryfy" for me??  many thanks.
http://www.darlingmagazine.co.uk/testmasonry.html

**Comment by desandro** [comment]
Order your scripts so jquery.min.js is before masonry.pkgd.min.js

**Comment by charlieapple** [comment]
Thank you sooooo much!!!  I'm soooo happy!!! :)  Superstar!
