### ISSUE TITLE
3.3.1 seems to have broken prepend relayout transition/animation

### ISSUE THREAD

**Issue by Jonas-Jancarik** [desandro/masonry#742]
When using v3.3.1, prepending elements doesn't result in a smooth transition. It seems that the animation only goes half-way through and then quickly switches to the final state. This is clearly visible with very slow transitions, e.g. transitionDuration: '2s'. Switching back to version 3.3.0 fixes the issue for me (but brings up other issues). I am using `percentPosition: true` and percentage widths.

I am loading Masonry from the CDN:

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/masonry/3.3.0/masonry.pkgd.min.js">
</script>
```

BR, Jonas

**Comment by desandro** [comment]
Thanks for reporting this issue. This is a dependent on metafizzy/outlayer#37.

**Comment by Jonas-Jancarik** [comment]
Thanks for the quick fix!
