### ISSUE TITLE
Inserting/Replacing element

### ISSUE THREAD

**Issue by ArturGasparyan** [desandro/masonry#748]
Hello!

We are working on a large new platform and we use Masonry for our layout. We like it a lot!

However there are two issues we face:

1. 

We want to replace a div with a new one loaded over AJAX. The div itself also get's changed with new classes in it (but still with the masonry item classes) so that we cannot just replace the content. Also the content changes its height.

What we did is, we simply replaced (replaceWith()) the div via jQuery and called reloadItems and then layout on your masonry grid. This seems to work but what kind of happens is, that the new div disappears and appears at the top left corner of the container (where another div might already be!) and then animates to its (correct!) position. Is there a way to avoid that?

2.

Animating in general is not smooth. Is that normal? Or are there settings to fine tune it? It animates smoothly half the way and the second half it jumps.

Thank you

Kind regards

Artur Gasparyan

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by ArturGasparyan** [comment]
You should read your issue posts more carefully, "Desandro".

1. How to insert a div within the list of divs (not append, not prepend) - for this you need no test case, please just answer.

2. Your animations do not work properly. I used your instructions as is and they do not move as smoothly as on your frontpage. In your previous vanilla version of Masonry you had different animation styles. Is it possible to try different ones in the current version (3), too? Because as I said the current one is not smooth.
