### ISSUE TITLE
Container height is wrong when there is a caption, in the item div

### ISSUE THREAD

**Issue by dougcassidy** [desandro/masonry#749]
I set itemSelector: '.item' so:
```html
<div class="item">
<img>
<p>Some text about the thumbnail</p>
</div>
```
Seems like masonry is measuring the sum of img heights of the tallest column for the height of the container.  Is there a workaround for this?

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).
