### ISSUE TITLE
What am I doing wrong!?

### ISSUE THREAD

**Issue by hj8ag** [desandro/masonry#750]
Hi all,

This is such a stupid question I know, but I've been looking at this issue for a little bit and cannot seem to work out where I'm going wrong - I cannot seem to get Masonry to actually work at all. I'm sure I'm doing something rather stupid!

 I've created a test page (http://www.jameshenry.info/test/Masonry.php) and I can't even seem to get Masonry working on this! 

Any ideas?!

**Comment by desandro** [comment]
If your JS code is in `<head>`, then you'll need to wrap it in `docReady`

``` js
docReady( function() {
  var msnry = new Masonry( '.grid', {
    itemSelector: '.grid-item',
    columnWidth: 200
  });
});
```

That's using vanilla JS. Looks like you plan on using jQuery.

``` js
$(document).ready( function() {
  $('.grid').masonry({
    itemSelector: '.grid-item',
    columnWidth: 200
  });
});
```

I also see you have a `.php` JS source pointing to more HTML. This will cause a JavaScript error.
