### ISSUE TITLE
`$container.imagesLoaded is not a function` error

### ISSUE THREAD

**Issue by sevekim** [desandro/masonry#751]
So, I am getting `$container.imagesLoaded is not a function` error.

Here is the code which is located in header:

    (function ($, root, undefined) {
	
	    $(function () {
		
		'use strict';
		////
		
		var $container = $('.grid');

			$container.imagesLoaded(function(){
			  $container.masonry({
				itemSelector: '.grid-item',
				columnWidth: 100
			  });
			});

			$container.infinitescroll({
			  navSelector  : '#rh_nav_below',   
			  nextSelector : '#rh_nav_below .rh_nav_next a',  
			  itemSelector : '.grid-item',   
			  loading: {
				  finishedMsg: 'No more pages to load.',
				  img: 'http://i.imgur.com/6RMhx.gif'
				}
			  },			 
			  function( newElements ) {				
				var $newElems = $( newElements ).css({ opacity: 0 });				
				$newElems.imagesLoaded(function(){				  
				  $newElems.animate({ opacity: 1 });
				  $container.masonry( 'appended', $newElems, true ); 
				});
			  }
			);		
		
		////
		
	});
	
    })(jQuery, this);

Then the footer has following js files:

        <script type="text/javascript" src="http://example.com/js/masonry.pkgd.min.js"></script>
		<script type="text/javascript" src="http://example.com/jquery.infinitescroll.min.js"></script>

Is there something I am missing? is the location of file that's causing the problem?

Thank you.

**EDIT 1**

Followings are located at the footer and script is passed by anonymous function.
But still getting same error.

	    <script type="text/javascript" src="http://example.com/js/masonry.pkgd.min.js"></script>
		<script type="text/javascript" src="http://example.com/jquery.infinitescroll.min.js"></script>
		<script type="text/javascript">
		(function($) {
			var $container = $('.grid');

				$container.imagesLoaded(function(){
				  $container.masonry({
					itemSelector: '.grid-item',
					columnWidth: 100
				  });
				});

				$container.infinitescroll({
				  navSelector  : '#rh_nav_below',   
				  nextSelector : '#rh_nav_below .rh_nav_next a',  
				  itemSelector : '.grid-item',   
				  loading: {
					  finishedMsg: 'No more pages to load.',
					  img: 'http://i.imgur.com/6RMhx.gif'
					}
				  },			 
				  function( newElements ) {				
					var $newElems = $( newElements ).css({ opacity: 0 });				
					$newElems.imagesLoaded(function(){				  
					  $newElems.animate({ opacity: 1 });
					  $container.masonry( 'appended', $newElems, true ); 
					});
				  }
				);		
		})(jQuery);
		</script>

**Comment by stehefan** [comment]
Hej,

thats because imagesLoaded [is not longer included](http://masonry.desandro.com/appendix.html#upgrading-from-v2), you have to include it seperately with the new version of masonry.

**Comment by liuliangsir** [comment]
![image](https://cloud.githubusercontent.com/assets/8049878/9566471/26ca8308-4f39-11e5-8f65-32de02857246.png)

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by anuraghakeem** [comment]
I'm getting a similar error when i used Autoptimize plugin in my wordpress website and I can't figure out hoe to fix this.

Link to my website : humanrace.asia

A similar error can be found in the console.
P.S. this error occurs only in desktop and ipad view ie if you change your view to a phone's view (iphone X etc) from the "Toggle device toolbar", all the images load.
