### ISSUE TITLE
imagesLoaded issue

### ISSUE THREAD

**Issue by liuliangsir** [desandro/masonry#752]
imagesloaded($container,function(){
				$container.masonry({
					columnWidth: '.item',
					itemSelector: '.item',
				});
			});
this code can auto call $container.masonry('layout')? if yes, first call upper code success,second call upper code fail. I want to know why

**Comment by liuliangsir** [comment]
second call upper code layout fail 

![qq](https://cloud.githubusercontent.com/assets/8049878/9571096/e018bf32-4fca-11e5-9199-39b1707dab19.jpg)
![2015-08-31_10-26-16](https://cloud.githubusercontent.com/assets/8049878/9571098/ece47ee0-4fca-11e5-89ce-3f059474894d.png)

**Comment by desandro** [comment]
Try using imagesLoaded as a jQuery plugin.

```js
$container.imagesloaded(function(){
  $container.masonry({
    columnWidth: '.item',
    itemSelector: '.item'
  });
});
```

I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by liuliangsir** [comment]
thanks i has solved this problem by adding $container.masonry("reloadItems"); then $container.masonry()
