### ISSUE TITLE
rails assets - doc ready

### ISSUE THREAD

**Issue by andy-dev** [desandro/masonry#753]
hi!, 

this might be a quick fix, i am still learning how to work with js in rails asset pipeline

i have two js files, both on doc ready, but my file that needs uses masonry wont work unless i remove the doc ready of the other file

should i not use //= tree

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Unfortunately, I don't have any expertise with rails assets. Hopefully someone else can chime in with an answer

**Comment by reinaris** [comment]
@andy-dev hi, I may be able to help you but I dont get the problem exactly.
Do you have issues with the loading order of the javascript files you have in your project?

Please explain a bit more and add some code examples.
