### ISSUE TITLE
Diferent Size image autoalign

### ISSUE THREAD

**Issue by PixelArg** [desandro/masonry#754]
Well, I am making a pixel art community and I need to stay te original size in the images (exept in the bigger images, it fix with max-width:100%). but I cant agrupate the images and autoalign, how I can do this? adding a margin between the other images, some like that:

![image](https://cloud.githubusercontent.com/assets/13700579/9648368/5670ade4-51be-11e5-9c4c-204375bf40ff.png)

Thanks you very much!

**Comment by desandro** [comment]
[Use Packery](http://packeryjs.com)! Packery is designed specifically for these kind of organic layouts.
