### ISSUE TITLE
Foundation responsive grid elements not stacking correctly

### ISSUE THREAD

**Issue by burbanczyk** [desandro/masonry#755]
Hello, I created this pen to illustrate the problem.
http://codepen.io/burbanczyk/pen/MaYprY

There are two kinds of tiles 'small' (25% wide on desktop 50% on tablet 100% on mobile) and 'large' (50% on desktop 100% on tablet and 100% on mobile)
When you are in desktop mode, everything is fine but when you switch to tablet you would expect to have 'small' tiles next to each other. This happens only if they were placed next to each other in the code. I would expect the last two small tiles to be tohether, but they are separated by two large ones.

**Comment by burbanczyk** [comment]
@desandro is this a bug or I'm doing something wrong??

**Comment by desandro** [comment]
Nope. This is how Masonry works. There may be gaps. To fill gaps, [try Packery](http://packery.metafizzy.co)
