### ISSUE TITLE
Sometimes working, sometimes not

### ISSUE THREAD

**Issue by ungeruehrt** [desandro/masonry#756]
Hi there,

I’ve been trying to use your masonry js on my webpage and when it works, it’s doing really well (thanks for that!). Unfortunately sometimes when I load a web page, the images are not aligned like they should, but are clustered on top of the page with nearly no height each on top of each other.

Do you have any idea how to fix this behaviour? I’ve tried to load the page with no scripts but masonry and it occurs still. May this behaviour be caused by  which I’m using as well?

![bildschirmfoto 2015-09-08 um 15 15 29](https://cloud.githubusercontent.com/assets/3136416/9735850/e88d5140-563d-11e5-8636-2e83fd520dd0.png)

**Comment by ungeruehrt** [comment]
Some more information:

If this error occurs, my grid-div with all the images in it gets a `height:48px;` in inline-css while it should be `height:100vh;` normally.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by ungeruehrt** [comment]
Since I wasn’t able to find out which script was interfering with Masonry, I simply loaded Masonry with window.onload().

Thanks though!
