### ISSUE TITLE
Bower + Brunch Error: Cannot read property 'Item' of undefined

### ISSUE THREAD

**Issue by kodie** [desandro/masonry#757]
When installed with bower, it installs a bunch of dependencies and then doesn't work.

These are all of the dependencies that are installed when installed masonry via bower:

masonry#3.3.2 bower_components\masonry
├── fizzy-ui-utils#1.0.1
├── get-size#1.2.2
└── outlayer#1.4.2

fizzy-ui-utils#1.0.1 bower_components\fizzy-ui-utils
├── doc-ready#1.0.4
└── matches-selector#1.0.3

get-size#1.2.2 bower_components\get-size
└── get-style-property#1.0.4

outlayer#1.4.2 bower_components\outlayer
├── doc-ready#1.0.4
├── eventEmitter#4.2.11
├── eventie#1.0.6
├── fizzy-ui-utils#1.0.1
├── get-size#1.2.2
├── get-style-property#1.0.4
└── matches-selector#1.0.3

eventie#1.0.6 bower_components\eventie

eventEmitter#4.2.11 bower_components\eventEmitter

matches-selector#1.0.3 bower_components\matches-selector

doc-ready#1.0.4 bower_components\doc-ready
└── eventie#1.0.6

get-style-property#1.0.4 bower_components\get-style-property

and then this is the error I get when using the script:

Uncaught TypeError: Cannot read property 'Item' of undefined

Masonry works fine when I include masonry.pkgd.js manually.

Just thought I'd let you know! Thanks!

**Comment by desandro** [comment]
How did you try using Masonry? Sounds like your asset pipeline is missing the CommonJS or AMD hooks.

**Comment by kodie** [comment]
I installed Masonry using Gulp/Bower. Are CommonJS and AMD included in masonry.pkgd.js?

**Comment by gcatto** [comment]
I am having the same issue using Bower under Brunch, https://github.com/brunch/brunch although I haven't yet gotten a chance to dig in

**Comment by desandro** [comment]
> Are CommonJS and AMD included in masonry.pkgd.js?

Yes. See [Appendix on docs using Common JS or Require JS with Masonry](http://masonry.desandro.com/appendix.html)

**Comment by gcatto** [comment]
BTW my issue when installing via Bower under Brunch was resolved by providing a local override for masonry to use masonry.pkgd.js instead of masonry.js and to not have any dependencies; something about how they dependencies were being built under Brunch was causing things, but I did not look into it too much.

**Comment by ROBsoer** [comment]
The same problem when I installed masonry via Bower and builded vendors via gulp.
Build system have included dependencies to project than we fased this problem.

**Solution:** add to *bower.json* of your project
```javascript
"overrides": {
    "masonry": {
      "main": [
        "dist/masonry.pkgd.js"
      ],
      "ignore": false
    },
    "outlayer": {
      "ignore": true
    }
```

**Comment by desandro** [comment]
I'm closing this issue as its been quiet for a while.
