### ISSUE TITLE
Having trouble with infinite-scroll plugin for wordpress

### ISSUE THREAD

**Issue by pknadella** [desandro/masonry#758]
HI :)
*the problem* : images overlap in the first load, again after refresh they adjust fine

this kind of issue is posted by many users here and in wordpress forums.....I tried every solution suggested but not working for me.....I am trying this for the past 2weeks but of no use.....I am a complete noob in JS, so hoping some one here could help me.

JS included in the header, manually
```html
<script src="http://localhost/salv/wp-includes/js/jquery/jquery.js?ver=1.11.3" type="text/javascript">
<script src="http://localhost/salv/wp-content/themes/salv/js/masonry.pkgd.js?ver=20150830" type="text/javascript">
```
JS included by the plugin in the footer
```html
<script src="http://localhost/salv/wp-content/plugins/infinite-scroll/js/front-end/jquery.infinitescroll.js?ver=2.6.1" type="text/javascript">
<script src="http://localhost/salv/wp-content/plugins/infinite-scroll/behaviors/masonry-isotope.js?ver=2.6.1" type="text/javascript">
```
the code in my footer to activate masonry, '#grid'  is masonry container and '.post' is item selector
```javascript
<script>
// Code inside here fires when the DOM is ready
jQuery(window).load(function(){
	jQuery('#grid').masonry({
		itemSelector : '.post',
	});
});
</script>
```
the code to initiate masonry specified on official masonry site is not working for me, don't know why, only the above code is working to make masonry work (found this on some forum)

**Comment by desandro** [comment]
See https://github.com/desandro/masonry/issues/747#issuecomment-135777533
