### ISSUE TITLE
problem in desktop screen

### ISSUE THREAD

**Issue by federicolucca** [desandro/masonry#760]
Hi everyone,

I have this problem,here http://www.reputeka.com/categoria/homedesign/cucina i use masonry gallery with angularjs. At the 90% of the times everything works fine but sometimes in the desktop screen the gallery is limited on one column, like in mobile screen . i am not able to understand why , i am changing filters,categories but i don't find the cause. 

Could be a known problem?

Federico

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. I appreciate you providing a live link, but could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).

I cannot debug you live production site.
