### ISSUE TITLE
jQuery implementation not defined.

### ISSUE THREAD

**Issue by galenscook** [desandro/masonry#761]
The function defined in the documentation for the jQuery implementation is undefined.  The work around requires you use the vanilla javascript constructor function.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).

Sounds like you `masonry.pkgd.js` was loaded before `jquery.js`. Can you check that `masonry.pkgd.js` appears _after_ `jquery.js`.

``` html
<script src="jquery.min.js"></script>
<script src="masonry.pkgd.min.js"></script>
```
