### ISSUE TITLE
Safari problem

### ISSUE THREAD

**Issue by snecz** [desandro/masonry#762]
Hello,
On Safari browser (7.1.7) the grid doesn't look good, grid items overlap each other. 
After resizing the browser window grid looks as it should but again after refreshing the problem remains.
Any idea how can I fix it?

**Comment by snecz** [comment]
When I look at Safari source of the page the grid which overlaps has this code:
`<div class="grid-item" style="position: absolute; left: 0px; top: 24px;">`

While in Chrome for example the code is:
`<div class="grid-item" style="position: absolute; left: 0px; top: 240px;">`

After resizing the window in Safari the code is as it should be:
`<div class="grid-item" style="position: absolute; left: 0px; top: 240px;">`

**Comment by snecz** [comment]
Forgot about imagesLoaded. It's fine now.

**Comment by snecz** [comment]
Actually there's still problem. Now also in Chrome. The grid sometimes loads properly and sometimes with overlaping problem.

**Comment by snecz** [comment]
Loading imagesLoaded before masonry script resolved the problem.

**Comment by snecz** [comment]
Actually something still is wrong. The grid doesn't change smooth as I resize the browser window. In any browser.
I used codepen to show it but it's my first time on codepen and I could do something wrong. The real site doesn't look so bad.
http://codepen.io/anon/pen/gaWeVm

**Comment by desandro** [comment]
Looks to be an issue using `fitWidth` with a `grid-sizer` with media queries and `percentPosition`. You can smooth the transition by removing `percentPosition: true`. See [demo on CodePen](http://codepen.io/desandro/pen/84cd54d1ccf5268625ae32502d6557ef/)

**Comment by ale379** [comment]
In 2020 it seems that safari for mobile still encounters problems with this. 
I had a combo together with AOS and my solution was to disable it for mobile (disable: 'mobile') and add imagesloaded module ( https://masonry.desandro.com/layout.html#imagesloaded ).
Hope it helps somebody

**Comment by tarik-besic** [comment]
Using fitWidth just makes my masonry layout in a straight line... Any way to fix it? I did use imagesLoaded...
