### ISSUE TITLE
grid-item--width2 isn’t working for me

### ISSUE THREAD

**Issue by ungeruehrt** [desandro/masonry#764]
Hi there,

I tried to make a grid with one item that should be (depending on the screen size) twice as wide as regular grid-items. Unfortunately all regular/1x items are then not arranged in a grid but one underneath the other. 

I made a codepen with my basic css rules and it isn’t working as well – I’d be happy if you could take a look at it:
http://codepen.io/ungeruehrt/pen/gaMmdP

**Comment by desandro** [comment]
1. Use [imagesLoaded](http://masonry.desandro.com/layout.html#imagesloaded) instead of window.load
2. I moved around the JS in your HTML to the JS setting of the CodePen

See http://codepen.io/desandro/pen/MaeQYB

**Comment by ungeruehrt** [comment]
Thanks, but for me it’s not working in your codepen either (take a look at the screenshot attached, all regular items are still one underneath each other).

I also don’t think that it’s caused by using window.load instead of imagesLoaded since this problem occurs only when I have a double-sized item in my grid. 

![bildschirmfoto 2015-09-22 um 08 37 33](https://cloud.githubusercontent.com/assets/3136416/10012250/68cdd942-6106-11e5-925f-ca9ff956082d.png)

**Comment by ungeruehrt** [comment]
@desandro Did you manage to take a look at your codepen again?
