### ISSUE TITLE
Add method to get all Masonry instances 

### ISSUE THREAD

**Issue by panayotov** [desandro/masonry#765]
Hi,

It would be great to add Masonry method, that returns all Masonry instances ( could be an array ), or single Masonry instance based on jQuery object/Selector. In a lot of themes the Masonry instance is not globally accessible and adding additional functionality usually involves modifying the theme. Adding such a method ( for example Masonry.getInstances() => [  ] ) would make it easy to listen for events on particular instance. 

Best, 
Chris

**Comment by desandro** [comment]
Use [`Masonry.data()`](http://masonry.desandro.com/methods.html#masonry-data)

> Get the Masonry instance via its element. `Masonry.data()` is useful for getting the Masonry instance in JavaScript, after it has been initalized in HTML.

``` html
<!-- init Masonry in HTML -->
<div class="grid js-masonry" data-masonry-options='{...}'>...</div>
```
``` js
// jQuery
// pass in the element, $element[0], not the jQuery object
var msnry = Masonry.data( $('.grid')[0] )

// vanilla JS
// using an element
var grid = document.querySelector('.grid')
var msnry = Masonry.data( grid )
// using a selector string
var msnry = Masonry.data('.grid')
```
