### ISSUE TITLE
ImagesLoaded & Masonry

### ISSUE THREAD

**Issue by hj8ag** [desandro/masonry#767]
I've got the 'Overlapping Elements' issue occurring on my page (I'm using spacer images to resize my DIV's to a specific ratio) - My understanding is I need to also include imagesloaded to enable the layout to flow correctly, I'm doing this but having a few issues, mainly my implementation now seems to have broken Masonry functionality on my page and nothing seems to be working as it should. 

I'm including both 'imagesloaded.pkgd.min.js' and Masonry 3.3.2 (as well as jQuery)

My Javascript is as follows

```
$(document).ready( function() {

				var $container = $('.thumbnail-array');

					$container.imagesLoaded( function(){
						$container.masonry({
    			 		itemSelector: '.video-thumbnail',
    			 		columnWidth: '.grid-sizer',
    			 		gutter: '.gutter-sizer',
    			 		percentPosition: true
					});
				});
			});
```

The page can be found [here](http://www.jameshenry.info/test/) - If anyone has any idea I would really appreciate it!

**Comment by desandro** [comment]
Thanks for the example. Looks like the code was missing a quote mark `<div class=gutter-sizer"></div>`.

See http://codepen.io/desandro/pen/b3db625eccc8afac649244a96ab6dd3f?

You'll have to expand the window bigger than 1400px to see the columns

2.

**Comment by hj8ag** [comment]
Ah, can't believe I missed that! I guess after looking at this so long sometimes you can't see the wood for the trees... Thanks so much, really appreciate you taking a look for me!
