### ISSUE TITLE
prepend elements before stamped elements

### ISSUE THREAD

**Issue by thargal** [desandro/masonry#768]
Hi,
I would like to add elements (prepend) before some stamped elements but it's not working. The element are always add after.

I want to make a system to show a lot of picture without 'next page' juste by scrolling.

Currently I add elements (append method) with no mistake and I delete elements over the top of the screen (I have more than 4000 pictures, I can't show all of them on screen. not enough memory). because I don't want change the order when I delete picture on screen, I set all my element as a 'stamp'. So it's working as I want.

But now, I want reload the deleted picture when I scroll up. And here is my mistake... I can't add elements on the top ! I think is because all my elements are set as 'stamp'. But I haven't got any other way.

You can see my website here : http://thargal.ddns.net/xavcarousel/index3.php

My code : http://thargal.ddns.net/xavcarousel/index3.docx

Thanks !

**Comment by thargal** [comment]
My code : 

<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=0.39">
	<title>jQuery Waterfall Light Plugin Demo</title>
    <link href="http://www.jqueryscript.net/css/jquerysctipttop.css" rel="stylesheet" type="text/css">
	<link rel="stylesheet" type="text/css" href="css/style_caption.css" media="screen"/>
	<script src="http://code.jquery.com/jquery-1.11.2.min.js"></script>
	<script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
	<script src="jquery.capSlide.js" type="text/javascript"></script>
	<script src="masonry.js"></script>-
	<script src="onScreen_perso.js"></script>
<style type="text/css">

	body{
		margin : 10px;
		padding : 0px;
		overflow: auto;
	}

.gradient-pattern {
  -webkit-box-sizing: content-box;
  -moz-box-sizing: content-box;
  box-sizing: content-box;
  border: none;
  font: normal 100%/normal Arial, Helvetica, sans-serif;
  color: rgba(255,255,255,1);
  -o-text-overflow: clip;
  text-overflow: clip;
  background: -webkit-linear-gradient(45deg, rgba(65,163,50,0.05) 0, rgba(255,255,255,0.2) 25%, rgba(0,0,0,0) 25%, rgba(0,0,0,0) 50%, rgba(65,163,50,0.05) 50%, rgba(255,255,255,0.2) 75%, rgba(0,0,0,0) 75%, rgba(0,0,0,0) 100%), rgba(13,53,0,0.1);
  background: -moz-linear-gradient(45deg, rgba(65,163,50,0.05) 0, rgba(255,255,255,0.2) 25%, rgba(0,0,0,0) 25%, rgba(0,0,0,0) 50%, rgba(65,163,50,0.05) 50%, rgba(255,255,255,0.2) 75%, rgba(0,0,0,0) 75%, rgba(0,0,0,0) 100%), rgba(13,53,0,0.1);
  background: linear-gradient(45deg, rgba(65,163,50,0.05) 0, rgba(255,255,255,0.2) 25%, rgba(0,0,0,0) 25%, rgba(0,0,0,0) 50%, rgba(65,163,50,0.05) 50%, rgba(255,255,255,0.2) 75%, rgba(0,0,0,0) 75%, rgba(0,0,0,0) 100%), rgba(13,53,0,0.1);
  background-position: auto auto;
  -webkit-background-origin: padding-box;
  background-origin: padding-box;
  -webkit-background-clip: border-box;
  background-clip: border-box;
  -webkit-background-size: 50px 50px;
  background-size: 50px 50px;
}

/* ---- grid ---- */

.grid {
	margin: 0 auto;
}
/* clearfix */
.grid:after {
  content: '';
  display: block;
  clear: both;
}

/* ---- grid-item ---- */

.grid-item {
  width: 300px;
  margin-bottom: 20px;
  float: left;
  background: #D26;
  border: 1px solid #000;
}

</style>
</head>
<body class="gradient-pattern">
	<div id="info" style="position:fixed; bottom:-30px; right:0px; color:#fff; background-color:#000; width:100%; height:100px; z-index:9999; overflow:auto; opacity:0.5"></div>

	<div class="grid">

		<?php
			// first 35 elements
			for ($i=0; $i < 35; $i++) { 
				echo $div_x = '
					<div class="grid-item ic_container stamp" style="height:'.rand(100,500).'px; background-color:orange; /*background-image:url(\'https://www.kimono-archive.com/files/KimonoArchive/1434608477/1441677172/il_570xN.766747385_foxe.jpg\'); background-size:cover;*/ box-shadow: 0px 0px 15px #777; visibility:visible" id="div_'.$i.'">
						
						DIV_'.$i.'
						<div class="overlay" style="display:none;"></div>
			            <div class="ic_caption" style="bottom:0px">
			                <p class="ic_category">Kimono Archive</p>
			                <center><h3>Amazing Image Title</h3></center>
			                <p class="ic_text">
			                Lorem ipsum dolor sit amet, consectetur adipisicing elit,
			                sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
			            	</p>
			            </div>
					</div>
				';

			}
		?>
	</div>

<script>
$(document).ready( function() {
	$('.grid').masonry({
		itemSelector: '.grid-item',
		columnWidth: 20,
		isFitWidth: true,
		transitionDuration: 0
	});
});

// DETECT TOP
$(window).on('scroll', function() {

    var scrollTop = $(this).scrollTop();

    var $grid = $('.grid');

    var $stamp = $grid.find('.stamp');
		var isStamped = false;

		if ( isStamped ) {
      $grid.masonry( 'unstamp', $stamp );
    } else {
      $grid.masonry( 'stamp', $stamp );
    }
    // trigger layout
    $grid.masonry('layout');
    // set flag
    isStamped = !isStamped;

    $('.ic_container').each(function() {
        var topDistance = $(this).offset().top;

        if ( (topDistance) < scrollTop ) {
            $(this).css('background-color','red');
        }


        var element = $(this);
		var offset_element = element.offset();

		var element_top = offset_element.top;
		var element_bottom = element_top + element.outerHeight();

        if ( (element_bottom + 100) < scrollTop ) {
        	
            $(this).remove(); // delete element over the top of the screen
        }

  		var last_element_top = $('.grid').find('.grid-item').last().offset().top;
  		var first_element_top = $('.grid').find('.grid-item').first().offset().top;

  		var first_div = parseInt($('.grid').find('.grid-item').first().attr('id').substr(4));
  		var last_div = parseInt($('.grid').find('.grid-item').last().attr('id').substr(4))

  		// Add new elements
  		if ((last_element_top - 2200) < scrollTop) {

  			var last = $('.grid > *').length - 1 ;
		  	var last_div_id = $(".grid").find('.ic_container').eq(last).attr('id');

	        var $items = $('<div id="div_' + (parseInt(last_div_id.substr(4))+1) + '" class="grid-item ic_container stamp" style="height:' + Math.floor((Math.random() * 400) + 100) + 'px; background-color:green;/* background-image:url(\'https://www.kimono-archive.com/files/KimonoArchive/1434608477/1441677172/il_570xN.766747385_foxe.jpg\'); background-size:cover;*/ box-shadow: 0px 0px 15px #777; visibility:visible">DIV_' + (parseInt(last_div_id.substr(4))+1) + '<div class="overlay" style="display:none;"></div><div class="ic_caption"  style="bottom:0px"><p class="ic_category">Kimono Archive</p><center><h3>Amazing Image Title</h3></center><p class="ic_text">Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p></div></div>');

	        var $grid = $('.grid');
	      		
	  		// append items to grid
			$grid.append( $items )
			// add and lay out newly appended items
			.masonry( 'appended', $items );

  		};

  		// add old elements on top (Not working)
  		if (scrollTop < first_element_top && first_div > 0) {

		  	var last_div_id = $(".grid").find('.ic_container').first().attr('id');

	        var $items2 = $('<div id="div_' + (parseInt(last_div_id.substr(4))-1) + '" class="grid-item ic_container stamp" style="height:' + Math.floor((Math.random() * 400) + 100) + 'px; background-color:blue;/* background-image:url(\'https://www.kimono-archive.com/files/KimonoArchive/1434608477/1441677172/il_570xN.766747385_foxe.jpg\'); background-size:cover;*/ box-shadow: 0px 0px 15px #777; visibility:visible">DIV_' + (parseInt(last_div_id.substr(4))-1) + '<div class="overlay" style="display:none;"></div><div class="ic_caption"  style="bottom:0px"><p class="ic_category">Kimono Archive</p><center><h3>Amazing Image Title</h3></center><p class="ic_text">Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p></div></div>');

	        var $grid = $('.grid');
	      		
	  		// append items to grid

			//$grid.prepend( $items2 ).masonry('prepended', $items2);
			  
  		};

$('#info').html("scroller : " + $(window).scrollTop() + " document height : " + $(document).height() + " first id : " + first_div + " last id : " + last_div + " total element on screen : " + (last_div-first_div) + " first div height : " + first_element_top);
    });
});
</script>
</body>
</html>

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. I appreciate you linking to your site, but I'm having trouble understanding this request. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by thargal** [comment]
Hello,

Thanks to answer me. Sorry, my english is not very good...

I try to make a system to show on screen only 30 elements (not more because smartphone have only few memory).
So when I scrollDown, I append new elements and I delete old elements (this part work well).
And when I scrollUp, I want Prepend new elements and delete old elements (This part doesn't work yet).

I need to prepend elements without reorder old elements... (When I deleted old elements, the space on top still blank, no reorder).
So I want prepend element in this space.

You can see my mistake here : http://thargal.ddns.net/xavcarousel/index3.php

In orange, the first elements.
In green, the append elements when you scrollDown
In red, the elements will be delete.
In blue, the prepend elements when I scrollUp (but because there is an reorder, it's not really working). <== I want fixe this part.

I need to delete old pictures because I have more than 4000 pictures to show and after 700 pictures it's very slow (because pc and smartphone don't have enough memory).

That is my mistake.

Best regards,
Xavier.

**Comment by desandro** [comment]
> I need to prepend elements without reorder old elements

Sorry, but Masonry does not support this feature. You would have to re-write its layout logic to enable for items to be inserted before other items while maintaining their position.
