### ISSUE TITLE
Blocks jump on Safari browsers

### ISSUE THREAD

**Issue by aliergal** [desandro/masonry#769]
Hi there,

Im using this plugin but it works buggy on Safari browser. When I scroll on the page, some of the div blocks goes right offset of the screen and comes back. I tried to disable animation but nothing changed. Is there any solution for this.

Thank you

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).
