### ISSUE TITLE
Problem with object tag

### ISSUE THREAD

**Issue by ipbebnev** [desandro/masonry#770]
Hello. We using masonry and each our item is link that have link inside that own.
Example:

a href="#" class="masonry item"
   object class="validation hack"
      a href="#" class="some element of interface" /a
   /object
/a

and after this manipulation our masonry is broken.

If this object-structure was removed then masonry is works perfectly.

Have you any things about ?

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).
