### ISSUE TITLE
Multiple calls before layoutComplete causing glitches

### ISSUE THREAD

**Issue by aHulswitt36** [desandro/masonry#771]
I'll start off that this is a little hard to explain.  I am using Masonry 3.3.2 inside of an Angular app.  I am using the Passy/angular-masonry directive, with some modifications to it.  In my app I have, on average, about 60 'bricks'.  The information within the 'bricks' gets updates constantly (via signalR) so the order of the bricks is constantly changing.  The issue is that when we get updates and need to refresh the brick list, in the middle of that refresh I am getting more updates and trying to refresh again.  This is causing brick's to get stacked on top of each other and then gaps as well.  I tried setting a boolean to stop calling for refresh until the layoutComplete event has been thrown, but this hasn't fixed the issue.  The application will start off and order everything fine, but as time goes on this issues just starts constantly happening.  Has anyone seen anything like this?

Thanks

**Comment by desandro** [comment]
Thanks for reporting this issue. I'm sorry I don't have any expertise with Angular. I've moved this issue to passy/angular-masonry so it can get more exposure.
