### ISSUE TITLE
layoutComplete not fired when container has padding-top

### ISSUE THREAD

**Issue by OscarDeDios** [desandro/masonry#775]
Hi,
I want padding-top in the container of masonry, but when I set it the layoutComplete doesn't fire. 

The code is:

	$('#container').css('padding-top','120px');

	var container = document.querySelector('#container');
	var msnry = new Masonry( container, {
		columnWidth: 20,
		isInitLayout: false,
		transitionDuration: '1.5s',
		itemSelector: 'div[class *= postit]'
	});
	msnry._isLayoutInited = true;
	msnry.on( 'layoutComplete', function( items ) {
	 	console.log( items.length );
	});
	msnry.layout();

If I remove the first css padding line the event is fired.

Thanks,
Oscar

**Comment by desandro** [comment]
Thanks for reporting this issue. I think the problem is `msnry._isLayoutInited = true;` Try the code below. See demo http://codepen.io/desandro/pen/61d3dc2b05eb76fffa39357f64f60609/

``` js
var $grid =  $('.grid').css('padding-top','120px');

$grid.masonry({
  ...
  isInitLayout: false
});

$grid.on( 'layoutComplete', function( items ) {
  console.log( items.length );
});

$grid.masonry();
```

**Comment by OscarDeDios** [comment]
Hi, you were right, deleting the line "msnry._isLayoutInited = true;" the event is correctly fired.

Thank you very much @desandro !!!

**Comment by OscarDeDios** [comment]
I'm sorry I reopen the issue because I have another problem with the event.

After the init I execute msnry.layout(); and all works well and the event is fire.

But when I add some element I execute:

		msnry.reloadItems();
		msnry.layout();

Then the event is not fired anymore. What am I doing wrong?

Thanks.

**Comment by OscarDeDios** [comment]
I forget another thing regarding the original issue.. 
Deleting the line:
      msnry._isLayoutInited = true;

The event is fired but I loose the animation in the initial layout that is what I wanted.

Thanks.

**Comment by polack45** [comment]
Hi,

I use masonry for my agenda. But it's not order : 
http://www.verdun.fr/agenda
I don't understand.
Do you have an issue ?
Thanks of lot.
See you.
Bye
