### ISSUE TITLE
TypeError: o.imagesLoaded is not a function?

### ISSUE THREAD

**Issue by xanka** [desandro/masonry#777]
after i'm include jquery Masonry v2.1.07 in my project get error 
imagesLoaded PACKAGED v3.1.4
TypeError: $container.imagesLoaded is not a function
$container.imagesLoaded(function(){...}
what wroong!

**Comment by SgtOddball** [comment]
Are you sure you're calling the masonry js file first? 

Also is $container being populated with an element first? 

ie: 
```javascript
var $container = $('.container');
  $container.imagesLoaded(
    function(){
      $container.masonry({itemSelector:'li' .......})
    }
  )
```

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).
