### ISSUE TITLE
items overlapping on browser resize

### ISSUE THREAD

**Issue by sonkrishna** [desandro/masonry#778]
![masonry resize issue](https://cloud.githubusercontent.com/assets/3024982/10596144/7bb566b6-76fe-11e5-9757-576b4372baaa.png)
hi
I have a bunch of items which masonry is placing very well.
But on resize, sometimes the items overlap.

eventItems: function() {
                var eventItems = $('.event-items');
                if(eventItems.length <= 0)
                    return;
                eventItems.append('<div class="item-sizer"></div>');
                $masonryEvents = eventItems.masonry({
                // options...
                itemSelector: '.item',
                columnWidth: '.item-sizer',
                percentPosition: true
            });
            $masonryEvents.imagesLoaded().done( function() {
                $masonryEvents.masonry('layout');
            }); // layout Masonry after each image loads

This is my code

Should we do something like invalidate? or destroy and reapply masonry?

**Comment by sonkrishna** [comment]
Update1: on every resize of window, I am giving a timeout of 500ms and calling $masonryEvents.masonry('layout'); again

This seems to work fine.

Can you give me a better way to accomplish this.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by PLPeeters** [comment]
I can confirm I've been having this issue for quite some time. I suspect it is related to image loading. I'll try to make a reduced test case if I find some time.
