### ISSUE TITLE
Stamp + Percentage Masonry

### ISSUE THREAD

**Issue by wpsmith** [desandro/masonry#779]
I am trying to create a layout (4 columns: 25%) that has a stamp (2x2) top left (left:0;top:0) with 2 blocks (1x1) to the right followed by another stamp (2x2) flushed right (left:50%;top:25%) with 2 blocks (1x1) below the first stamp. In doing this, I believe I found a bug; err, expose a bug/flaw.

On the [options page](http://masonry.desandro.com/options.html#stamp), there is an example stamp with this [CodePen](http://codepen.io/desandro/pen/hsine). Forking that to reproduce my issue, [here](http://codepen.io/wpsmith/pen/meXoEW) is an example of a modification of the sample masonry stamp to highlight the issue: http://codepen.io/wpsmith/pen/meXoEW

Here is what the expected outcome should be:
![masonry](https://cloud.githubusercontent.com/assets/817366/10706322/ee066316-79b3-11e5-9616-96d804ebc0f5.jpg)

Here is what the outcome is:
![masonry-original](https://cloud.githubusercontent.com/assets/817366/10706434/d6ce0702-79b4-11e5-9db4-d1736d7e0a92.jpg)

So, if the window is 1200px (as the example), widths calculate to:
* .grid-item: 300px
* .featured: 600px

So when masonry does the calculation, a row of four elements, the left value is (parenthesis refers only to the column number for reference only):
* .grid-item(1): left: 0px
* .grid-item(2): left: 300px
* .grid-item(3): left: 600px
* .grid-item(4): left: 900px

But if the first one is a featured item (parenthesis refers only to the column number for reference only):
* .featured.stamp(1): left: 0px
* .grid-item(3): left: 601px
* .grid-item(4): left: 901px

Now, I did add this CSS to every item to no avail...

```.stamp,
.grid-item {
  float: left;
  margin-left: -1px;
  position: relative;
  transform: translateX(1px);
}
```
So when masonry does the calculation, a row of four elements, the left value is (parenthesis refers only to the column number for reference only):
* .grid-item(1): left: 0px
* .grid-item(2): left: 299px
* .grid-item(3): left: 598px
* .grid-item(4): left: 897px

But if the first one is a featured item (parenthesis refers only to the column number for reference only):
* .featured.stamp(1): left: 0px
* .grid-item(3): left: 599px
* .grid-item(4): left: 898px

This makes the width **1px too wide**! I *believe* this is the result of jQuery rounding up within Masonry.

Specifically, as a personal request, [here](http://stackoverflow.com/questions/33310899/jquery-masonry-multiple-stamps-lazyload) is what I was doing, but I believe if we can find the bug in the above scenario, then I can apply it to my personal situation.

**Comment by desandro** [comment]
Thanks for reporting this issue. [Masonry lays out items _below_ stamps](http://masonry.desandro.com/options.html#stamp). This is how Masonry algorithm works. Good news is that you can create this layout but rearranging the order of the featured items in HTML and not using stamps. See demo http://codepen.io/desandro/pen/KdoKQb . I recommend using [element sizing for `columnWidth`](http://masonry.desandro.com/options.html#element-sizing)

Another solution is to use [Packery, which can lay items _around_ and above stamps](http://packery.metafizzy.co/options.html#stamp).
