### ISSUE TITLE
wrong block position with different height

### ISSUE THREAD

**Issue by dhenriet** [desandro/masonry#781]
Hi, 
I am having issue with blocks position. 
With 4 columns, one of a block has a different height and broke layout, on responsive on 3 and 2 colums the order of blocks is not good. I don't understand why, thanks for your help.

![screenshot_2](https://cloud.githubusercontent.com/assets/4640027/10710460/cb639902-7a5b-11e5-9c3d-d90619faffec.png)

Here is a JS Fiddle with the settings http://jsfiddle.net/gamedware/p3k6w9mn/3/

**Comment by desandro** [comment]
This is how the layout algorithm of Masonry works. If you want to preserve left-to-right ordering, look at [Masonry Ordered](http://masonry-ordered.tasuki.org/).

**Comment by dhenriet** [comment]
Thanks, I understand for the order, but why first block (with a different height) break absolute position of the block 5 and 6 (I understand with float elements, but the goal of masonry is to set absolute position) ? Look at this website done with packery, http://www.motogp.com/fr, there is different blocks height and the layout is not broken, it doesn't use Masonry order ?

**Comment by desandro** [comment]
I've opened a new issue to track this feature request. See #873
