### ISSUE TITLE
Dynamic columnWidth causing stacked images in Masonry

### ISSUE THREAD

**Issue by christoph88** [desandro/masonry#784]
I am trying to recreate the masonry blog view from Unify in Rails 4. http://htmlstream.com/preview/unify-v1.8/blog_masonry_3col.html

I bought the theme and included the latest imagesLoaded and Masonry files within my application (using bower-rails).

Masonry PACKAGED v3.3.2
imagesLoaded PACKAGED v3.2.0

When using the with the theme supplied js file all images are stacked on top of each other. From what I can see imagesLoaded is working perfectly. Could this be a bug within columnWidth since it does work more or less with an older version of Masonry?

I made a detailed explanation with screenshots and fiddles on stackoverflow.
http://stackoverflow.com/questions/33617292/dynamic-columnwidth-causing-stacked-images-in-masonry

Any help is greatly appreciated!

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by christoph88** [comment]
Hi David,

Sorry I wasn't aware of these guidelines. (I am quite new to web development and javascript)

I made a test case, hopefully this suffices. If not please let me know what other info you need.

http://codepen.io/anon/pen/zvMObr

**Comment by desandro** [comment]
In Masonry v3, `columnWidth` no longer accepts a function. Instead, use [element sizing for responsive layouts](http://masonry.desandro.com/layout.html#responsive-layouts).

Here's a demo http://codepen.io/desandro/pen/f3451d70f80c35812b33956785ee152c/

**Comment by christoph88** [comment]
Thanks! Going to try it this evening.

**Comment by christoph88** [comment]
This fixes the issue, I forgot to leave my answer :) thanks for your help!
