### ISSUE TITLE
Reload Masonry after ajax call

### ISSUE THREAD

**Issue by Ceyar** [desandro/masonry#785]
Hello, 

First of all, thank you for this great plugin. 

I'm using wordpress, masonry and ajax. I have a problem with masonry when I use ajax to filter my posts by cat.

See example below:
That's the current display for my articles before filtering with ajax:

![capture d ecran 2015-11-10 a 14 46 32](https://cloud.githubusercontent.com/assets/1465346/11063918/f4794894-87b9-11e5-87ce-e72b7e2ea9e9.png)

And after filtering with ajax, masonry doesn't work:

![capture d ecran 2015-11-10 a 14 46 51](https://cloud.githubusercontent.com/assets/1465346/11063980/59ce4280-87ba-11e5-904d-f5e945675fc4.png)

Here is my codes:

I have a my-script.js file for masonry with:

     jQuery(window).load(function(){
       jQuery('.sub-home-article-container').masonry({
    
        columnWidth: '.grid-sizer',
        gutter: '.gutter-sizer',
        itemSelector: '.item',
        percentPosition: true

	});
    });

Then that's my file who is for my ajax call, change_cat_ajax.js:

                jQuery(document).ready(function($){

		$('#cat-home-select').change(function(){
		 if (event.preventDefault) {
			event.preventDefault();
		 } else {
			event.returnValue = false;
		}

		var selected_cat = $(this).val();
		console.log(selected_cat);
		$('.tagged-posts').fadeOut();
		data = {
		            action: 'filter_posts', // function to execute
		            my_ajax_nonce: my_ajax_vars.my_ajax_nonce, // wp_nonce
		            taxonomy: selected_cat, // selected tag
		        };

		        $.post( my_ajax_vars.my_ajax_ajax_url, data, function(response) {

		        	if( response ) {
		                // Display posts on page
		                $('.tagged-posts').html( response );
		                // Restore div visibility
		                $('.tagged-posts').fadeIn()
		            };
		        });
		    });

		});

And in my function.php I have the code below who is called:
         // Script for getting posts
	 function ajax_filter_get_posts( $taxonomy ) {

	  // Verify nonce
	  if( !isset( $_POST['my_ajax_nonce'] ) || !wp_verify_nonce( $_POST['my_ajax_nonce'], 'my_ajax_nonce' ) )
	    die('Permission denied');
	 
	  $taxonomy = $_POST['taxonomy'];
	 
	  // WP Query
	  $args = array(
	    'category_name' => $taxonomy,
	    'posts_per_page' => -1,
		'post_type'      => 'post',
		'orderby'   	 => 'rand',
		'meta_query'     => array(
			array(
				'key'        => 'n_de_ldition',
				'value'      => 36,
				)
			)
	  );
	 
	  // If taxonomy is not set, remove key from array and get all posts
	  if( !$taxonomy ) {
	    unset( $args['category_name'] );
	  }
	 
	  $query = new WP_Query( $args );
	 
	  if ( $query->have_posts() ) : while ( $query->have_posts() ) : $query->the_post(); ?>
	 
	   // My content
								

	  <?php endwhile; ?>
	  <?php else: ?>
	    <h2>No posts found</h2>
	  <?php endif;
	 
	  die();
	}
	 
	add_action('wp_ajax_filter_posts', 'ajax_filter_get_posts');
	add_action('wp_ajax_nopriv_filter_posts', 'ajax_filter_get_posts');

So, I think I have to reload masonry after each call of ajax but I don't know how and where.
Do someone have an idea?
Any help would be great. Thank's in advance. 
Best regards

Dan

**Comment by desandro** [comment]
After adding new items to the page, You can either add them to the Masonry instance with [`appended`](http://masonry.desandro.com/methods.html#appended) or [`reloadItems`](http://masonry.desandro.com/methods.html#reloaditems). Looking at your code it's probably easier to use `reloadItems`.

**Comment by Ceyar** [comment]
Hello,

Thank you for your response. Adding reloadItems doesn't work for me, but I used .masonry(reload) and that worked perfectly. 

    jQuery(document).ready(function($){

    	$('#cat-home-select').change(function(){
    // Prevent defualt action - opening tag page
    if (event.preventDefault) {
    	event.preventDefault();
    } else {
    	event.returnValue = false;
    }

    var selected_cat = $(this).val();
    console.log(selected_cat);
    $('.tagged-posts').fadeOut();
    data = {
                action: 'filter_posts', // function to execute
                my_ajax_nonce: my_ajax_vars.my_ajax_nonce, // wp_nonce
                taxonomy: selected_cat, // selected tag
            };

            $.post( my_ajax_vars.my_ajax_ajax_url, data, function(response) {

            	if( response ) {
                    // Display posts on page
                    $('.tagged-posts').html( response ).masonry( 'reload' );
                    // Restore div visibility
                    $('.tagged-posts').fadeIn();
                };
            });



        });


    });

Also, Thank you for your advise! 

Best regards

Dan

**Comment by Ceyar** [comment]
Hello,

It seems that doesn't completely resolve my first problem so I reopened the issue.

If you have time to help me, that would be very nice ^^.

Here are my problems:

I use ajax to sort my articles. When I sort them, sometimes an articles overlap an other but sometimes not. Apparently, it does do that just on chrome. 

See image below:

![capture d ecran 2015-11-25 a 10 36 35](https://cloud.githubusercontent.com/assets/1465346/11394192/e04c0068-9363-11e5-8233-3bb9f376bf8d.png)

and here is my code:

    $('#cat-edition-select').change(function( event ){
    // Prevent defualt action - opening tag page
    
        event.preventDefault();

    var selected_cat = $(this).val();
    console.log(selected_cat);

     var selected_edition = $(this).attr('data-edition-id');
     console.log(selected_edition);
    $('.tagged-posts-edition').fadeOut();

    

    data = {
                action: 'filter_posts_editions', // function to execute
                my_ajax_nonce: my_ajax_vars.my_ajax_nonce, // wp_nonce
                taxonomy: selected_cat, // selected tag
                editionid: selected_edition,
            };

            $.post( my_ajax_vars.my_ajax_ajax_url, data, function(response) {

                if( response ) {
                    // Display posts on page
                    $('.tagged-posts-edition').html( response );
                    // Restore div visibility
                    $('.tagged-posts-edition').fadeIn().masonry( 'reload' );
                };
            });



        });

I don't know how to reload properly my items...
I have also tried this:

                    // Restore div visibility
                    $('.tagged-posts-edition').fadeIn().imagesLoaded().progress( function() {
                         $('.tagged-posts-edition').masonry('reload'); 
                     });
            

But it's the same issue, sometimes it works and sometimes it doesn't. 
I use google fonts for my articles fonts.

2nd problem:
Something strange appear on my articles when I sort them, sometimes my articles are blurry but not the first article.

Is that a known issue? Here is an image:

![capture d ecran 2015-11-25 a 10 52 07](https://cloud.githubusercontent.com/assets/1465346/11394589/57be8db2-9366-11e5-8f32-5e1af2e29df9.png)


So thank's in advance for your answers.
And if you want I can give you an url or an access to my files in private message to get a closer look. 

Best regards
Dan

**Comment by desandro** [comment]
Sorry, but I am not able to personally debug this issue. See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).
