### ISSUE TITLE
Problem with ajax image loading

### ISSUE THREAD

**Issue by gusteva** [desandro/masonry#787]
Hello. 
I have portfolio page with photos. When user visits page, i need to load first portion photos by ajax. Then when user scrolls page i need to load next portion images by ajax. 

Current problem: all images overlap one another. But when browser cached images it works perfect.
JS  here - https://gist.github.com/gusteva/63ff2d5461fd4770fc38 

screen
![2015-11-19 20 09 07](https://cloud.githubusercontent.com/assets/15928234/11279550/f9d34e38-8ef9-11e5-933e-d52b7fba2de5.png)

Please help me to solve this issue, i tried many different ways, but they did not succeed.

**Comment by desandro** [comment]
Try this code for `success`:

``` js
success: function(data) {
  var $container = $('#photo-container');
  var arr = JSON.parse(data);
  var fragment = document.createDocumentFragment();
  var elems = [];

  elems = arr.map(function(item) {
    var $elem = $('<div class="grid__item"><img src="' + item.image.url + '" /></div>');
    $elem.hide();
    // get DOM element, not jQuery
    var elem = $elem[0]
    // add element, not jQuery, to fragment
    fragment.appendChild( elem );
    return elem
  });
  // append elems to container
  $container.append( fragment );

  $container.imagesLoaded(function() {
    // show items once all visible
    $( elems ).show();
    $container.masonry( 'appended', elems )
  });

  loading=false;
}
```

**Comment by gusteva** [comment]
Thank you very much! It's works perfect!
