### ISSUE TITLE
Grid items overlaps

### ISSUE THREAD

**Issue by macch** [desandro/masonry#789]
![grid issue](https://cloud.githubusercontent.com/assets/12773010/11415875/5fd19080-942e-11e5-8619-c1790fb3d313.png)
Hello,

I have one issue.
When I first time loads the page the grid item overlaps. Check the screenshot.
Here is my code http://codepen.io/anon/pen/YyopBR. It works fine here. But not in my website.

It looks like there is height issue. I can give the min-height to grid item but them masonry functionality will be useless. 

Thank You!

**Comment by desandro** [comment]
Use [imagesLoaded](http://masonry.desandro.com/layout.html#imagesloaded)

See demo http://codepen.io/desandro/pen/2a659ec31bc9762d6fb01f012fec4a6f/

**Comment by macch** [comment]
Thank You so much. It worked...
