### ISSUE TITLE
Look for Reload of Masonry after Resize

### ISSUE THREAD

**Issue by derSteffen** [desandro/masonry#790]
I have an Accordion-Script! In this Accordionscript are Tabs and an image-gallery with lazload .. everthing is fine ... the gallery-divs / masonry-divs became an id ... 
If I click of an Accordion-Head and on an Tab an scroll the images are sort .. in every div which an gallery .... BUT If i resize only the images sort by the current open div and by all image-divs which was before not open (problem: imagesLoaded ??)... The images from div which was before opened dosn't sort.

Is there an solution to reload the function? reloadItems was not the soltion or I have taken an mistake.

Here ist my script which i count and give numbers for every div which has a gallery

```javascript
	$('#veranstaltungen').find('.bildergalerie').each(function(index) {		
	var idbildergalerie = $('.bildergaleriecount').length;
	$(this).before('<span class="bildergaleriecount" style="display:none;"></span>');
	$(this).addClass('bildergaleriedyn'+idbildergalerie);
		
		$('.bildergaleriedyn'+idbildergalerie+' .imgresize').addClass('not-loaded');
		$('.bildergaleriedyn'+idbildergalerie+' img.not-loaded').show().lazyload({ 
					threshold       : 0,
					failure_limit   : 0,
					event           : "scrollstop",
					effect          : "fadeIn",
					container       : window,
					data_attribute  : "original",
					skip_invisible  : true,
					appear          : null,
					load: function() {
					$('.bildergaleriedyn'+idbildergalerie+' img.not-loaded').removeClass("not-loaded");						

					$('.bildergaleriedyn'+idbildergalerie).imagesLoaded( function() {	
							$('.bildergaleriedyn'+idbildergalerie).masonry({		
							itemSelector:'div.imagecontainer',
							gutterWidth: 0,
							isAnimated: false,
							animationOptions: {
								duration: 750
							}
						});
					});
				}
		});
	});
```

Thank you very much

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).
