### ISSUE TITLE
v3.3.2 raise an error on IE8

### ISSUE THREAD

**Issue by MrGrabazu** [desandro/masonry#791]
Hello,

When the page load, the masonry engine try to get the width style value and for that choose the builded function getComputedStyle instead of the property currentStyle on the current element adn after that execute the function :

    getStyleSize(style.width) //(line 887 from masonry.pkgd.js file).

At this point the value of width is undefined and getStyleSize raise an error when the engine try to get the indexOf property on the undefined parameter value.

When the choice is made between getComputedStyle and currentStyle I can see that currentStyle has the property width, but the returned value of getComputedStyle has not.

We are using normally masonry (like the examples on the website) what is wrong ?

Thank you for your answer :)

**Comment by desandro** [comment]
Hello! Thanks for reporting this bug. I have not been able to reproduce this bug in IE8. Can you put together a **reduced test case** with the bug?  See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by MrGrabazu** [comment]
Ok I'll try to provide that to you :)

**Comment by MrGrabazu** [comment]
My bad, one of my coworker has declare getComputedStyle when we are in a IE context if there is no getComputedStyle method... And it doesn't return width value, so it is not going from masonry..
I close the issue because there is no issue !! 

Thank you !
