### ISSUE TITLE
Masonry reload issue. When I reload my page masonry reload function is not working?

### ISSUE THREAD

**Issue by ramyaravindranath** [desandro/masonry#792]
I have placed the below code in head tag of html and also used cdn link as below. But It has got reload issues? Could you please help me on this?

<script src="https://cdnjs.cloudflare.com/ajax/libs/masonry/3.3.2/masonry.pkgd.js"></script>

 <script type="text/javascript">

		$(function() {
						$('.mediaListContainer').masonry({
						itemSelector: '.mediaContainerMasonary',

					}).imagesLoaded(function() {
   						$('.mediaListContainer').masonry('reload')
  					});;
				});
	</script>

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).
