### ISSUE TITLE
Items flash when using ajax append data

### ISSUE THREAD

**Issue by Windsooon** [desandro/masonry#794]
$(document).ready(function(){
    //masonry init()
    var $container = $('#posts-container').masonry({
        columnWidth: 20,
        itemSelector: '.post-container',
        transitionDuration: 0
    });
    var page = 1;
    //get first page data when document ready
    ajax_post(page)
    $(window).scroll(function(){
        if (checkscroll() && ajax_state){
            page += 1;
            ajax_state = false;
            ajax_post(page)
        }
    })

    //ajax get data 
    function ajax_post(page){
        $.ajax({
            url: "/api/post/",
            type: "GET",
            datatype: "json",
            data:  {"page": page},
            beforeSend:function(){
            },
            success: function(data) {
                if (data.results.length > 0) {
                    var elems = [];
                    $.each(data.results, function(key, value){
                        //here to create the dom
                        var single_post = document.createElement("div");
                        single_post.className = "post-container";
                        var post_thumb_a = document.createElement("a");
                        //post_thumb_a.className = value["id"];
                        post_thumb_a.setAttribute("href", "#post_details");
                        post_thumb_a.setAttribute("data-toggle", "modal");
                        var post_thumb_url = document.createElement("img");
                        post_thumb_url.src = value["post_thumb_url"];
                        post_thumb_url.setAttribute("onerror", "imgError(this);");
                        var single_title = document.createElement("div");
                        single_title.className = "single-title";
                        var single_content = document.createElement("div");
                        single_content.className = "single-content-post";
                        var single_title_p = document.createElement("p");
                        single_title_p.className = "post-title";
                        single_title_p.innerHTML = value["post_title"];
                        var single_content_p = document.createElement("p");
                        single_content_p.className = "post-content";
                        single_content_p.innerHTML = value["post_content"];
                        post_thumb_a.appendChild(post_thumb_url);
                        single_post.appendChild(post_thumb_a);
                        single_title.appendChild(single_title_p);
                        single_content.appendChild(single_content_p);
                        single_post.appendChild(single_title);
                        single_post.appendChild(single_content);
                        elems.push(single_post);
                    })
                    var $elems = $(elems);
                    $container.append($elems);
                    //already add imagesLoaded and using masonry
                    $container.imagesLoaded(function(){
                        $container.masonry('appended', $elems, true); 
                    });
                }
            },
            complete:function(){
                ajax_state = true;
            }
        });
    }

    function checkscroll(){
        if($(window).scrollTop()+500 > ($(".post-container:last").offset().top)){
            return true; 
        }
        else{
            return false;
        }
    }
});

Everything works fine,but the problem is when the first time masonry try to append the items(using ajax to get the second page data), the items **show from the top of the container and moving fast to the bottom just like a flash.**Anyway to avoid this?

**Comment by desandro** [comment]
Try hiding the new elems, then they can be revealing them when imagesLoaded

``` js
var $elems = $(elems).hide();
$container.append($elems);
//already add imagesLoaded and using masonry
$container.imagesLoaded(function(){
    $elems.show();
    $container.masonry('appended', $elems); 
});
```

**Comment by Windsooon** [comment]
It works!! Thanks a lot.
