### ISSUE TITLE
TypeScript type definition file (d.ts) for Masonry

### ISSUE THREAD

**Issue by m-a-wilson** [desandro/masonry#799]
Someone has done a type definition file for jQuery and for imagesloaded. A type definition file for the Masonry public interface would enable using TypeScript to create Masonry apps.

**Comment by desandro** [comment]
Thanks for this feature request. **+1 this issue** if you'd like to see Masonry have TypeScript support added.

I'd like to hold off on supporting another platform. TypeScript is out of my expertise so I'd rather not add something unless I know its valuable to a large number of developers and it can be properly maintained.

**Comment by Tommertom** [comment]
+1

**Comment by desandro** [comment]
Closing this issue. Looks like it didn't get much public interested :whale:

**Comment by stombeur** [comment]
see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/7989 
it's in a pull request, but not yet merged
don't know if it's good yet, still need to try it

**Comment by m-a-wilson** [comment]
Excellent. Thanks.

**Comment by m-a-wilson** [comment]
Closed but not forgotten. The pull request for DefinitelyTyped mentioned above died for lack of response from the original author. However, I took the previous work, addressed the issues and submitted another pull request ( [#10117](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10117) ) which is currently pending.

**Comment by judowalker** [comment]
It's been merged.
