### ISSUE TITLE
Empty places in masonry lists of pictures on firefox

### ISSUE THREAD

**Issue by Tuhaj** [desandro/masonry#800]
On long lists of pictures some of the grids are skipped as if there
was an element, but nothing is there. Happens only on Firefox.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).
