### ISSUE TITLE
transitionDuration has no effect

### ISSUE THREAD

**Issue by brethummel** [desandro/masonry#802]
I've been poking at this for sometime and scouring the web for a solution, but falling up short, which makes me think there's some sort of bug going on in version 3.3.2.  I cannot disable the transitions.  I've set transitionDuration to 0, set it to some crazy big number as well, and nothing changes.

You can see it here:  http://www.brethummel.com/clients/mcg/mcg001/
You can see in the main.js file that transitionDuration is set to 0.

Any ideas?

**Comment by desandro** [comment]
Looks like you are initializing with HTML and JS at the same time. You should use one or the another, but not both - to avoid conflicts. Try removing `js-masonry` from your HTML.

**Comment by brethummel** [comment]
I see that, whoops.  I've removed `<js-masonry>' and verified that the main.js script is being called.  But NOW masonry won't even initialize.  http://www.brethummel.com/clients/mcg/mcg001/

Is there something wrong with this code?

```javascript
$('.masonry-grid').masonry({
		itemSelector: '.grid-item',
		columnWidth: '.grid-sizer',
		percentPosition: true,
		isResizeBound: false,
		transitionDuration: 0
});
```

I'm pulling my hair out over this one.

**Comment by desandro** [comment]
From what I can tell, your Masonry initialization code is not in any part of your `.js` files or in the page's source.

**Comment by brethummel** [comment]
It's in the main.js file which is called after masonry.js, up in the header.

http://www.brethummel.com/clients/mcg/mcg001/wp-content/themes/microgigantic/js/main.js

**Comment by brethummel** [comment]
Here's a jsfiddle:

https://jsfiddle.net/2g4rk7zv/

**Comment by brethummel** [comment]
I think I got it.  Somehow in my modifications to the html, I'd removed the item selector class of `.grid-item` which was still in the masonry initialization call.
