### ISSUE TITLE
Images overlapping on prepend

### ISSUE THREAD

**Issue by itzikbenh** [desandro/masonry#804]
Hey, I'm using bootstrap to show images in a thumbnail and I use AJAX to upload them. When I prepend then the image on the right that is going to the second line always overlaps half of the the thumbnail that I just uploaded. Is it not possible to prepend images? 

 $("#pins").imagesLoaded(function(){
   $("#pins").masonry()
   .prepend($(data))
   .masonry( 'appended', $(data), true)
});

I tried many variations, but It doesn't work. Also when when I put 'prepended' on the last line I get an error that this method doesn't exist. Very weird.

**Comment by desandro** [comment]
Sorry to hear you're having trouble with Masonry. I believe the issue is that imagesLoaded needs to be triggered on the new content. Try this code.

``` js
var $data = $(data).imagesLoaded( function() {
  $('#pins').prepend( $data )
    .masonry( 'appended', $data );
});
```

**Comment by itzikbenh** [comment]
Thanks for answering. Your solution worked, but I had to first give the images a fixed height. Luckily it's not an issue for me to do that.
