### ISSUE TITLE
Responsive layout delay

### ISSUE THREAD

**Issue by vadimilyin** [desandro/masonry#806]
When I resize window – items change size as it should be but top position changes with delay (with speed of transitionDuration) like in demo. Question is how to make items change top position immediately. Example http://emilolsson.com/hi-response/index/masonry/ (actually on Packery, but with the masonry layout)

**Comment by desandro** [comment]
Have you tried  `percentPosition: true` http://masonry.desandro.com/options.html#percentposition ? See demo: http://codepen.io/desandro/pen/JFpeg

**Comment by pushkaruk** [comment]
Of course. When block height is dynamic like image – it gives a delay. Like in this your demo http://codepen.io/desandro/pen/bdgRzg Somehow Emil Olsson made this through

**Comment by desandro** [comment]
That delay is there for the benefit of your users. Otherwise `resize` logic gets triggered every millisecond the window is resized.

The good news is that I am working on [another library, Colcade](https://github.com/desandro/colcade/blob/master/colcade.js) that doesn't rely on positioning with JS.

**Comment by pushkaruk** [comment]
Thank you for your great work. Is there code in a masonry that I can change or delete to remove this delay on top position?
