### ISSUE TITLE
isFitWidth but fluid with tiles aligned left

### ISSUE THREAD

**Issue by TKB21** [desandro/masonry#808]
I just started using Masonry and ran into a small issue when putting together my layout. I basically want a container div to hold rows of tiles and have them fill the entire width of their parent and aligned left. Luckily I found the option `isFitWidth`. 

The only problem is that I need the container to be fluid and non-centered as done in the example. I noticed that there's an automatic right margin applied to the container when this option is applied, which to my understanding is preventing this from happening. Is there a way I can effectively get this to work?

http://codepen.io/CEB/pen/eJVJgj

**Comment by desandro** [comment]
I believe you do not need `isFitWidth`. `fitWidth` does the opposite of what you want: sets a width on the container so it can be centered with `margin: 0 auto` CSS. See demo http://codepen.io/desandro/pen/1a5e861609b8942c4c06bdb9dbba1c29/

**Comment by TKB21** [comment]
Thanks for the prompt response. Is there a way to get it so that spacing is even on both sides (identical to what's done with is it width)? I noticed in your pen that there's more space to the right edge.

**Comment by desandro** [comment]
If you want the container to be centered, use [fitWidth](http://masonry.desandro.com/options.html#fitwidth), but fitWidth does not work with percentage width

> fitWidth: true does not work with element sizing with percentage width. Either columnWidth needs to be set to a fixed size, like columnWidth: 120, or items need to have a fixed size in pixels, like width: 120px. Otherwise, the container and item widths will collapse on one another.

**Comment by TKB21** [comment]
I guess my only question now is if there's an override to remove the automatic margin that's applied to the container. Adding `!important` doesn't seems to do the trick. My guess is that this is because the margin takes higher priority being that it's injected inline?

**Comment by desandro** [comment]
There is no margin being added. What is being set is the width of the container, hence `fitWidth`. Masonry is setting the width of the container to fit the exact amount of columns. With that width set, you can center the container with `margin: 0 auto`. See demo  http://codepen.io/desandro/pen/nGLvx

**Comment by cbanksbi** [comment]
Ah I see now! Thanks so much for your help and keep up the great work. This plugin has been a godsend to my current project.

**Comment by TKB21** [comment]
Ah I see now! Thanks so much for your help and keep up the great work. This plugin has been a godsend to my current project.
