### ISSUE TITLE
Gaps/overlaps with fluid text

### ISSUE THREAD

**Issue by Enkii-Muto** [desandro/masonry#809]
Hello, sir! Thank you for such amazing work and support. I feel like an idiot not doing something very obvious, but I tried everything to my knowledge to fix it (although, to be fair, it isn't much).

Bootstrap along with Masonry creates gaps when it resizes the view with a dramatic difference than before, on a computer it just looks ugly but on a mobile, when rotating view, it tends to even break its wrapper and wear the next element it like a [cute skirt](http://imgur.com/19M3Gha).

When change happens gradually, no problems occur that aren't fixed on a fraction of a second while it calculates.

My reduced test case [here](http://codepen.io/Munin/pen/wMymvZ) displays the same problem (although I didn't test it on mobile), usually on columns 4 and 5. It is worth mentioning that unlike the mobile, neither my website nor the test got out of its parent on the PC.

While searching for similar cases, I did find that your [example](https://github.com/desandro/masonry/issues/803) solving an overlap issue displays a similar error that can be seen [here](http://imgur.com/Ugvikeq).

I suppose this is data enough, but if you need more details I'll see what I can do. Again, sorry to bother you and thank you for your time.

Edit: typo.

**Comment by desandro** [comment]
Thanks for reporting this issue. This issue is the same as https://github.com/desandro/masonry/issues/427#issuecomment-50423923

You can resolve the issue by setting a default size of `width: 100%` on the column elements. This might be a bit tricky because of how CodePen loads its CSS, but it should be easier in your own workflow.

**Comment by Enkii-Muto** [comment]
Thank you for your time and sorry to bother even though you closed it. I followed your suggestions (and your example on #427), it worked, mostly. I found out that older mobiles have a problem with masonry in gaps and overlaps when resizing. I tried to see with 3 phones, two different models of samsung duos and a newer one I don't recall the name.

Only the newer one worked perfectly, but I can see how this might become a problem for older ones. As I'm using bootstrap, and only md-columns, do you think it would be easy to avoid this error if I disable masonry for screens smaller than 970px wide, where bootstrap would stack them anyway?

If so, do you think just removing the selectors would do the trick? Something like:


`$(window).resize(function(){
		if ($( window ).width() < 970 ){
			$( "div#ms-container" ).children(".myJ").removeClass("ms-item");
       }
       else{
			$( "div#ms-container" ).children(".myJ").addClass("ms-item");
       }
	});`
