### ISSUE TITLE
Feature request: Not always choose the shortest column

### ISSUE THREAD

**Issue by dwilmer** [desandro/masonry#810]
This is a feature request to change the positioning algorithm. Currently, the algorithm works as follows:
 1. select the height of the shortest column
 2. Select the leftmost (or rightmost) column of the columns with that height.

I would like to propose another algorithm:

1. Select the height of the shortest column
2. Select the leftmost (or rightmost) column of the columns with `height <= (min_height + e)`, where `e` is a small value which the user can set, for example three pixels.

An example where this use case would be nice, can be seen here: http://codepen.io/anon/pen/JGLQVp
In this example, the slightly larger box on the left causes the box on the next line to be positioned in the middle column, while a position in the left column would be more visually pleasing — especially since the small height difference between the columns is not noticeable, due to the gutters and margin.

**Comment by desandro** [comment]
Thanks so much! Closing issue here to discuss in the pull request #811.
