### ISSUE TITLE
animating max-height of item and relayout items

### ISSUE THREAD

**Issue by gerryxx** [desandro/masonry#812]
I implemented a screen with 2 columns of collapsable tiles which are layouted by masonry. Now i want to animate the open/collapse of the tile simulatnously with the relayout of the tiles.

On the website under extras is a article which illustrates how to do this. Unfortunately the height of the tile is variable (it depends on the content), hence I have to work arround with the max-height property. The two animations work now simultaneously, but masonry computes the wrong (previous) height.

It seems that in case of animating the max-height property, masonry takes the initial height value for relayouting the tiles and not the real (after the animation is finished) one. 

Is there a workarround for this problem?

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by gerryxx** [comment]
I've seen that my problem description above was a little bit confusing, so i rephrased it. I reproduced the problem in this [codepen](http://codepen.io/gerryxx/pen/jWpLBO)

**Comment by desandro** [comment]
Thanks for that. Because the item size is determined by the size of the content, we can't use [the technique covered in the docs](http://masonry.desandro.com/extras.html#animating-item-size). But we can at least resolve it. `layout` needs to be triggered after the item size has completely changed

[See demo on CodePen](http://codepen.io/desandro/pen/433dc9d65b245d9d6377b5d8c30806cc/)

``` js
$grid.on( 'click', '.grid-item-content', function( event ) {
  var $gridItem = $( event.currentTarget ).parent('.grid-item');
  $gridItem.one( 'transitionend webkitTransitionEnd', function() {
    $grid.masonry();  
  });
  $gridItem.toggleClass('is-expanded');
});
```

**Comment by gerryxx** [comment]
Thank you for your feedback. 

I had expected that the animations can't be combined. At least you provided me a better solution than my current workarround using timeout for triggering the relayout.
