### ISSUE TITLE
Masonry only update height value after load ajax content for second time

### ISSUE THREAD

**Issue by pmiguelr** [desandro/masonry#813]
Hi,
Im using masonry with imagesloaded. Everything ok, but i have a problem:
- The only very small issue that I have is that first 6 items loaded via AJAX, masonry shows them overlapped.
- Then i request ajax to load more 6.
Result: Itens 1-6 are ok now, but itens 7 - 13 are overlapped.
And this happen each time i request ajax load, i need that masonry div height update at 1st time.

**Comment by desandro** [comment]
Sorry to hear you're having trouble with Masonry. Could you post your ajax code, or better yet provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).
