### ISSUE TITLE
Masonry with instafeed

### ISSUE THREAD

**Issue by heenac** [desandro/masonry#814]
Hi,
I'm new to Masonry.js. 
I'm displaying Instagram account images on my webpage using instsfeed.js.
I wish to display them in a masonry style.
I tried clooking for tutorials where instafeed.ja and masonry is used together. But there seem to be no tutorials out there.
Could you please help me with this.

The following isthe code i use for instafeed.

javascripts:
<script type="text/javascript" src="themes/Theme/js/instafeed.min.js"></script>
<script type="text/javascript">
var feed = new Instafeed({
get: 'user',
userId: xxxxxxxxxxx,
accessToken: 'xxxxxxxxxx.xxxxxxxxxx.xxxxxxxxxx'
});
feed.run();
</script>

css:
.instafeed {
    white-space: nowrap;
    position: relative;
}
.instafeed a {
    vertical-align: top;
    display: block;
    float: left
}
.instafeed a:hover img {
    box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
    -webkit-transform: scale(1.1);
    transform: scale(1.1)
}
.instafeed img {
    display: block;
    border-radius: 4px;
    transition: all 220ms ease-in-out
}

html:
<div class="instafeed" id="instafeed"></div>

Could you help me form the code for the Masonry with the above. 
Thanks in advance.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by heenac** [comment]
Hi Desandro.

Thanks for the quick reply. 
here is the codepen link.

http://codepen.io/chauhanheena/pen/OMBdQK

I wish to display this in a masonry grid format.

**Comment by desandro** [comment]
Looks like you should use the `after` callback to trigger Masonry. See [demo on CodePen](http://codepen.io/desandro/pen/f7b9870b16328fb4539afcca890349cd/)

``` js
var gridElem = document.querySelector('#instafeed');
var msnry;

var feed = new Instafeed({
  get: 'user',
  userId: 2862069247,
  accessToken: '2862069247.8f389c0.7982b9a9eea34e07ba61dbe3e1fddeaf',
  after: function() {
    msnry = new Masonry('#instafeed');
    imagesLoaded( gridElem ).on( 'progress', function() {
      msnry.layout();
    });
  }
});
feed.run();
```

**Comment by heenac** [comment]
Hi Desandro.

Thank you for the help. I have a very small alignment issue.
the codepen link is http://codepen.io/chauhanheena/pen/BjGKOB

How can I center align the instafeed div in the wrap div. it is by default left aligned. I tried my ways out but nothing worked. Could you please help.

thanks a lot.

**Comment by desandro** [comment]
You can center a container with the [`fitWidth` option](http://masonry.desandro.com/options.html#fitwidth). It's supported by Masonry, but not by Packery.
