### ISSUE TITLE
Bower install with Bootstrap in roots/sage

### ISSUE THREAD

**Issue by hphioolen** [desandro/masonry#817]
Hi,
I tried to bower install masonry 4.0.0 on a fresh "sage" theme (Roots framework).
After gulping the theme i get js errors like below. Removing packages like carousel.js, just fires another error on another package. Do you know any issues regarding this or doe you have a solution in avoiding this? Loading the pkgd from the CDN does work. 

TypeError: undefined is not an object (evaluating 't.Outlayer.Item')
(anonieme functie)carousel.js:157
(anonieme functie)carousel.js:159

**Comment by desandro** [comment]
Sounds like roots relies on `bower.json` main to point to all files. It's missing `outlayer/item.js`. See metafizzy/outlayer#33 for some solutions.

**Comment by hphioolen** [comment]
Thanks, that put me on the right track. I found the definite solution on https://github.com/austinpray/asset-builder/wiki/User-Contributed-Examples
