### ISSUE TITLE
Chrome vs Firefox

### ISSUE THREAD

**Issue by tispratik** [desandro/masonry#818]
Seems like there is some issue with Chrome. The site topmunch.com works perfectly on firefox but not on chrome. Do you happen to know the reason why? 

I have tried many different things to see what could be causing it, but could not figure out. Any inputs here will be appreciated.

**Comment by desandro** [comment]
Masonry is not initialized on this page. Sorry, but I won't be able to debug this production site. If you have a **reduced test case** I'd be happy to take a look. See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).
