### ISSUE TITLE
Masonry error when bundling with SystemJS

### ISSUE THREAD

**Issue by stefankorun** [desandro/masonry#819]
I am using the Masonry with npm and SystemJS and in the development version I am referencing the pkgd file like this (using the packaged version):

`'masonry-layout': 'npm:masonry-layout/dist/masonry.pkgd'`

The problem arises when I try to bundle SystemJS files using [systemjs-bulder](https://github.com/systemjs/builder) using the same SystemJS config (so we have same reference for masonry). It seems that despite the packaged version being used, Masonry still requires `outlayer/outlayer`. If I fix the `outlayer` path in SystemJS config than it fails on `get-size` and so on. 

The first `outlayer` error:

```
Unhandled rejection Error on fetch for outlayer/outlayer.js at file:///d:/path/to/project/outlayer/outlayer.js
    Loading builds/dev/boot.js
    Loading builds/dev/src/app.js
    Loading builds/dev/src/components/components-preview/components-preview.js
    Loading builds/dev/src/components/masonry/masonry.js
    Loading npm:masonry-layout/dist/masonry.pkgd.js
    Error: ENOENT: no such file or directory, open 'd:\path\to\project\outlayer\outlayer.js'
    at Error (native)
```

The final workaround:

```
System.config({
  defaultJSExtensions: true,
  format: 'register',
  paths: {
    'npm:*': 'node_modules/*'
  },
  map: {
    ... other references ...

    // masonry reference
    'masonry-layout': 'npm:masonry-layout/dist/masonry.pkgd',

    // workaround references
    'outlayer': 'npm:outlayer',
    'get-size': 'npm:get-size',
    'ev-emitter': 'npm:ev-emitter',
    'fizzy-ui-utils': 'npm:fizzy-ui-utils',
    'desandro-matches-selector': 'npm:desandro-matches-selector'
  }
});
```

Is there a fix for this or am I missing something, because referencing libraries for a packaged version seems more like a temporary workaround than a solution.

**Comment by desandro** [comment]
I don't recommend use of `masonry.pkgd` for package managers like SystemJS because `masonry.pkgd` is designed for use when you don't want to use package management.

Have you looked just using `masonry-layout` and relying on its `package.json` dependencies? Masonry works with [Webpack](http://masonry.desandro.com/extras.html#webpack) and [Browserify](http://masonry.desandro.com/extras.html#browserify) just fine without any config. [RequireJS](http://masonry.desandro.com/extras.html#requirejs) works as well.

**Comment by stefankorun** [comment]
I am using the packaged version because I had the same problem with the normal version even in the `dev` build. Over there I get:

`Error: XHR error (404 Not Found) loading http://localhost:3000/outlayer/outlayer.js`

The workaround for this is the same as the previous in SystemJS config. The second workaround is to map `node_modules` like this:
```
System.config({
  ... other settings ...

  paths: {
    ... other mappings ...

    '*': 'node_modules/*'
  }
}
```

The reason I am asking this and not defaulting to the solutions above is that only masonry is giving me this type of import errors.

**Comment by desandro** [comment]
Take a look over systemjs/systemjs#767 for possible solutions. This one looks to be the most promising:

``` js
System.config({
  paths: {
    '*': 'node_modules/*',
    'app/*': 'app/*'
  }
});
```

If you're not a fan of the ` '*': 'node_modules/*'` config, then, yes, your original solution works just as well.

**Comment by n0mid** [comment]
Hi. I use `masonry-layout` with `angular2-masonry`. And when I use systemJS to build bundle I got next error on project load: 
`Uncaught Module ./item not present.`

I found  `require('./item')` in masonry.pkgd.js, but I don't found any item.js file.

Somebody has any solutions for this problem?

**Comment by jmls** [comment]
@n0mid did you ever find a solution ? I've just hit the exact same error but using brunch.io

**Comment by ericmmartin** [comment]
I was also having an issue loading the `node_modules/masonry-layout/masonry.js` file and getting the outlayer and get-size issues. I tried some of the solutions above, but couldn't get them working. In the end, the following did the trick for me:

In `systemjs.config.js`:

```javascript
System.config({
    defaultExtensions: true,
    transpiler: 'plugin-babel',
    paths: {
        'npm:': 'node_modules/'
    },
    map: {
        // ...
        'masonry-layout': 'npm:masonry-layout/masonry.js',
        'outlayer': 'npm:outlayer',
        'get-size': 'npm:get-size',
        'ev-emitter': 'npm:ev-emitter',
        'fizzy-ui-utils': 'npm:fizzy-ui-utils',
        'desandro-matches-selector': 'npm:desandro-matches-selector'
    },
    packages: {
        // all of these are for masonry-layout
        '/node_modules/outlayer': {
            main: './outlayer.js'
        },
        '/node_modules/get-size': {
            main: './get-size.js'
        },
        '/node_modules/ev-emitter': {
            main: './ev-emitter.js'
        },
        '/node_modules/fizzy-ui-utils': {
            main: './utils.js'
        },
        '/node_modules/desandro-matches-selector': {
            main: './matches-selector.js'
        }
    }
});
```
