### ISSUE TITLE
Overlapping elements without refresh 

### ISSUE THREAD

**Issue by jsm23097** [desandro/masonry#820]
My website has a few divs overlapping when you scale down. However if you refresh the page it corrects itself. How can I get my divs to transition properly without refresh?

**Comment by jsm23097** [comment]
My Site is http://jasminejones.online/

**Comment by desandro** [comment]
Use imagesLoaded. See http://masonry.desandro.com/layout.html#imagesloaded

Some other things that should help

1. Remove `<script src="/path/to/masonry.pkgd.min.js"></script>`. Masonry is already included in `JS/Plugin.js`
2. Add [`imagesloaded.pkgd.min.js`](http://imagesloaded.desandro.com/imagesloaded.pkgd.min.js) to `Plugin.js`
3. Return your `<script>` code. 

From

``` html
<script>$('.grid').masonry({
  itemSelector: '.grid-item',
  columnWidth: 400,
  originTop: false,
  fitWidth: true
});
</script>
<script>
var elem = document.querySelector('.grid');
var msnry = new Masonry( elem, {
  // options
  itemSelector: '.grid-item',
  columnWidth: 400
 
});


// element argument can be a selector string
//   for an individual element
var msnry = new Masonry( '.grid', {
  // options
});
</script>
```

to

``` html
<script>
var msnry = new Masonry( '.grid', {
  itemSelector: '.grid-item',
  columnWidth: 300
});

imagesLoaded( '.grid' ).on( 'progress', function() {
  msnry.layout();
});
</script>
```

**Comment by jsm23097** [comment]
Thank you for your help. Unfortunately that new line of code you suggested broke the plugin. I'm not sure how to call the plugin with this new script or if I am doing something else wrong.

**Comment by desandro** [comment]
Try taking a look at the source code of the [imagesLoaded example](http://masonry.desandro.com/layout.html#imagesloaded): http://s.codepen.io/desandro/debug/MwJoZQ

**Comment by jsm23097** [comment]
I actually got It! Thanks. I found that by changing the column width to ".item" instead of an px dimension. However I am seeing that on mobile the entire site shirks down. Its that normal?

**Comment by desandro** [comment]
You still have bugs occuring

![screen shot 2016-02-18 at 9 53 05 am](https://cloud.githubusercontent.com/assets/85566/13146873/8044e978-d625-11e5-9b79-835d3826eb4e.png)

These bugs are viewable in the Developer Console. I'm using [Chrome Developer Tools](https://developer.chrome.com/devtools).

You can resolve these bugs.

1. Remove `<script src="/path/to/masonry.pkgd.min.js"></script>` from your HTML. This file does not exist for your site. Masonry is already included in `JS/Plugin.js`
2. Change your `<script>` code
  
From

``` html
<script>$('.grid').masonry({
  itemSelector: '.grid-item',
  columnWidth: ".item",
  originTop: false,
  fitWidth: true
});
</script>
<script>
var elem = document.querySelector('.grid');
var msnry = new Masonry( elem, {
  // options
  itemSelector: '.grid-item',
  columnWidth: ".item"
 
});


// element argument can be a selector string
//   for an individual element
var msnry = new Masonry( '.grid', {
  // options
});
</script>
```

To

``` html
<script>
var msnry = new Masonry( '.grid', {
  itemSelector: '.grid-item',
  columnWidth: 310
})
</script>
```


You should set `columnWidth: 310`. You have it set to `.item`, but there are no `.item` elements, so it's [falling back to the outerWidth of the first element](http://masonry.desandro.com/options.html#columnwidth). This so happens to be 310px. But if you change that first element to a bigger element, you'll find the layout has gaps.
