### ISSUE TITLE
originLeft: false not working

### ISSUE THREAD

**Issue by airani** [desandro/masonry#821]
Hi,
After adding origiLeft:false to my options right-to-left not working for masonry in version 4!

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? Try forking [the `originLeft: false` demo](http://codepen.io/desandro/pen/adwgL). See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by airani** [comment]
Look at your sample in [this pgae](http://codepen.io/desandro/pen/adwgL). if originLeft true or false no differents elements are placed from left to right!
