### ISSUE TITLE
fadeIn() breaking appended transition 

### ISSUE THREAD

**Issue by Windsooon** [desandro/masonry#824]
``` js
  var $elems = $(elems);
  var $elems = $(elems).hide();
  $container.append($elems);
  $container.imagesLoaded(function(){
  $elems.fadeIn(500);
  $container.masonry('appended', $elems);  
```

This work prefect when I using jquery.masonry.js, but when I use newest masonry.js, the elems append animation become strange. Thanks for any help

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by Windsooon** [comment]
http://codepen.io/WindsonYang/pen/eZOzLx/  here is my code, but because of "Access-Control-Allow-Origin" here, the ajax call won't work.Sorry for that,  and I found is not related to the new vision, both will have this problem.

**Comment by desandro** [comment]
Thanks for that. I believe `fadeIn`, is the issue. This will conflict with Masonry's hide/reveal transitions.

Try: 

``` js
var $elems = $(elems).hide();
$container.append($elems);
$container.imagesLoaded(function(){
    $elems.show();
    $container.masonry('appended', $elems); 
});
```

You can disable the scale transition on `appended` with `hiddenStyle` and `visibleStyle` options

``` js
var $container = $('#posts-container').masonry({
    columnWidth: 20,
    itemSelector: '.post-container',
    isFitWidth: true,
    transitionDuration: '0.5s',
    hiddenStyle: { opacity: 0 },
    visibleStyle: { opacity: 0 }
});
```

**Comment by Windsooon** [comment]
Thank you, it works!
