### ISSUE TITLE
demo width issue

### ISSUE THREAD

**Issue by Nic787** [desandro/masonry#826]
Hi,

I was trying some stuffs in the last layout demo and found something strange. Images are not aligned on the right side and it make gallery very weird.

![capture d ecran 2016-02-24 a 09 07 18](https://cloud.githubusercontent.com/assets/11185348/13287672/4139c3f6-dad6-11e5-8af4-d942b9885b7d.png)

I tried to add fitwidth: true, but it still here.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by Nic787** [comment]
I used your demo here : http://codepen.io/desandro/pen/bdgRzg

It happen when width is more than 1900px;

**Comment by desandro** [comment]
Looks like its a CSS bug. Set `width: 100%` on images, instead of `max-width`. I've updated the demo.
