### ISSUE TITLE
Alignment issue when using percentage gridding and stamp

### ISSUE THREAD

**Issue by bigbrov** [desandro/masonry#827]
I'm having issues where items are not correctly positioned when using a stamp. Each item is 1/3th of the grid where the stamp takes 2/3th. Theoretically the normal items should fit within the 1/3th space next to the stamp but unfortunately it is not the case.

Problem occurs on :
- Firefox (using version 43.0.3) - 100% zoom level
- Internet Explorer (using version 11.0.9600.18163) - 100% zoom level
- Chrome (using version 47.0.2526.106) - 25% zoom level

I created an example to visualize the problem : http://codepen.io/bigbrov/full/adeMMz/

I checked within the source, it seems to be a rounding problem within the _ _manageStamp_ function when calculating the first column (or last column). I've noticed that I had 0.99999242 or 1.00001424 numbers as result. I have overridden the _ _manageStamp_ function at my side, and added a Math.round() to resolve the rounding issues.

This is my version of the function, maybe it can help you.

    Masonry.prototype._manageStamp = function( stamp ) {
		var stampSize = getSize(stamp),
			offset = this._getElementOffset(stamp),
			firstX = this.options.isOriginLeft ? offset.left : offset.right,
			lastX = firstX + stampSize.outerWidth,
			firstCol = Math.floor(Math.round(firstX / this.columnWidth)),
			lastCol = Math.floor(lastX / this.columnWidth),
			stampMaxY = (this.options.isOriginTop ? offset.top : offset.bottom) + stampSize.outerHeight;

			firstCol = Math.max(0, firstCol);
			lastCol -= lastX % this.columnWidth ? 0 : 1;
			lastCol = Math.min(this.cols - 1, lastCol);

		for (var i = firstCol; i <= lastCol; i++) {
			this.colYs[i] = Math.max( stampMaxY, this.colYs[i] );
		}
	};

**Comment by desandro** [comment]
Thanks for reporting this issue. I'm closing this issue. See #692
