### ISSUE TITLE
Composer version

### ISSUE THREAD

**Issue by killua99** [desandro/masonry#828]
Composer need the submission. You need to press the green button "update" and leave all the branches.

This is how it should look: https://packagist.org/packages/components/jquery

**Comment by killua99** [comment]
There is also a settings/hooks where you could add you composer API token so it keep auto updated, so no need to do it manually.

**Comment by desandro** [comment]
On the Packagist side, I followed the [GitHub Service Hook](https://packagist.org/about#how-to-update-packages) instructions. I'm not seeing any auto-update warning.

![screen shot 2016-02-26 at 9 43 18 am](https://cloud.githubusercontent.com/assets/85566/13355268/8546f440-dc6d-11e5-9ac1-c9ef82205e37.png)

On the GitHub side, there is a warning "Last delivery not successful. Service timeout"

![screen shot 2016-02-26 at 9 43 03 am](https://cloud.githubusercontent.com/assets/85566/13355352/e9e54a28-dc6d-11e5-9922-da95e502d5ed.png)

Here's the webhook settings

![screen shot 2016-02-26 at 9 46 42 am](https://cloud.githubusercontent.com/assets/85566/13355367/f4d2a0f2-dc6d-11e5-93b6-cc7705f6cb9f.png)

**Comment by killua99** [comment]
It needs the domain: https://packagist.org

And what happen when you click on the update button?

**Comment by desandro** [comment]
> defaults to https://packagist.org

Prior to this issue being opened, I set it to `packagist.org`.

I hit the update button and nothing happened.

**Comment by killua99** [comment]
Something odd, I just try it and it work. No idea why the update button isn't working. I'll check why

**Comment by killua99** [comment]
Ok I check with a composer maintainer and this was his answer.

https://twitter.com/seldaek/status/704262687396646912

So, you set right the webhook for both "masonry and imageupload" should be fine for the future. So the old tags will be ignored until you submit another tag (version).

I've no problem with keep using the "dev-master" until you want to commit another tag. But could be awesome if we could have a stable version like 4.0.1 or sort of to work on production environments.

At the end this issue could be close if the webhook work well.

**Comment by heddn** [comment]
Bump. Please get a stable release posted to packagist.

**Comment by desandro** [comment]
v4.1.0 and v4.1.1 are currently available. Looks like its working https://packagist.org/packages/desandro/masonry
