### ISSUE TITLE
Two collumns same height?

### ISSUE THREAD

**Issue by Nic787** [desandro/masonry#831]
Hi,

I'm a bit lost. I created a new question on Stackoverflow : http://stackoverflow.com/questions/35804935/how-to-set-two-divs-side-by-side-with-the-same-height

I would like to always have 1 big image and 2 small images on the side, but masonry seem to just fit everything depending of image size... I need something that can change image width dynamically to get the same div height. Not sure if it's possible with your masonry script.

**Comment by desandro** [comment]
Have you looked at [fluid layouts with Masonry](http://masonry.desandro.com/layout.html#responsive-layouts)?

**Comment by Nic787** [comment]
Yes I have, but I'm not sure to understand how it could work with what I'm trying to achieve.
