### ISSUE TITLE
Image load issue with React

### ISSUE THREAD

**Issue by robcalcroft** [desandro/masonry#833]
I have the following React class:

``` javascript
import React from 'react';
import Container from 'components/common/Container';
import Masonry from 'masonry-layout';
import './photos.scss';

export default class Home extends React.Component {

    constructor() {
        super();

        this.state = {
            photos: []
        };
    }

    componentWillMount() {
        $.getJSON('/api/photoset').done(photos => {
            this.setState({
                photos: photos.reverse()
            });
        }).fail(err => {
            console.log(err);
            alert('Can\'t get photos');
        });
    }

    componentDidMount() {
        this.layout = new Masonry('.photos--container', {
            itemSelector: '.photo',
            columnWidth: '.photo',
            percentPosition: true
        });
    }

    renderPhotos(photos) {
        if(!photos.length) {
            return (
                <div>
                    <div className="progress">
                      <div className="indeterminate"></div>
                    </div>
                    <h2 className='center'>Loading photos...</h2>
                </div>
            );
        }

        return photos.map(photo => <img onLoad={this.imageLoaded.bind(this)} className='photo fadein' key={photo.id} src={photo.url_m} alt={photo.title} />);
    }

    imageLoaded(event) {
        this.layout.appended(event.target);
        $(event.target).show();
    }


    render() {
        return (
            <Container nav='true' activeLink='photos'>
                <div className='photos--container'>
                    {this.renderPhotos(this.state.photos)}
                </div>
            </Container>
        );
    }
}
```

And the SCSS:

``` scss
.photo {
    width: 33.33%;
    display: none;
}
```

When I run the page from scratch i.e. no cache, I get all the images on top of one another and not rendered into the masonry grid, when I resize the browser it prompts them into the correct place. I can't work out how the method I'm using above is causing these issues. I've looked at your demos on the website and attempted to use your `imagesLoaded` package, none of these has helped this issue.

Thanks

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by robcalcroft** [comment]
http://jsbin.com/conesiluya/edit?js,output demos the issue, once the images have loaded they are on top of one another and you have to resize the window to get them to move into the correct place

**Comment by johngulb** [comment]
@desandro @robcalcroft I am experiencing the same issue using ember, has there been any more insight on this issue?

**Comment by martinlemahieu** [comment]
Hi everyone !

Just had the same issue with React and fixed it by passing a callback (`handleImageLoad()`), that calls `masonry.layout()`, to my `Image` child components, which call it when `onLoad` is triggered. (On the `<img>` tag.)

Hopefully this will solve the issue for you guys.

**Comment by halojedi20** [comment]
@martinlemahieu's solution worked perfectly for React. Was having an issue of overlapping image cards using Materialize + React. Setting a callback on an image's onLoad back to the parent container and calling layout() correctly displayed the cards.
