### ISSUE TITLE
Transition bug, broken layout in iOS

### ISSUE THREAD

**Issue by butlimous** [desandro/masonry#834]
Hi,

On initial loading of page, the layout arranges the elements as expected but when changing orientation of  an iOS device, the layout remains as it is and doesn't relayout. 

The issue is only in iOS. Works well on Chrome (desktop and android) and firefox.
I tested on iPhone 4 (real device) and iPhone 6 (iOS simulator for mac)

I tried nearly all options of the plugin with tons of different combinations and the bug is always there. Even the demo pan has it.

I created a very simple demo page to demonstrate the issue:
http://quizone.co/test.html

Load the page and then rotate the device and you would reproduce the bug.

I confirm that this is a bug because when I tried to include version 3.3.0 from the link below, it worked well. So this is a bug in version 4 of the plugin.
http://cdnjs.cloudflare.com/ajax/libs/masonry/3.3.0/masonry.pkgd.min.js

Thanks
Regards
Michael

**Comment by desandro** [comment]
Thanks for reporting this issue. This bug was caused in Outlayer v2.0.0. It has since been [resolved in Outlayer v2.0.1](https://github.com/metafizzy/outlayer/commit/aaa786769592a75f199f98b6e17b08d50a82a10a). This will be fixed in the next version of Masonry.

**Comment by tobiberlin** [comment]
I applied the changes from the link above to my local Masonry script and this fixed the problem of not adjusted masonry items. But now they are flickering after the window width or the device orientation changed. Just to mention that as you wrote that these changes will be part of the next Masonry version.

Do you know about that and how to avoid this flickering?

**Comment by rgallison** [comment]
When will the next version of Masonry be available?
