### ISSUE TITLE
1px horizontal lines

### ISSUE THREAD

**Issue by tiagogon** [desandro/masonry#835]
On my project i have a gallery with no gutter, just like this one: http://codepen.io/desandro/pen/RPKgEN

does anyone knows why sometimes (it dependes on the window size) this lines appear between elements?

![screen shot 2016-03-10 at 22 21 41](https://cloud.githubusercontent.com/assets/3286869/13685064/f1e2201a-e70e-11e5-9767-5f361a545b0c.png)

**Comment by desandro** [comment]
The reason pixel rounding errors. It's a tough issue to resolve because they appear inconsistently. Vertical gaps

See possible fix in https://github.com/metafizzy/isotope/issues/916#issuecomment-108899516 or feature request #795

**Comment by wjramos** [comment]
When you zoom, do they "flicker" (appear and the disappear with zoom level) ? 

This is likely due to sub-pixel rendering differences between browsers. The only real way to address this is by having a -.5px (or so) overlap so that it "forces" rounding up to the nearest whole pixel
