### ISSUE TITLE
HTMLElement is a function

### ISSUE THREAD

**Issue by heyarny** [desandro/masonry#836]
I was about to use masonry 4.0, but it never worked for me.
After debugging the whole thing I saw it was never actually adding the elements, because the ``` elem instanceof HTMLElement``` always failed. Even thou it's a div element.
Now I saw HTMLElement is actually a function, which in this case this line doesn't seem to make sense.

```
elems.forEach( function( elem ) {
    // check that elem is an actual element
    if ( !( elem instanceof HTMLElement ) ) {
      return;
    }
```

I saw some older issues (#524 ) on this which but they were fixed and belonged to the earlier versions.
I don't get why this seems to be working on some examples, but mine is not working?
Using latest Chrome here.

**Comment by desandro** [comment]
Thanks for reporting this bug. Could you provide a **reduced test case** so I can better debug this issue? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by heyarny** [comment]
@desandro thank you, but we decided not to use it further more because of a more important issue for us #837

**Comment by wjramos** [comment]
@heyarny, I believe the issue you were encountering was due to objects of the type NodeList do not have the method forEach
