### ISSUE TITLE
Inconsistent layout between different container sizes

### ISSUE THREAD

**Issue by heyarny** [desandro/masonry#837]
We've noticed there is inconsistency within the layout algorithm when using different container sizes, while still using the same data with the same relative sizes (percentages).

Desktop container size:
![screen shot 2016-03-14 at 15 08 00](https://cloud.githubusercontent.com/assets/821278/13747469/ae7dcbf2-e9f8-11e5-8129-6f08f744a14d.jpg)

Mobile container size:
![screen shot 2016-03-14 at 15 08 23](https://cloud.githubusercontent.com/assets/821278/13747486/bc88abfe-e9f8-11e5-8a77-b92e7a605276.jpg)

For some it may not be important to have consistent layout across different platforms, but for us it's a quality factor.

Hope this helps to improve your algorithm.

**Comment by desandro** [comment]
Thanks for reporting this issue. This issue would be resolved by #811. Closing here, keep discussion going there.
