### ISSUE TITLE
Fluid masonry with gutters

### ISSUE THREAD

**Issue by dasi1va** [desandro/masonry#838]
Hello very nice work with masonry!
I wondering is any way create fluid masonry animated with gutters?

thanks in advance!

**Comment by desandro** [comment]
Sure thing, take a look at the 3rd example here: http://masonry.desandro.com/options.html#gutter

See CodePen: http://codepen.io/desandro/pen/BAJKn

**Comment by dasi1va** [comment]
ok thank you!
