### ISSUE TITLE
How to load Masonry with ES6

### ISSUE THREAD

**Issue by eparizzi** [desandro/masonry#839]
I'm trying to use Masonry in an Aurelia project but I'm having a hard time initializing the grid programmatically.

Since I'm not using jQuery the only method I have is to use vanilla javascript, but since the masonry package is loaded using the `import` ES6 statement doing `var grid = new Masonry(elem, options)` doesn't work.

Any ideas?

**Comment by desandro** [comment]
Masonry and its dependencies do not use ES6 `export` so I don't believe using `import` will work. I'm not sure how Aurelia manages non ES6 modules. You'll have to look into that.

**Comment by emzero** [comment]
Module loading is not an Aurelia thing. It's just the System.js library which extends the ES6 Module Loader polyfill.

I'm new at this way but I do see in your masonry.js the following code and as far as I know System.js is able to load AMD and CommonJS modules. There should be a way to do it if the following code is defining a module to export either in AMD or CommonJS format.

```
( function( window, factory ) {
  // universal module definition
  /* jshint strict: false */ /*globals define, module, require */
  if ( typeof define == 'function' && define.amd ) {
    // AMD
    define( [
        'outlayer/outlayer',
        'get-size/get-size'
      ],
      factory );
  } else if ( typeof module == 'object' && module.exports ) {
    // CommonJS
    module.exports = factory(
      require('outlayer'),
      require('get-size')
    );
  } else {
    // browser global
    window.Masonry = factory(
      window.Outlayer,
      window.getSize
    );
  }

}( window, function factory( Outlayer, getSize ) {
// ...
}
```

**Comment by desandro** [comment]
Look through the [RequireJS](http://masonry.desandro.com/extras.html#requirejs) and [Browserify](http://masonry.desandro.com/extras.html#browserify) documentation on how to load Masonry via AMD or CommonJS

**Comment by juancabrera** [comment]
Hey @emzero, 

Had same issue and this is how I got it working.

First install the npm package through jspm:  
`jspm install npm:masonry-layout`

So now you can import `'masonry-layout'` (not `.masonry-layout` or `masonry-layout.js`), just `masonry-layout`.

Here is my actual code:

```javascript
'use strict'

import Masonry from 'masonry-layout'

const grid = document.querySelector('.masonry-grid')
const msnry = new Masonry(grid, {
  itemSelector: '.tile',
  columnWidth: 280,
  gutter: 20,
  transitionDuration: 0,
  initLayout: false
})

msnry.once('layoutComplete', () => {
  grid.classList.add('load')
})

msnry.layout()

```

Hope this is helpful!

**Comment by wjramos** [comment]
Worth mentioning – commonJS and ES6 modules are cross-compatible (as you have already indicated) 

```
module.exports = Masonry;

// Equals
export Masonry;
```

**Comment by johnmanko** [comment]
Masonry is listed in the [jspm registry](https://kasperlewau.github.io/registry/#/), so to install you just need to do:

`jspm install masonry`

That is similar to adding it using it's github reference:

`jspm install github:desandro/masonry`

Say you have an Aurelia app, you can load it in your view as such:

```js
import Masonry from 'masonry'; // if using the jspm registry reference
// import 'desandro/masonry'; // if using the direct github reference

export class SomeView {
    activate() {
         this.msnry = new Masonry({/*stuff*/});
    }
}
```

**Comment by ChrisShain** [comment]
I found that the following worked:

```
// Put this in global scope
var jQueryBridget = require('jquery-bridget/jquery-bridget');
var Masonry = require('masonry-layout');
// make Masonry a jQuery plugin
$.bridget( 'masonry', Masonry, $ );
// Now you can use $('...').masonry(...) 
```

**Comment by tonybravano** [comment]
Any updates on using Masonry with Aurelia.  None of the suggested methods work.  Would be nice to see a sample.

**Comment by jamesond** [comment]
I am curious myself as I haven't gotten it to work with Aurelia.

**Comment by Grawl** [comment]
Trying to do the same with Rollup.js. All I need is [`rollup-plugin-commonjs`](https://github.com/rollup/rollup-plugin-commonjs) and import jQuery Bridget:

```js
import 'jquery-bridget'
import 'masonry-layout'
```

Looks like when importing Masonry there is missing dependency.

To use with vanilla JS you have to use named import:

```js
import Masonry from 'masonry-layout`
```

and then I can use `new Masonry()`.

**Comment by henrypenny** [comment]
This finally got me going with masonry and imageLoaded:

```
import $ from 'jquery';
let ImagesLoaded = require('imagesloaded');
let jQueryBridget = require('jquery-bridget');
let Masonry = require('masonry-layout');

jQueryBridget( 'masonry', Masonry, $ );
jQueryBridget( 'imagesLoaded', ImagesLoaded, $ );

let doMasonry = function($wrapper) {
    let $grid = $wrapper.find('.grid');
    $grid.imagesLoaded(function () {
        $grid.masonry({
            itemSelector: '.item',
            columnWidth: '.grid__sizer',
            percentPosition: true
        });
    });
};

```

**Comment by NevenLeung** [comment]
@desandro 

Please update the ES6 import usage to README.md.

**Comment by desandro** [comment]
[ES6 import docs added to Extras](https://masonry.desandro.com/extras.html#es6)

**Comment by alcohol** [comment]
ES6 does not seem to work when loading Masonry from a CDN; e.g.:

```js
import Masonry from 'https://cdn.jsdelivr.net/npm/masonry-layout@4/dist/masonry.pkgd.min.js'

// results in
// Uncaught SyntaxError: The requested module 'https://cdn.jsdelivr.net/npm/masonry-layout@4/dist/masonry.pkgd.min.js' does not provide an export named 'Masonry'
```

**Comment by empz** [comment]
> ES6 does not seem to work when loading Masonry from a CDN; e.g.:
> 
> ```js
> import Masonry from 'https://cdn.jsdelivr.net/npm/masonry-layout@4/dist/masonry.pkgd.min.js'
> 
> // results in
> // Uncaught SyntaxError: The requested module 'https://cdn.jsdelivr.net/npm/masonry-layout@4/dist/masonry.pkgd.min.js' does not provide an export named 'Masonry'
> ```

Why are you trying to use this library in 2024? There's no need.

**Comment by Grawl** [comment]
There is no CSS native masonry yet
