### ISSUE TITLE
Static Banner/Poll inside the masonry grid

### ISSUE THREAD

**Issue by awongCM** [desandro/masonry#841]
Hi there,

I just want to ask.

In this page section, http://masonry.desandro.com/options.html,  I'm just wondering is it possible to include a static poll/banner of certain dimensions that could be fit within the layout of the masonry grid, but I don't want the plugin to realign the poll/banner at different positions of the grid?  As in, I would like the static poll/banner to stay in the top right corner of the grid screen, so when I do web responsive test, its original position does not changed?  Is it possible to do so within this plugin?

Hope this makes sense.

**Comment by desandro** [comment]
Thanks for reporting this issue. I'm having trouble understanding what you're trying to achieve. Could you please try forking one of the CodePens on the options page so I have a better idea? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues).

**Comment by awongCM** [comment]
Sure @desandro 

This is what I came up with.

http://codepen.io/awongCM/pen/KzWjXN

In short, I have a responsive masonry grid (in pink) and I have two banners in the grid.  One is green, and the other is indigo.  The indigo one sits inside masonry grid and it's part of the masonry grid item layout ie `grid-item` while the green on sits also sits inside masonry grid, but it's not using `grid-item` class.  When you resized the document or window browser, you will see that the green box remains fixed at a certain position, but the indigo box's position moves around inside grid each time you resize.

Therefore I want to know, if possible, that I could have a static banner(like the indigo banner) that could stay at a fixed position(like the green banner) within the masonry grid and its position could never be altered at differrent positions when going for responsive layouts.  Is there any such API method in your plugin that allows me to do such ability like that?

Hope this makes more sense to you now.

Let me know if you have questions.

**Comment by desandro** [comment]
Sounds like you're asking about using the [`stamp` option](http://masonry.desandro.com/options.html#stamp). Or, why not use the same code for the indigo banner like you do with the green banner?

**Comment by awongCM** [comment]
Thanks for the prompt reply.

I think the stamp would probably my best option to use for my case as described above.

I could also use the same code for the indigo banner - as I've just my update my codepen below.

http://codepen.io/awongCM/pen/KzWjXN

to achieve the same result.

However, the issue with this is that if you put any content inside each grid items (which I labelled 1,2,3,4,5...), when you resize the browser, while the indigo/green banner stays the same spot, one or two of the grid items with content get 'overlapped' by the static banner.  It is obvious these grid items will get reordered when resizing thus there's always a chance that my static banners will overlap or hide some of grid item content.  I would find this is not desirable behaviour as I may have as many static banners as I want, with various dimensions, hence many of my grid item content will get hidden away when viewing things in responsive mode.

Thanks again for the stamp option again.  I will try that one out!

Cheers.
