### ISSUE TITLE
Layout not working in Chromium

### ISSUE THREAD

**Issue by jakob-o** [desandro/masonry#842]
Hi,

it seems as if layout does not work properly for me in Chromium (Version 34.0.1847.116 Ubuntu 12.10 (260972)). The items are not re-layout but stay at their inital position. I checked against the codepen from the masonry homepage: http://codepen.io/desandro/pen/JdEyYQ 

It works fine in Firefox though.

Regards

Jakob

**Comment by jakob-o** [comment]
Ok, seems to be related to this bug https://github.com/desandro/masonry/issues/834 I updated to Outlayer v2.0.1 and compiled my own masonry, which works fine.

**Comment by desandro** [comment]
Thanks for following up! Closing as a duplicate.
