### ISSUE TITLE
Issue with wordpress theme i

### ISSUE THREAD

**Issue by khbibo** [desandro/masonry#843]
**Test case:** http://codepen.io/desandro/pen/osFxj
I try to use the blugin with a theme that is created by me.
https://youtu.be/NU3d3dLuxhI

that is the link file
http://www.mediafire.com/download/ffiq046762hat87/myTrial.rar

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues).

Can you post that URL you are working on so its live & we can look at it?

**Comment by khbibo** [comment]
i provide you with the linke
http://www.mediafire.com/download/ffiq046762hat87/myTrial.rar

**Comment by khbibo** [comment]
thank you.
I could solve the problem.
