### ISSUE TITLE
Margin Bottom ignored after ajax success loading masonry

### ISSUE THREAD

**Issue by markmaurerrr** [desandro/masonry#845]
Hello,

i'm loading pages into the dom with ajax. When i open the page via url, everything is alright, but if i switch with ajax to that masonry page with the following code -> Margin-bottom is ignored and der is no vertical spacing between the elements. The rest works fine. What am i doing wrong?

Thanks in advance!

```
JS:
function fetchAndInsert(href){
			
			$.ajax({
				
				url: href,
				method: 'GET',
				cache: false,
				success: function(data){
					
					$(".main-content").html(data);

					$('.news .news--wrapper').masonry({

						 itemSelector: '.col-4-12',
						gutter: 20
	  
					});

					}
					
				}
				
			});

		}


CSS:
.col-4-12 {
		background: white;
		margin-bottom: 20px;
		padding: 0;
		width: calc((100% - 80px) / 3);
		overflow: hidden;
}
```

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues).

**Comment by markmaurerrr** [comment]
@desandro Thank you for the fast answer. I've read the guideluines but it's hard for me/impossible to reproduce this in codepen and i cannot publish a pre version of the clients website. 

But you should get an idea of what's breaking if you have a look at the code. I'm loading a new page into my website via ajax. In this new page there are my masonry objects and i'm initiating masonry in ajax success function (so new dom should be loaded already). 

But then this happens: The margin bottom value is being ignored on the first 3-4 elements, so no vertical gutter exists. BUT then somehow it gets the value and it starts to show the gutter on the following elements. 

If i init the masonry() function with a timeout of – let's say 400 – it's working. But thats a buggy version of fixing this? 

Do you have any idea what to do? I'm wondering why nobody else had this problem before...

Thank's a lot in advance!

**Comment by desandro** [comment]
Looks like content is being added, but it's not being added to the Masonry instance. I can't tell how content is being added without a live website to look at. But [`reloadItems`](http://masonry.desandro.com/methods.html#reloaditems) might be what you're looking for. Try some code like this:

``` js
// initialize Masonry
var $newsWrapper = $('.news .news--wrapper').masonry({
  itemSelector: '.col-4-12',
  gutter: 20
});


$.ajax({
  // ...
  success: function(data){
    // add content
    $(".main-content").html( data );
    // reload and layout masonry
    $newsWrapper.masonry('reloadItems').masonry();
  }
});
```

**Comment by markmaurerrr** [comment]
@desandro solved it. Thanks a lot mate!
