### ISSUE TITLE
Items not fitting to minimum number of rows

### ISSUE THREAD

**Issue by czmj** [desandro/masonry#847]
I have a grid with 6 items, 3 each of 1/3 and 2/3 width, so this should equal 3 complete rows. Instead I am being given 4 rows, with only the first row showing as complete ([demo](https://jsbin.com/paposi/4/edit?html,js,output))

If I change the order of the items so the 1/3 items are at the end it works as expected ([demo](https://jsbin.com/paposi/5/edit?html,js,output)), but I have no control over this as the markup is coming from a CMS.

Is there anything I can do to make the items appear over 3 rows?
Thanks

**Comment by desandro** [comment]
Thank you for submitting this issue. Masonry's layout algorithm cannot fill gaps. [But Packery's can](http://packery.metafizzy.co/). Packery was designed to be able to fill gaps.
