### ISSUE TITLE
Masonry Items Not Aligning when Initialized 

### ISSUE THREAD

**Issue by 4everyoungz** [desandro/masonry#848]
I have been having issue using responsive layout of masonry grid.

For some reason, I can not get the layout correct. It's suppose to be:

1st row, two images 50/50% 2nd row, three images 33.3% 3rd row, two images 50%

When applying just CSS it works perfectly fine. The layout displays properly. Upon initializing (using imagesload too), everything goes out of whack. 

**Test case:** http://codepen.io/byoungz/pen/eZeJdd

**Comment by desandro** [comment]
If your items are 33.33% and 50% wide, then you'll need a columnWidth that can fit both. Use `16.667%`. See demo http://codepen.io/desandro/pen/004381e1a1eeb552adb16de0ef97b3ac/

**Comment by 4everyoungz** [comment]
Thank you!! I guess I misunderstood the point of column width. Thanks for clarifying each grid-item has to be divisible by it.
