### ISSUE TITLE
Safari 5 and mobile IOS problem

### ISSUE THREAD

**Issue by Alec00** [desandro/masonry#850]
Hi. thanks for Masonry.
I tried to find a solution, but without success.
In desktop Safari 5 Layout does not work correctly when you try to change the height of the element.

Test case: http://codepen.io/desandro/pen/JdEyYQ
Thanks for help!

**Comment by desandro** [comment]
Thank you for reporting this issue. This sounds related to #834. Closing here as a duplicate.
