### ISSUE TITLE
Padding and text height breaks vertical spacing at specific sizes.

### ISSUE THREAD

**Issue by isaacsgraphic** [desandro/masonry#852]
Hi there, I'm unsure if I'm missing something basic, but I keep running into the same issue, with vertical spacing being reduced intermittently. 

As far as I can work out, it occurs when I add padding to a grid item, and when the heights of the grid items are determined by text.

With this particular example, you should be able to see the issue on when the codepen window is sized to 1050px, but I've encountered the same problem with other examples at other sizes.

http://codepen.io/isaacsgraphic/pen/WwYWem/

**Comment by desandro** [comment]
Thanks for reporting this issue! I'm not sure if I am seeing the issue. Everything looks good in Firefox and Chrome on desktop. Is there something specific I should look at?


![screen shot 2016-05-03 at 11 52 32 am](https://cloud.githubusercontent.com/assets/85566/14989403/a6bbc87a-1125-11e6-8879-15c59b416342.png)

**Comment by isaacsgraphic** [comment]
That's interesting. Trying it again, it only breaks when the right scrollbar is visible. 
Here's some screenshots.
![d__reference_how to_wordpress_masonry txt 160402 160405 160404 16-03-05 160000493](https://cloud.githubusercontent.com/assets/16480575/14989862/e1c6b886-1151-11e6-8f79-7543ea2454f6.png)
![d__reference_how to_wordpress_masonry txt 160402 160405 160404 16-03-05 160000492](https://cloud.githubusercontent.com/assets/16480575/14989863/e1cec03a-1151-11e6-97d3-13202074fa71.png)

**Comment by desandro** [comment]
If this is a scroll bar bug then the simplest solution is to force one with css

``` css
html { overflow-y: scroll }
```

See demo http://codepen.io/desandro/pen/3eda496ad11f79ec49f87bc3f8761c44/

**Comment by isaacsgraphic** [comment]
That does indeed fix the issue for the test case, I'll let you know if it works for my main example. Not sure why it's happening, I assume you've not been able to replicate it? It only happens when I refresh at particular screen sizes. Thanks so much for your time and thoughts.

**Comment by isaacsgraphic** [comment]
That also fixes the main example I was having trouble with. Thanks!
