### ISSUE TITLE
Masonry and Woocommerce product pages

### ISSUE THREAD

**Issue by AdriOosterwijk** [desandro/masonry#853]
Hi,
On the site I'm developing I'm using your Masonry script. Works great. However I stumble into an issue I am not able to resolve myself (as being a noob).

Case is this. 
The site I'm developing is a stockphoto site. On the product page I want to display just images. I was able to get rid of all the additional data and just display the images. 

**The thing is I really want to display the landscape images in a two column with and the portrait images in a one column width.**

The number of columns however is dictated by Woocommerce. On the product pages is a class "product" which I am using as the selector for the masonry. I hope I made myself a bit clear and looking forward to your response.

Thanks in advance.

Best Regards,

Adri

**Comment by desandro** [comment]
Hello! Sorry to hear you're having trouble with Masonry. [How you size your images is up to your own CSS](http://masonry.desandro.com/#css). I recommend first setting appropriate sizes with CSS, then adding Masonry to see how it works.

This issue tracker is for bugs and feature requests. Sorry, but we're not able to help with support requests here.
