### ISSUE TITLE
Bind to Parent Width Change Event

### ISSUE THREAD

**Issue by charlielondon** [desandro/masonry#854]
**Test case:** http://codepen.io/gnarlycharlie/pen/GZzewr

It would be really nice if I could manage to configure masonry to watch for parent element width change, (or the width change of any element) rather than only window resizing.

The problem reared its head within an app prototype with a number of width-changing animations in the side nav bars.

It's pretty tricky to watch for an element's width change besides the window, so I'm having trouble coming up with a hacky general solution.

This should probably be a feature request..

**Comment by desandro** [comment]
Thank you for submitting this feature request. This kind of behavior is best done outside of Masonry. You can write your own custom code to track changes in the layout, or hook into events that change layout.  Then trigger `.masonry()` to layout Masonry again. There's multiple ways to do it. Masonry doesn't have to handle it.

I appreciate your feedback, but we'll have to pass on this one.
