### ISSUE TITLE
Dynamically loaded Masonry images are overlapping

### ISSUE THREAD

**Issue by azazza** [desandro/masonry#856]
I'm using the jQuery plugin Masonry to load images on my site, but the majority of the time a lot of them are overlapping.when i resize my page everything looks fine. I have found this to be a popular problem with the plugin and have tried various solutions, but still haven't gotten it working properly. This is what I have so far

 $('grid').imagesLoaded( function(){
      itemSelector: '.grid-item',
      $('grid').masonry({
     isFitWidth: true
       isAnimated: true,
   / });
   });

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues).

**Comment by azazza** [comment]
as mentioned in the http://stackoverflow.com/questions/23769642/dynamically-loaded-masonry-images-are-overlapping. I have the same issue. when i resize my page everything looks fine.I have tried various solutions, but still haven't gotten it working properly.

JS:
$('grid').imagesLoaded( function(){
itemSelector: '.grid-item',
$('grid').masonry({
isFitWidth: true
isAnimated: true,
 });
});

**Comment by azazza** [comment]
![image](https://cloud.githubusercontent.com/assets/19339720/15304359/c4b01740-1b71-11e6-9cf6-c8aaa9cf383a.jpg)

**Comment by Rizwanilahi** [comment]
@desandro Hi, I am facing same problem with Dynamic Images, Images are overlapping on first time page visit.
