### ISSUE TITLE
Masonry only working after $.slideUp()

### ISSUE THREAD

**Issue by zner0L** [desandro/masonry#859]
I am totally frustrated by an issue with masonry and ajax. Unfortunately it seems very hard to reproduce this error in an small test case which is why I didn't include any.

Basically, some third party code is loading stuff via ajax and then replaces the current view I have ajax activated on. After the call is done, I try to `$.masonry('reloadItems')` or reinitialise the masonry if the masonry was destroyed by the ajax call:

```javascript
$(document).ajaxComplete(function() {
    if(!$(container_selector).data('masonry')) {
        window.$grid = $(container_selector).imagesLoaded().progress().masonry({
            itemSelector: item_selector,
            columnWidth: width_selector,
            percentPosition: true,
            transitionDuration: '0.05s'
        });
    } else {
        window.$grid.imagesLoaded().masonry('reloadItems').masonry('layout');
    }
});
```

This seems to do something, it reorganises the items in the grid, but not always *properly* (like overlapping items, no resizing of the container). When I call
```javascript
$.slideUp(200, function() {
    window.$grid.masonry('layout');
});
```
on some items with slideable content, though, the grid now looks nicely and as expected. I guess `$.slideUp()` does some kind of refresh magic that is not included in `$.masonry('reloadItems')`. I tried several combinations of masonry functions, including destroying the masonry before reinitialising it, but I'm completely lost. Also, this only seems to work, when there really is something to `$.slideUp()`. If I e.g. hide these elements via CSS (`display: none;`), the grid is not displayed correctly.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues).
