### ISSUE TITLE
(Re-)Initialize Masonry after DOM manipulation

### ISSUE THREAD

**Issue by simonhestermann** [desandro/masonry#860]
Hi,
I am pulling reviews from my Facebook page using the Facebook JavaScript SDK. All necessary data is stored within the array `fb_reviews`.
Next, the following function `reviews()` is supposed to display all reviews and reload Masonry accordingly:

```
var reviews = function () {
                var z = fb_reviews.length - 1;
                var print2;
                for (i = 0; i < z; i++) {
                    if (!fb_reviews[i].review_text) {
                        fb_reviews[i].review_text = "<i>No review text available</i>";
                    }
                    var print2_s = $('<div class="review" id="review-' + i + '"><div class="meta">' + fb_reviews[i].reviewer.name + ' rated ' + fb_reviews[i].rating + '/5</div><blockquote>' + fb_reviews[i].review_text + '</blockquote></div>');
                    print2 = print2 ? print2.add( print2_s ) : print2_s;
                }

                $container.append(print2).masonry("reloadItems").masonry("layout");
                console.log($container.masonry("getItemElements"));
            }
            ;
```
Since there are no objects in the `$container`-element before the Facebook reviews are appended, I am using this code to initialize Masonry with `initLayout:false` :
```
 $(document).ready(function () {
                $container = $("#reviews");
                $container.masonry({
                    initLayout: false,
                    itemSelector: ".review",
                    columnWidth: ".review"
                });
            });
```
However, when opening the page, all `.review` items have collapsed and are displayed above each other.

What makes me wonder is that the following line gives me the correct DOM data in my console:
`console.log($container.masonry("getItemElements"));`
Output:
`<div class="review" id="review-0"><div class="meta">Name Example rated 5/5</div><blockquote>This is my review.</blockquote></div><div class="review" id="review-1">...`

Since the following test code before the `</body>`-tag solves the issue, I am quite sure Masonry is not reloading/redoing the layout correctly:
```
setTimeout(function() {
                $container.masonry({
                    itemSelector: ".review",
                    columnWidth: ".review"
                });
            }, 2000);
```
So how do I re-initialize Masonry so that it kicks in AFTER all reviews are loaded and appended?
I also tried to initialize masonry not within `$(document).ready()`, but within the reviews function instead, and it did not work either.
Really appreciate your support, thank you in advance :)
Simon

**Comment by simonhestermann** [comment]
I think I found the issue!
It is because I am using jQueryTools Tabs!
http://jquerytools.github.io/documentation/tabs/

I am now figuring out how that interferes with Masonry.

**Comment by simonhestermann** [comment]
Seems like it's an issue of jQueryTools... Finally got it working.

**Comment by RWAP** [comment]
How did you fix it?  I have the same issue with some another tab tool....
