### ISSUE TITLE
Is there a away to identify the last item for each row of masonry?

### ISSUE THREAD

**Issue by abouolia** [desandro/masonry#861]
Is there a away to identify the last item to each a row of masonry? by adding class to last item.

**Comment by desandro** [comment]
You can do this by looping through `.items` and checking position. It involves some internal Masonry code, but you can do it. See demo http://codepen.io/desandro/pen/167238f1ebb89502666f62ecb8347613/

**Comment by abouolia** [comment]
I thought about solution like that yesterday, this is my final code http://codepen.io/abouolia/pen/pyMMwR, if there's someone else looking for same issue. Thank you David for your response and for great library.
