### ISSUE TITLE
`transitionDuration` breaks layout in IE 9

### ISSUE THREAD

**Issue by panteng** [desandro/masonry#862]
I know IE 9 doesn't support CSS3 Transition.

The problem is, when I set `transitionDuration` for other browsers, it works really fine in those other browsers. But in IE 9, when I resized the window, the items will not re-position. They keep stay where they are. I don't think this is a correct behavior. And then I set `transtionDuration` to `0`, every browser (include IE 9) works fine, the items will re-position but I lose the transition effect in all browsers. This is not what I want.

Your official demo also has this problem: [http://masonry.desandro.com/](http://masonry.desandro.com/)

Thanks for reading~

**Comment by desandro** [comment]
Hello! [Masonry v4 does not support IE9](http://masonry.desandro.com/extras.html#browser-support), but [you can use legacy version Masonry v3](http://masonry.desandro.com/v3). But even then, transitions are not supported in IE 9, so there is no way to enable transitions in IE 9. Sorry!

**Comment by panteng** [comment]
Ok, thank you.
