### ISSUE TITLE
Double width items can cause orphans

### ISSUE THREAD

**Issue by TimFletcher** [desandro/masonry#863]
I'm not sure if this is a bug or user error. Apologies if it's the latter.

I have single (50%) and double width (100%) items. If the first and third items are single width but the second is double width, the first item becomes an orphan. I'd expect Masonry to move the third item alongside the first.

So I get this:

<img src="http://d.pr/i/ZxZk+" width="100px" />

When I'm expecting this:

<img src="http://d.pr/i/14UeS+" width="100px" />

Here's a minimal codepen that exhibits this behaviour — http://codepen.io/timfletcher/pen/xOKLjz

**Comment by isilsh** [comment]
this behaviour is related to the order of gallery items, i believe if you make sure to have at least two smaller items first and then place the larger ones in between groups of two smaller ones you will get the expected result, allthough there might be a better solution?

**Comment by TimFletcher** [comment]
Yeah, I wrote some code that detects if the first element is single and the second element is double and swaps them if that's the case. Whereas this does fix the problem, it can still happen at any point lower down. The card ordering is static (date order) with some of them being 'featured' i.e. double width.

**Comment by desandro** [comment]
Yup, that's how Masonry works. Fortunately, [there is Packery, which is designed to fill gaps](http://packery.metafizzy.co/). Take a look!

**Comment by TimFletcher** [comment]
Brilliant. Thank you!
