### ISSUE TITLE
Jquery Masonry is not working in Safari

### ISSUE THREAD

**Issue by usamamashkoor** [desandro/masonry#864]
Hi i am using Jquery Masonry it is working on other browsers like Chrome,Firefox but it is not working in Safari Browser in 5 on windows and on Safari 8 on Mac.

The problem is that all the divs are having top : 0px this div <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 grid-item grid-item--width2" > due to which all post are being are showing on top of each other  Here is the link of the page where Masonry is not working 185.14.184.118/app/inspiration-gallery

In Masonry i am embedding facebook posts then using the Masonry container to apply Masonry styling on it.

Here is my html
```
 <div class="grid row">
  <div class="inspiration-gallery">
    <div class="grid-sizer"></div>
    <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 grid-item grid-item--width2" >
      <div class="inspiration-grid">
        <div class="fbpost-inspiration" id="fbpost-inspiration">
          <div class="fb-post" id="myId" data-href="post_url" data-width="200" data-height="200"></div>
        </div>

      </div>
      <div class="clearfix"></div>
    </div>
  </div>
</div>
```
Here is my Jquery Code to initialize Masonry
```
var $container = $('.grid');
$container.masonry({
    columnWidth: '.grid-sizer',
    itemSelector: '.grid-item',
    percentPosition: true
});
```
Here is my CSS
```
.grid-sizer,.grid-item { width:33.33333333%; }
```
Kindly Please help me on this.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues).

**Comment by usamamashkoor** [comment]
Sorry for the late reply our site was down for a momment 
here is the page of the link
http://185.14.184.118/app/inspiration-gallery

**Comment by desandro** [comment]
I'm not able to reproduce this error in Safari 9 on Mac. [Safari 8 has .25% global browser usage](http://caniuse.com/usage-table). Given this small usage, I'm going to decline looking into this one.

**Comment by bdchauvette** [comment]
@usamamashkoor I just ran into a similar problem, and it seems that Masonry v4 doesn't work in Safari 8. We ended up downgrading to v3.3.2, and everything worked fine :+1:

**Comment by usamamashkoor** [comment]
Thanks bdchauvette

**Comment by tarandigi** [comment]
Hi .. I am also Facing the same issue , I have even updated my js from 4.1 to 3.3.2 but its not working for me . Suggest me any other alternative 
Thanks
