### ISSUE TITLE
Flickr images with ajax and imagesloaded still overlapping until window is resized

### ISSUE THREAD

**Issue by titolstwo** [desandro/masonry#865]
Having an issue with AJAX, the images stack up on top of each other until the window is resized. Then they align perfectly, with no further issues.
I know that I should be calling imagesLoaded on the new content so I tried building the code as you suggested in issue #705, but apparently you can't wrap an array of jquery objects in $( ), so wrapping the array `var elements = []` in `$elements = $( elements )` causes a _Cannot read property ownerDocument of undefined_ error.
Anyways, here's my code.
```
$grid = $(".grid");

  $.ajax({
      url: flickrAPI,
      dataType: "json",
      success: function(data, status, xhr) {
        $.each(data.photos.photo,function(i,photo){ 
          url = "https://farm"+photo.farm+".staticflickr.com/"+photo.server+"/"+photo.id+"_"+photo.secret+"_c.jpg"; 
            var $content = $('<div class="grid-item"><img src="'+url+'" /></div>');
            $grid.append($content);
        });
        $grid.imagesLoaded(function(){
              $grid.masonry({
                itemSelector: '.grid-item',
                percentPosition: true,
                columnWidth: '.grid-sizer'
              });
            });
      },
```

Thanks!

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues).

**Comment by kingIZZZY** [comment]
I might be experiencing a similar issue, not sure if it's the same/related: http://dev.randompod.com

Should I open my own issue/thread?

**Comment by desandro** [comment]
@kingIZZZY please open a new issue.
