### ISSUE TITLE
Empty space in the layout with a width of 4 tiles

### ISSUE THREAD

**Issue by inreka** [desandro/masonry#866]
When the width of the grid is 4 tiles, and I expand the 3rd tile on any row, a hole is left in the grid where that tile was.
See my fork of the animate item example here : http://codepen.io/anon/pen/LZNLWB
I changed the max-width on .grid to 500px to reduce the size of the grid.
I would expect another tile to fill that space: http://imgur.com/Vg3bvwK

**Comment by desandro** [comment]
Hello! Thanks for reporting this issue. That empty space is just how the Masonry layout works. It may leave gaps.

There is a solution: [Packery was designed to fill gaps](http://packery.metafizzy.co/). See demo http://codepen.io/desandro/pen/dcf32957d2b63bab5797d6846e606cfb/
