### ISSUE TITLE
Loading masonry as a module, using commonjs and webpack

### ISSUE THREAD

**Issue by xeor** [desandro/masonry#867]
Based on what I read, there should be no problems loading masonry in webpack using commonjs.
However; loading masonry using ecma2015 ([style](http://www.ecma-international.org/ecma-262/6.0/#sec-imports) imports, like `import * as masonry from 'masonry-layout';`, gives an error.
[angular2-masonry](https://github.com/jelgblad/angular2-masonry) does this, but are using some extra systemJS configuration to get it to work.

I created [this](https://stackoverflow.com/questions/37888395/loading-masonry-layout-in-webpack) question on stackoverflow about the same. But I am posting it here as well if anyone have any tips.

Loading modules like this looks like will be the "norm" using at least Angular 2..

Ideas on how to solve this issue?

**Comment by egucciar** [comment]
whats wrong with:

`import Masonry from 'masonry-layout'

in the short term?

**Comment by desandro** [comment]
See https://github.com/desandro/masonry/issues/839#issuecomment-212482861 Let's keep discussion about Masonry & ES6/ES2015 there. Closing here.
