### ISSUE TITLE
Masonry+Materialize: Overlapping occurring even with imagesLoaded js

### ISSUE THREAD

**Issue by kingIZZZY** [desandro/masonry#868]
http://dev.randompod.com

Trying to use MaterializeCSS (known css library) with masonry as templated/exemplified here: https://github.com/Dogfalo/materialize/tree/master/templates/masonry-template
View Source: Source: http://dev.randompod.com/wp-content/themes/dev/js/app.js

Grid items are **overlapping**, despite running the [imagesLoaded](http://masonry.desandro.com/layout.html#imagesloaded) javascript.
Am I doing anything wrong?

**Comment by desandro** [comment]
Try this code for your Masonry behavior

``` js
  var $container = $('.masonry-grid'); // our container
  // init Masonry
  $container.masonry({
    columnWidth: '.col',
    itemSelector: '.col'
  });

  $.fn.almComplete = function( alm ) { // Ajax Load More callback function
    var $items = alm.el;
    // hide newly added items
    $items.hide();
    // reveal items after images loaded
    $items.imagesLoaded( function() {
      $items.show();
      $container.masonry( 'appended', $items );
    });
  });
```

It uses [appended](http://masonry.desandro.com/methods.html#appended) to add and layout new items to the Masonry instance.

**Comment by kingIZZZY** [comment]
I set up some conditional code paths based on URL parameters ([see details here](https://github.com/dcooney/wordpress-ajax-load-more/issues/114#issuecomment-227633013))

If you browse to http://dev.randompod.com/?imagesLoaded=1&masonry=1 it should have a code path such like you suggested. The problem still seems present...

**Comment by desandro** [comment]
Sorry, but I won't be able to personally debug this issue. The solution is to use `appended` to append new items to the container.
