### ISSUE TITLE
Cannot Set Property 'element' of Undefined

### ISSUE THREAD

**Issue by whiterook6** [desandro/masonry#869]
I added a test case. I had to **inspect element** to see the error in the chrome console, since it didn't appear in the codepen console for some reason. The masonry doesn't appear to be stacking elements.

**Test case:** http://codepen.io/whiterook6/pen/dXOqpj

Whenever I try to run masonry I immediately get the following exception: Uncaught TypeError: Cannot set property 'element' of undefined

at this point:
```
function Outlayer( element, options ) {
  var queryElement = utils.getQueryElement( element );
  if ( !queryElement ) {
    if ( console ) {
      console.error( 'Bad element for ' + this.constructor.namespace +
        ': ' + ( queryElement || element ) );
    }
    return;
  }
  this.element = queryElement; // error here
  // add jQuery
  if ( jQuery ) {
    this.$element = jQuery( this.element );
  }
```

**Comment by desandro** [comment]
Looks like you're missing the `new` keyword.

``` js
var masonry = new Masonry('.masonry', {
  itemSelector: '.brick'
});
```

See demo http://codepen.io/desandro/pen/2784586bd1c0bd032bfa3dcd6f160bdd/
