### ISSUE TITLE
Gutter, different widths

### ISSUE THREAD

**Issue by gokhanipek** [desandro/masonry#870]
Hi desandro

I have 2 different widths for boxes (242px and 490px). While they align perfectly for resolutions : 1024 and higher and 767 and lower, **gutter** doesn't seem to work for resolutions between 768px and 1023px. Boxes align without space between them. I'm trying to solve this, if you have any suggestions, I'll be more than grateful.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues).

**Comment by gokhanipek** [comment]
Hi, I'm sorry for my late response. 
I tried to handle the situation with css, I'm a little busy now to provide a reduced test case now. 

Thanks anyways.
