### ISSUE TITLE
Box order changes on different browsers, creating holes (Isotope as well)

### ISSUE THREAD

**Issue by bschuon** [desandro/masonry#871]
The same layout, with identical heights, renders differently on Safari, IE, and Edge than it does in Firefox and Chrome.  Since all the columns/rows are of identical height (or 2x height/width), the layout should retain it's original order, but it does not.
For a live example of this, see:

[https://www.loungelizard.com/work/](https://www.loungelizard.com/work/)

This issue also occurs on Isotope, even with the "original order" flag set.

**Comment by desandro** [comment]
Thanks for reporting this issue. This is well known issue with pixel rounding differences between JS and CSS. See possible solution in #811. Closing here, keep discussion there.

**Comment by bschuon** [comment]
David,

     The fix from Github pull #811 seems to work swimmingly! Thank you 
for pointing that out to me.  I would like to request that the option be 
made part of the codebase, for that occasion where one browser 
calculates the numbers one way, and others ever so slightly different.  
Yes, it's an edge case, but it seems to be a fairly common one.

Great module, by the way!  Very, very useful, and easy to use. Thank you 
for all of your hard work and help!


Bob S.


On 7/1/2016 4:47 PM, David DeSandro wrote:
>
> Thanks for reporting this issue. This is well known issue with pixel 
> rounding differences between JS and CSS. See possible solution in #811 
> <https://github.com/desandro/masonry/pull/811>. Closing here, keep 
> discussion there.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/desandro/masonry/issues/871#issuecomment-230043938>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AJbUvI9q30uvpofz4ZcTlYhEJb_bnfiZks5qRXzegaJpZM4JDXeh>.
>

-- 
*Bob Schuon /Senior Developer*
*Lounge Lizard Worldwide Inc.*
tel 1-888-444-0110 ext 108 | e-fax 1-888-308-8990 | www.loungelizard.com 
<http://www.loungelizard.com>

*Union Square - NYC*
41 East 11th Street
11th Floor
New York, NY 10003

*Long Island*
31 West Main Street
Suite 212
Patchogue, NY 11772

*Los Angeles - California*
1100 Glendon Avenue
17th Floor
Los Angeles, CA 90024

**Comment by desandro** [comment]
@themenow See metafizzy/packery#366
