### ISSUE TITLE
When the page is loaded the first time,all the images lay in one column and after that the layout is right.

### ISSUE THREAD

**Issue by chenzimu** [desandro/masonry#872]
![test](https://cloud.githubusercontent.com/assets/7547416/16615137/218cc3d4-43a7-11e6-8b6f-0d9086f55b74.png)
![t2](https://cloud.githubusercontent.com/assets/7547416/16615172/46f80674-43a7-11e6-97aa-31748d01d1c4.png)

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues).

**Comment by camiloburro** [comment]
same problem here, 
http://grossostudio.com/camilo/

**Comment by cxm3264** [comment]
I meet the same problem.How can I solve  it?
