### ISSUE TITLE
masonry layout not updating, when calling masonry() after container resize

### ISSUE THREAD

**Issue by mapofemergence** [desandro/masonry#875]
This is to report a possible issue but please pardon me if it's not. I'm not an expert with masonry, nor jquery, so I couldn't tell if this depends on masonry or jquery or just me missing some fundamentals about how the two are supposed to interact.
I looked a lot around the web for the last 3 days and tried to simplify the code as much as I could to try identify the cause; unfortunately I didn't manage to get any better understanding.

A fullpage example is here:
http://sketches.futuroanteriore.org
In the "Test the Issue" section I tried to briefly explain how to reproduce the problem.

My aim is to have a page with a collapsible sidebar.
Every time the sidebar appears or disappears, the main div (containing masonry) gets resized and the masonry layout is refreshed.
This seems to work at the beginning and when I first call the function masonry(), after making the sidebar appear. If I resize the window after that, masonry doesn't update anymore.

Am I missing something?

**Test case:**http://codepen.io/mapofemergence/pen/grxodX
(I left some commented code there, just to give a hint of what I have also tried...)

**Comment by desandro** [comment]
Looks like you are setting the Masonry container to a specific width. With that width set, Masonry measures the same width when the browser window changes. Consider using another technique to resize the area that the items are in, but keep the container fluid. Perhaps using `calc()` or flex box.

**Comment by mapofemergence** [comment]
Ok. Got the point; the answer was no masonry issue, no jquery issue, just css and me being ignorant :)
Non-issue resolved.
Thank you for your help and patience.
