### ISSUE TITLE
Disable specific transitions or disable at runtime

### ISSUE THREAD

**Issue by btecu** [desandro/masonry#878]
Is it possible to disable only specific transitions (`addItem`) while keeping the transition on resize?
If not, is it possible to change `transitionDuration` once `masonry` has been instantiated?

**Comment by desandro** [comment]
Yes, you can hack this by setting `transitionDuration: 0`  before `addItem`, then resetting back afterward.

``` js
$grid.masonry( 'option', { transitionDuration: 0 });
$grid.masonry( 'addItem', item );
$grid.masonry( 'option', { transitionDuration: '0.4s' });
```

**Comment by btecu** [comment]
Thanks. I was able to get it to work with `masonry.options.transitionDuration`.
