### ISSUE TITLE
fitHeight

### ISSUE THREAD

**Issue by cicerohellmann** [desandro/masonry#879]
Good day I wanted to know if we can controll the grid, as I read the lib specifications looks like I can't but I can be wrong, like we do with fitWidth if I could use some tag to fit my grid-itens in height.

The way my app should work today is with the grid itens in a two column grid and, some times, I add a long item that uses the entire width of the screen.

Some times the itens that fit in the two columns grid will generate a gap between them and the one that fill the entire width.

There is a way for me to use something like fitWidth? I understand that would mean all the other components would need to be reloaded to get resized.

My codepen http://codepen.io/cicerohellmann/pen/OXkapg

**Comment by desandro** [comment]
Thanks for this feature request. I'm sorry to say no to this request. Masonry will not support this feature
