### ISSUE TITLE
Initiate Masonry grid - After infinite scroll and parametric search

### ISSUE THREAD

**Issue by higraf** [desandro/masonry#882]
This is my first post at github, so please be patient. 

There is a problem between AJAX and Masonry grid. Masonry grid is simple not being initiated at the right moments. 

Before scrolling or using the parametric search to go to a specific category, it works very well. 

Sample site can be found [here](http://www.unicornart.no/kunst/).

**When scrolling**
The next columns are being added above (or behind) the older ones. Giving almost the same output as unloaded images which makes [images overlapping](http://masonry.desandro.com/layout.html#imagesloaded). 

**When using parametric search**
The Masonry is not being fired correctly. Meaning it does not work at all.

Please see sample site above.

Both scrolling and parametric search is delivered by [Toolset](https://wp-types.com/). They have a good system with making it very easy to load JS at specific times. Both after the AJAX Pagination has been completed, and also before, during and after Parametric search. Since the problem is after scrolling, and after the results for Parametric search has been updated, I would like to initiate the Masonry grid at this very moment.

The easiest example is when the scrolling is done, or pagination as it's also called.

I used `reloadItems` as I guessed would be correct. Please correct me if I am wrong.

```
jQuery( document ).on( 'js_event_wpv_pagination_completed', function( event, data ) {
  $container.masonry('reloadItems')
});
```

In my theory it would reload all the items when scrolling, so they would be arranged properly. But it changes nothing.

I also tried to reload the items when the parametric search results has been updated. 

```
jQuery( document ).on( 'js_event_wpv_parametric_search_results_updated', function( event, data ) {
	 $container.masonry('reloadItems')	
});
```

But this did not work either.

The Masonry is also added in the footer by using [one of the methodes](http://masonry.desandro.com/methods.html). 

```
(function( $ ) {
	"use strict";
	var $container = $('.masonry-container');
	$container.imagesLoaded( function () {
		$container.masonry({
			columnWidth: '.col-md-3',
			percentPosition: true,
			itemSelector: '.col-md-3'
		});
	});
})(jQuery);
```

Do you have any ideas?

**Comment by desandro** [comment]
1 - remove `$(window).resize(function() {` stuff. Masonry already has this behavior built in.

2 - remove duplicated portions of code. I'm seeing two event handlers for `js_event_wpv_pagination_completed`

3 - Within `js_event_wpv_pagination_completed` or `js_event_wpv_parametric_search_results_updated` event handlers, Try triggering `.masonry()` as well.

Your code should look something like this

``` js
(function( $ ) {
  "use strict";
  var $container = $('.masonry-container');
  $container.imagesLoaded( function () {
    $container.masonry({
      columnWidth: '.col-md-3',
      percentPosition: true,
      itemSelector: '.col-md-3'
    });
  });

  $( document ).on( 'js_event_wpv_pagination_completed', function( event, data ) {
    $container.masonry('reloadItems').masonry();
  });

})(jQuery);
```

**Comment by higraf** [comment]
Thank you very much desandro.

So simple, and yet it works. Solved alot, and it's almost perfect.

The only problem is that when scrolling, sometimes the last posts are overlapping. When the next posts are added, the overlapping disappears. Meaning at the bottom there still will be overlapping. Please see provided screenshot.

Any ideas how this can be solved?
![skjermbilde 2016-08-08 kl 10 44 35 copy](https://cloud.githubusercontent.com/assets/20775360/17474448/36eb2806-5d56-11e6-84f9-2b2126bef1c3.png)

Ended up with the following code:
`(function( $ ) {
  "use strict";
  var $container = $('.masonry-container');
  $container.imagesLoaded( function () {
    $container.masonry({
      columnWidth: '.item',
      percentPosition: true,
      itemSelector: '.item'
    });
  });

  $( document ).on( 'js_event_wpv_pagination_completed', function( event, data ) {
    $container.masonry('reloadItems').masonry();
  });

 $( document ).on( 'js_event_wpv_parametric_search_results_updated', function( event, data ) {
	 $container.masonry('reloadItems').masonry();	
});

})(jQuery);`

**Comment by desandro** [comment]
You may need to trigger layout after newly added items have their images loaded.

``` js
  $( document ).on( 'js_event_wpv_pagination_completed', function( event, data ) {
    $container.masonry('reloadItems').masonry();
    $container.imagesLoaded( function() {
      $container.masonry();
    });
  });

  $( document ).on( 'js_event_wpv_parametric_search_results_updated', function( event, data ) {
    $container.masonry('reloadItems').masonry();
    $container.imagesLoaded( function() {
      $container.masonry();
    });
  });
```

**Comment by higraf** [comment]
Once again you are correct.

Thank you very much. Problem solved.
