### ISSUE TITLE
Expand item to left if last column

### ISSUE THREAD

**Issue by dioogbento** [desandro/masonry#883]
Hello,

Wanted to figure out if it would be possible to expand an item to the left if in the last column. For example, if I have a layout of 3 columns and wanted an item to expand to two columns on click, is it possible to expand an item in the last column to the left?

My intention is that the items always stay in place (after expanded), so that it doesn't move to the next row, and the other items around get layed out accordingly. The same behavior expected for items on the left side of the grid.

Or can anyone give me any guidance on how to achieve a similar effect?

Hope I have made myself clear!

Thanks!

**Comment by desandro** [comment]
I recommend using [Packery and its `fit` method](http://packery.metafizzy.co/methods.html#fit), which is perfectly designed for this use case.

**Comment by dioogbento** [comment]
Hi DeSandro,

Thanks a lot for your attention.

Will Packery work in conjunction with Isotope, for filtering?

Cheers!

**Comment by desandro** [comment]
Yes, you can use the [Packery layout mode for Isotope](http://isotope.metafizzy.co/layout-modes/packery.html)

**Comment by dioogbento** [comment]
Sorry for reopening this issue but, I've noticed that an item in the far right column still expands to the right (even though it does keep its position with Packery). Is there a way to "correct" this behavior?

Thank you for your attention.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Packery. Could you open a new issue in the [Packery issues](https://github.com/metafizzy/packery/issues) and provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/.github/contributing.md#submitting-issues).

**Comment by dioogbento** [comment]
Never mind, I needed filtering and packery, which apparently don't go together…
Thanks anyway.
