### ISSUE TITLE
Overlap / height issue

### ISSUE THREAD

**Issue by ms92** [desandro/masonry#884]
I know that there are plenty of issues regarding overlapping items etc... however I've ran in to one I've not seen before. I'm using Masonry, alongside Images Loaded and it works fine from what I've seen so far.

The issue I seem to be having is that on page load the .grid-item divs are overlapping slightly. On page refresh it sometimes fixes itself, but 50% of the time the divs are still overlapping.

Any thoughts on as to why this is happening? I've attached images of both the issue, and when the divs are displayed correctly.

![screenshot 2016-08-03 02 19 58](https://cloud.githubusercontent.com/assets/13870538/17350754/48fac9ae-5921-11e6-8854-efdad8e98f8e.png)

![screenshot 2016-08-03 02 19 50](https://cloud.githubusercontent.com/assets/13870538/17350755/48fe82b0-5921-11e6-89ab-1a4256828f16.png)

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues).
