### ISSUE TITLE
A div sometimes cover another div

### ISSUE THREAD

**Issue by yyy2015c01** [desandro/masonry#885]
#884 That **doesn't always** happen.But sometimes,**Masonry set up elements when some of the elements are not fully loaded**(images are loaded,because I am using Jquery.Imageloaded plugin),then,A div cover another div(Images are not covered.).**I try to use 'reload' and 'reloadItems' method in my code,but it doesn't work,either.**So,it's my fault or what?
:) Sorry,I am not very good at English
![1](https://cloud.githubusercontent.com/assets/18085788/17360461/4b9d58de-599e-11e6-9151-a3f3603ed5b6.png)

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues).

**Comment by RikuAnsem** [comment]
Hi.
I have the same issue, I fixed it with a "setTimeOut" (in document ready)

```
jQuery(document).ready(function ($) {
    setTimeout(function () {
        $('.masonry').masonry({
            itemSelector: '.item',
            columnWidth: '.lista_productos > div',
            percentPosition: true
        });
    }, 700);
});
```


I hope it help you

**Comment by intelligentspark** [comment]
Please re-open this, using a timeout is a hacky solution.

To further elaborate, in our case, we have Doubleclick set up to serve ads and in two of our masonry elements are two ads that are called via AJAX.  I've used this timeout solution to delay masonry by 3 seconds, but ideally $grid.masonry('reloadItems'); would actually work the way I want it to, that is, to re-scan element sizes and adjust accordingly when I call that function in an event like "ajaxCompleted" for example.
