### ISSUE TITLE
imagesLoaded does not work when resizing the screen 

### ISSUE THREAD

**Issue by higraf** [desandro/masonry#889]
This is my second post on github, so I am sorry if I break any rules or anything by posting like I am. Please correct me if I am doing something wrong.

I have had this trouble for about one year now, and I have not yet figured out how to fix it.

When resizing the screen the posts and images are being shuffled, but they tend to always overlap. When resizing a bit more the overlap disappears.

Footer:
```
<script src="<?php bloginfo('stylesheet_directory'); ?>/js/masonry.pkgd.min.js"></script>
<script src="<?php bloginfo('stylesheet_directory'); ?>/js/imagesloaded.js"></script>

```

```
(function( $ ) {
	"use strict";
	var $container = $('.masonry-container');
	$container.imagesLoaded( function () {
		$container.masonry({
		  columnWidth: '.item',
		  percentPosition: true,	
		  itemSelector: '.item'
	});
});
```

I can't find the bug anywhere. Maybe the problem is that the imagesLoaded is loaded before the images have been resized? I have really no idea where to look, but I am pretty sure I can't be the only one with this problem, since I have not been able to solve this in the latest year.

Example: http://www.medusafoto.no/

**Comment by desandro** [comment]
Is this issue about overlapping while the browser is being resized?

This is the expected behavior. Masonry waits for resizing to be stopped for a moment before it triggers its layout behavior. This improves browser performance - rather than triggering it every frame its being resized.

**Comment by higraf** [comment]
Thank you for commenting,

 

I understand. I mean the overlap right after resizing is done. It seems like it does not trigger when changing the screen size from 768px wide to 767px wide. If I change it to 766px it works, but not from 768px to 767px.

 

Any guesses?

 

Mvh

 

OLE ANDREAS VEKVE

Webdesigner & rådgiver

ole.andreas@higraf.no / (+47) 406 06 457

 

 

Sentralbord: 454 88 700 – E-post: hei@higraf.no

Reklamehuset Higraf AS, Sentrumsgata 10, 7240 Hitra

www.higraf.no

 

Org nr. NO 958 956 134 MVA

 

Fra: David DeSandro <notifications@github.com>
Svar til: desandro/masonry <reply@reply.github.com>
Dato: onsdag 17. august 2016 17.41
Til: desandro/masonry <masonry@noreply.github.com>
Kopi: Reklamehuset Higraf <ole.andreas@higraf.no>, Author <author@noreply.github.com>
Emne: Re: [desandro/masonry] imagesLoaded does not work when resizing the screen (#889)

 

Is this issue about overlapping while the browser is being resized?

This is the expected behavior. Masonry waits for resizing to be stopped for a moment before it triggers its layout behavior. This improves browser performance - rather than triggering it every frame its being resized.

**Comment by desandro** [comment]
Sounds like it's a pixel rounding error - a discrepancy between browser rendering in CSS and measuring that layout with JavaScript. I don't think there's anything I can do about this.

**Comment by Tom29** [comment]
I thought imagesLoaded doesn't work for v4 version? I see the latest version is 2. It's outdated
