### ISSUE TITLE
grid div out of place 

### ISSUE THREAD

**Issue by Dudelini** [desandro/masonry#890]
Hi,
my project http://duszan.com/JS/ uses masonry to display tiles of architectural designs. 
I noticed an error, probably my mistake. Masonry grid should appear at the bottom, below the post. 
In new posts, like "Recto|Verso" or "Towarzyska" it is displayed on top of the post. Dont know why.
Any ideas?

**Comment by desandro** [comment]
Sorry, but I am not available for personal support.
