### ISSUE TITLE
Works in IE9?

### ISSUE THREAD

**Issue by antoniogarcez** [desandro/masonry#891]
Hi,

At this moment, I'm using v.4.0.0 of your code and I read in description that you had removed support for IE8 and IE9.

I want to know if your code is still working in that browsers?

**Comment by desandro** [comment]
Masonry v4 supports IE10+, Android 4+, Safari for iOS 5+, Firefox 16+, and Chrome 12+.

For IE8+ and Android 2.3 support, try [Masonry v3](http://masonry.desandro.com/v3/).
