### ISSUE TITLE
Infinite Scroll

### ISSUE THREAD

**Issue by thaonx1987** [desandro/masonry#894]
Please example for Infinite Scroll

**Comment by thaonx1987** [comment]
don't run 

<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="http://masonry.desandro.com/masonry.pkgd.js"></script>
<script src="http://codepen.io/desandro/pen/aOprQW.js"></script>
<link rel="stylesheet" href="http://codepen.io/desandro/pen/aOprQW.css" type="text/css" />


<h1>Masonry - remove</h1>

<p>Click items to remove</p>

<div class="grid">
  <div class="grid-item"></div>
  <div class="grid-item grid-item--width2 grid-item--height2"></div>
  <div class="grid-item grid-item--height3"></div>
  <div class="grid-item grid-item--height2"></div>
  <div class="grid-item grid-item--width3"></div>
  <div class="grid-item"></div>
  <div class="grid-item"></div>
  <div class="grid-item grid-item--height2"></div>
  <div class="grid-item grid-item--width2 grid-item--height3"></div>
  <div class="grid-item"></div>
  <div class="grid-item grid-item--height2"></div>
  <div class="grid-item"></div>
  <div class="grid-item grid-item--width2 grid-item--height2"></div>
  <div class="grid-item grid-item--width2"></div>
  <div class="grid-item"></div>
  <div class="grid-item grid-item--height2"></div>
  <div class="grid-item"></div>
  <div class="grid-item"></div>
  <div class="grid-item grid-item--height3"></div>
  <div class="grid-item grid-item--height2"></div>
  <div class="grid-item"></div>
  <div class="grid-item"></div>
  <div class="grid-item grid-item--height2"></div>
</div>

**Comment by thaonx1987** [comment]
not run
`
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="http://masonry.desandro.com/masonry.pkgd.js"></script>
<script src="http://codepen.io/desandro/pen/kwALv.js"></script>
<link rel="stylesheet" href="http://codepen.io/desandro/pen/kwALv.css" type="text/css" />


<h1>Masonry - appended</h1>

<div class="grid">
  <div class="grid-item grid-item--width3"></div>
  <div class="grid-item grid-item--height3"></div>
  <div class="grid-item"></div>
  <div class="grid-item grid-item--height2"></div>
</div>

<p><button class="append-button">Append new items</button></p>

`

**Comment by thaonx1987** [comment]
`<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>`

Not run 
Code: 

`<script src="http://masonry.desandro.com/masonry.pkgd.js"></script>`
`<script src="http://masonry.desandro.com/masonry.pkgd.js"></script>
<script src="http://codepen.io/desandro/pen/kwALv.js"></script>`
`<link rel="stylesheet" href="http://codepen.io/desandro/pen/kwALv.css" type="text/css" />`
`<h1>Masonry - appended</h1>`
`<div class="grid">`
`<div class="grid-item grid-item--width3"></div>`
  `<div class="grid-item grid-item--height3"></div>`
  `<div class="grid-item"></div>`
  `<div class="grid-item grid-item--height2"></div>`
`</div>`
`<p><button class="append-button">Append new items</button></p>`

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues).
