### ISSUE TITLE
Masonry Gallery with Thumnails? 

### ISSUE THREAD

**Issue by DavidGoldschnee** [desandro/masonry#895]
Hello togehter,

i love my new masonry gallery, but with almost 80 photos inside (around 500kb - 1mb per image) its quite difficult to load the site. Is there any chance to make a workaround with thumbnails and later in the lightbox the original sized images appears? My status quo is more or less this test case, but some tryouts to get it alive with thumbnails, failed. Hope you could help me a bit guys. Thanks a lot!

**Test case:** http://codepen.io/HVinh/full/EPYKYY

**Comment by desandro** [comment]
Sorry, but I won't be able to help with this issue.
