### ISSUE TITLE
An originCenter?

### ISSUE THREAD

**Issue by ConneXNL** [desandro/masonry#903]
Animating the width of the container (while centering with margin: 0 auto) is not performant. Is it a good idea to add a way to calculatee a centered position for the items itself similar to the originLeft setting.

This way the first centering is done via CSS transform to make it performant.

Any ideas on this?

Detailed description of the problem: http://stackoverflow.com/questions/28530204/isotope-container-resizing-is-jarring

**Comment by desandro** [comment]
Thank you for this feature request. I appreciate your interest, but I will not be adding this feature to Masonry. It will add additional complexity for a small change.
