### ISSUE TITLE
Server side errors with Angular Universal

### ISSUE THREAD

**Issue by thebarada** [desandro/masonry#904]
There are error 

```
}( window, function factory( Outlayer, getSize ) {
^
ReferenceError: window is not defined
```

using this module [angular2-masonry](https://github.com/jelgblad/angular2-masonry)
I think, it will fix if check for global window object

**Comment by Gorniv** [comment]
take a look https://github.com/Angular-RU/angular-universal-starter/blob/master/server.ts
