### ISSUE TITLE
Masonry doesn't load new sets of images in Safari (infinitescroll, imagesLoaded)

### ISSUE THREAD

**Issue by bedakb** [desandro/masonry#905]
I have this issue, and I tried everything but no luck yet.

So I have issue only in Safari, with masonry, infinite scroll and imagesLoaded.When user visit the page images would be displayed, if he scroll down, the items are loaded but images are missing - I noticed that height, for some reasons, of new item images are equal to 0.

Here is the image

https://s11.postimg.org/hb5212o6r/Screen_Shot_2016_10_20_at_10_12_15.png

And here is our code

```
define([
	'imagesloaded',
	'masonry-layout',
	'vendor/infinitescroll'
], function(imagesLoaded, Masonry, infinitescroll){

	$(document).ready(function() { 

		'use strict';

		// Main content container
		let gridSelector	= 'div.Grid',
				$container 		= $(gridSelector),
				itemSelector 	= '.StandardArticle';

		// Masonry + ImagesLoaded
		$container.imagesLoaded(function(){
			$container.layout = new Masonry(gridSelector, {
				itemSelector: itemSelector,
				percentPosition: true
			});
		});

		// Infinite Scroll
		$container.infinitescroll({
		    navSelector: "#infinite_navigation",
		    nextSelector: "#infinite_navigation a",
		    itemSelector: itemSelector,
		    dataType: 'html',
		    path: [$('#infinite_navigation a').attr('href') + '?page=', ''],
		    loadingImg: $('#infinite-loading-img').attr('src'),
		    loading: {
		      finishedMsg: 'Das wär&#39;s. Han nüm meh!'
		    }
		  },

			function( newElements ) {
				var $newElems = $( newElements ).css({opacity: 0});
				$newElems.imagesLoaded(function(){
				    $newElems.animate({opacity: 1});
				    $container.layout.appended( $newElems );
				 });
		    }
		);

	});

});

```

Very strange issue to me, so any help is appreciated.Thanks.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues).

**Comment by bedakb** [comment]
Hey @desandro sorry for topic.It was not about masonry.Basically we had some attributes on img tag, that Safari doesn't understand.
