### ISSUE TITLE
Get re-layout after image loaded

### ISSUE THREAD

**Issue by Tom29** [desandro/masonry#907]
Hello there, im using masonry as a gallery , each block has 1 picture and text under it.
The trouble is if i wait until the image loaded, it takes too long loading time (ajax load), but if i don't , the layout is wrong at the beginning , text jump on the image, and get re-layout after image finished loading.

Any solution here for prevent re-layouting and don't need to wait until all images loaded?

**Comment by tovic** [comment]
Trigger relayout once an image has been loaded.

**Comment by tovic** [comment]
~~~ .javascript
var $container = $('#container');
$container.find('img').each(function() {
    $(this).on("load", function() {
        $container.masonry('layout');
    });
});
~~~

Trigger re-layout on every image load event.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues).
