### ISSUE TITLE
Fixed width wrapper not working

### ISSUE THREAD

**Issue by HassanKanj** [desandro/masonry#908]
Hello,
The code is working when the wrapper (`<div class="grid">`) doesn't have any fixed width, but once the wrapper has a fixed width the code stops working correctly, is this an expected behavior or am I missing something?

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues).
