### ISSUE TITLE
On page return, layout is overlapped

### ISSUE THREAD

**Issue by baidoct** [desandro/masonry#914]
Hello,

I'm currently having a weird bug. It only happens on **Internet Explorer** and **Microsoft Edge**.

On the first page load, the layout looks good, as it needs to be. Once you go to a different page, and after you decide to return to the previous page where the Masonry is, the layout is broken, overlapped.

**Test case:** http://codepen.io/baidoc/pen/JbMBvX

_and here's a video demonstration directly on IE11:_ https://www.dropbox.com/s/l8eiwchb5yoiygg/bug_explained.mov?dl=0

Any help would be greatly appreciated

**Comment by spekulatius** [comment]
Hello @baidoct :)

I had a very similar looking issue (in Chrome tho) and fixed it by giving each element a fixed height.

Peter

**Comment by pineromarcos** [comment]
I solved that initializing the plugin into window.load event, because the plugin need the images loaded for calculating the height

**Comment by desandro** [comment]
Are you using imagesLoaded? See http://masonry.desandro.com/layout.html#imagesloaded

@pineromarcos [Window.load is a last resort](http://metafizzy.co/blog/window-load-last-resort/)

**Comment by ryankask** [comment]
I was having a similar issue, even when using imagesLoaded. I added `element.masonry('layout')` in in a `Window.load` callback and this still didn't work so I knew something was up.

My client enabled Cloudflare which has a feature called [Mirage Image Optimization](https://www.cloudflare.com/website-optimization/mirage/). Adding a page rule to disable it on the page which uses Masonry fixed the issue.

This may not be the same problem the original reporter faced but the effect was the same so I thought I would leave this here for future searchers.

**Comment by adeopura4** [comment]
Observing the same issue. We are using Masonry with Angular (wea re not using imagesLoaded). The cards layout nicely on Chrome and Safari, but on Edge, we observe that the cards are stacked together at the top left corner for a brief moment before they are moved to their positions. This happens every time we visit a different view. 

The options we use are:
gutter: 16,
columnWidth: 218

Are there any workarounds for this issue on Edge?

**Comment by silvenon** [comment]
@adeopura4 did you style their layout? You can use Flexbox or something else to lay them out the way you want them to appear initially.

**Comment by Bryze** [comment]
The problem is, your images are loaded later and the masonry aligns the items before the image actually sets. So, if you can reload the layout after the images load, you'll be good to go :)

**Comment by spekulatius** [comment]
Ah, thats good to know.

**Comment by kirstylmarks** [comment]
@Bryze I did reload the layout, however this appears to still oddly layout 
![image](https://user-images.githubusercontent.com/2578920/50895349-ca1c0b80-13fd-11e9-8783-830d81807645.png)

**Comment by silvenon** [comment]
@rusticblonde how do you wait for images to be loaded? Do you think you could provide a demo? One way to do this is to use [imagesloaded](https://github.com/desandro/imagesloaded).
