### ISSUE TITLE
Reflow after filtering

### ISSUE THREAD

**Issue by zmancrow** [desandro/masonry#915]
Hi. Thanks for the great bit of work on this. I'm wanting to check if a) this is expected behaviour and if not b) if there is a solution.

Works great until I filter listings by community. Even though it might return 6+ matches, it displays the matches in a single column. This is my masonry code. 

$(function(){
    $('#listings-wrap').masonry({
        // options
        itemSelector: '.listing',
        columnWidth: '.listing',
percentPosition: true,
isFitWidth: true
   });
});
var masonryUpdate = function() {
    setTimeout(function() {
        $('#listings-wrap').masonry();
    }, 550);
}
$(document).on('change', 600, masonryUpdate); 

And here is a live sample: http://cowichantourism.taijiweb.ca/stay/

Try filtering by community. Sometimes one might fill out 3 columns, but most of the time it is only in one.

**Comment by desandro** [comment]
Sorry, but I won't be able to debug this issue. I strongly recommend using [Isotope for filtering with Masonry layouts](http://isotope.metafizzy.co/). It was specifically designed to do this.
