### ISSUE TITLE
percentPosition from top

### ISSUE THREAD

**Issue by danielsolosyatov** [desandro/masonry#916]
Hi. Can you help me with this option `percentPosition: true`. It works well with position form left but not from top. How to achieve this?

Here position from top is in pixels too: http://codepen.io/desandro/pen/bdgRzg

**Comment by desandro** [comment]
Masonry cannot use percent values for `top` because it sets the height of the container itself. `top` values are determined by the height of the container. So it would induce a circular logic. Sorry, Masonry does not support this feature.
