### ISSUE TITLE
problem with percentage

### ISSUE THREAD

**Issue by fabienlm** [desandro/masonry#918]
hello, first of all, thx for this plugin !
but i have a problem with percentage for grid item
look this : https://codepen.io/fabiolm/pen/WoLpar
why the the last two grid-item (with 60% and 40%) are not side by side ?
it seems work just with 75% and 25% or 50% and 50% ...

any idea to resolve it ?
thx

**Comment by NoahWilcox** [comment]
I believe the numbers have to factor into each other.
Here is your codepen edited: https://codepen.io/rhev/pen/pNBQXK

**Comment by desandro** [comment]
@NoahWilcox Thank you! Email me yo@metafizzy.co so I can send some goodies your way.

**Comment by fabienlm** [comment]
@NoahWilcox thanks !! its perfect !

**Comment by spacedawwwg** [comment]
What was the fix for this? I have the same issue with internet explorer and percentage rounding

everything works apart from IE 9/10/11, where the columns drop underneath one another (though the column widths 'float' correctly without masonry enabled)
