### ISSUE TITLE
Adding items after removing other, container height problem.

### ISSUE THREAD

**Issue by Ceyar** [desandro/masonry#920]
Hello,
I have a similar issue as this post: [678](https://github.com/desandro/masonry/issues/678)
I'm trying to remove items and replace them by other new items got by ajax request.

Here is my code:
**Jquery**

```
jQuery(window).load(function () {
    // My grid container
    var gridContainer = jQuery('#portfolio-container');

//    Starting masonry
    jQuery(gridContainer).masonry({
        itemSelector: '.grid-item',
        percentPosition: true,
        columnWidth: '.grid-sizer',
        gutter: 23
    });
    
    // Ajax call
    jQuery.post(
            ajaxurl,
            {
                'action': 'pomzed_load_portfolio'
            },
            function (response) { 
                
                jQuery('#test-button').click(function () {
                    
                    var itemGrid = jQuery('.grid-item');
                    
                    // Remove old items with masonry
                    gridContainer.masonry('remove', itemGrid);
                    gridContainer.masonry('reloadItems');
                    gridContainer.masonry('layout');
                    
                    // Add new items
                    gridContainer.prepend(response).masonry('prepended', response);
                    gridContainer.masonry('reloadItems');
                    gridContainer.masonry('layout');
                });
                var msnry = Masonry.data(jQuery(gridContainer)[0]);
                console.log(msnry);
            }
    );
});
```
**Html**
```
<!--My masonry Container-->
<div id="portfolio-container" class="grid" style="position: relative; height: 880.359px;">
    <div class="grid-sizer"></div>
    
    <!--My items-->
    <a href="#" class="permalink-single-portfolio grid-item">
        <img src="img" class="thumb-wall-portfolio wp-post-image" alt="Texte alternatif" >
        <img class="thumb-wall-portfolio" src="" alt=""> 
        <div class="title-article-wall-container color-design-graphique">
            <div class="sub-title-article-wall-container">
                <h2 class="title-article-wall">Testing Amazing guys</h2>
            </div>
        </div>
    </a>
    
    <!-- and here more items…  -->
    
</div>
```
link test to the website: [Website](http://dev.pomzeddesign.ch/portfolio/)
Click on the TEST button remove the old items and prepend the new items.

As you can see, the height of my container is big as like the olders items were always there. But if I move the windows size, the grid come again nice with the good height.

I console.log the masonry data, and they said there is more items than displayed.

I tried adding this piece of code but nothing was changing:

```
Outlayer.Item.prototype.removeElem = function() {
  this.element.parentNode.removeChild( this.element );
  // remove display: none
  this.css({ display: '' });
  this.emitEvent( 'remove', [ this ] );
};
```

What can I do to debug this?

I'm using the version 4.1 of masonry. 

Thank's in advance and best regards.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues).

**Comment by Ceyar** [comment]
Hello,

here is a [JSfiddle link](https://jsfiddle.net/Lyu807sf/).

When I click on "Get the ajax content", there grid is not resized and there space on the bottom. Am I doing something false?

Thank you in advance.
Best regards

**Comment by Ceyar** [comment]
Hello, 
do you have any suggestion about the JSfiddle reduced test that I previously posted?

Thank you in advance and best regards

**Comment by desandro** [comment]
Looks like the issue is that you're appending an HTML string. But [Masonry's `appended` method](http://masonry.desandro.com/methods.html#appended) needs an element or elements-in-array.

You can resolve this issue by wrapping `responseTest` in a jQuery object

``` js
var html = '<div>Hello world</div>'
var $html = $( html );
$grid.append( $html ).masonry( 'appended', $html );
```

See demo https://jsfiddle.net/Lyu807sf/1/

**Comment by Ceyar** [comment]
Hello, your demo does not work too. Or I missing something. The height is still remaining the same as before I clicked.

Is there another solution?

Thank you for taking time.
Best regards

Dan

**Comment by desandro** [comment]
Updated fiddle for append content fix https://jsfiddle.net/Lyu807sf/2/
