### ISSUE TITLE
Masonry + Infinite Scroll images flash at the top of the page

### ISSUE THREAD

**Issue by jvolvovski** [desandro/masonry#921]
I am having an issue with the combination of Masonry + Infinite scroll. Everything works correctly, except that the images flash very briefly at the top when new images load. It happens somewhat inconsistently, but is very noticeable when it does happen. 

You can see the website here: http://www.womenwhodraw.com

This is the script:

`(function() {

	// Main content container
	var $container = $('.isotope-box');

	// Masonry + ImagesLoaded
	$container.imagesLoaded(function(){
		$container.masonry({
			// selector for entry content
			itemSelector: '.isotope-item',
			transitionDuration: 0  
			//stagger: 30,
			//hiddenStyle: { opacity: 0 }
		});
	});
  
	// Infinite Scroll
	$container.infinitescroll({

		// selector for the paged navigation (it will be hidden)
		navSelector  : ".navigation",
		// selector for the NEXT link (to page 2)
		nextSelector : ".nav-next a",
		// selector for all items you'll retrieve
		itemSelector : ".isotope-item",
    
    extraScrollPx: 150,
    animate: true,
    appendCallback: true,
    bufferPx: 40,
    
		// finished message
		loadingImg : "",
    loadingText : "",
    
		loading: {
  		img: "data:image/gif;base64,R0lGODlhAQABAHAAACH5BAUAAAAALAAAAAABAAEAAAICRAEAOw==",
  		msgText: "Loading new artists...",
			finishedMsg: "The end.",
			speed: 0
			}
		},

		// Trigger Masonry as a callback
		function( newElements ) {
			// hide new items while they are loading
			var $newElems = $( newElements ).css({ opacity: 0 });
			// ensure that images load before adding to masonry layout
			$newElems.imagesLoaded(function(){
				// show elems now they're ready
				$container.masonry( 'appended', $newElems, true );
				$newElems.animate({ opacity: 1 });
			});
	});
})();`

Any help would be greatly appreciated!

Thanks,
Jenny

**Comment by jvolvovski** [comment]
I found your suggestion to use this code instead and that seems to have done the trick!

`function( newElements ) {
    var $newElems = $( newElements ).hide();
    $newElems.imagesLoaded(function(){
        $newElems.show();
        $container.masonry( 'appended', $newElems );
    });
}`

**Comment by feryuk** [comment]
The hide() and show() trick definitely does the job :) Thanks!
