### ISSUE TITLE
grid height: 0 if one image is loaded

### ISSUE THREAD

**Issue by AmeliePoulain92** [desandro/masonry#922]
When i insert just one image i get this http://prntscr.com/dr3jzq So height of the grid-container is equals "0". Please, help me!

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues).
