### ISSUE TITLE
Cannot reset masonry after items have been removed

### ISSUE THREAD

**Issue by hanji866** [desandro/masonry#923]
I'm try to use masonry to display grid-items, but have the ability to click remove items. This works perfectly. But I also want the ability to reset/restore the original items (including the ones removed) with a button click event. I try to make this happen by calling 'reloadItems' or re-calling $grid.masonry(). But this does not work. The click event happens, but nothing changes in regards to masonry.

Here is my reduced test case: http://codepen.io/anon/pen/ZLWQgE

Click items to be removed.. then click button 'Reload Original Items'. I want everything to come back as it was prior to the removal of any items.

Thanks!
hanji

**Comment by hanji866** [comment]
Anyone? I figured this was an easy question.

**Comment by theedgy** [comment]
http://codepen.io/anon/pen/rjwEpQ

I know it's not a perfect solution, but if author of this plugin doesn't know how to resolve that problem, for now is the best and worked for me.
If someone know more optimally and less memory eating solution i will be glad :)
Pls let me know if it satisfied you

**Comment by hanji866** [comment]
Whoa.. thanks theedgy! That works really well. I've been struggling with masonry.data to capture the items left over, but got it. Thanks a ton for the help!

**Comment by desandro** [comment]
Here's how I would do it. See demo http://codepen.io/desandro/pen/3983057c8e77979c31b8280a89514f80 In order to replace with the original, we need to keep a copy of the original items

``` js
var $cloneItems = $grid.find('.grid-item').clone();
```

Then, when we reset, we remove the current items and replace them with the cloned items

``` js
$('#reload').on( 'click', function() {
  var $items = $grid.find('.grid-item');
  // remove current items
  $grid.masonry( 'remove', $items );
  $grid.masonry('layout');
  // add back original
  $grid.append( $cloneItems ).masonry( 'appended', $cloneItems );
  // update clone items
  $cloneItems = $cloneItems.clone();
});
```

There's a bug where items do not transition after the second reload. But otherwise it works.
