### ISSUE TITLE
Simultaneous reveal/hide prevents hideComplete

### ISSUE THREAD

**Issue by rk** [desandro/masonry#924]
I noticed that when calling reveal/hide in quick succession prevents the hideComplete event from firing, which prevents the `display: none` inline style from being applied to the items. It works visually, but foils any attempt to filter the items by `:hidden` or `:visible`.

For the test case, click the toggle button a couple of times. You should see `hideComplete` *if it correctly fires*, just like `revealComplete` shows in the log. You'll also see a count after each log entry indicating how many child elements are hidden.

The issue persists even if you reverse the following lines:

    this.hide(hideItems);
    this.reveal(revealItems);

**Test case:** http://jsbin.com/juxacivusi/edit?js,console,output

(Sorry it's not on CodePen, I'm used to JSBin.)

**Comment by desandro** [comment]
Thanks for reporting this issue. No one else has chimed in, so I am going to close this issue as `wontfix`. Please follow up if I should take another look.
