### ISSUE TITLE
"top" value 1 extra pixel

### ISSUE THREAD

**Issue by g1un** [desandro/masonry#925]
Hi!
I always see the issue with top value for example in mozilla (windows) on 850px viewport width.

Here are screenshots.
White 1px horizontal line:
![270dd84f5c](https://cloud.githubusercontent.com/assets/13907881/22352166/10309482-e42c-11e6-8ae4-1d30a2d2bb73.jpg)

The height of masonry item is 300.483px:
![001](https://cloud.githubusercontent.com/assets/13907881/22352300/94d3d7bc-e42c-11e6-92f1-bfe04ba551be.jpg)

The items on the third row has 1 extra pixel for top value:
![002](https://cloud.githubusercontent.com/assets/13907881/22352717/5638c420-e42e-11e6-83c6-e2620b69ff92.jpg)

You can reproduce the bug yourself here: http://dochery.ru/ru/works/view?id=56

I will be glad for any type of advice on how I can fix it and continue using masonry.

Thanks!

**Comment by makingthingswork** [comment]
Look at the styles on the image, particularly the display property. Try a 'block'

**Comment by desandro** [comment]
Looks like Masonry is no longer being used on this site.

**Comment by g1un** [comment]
Yes, it doesn't use masonry any more. Maybe, bug was caused by infinite-scroll, that have been used alngside. I didn't test it. This site with blocks of same dimensions never really needed masonry.
