### ISSUE TITLE
How to prioritize grid toward top of screen to eliminate blank spaces?

### ISSUE THREAD

**Issue by damonbowe** [desandro/masonry#927]
Is it possible to prioritize a completed grid vertically to prevent blank spaces? See [rosept.com/physical-therapists](url)

![screenshot_473](https://cloud.githubusercontent.com/assets/14153137/22982153/4357a3ba-f36c-11e6-845f-f568b7c67245.png)

![screenshot_474](https://cloud.githubusercontent.com/assets/14153137/22982220/7b678518-f36c-11e6-8de4-54e6c5383ccf.png)

**Comment by desandro** [comment]
If you're looking to fill gaps, then I recommend [Packery](http://packeryjs.com). It's specifically designed for this. Otherwise, you can sort items with [Isotope](http://isotopejs.com)

**Comment by damonbowe** [comment]
Thank you!
