### ISSUE TITLE
Masonry not working on iPhone safari or Chrome

### ISSUE THREAD

**Issue by mattkersner** [desandro/masonry#929]
**Test case:** http://codepen.io/desandro/pen/osFxj

Just wanted to bring this to your attention. My website, mattkersner.com, works fine in desktop mode and is completely responsive. But when I open the site in my iPhone, on chrome or safari, I get the "aw snap! something went wrong while displaying the webpage" error. Furthermore, the images never even load on the main page. They do load on the about and contact pages, but it also breaks after a bit if I try to scroll down and see all the pictures. Not sure what the problem is, hoping you've run into this before. It's clear that it's the images/masonry that's causing the problem.  

Here's a link to the repo for my portfolio page https://github.com/mattkersner/portfolio. Otherwise, just try visiting mattkersner.com on your iphone after visiting it on your desktop and you'll see what I mean.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues).
