### ISSUE TITLE
double animation

### ISSUE THREAD

**Issue by fastrer** [desandro/masonry#930]
Hi i'm working on a products dashboard and i need to ajust the size of a div, but when i ajust it with css class, and i do an update to the grid, this trigger two times the animation.

here is an example where the effect can be saw.
https://jsfiddle.net/Fastrer/wztgrxsq/8/

sorry for my bad english.

**Comment by desandro** [comment]
Looks to the a double transition bug. See http://isotope.metafizzy.co/faq.html#items-jump-after-transitioning-position

**Comment by fastrer** [comment]
Excelent, i did not think that was the problem.
