### ISSUE TITLE
Articles are sorted incorrectly

### ISSUE THREAD

**Issue by indikatordesign** [desandro/masonry#932]
I think forking a test case makes no sense with my problem, cause I really have no idea how I can imitate the error in such a case. I've made a short screen videos to show what happens. Perhaps anybody know this problem and can show me the right direction to fix it..

In my case I use masonry.js together with imagesLoaded to adjust a WordPress blogroll. I wanna sort the articles from the output and it works good so far. But there is a single blogpost that is not properly arranged. That leads to a bigger gutter on top. Any idea?

I tried it with the version that is delivered with WordPress itself and also with the newest release. With both I get the same result.

[Screen-Video](http://7.ly/pWbD)

**Comment by desandro** [comment]
Thanks for reporting this issue. I appreciate the video, but a live URL is necessary in order to understand the issue. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues).

**Comment by indikatordesign** [comment]
It is a really complex thing.. Is it helpful for you to share the url itself? It's on a development domain. If you send me your ip, I can whitelist you and share the link. All scripts are uncompressed there.

If that is an option for you, you can use my form to send me your ip: [Link](http://7.ly/pWg6)

**Comment by desandro** [comment]
Sorry, but a **reduced test case** is best way to identify the issue at hand. If you can reproduce the issue in an isolated example I can take a look.

**Comment by indikatordesign** [comment]
I don't think that I can reproduce it. It is not just pictures, but whole posts, even articles. I temporary removed the ip-protection. Perhaps you can take a look at it? [Link](http://7.ly/pWhX)

The setup is in the file: dfbm-blogroll.js, the styles are in the file dfbm.blogroll.css

**Comment by indikatordesign** [comment]
And there is another problem when 3 columns are used and the gutter is set to 0. If you play with the browser-width, there are sometimes a 1px overlapping or a 1px gap between the columns on the right and left between column 1 to 2 and between column 2 to 3.

I do not mean for images cause the masonry is triggered after imagesLoaded..

**Comment by indikatordesign** [comment]
Anybody else with the problem?

**Comment by indikatordesign** [comment]
It seems that it was something like a loading conflict. It was possible to fix it with a setTimeout:

```
this.grid.imagesLoaded( function()
{

	setTimeout(function()
	{

		$this.masonry();

	}, 100 );

});
```
