### ISSUE TITLE
Overlapping items

### ISSUE THREAD

**Issue by indikatordesign** [desandro/masonry#933]
**Test case:** http://codepen.io/IndikatorDesign/pen/EWVBKj

In the testcase, the grid-container has a fixed width of 825px. This is to show a problem that happens with a responsive design where the grid-container can vary.

There is no gutter. The items have an inline-shadow with a width of 1px.

From the first to the second column the corresponding shadow-width looks like 1px, but from the second to the third column it looks like 2px.

Any known workaround to fix this?

**Comment by desandro** [comment]
Looks like your items had `style="height: 300px"` attributes. If you remove this, everything looks good http://codepen.io/desandro/pen/b7093c61a327a6782930f421992665ac/

**Comment by indikatordesign** [comment]
I've added the style-attributes to simulate a better live-situation, cause it would be awesome, if I get it to work properly with some blogposts that vary in height.

But it's the same phenomenon with your changed codepen. You can see what meant in this short video: [Link](http://7.ly/pXxY)

**Comment by desandro** [comment]
If we're talking specifically about the 1px extra gap — that's just how Masonry works. There may be 1px mismatches between JavaScript and CSS sometimes.

One solution is to use [Colcade](https://github.com/desandro/colcade). Colcade works with your own column CSS, so there's no JS calculation mismatch.

**Comment by indikatordesign** [comment]
That's it. Since I don't wanna use multi-column-spanning, it's exactly the solution I was looking for. Thanks for the tip and your great work on this solutions!
