### ISSUE TITLE
Stamp issues with Masonry-Rails Gem

### ISSUE THREAD

**Issue by joespam** [desandro/masonry#934]
I'm having difficulty getting stamping to work. I have a full reduced example of my issue at the link below. Uncertain if the issue is in incorrect usage, Browser/OS compatibility, or a bug in the Masonry-Rails Gem, or the Masonry library itself, but the feature will not work for me in my code. Masonry ignores my stamped object and places the other items as if stamped object isn't there at a different Z value depending on the order the elements are created.

http://stackoverflow.com/questions/42518103/stamp-ed-item-in-masonry-being-completely-ignored

**Comment by desandro** [comment]
Try the `http` link for the CodePen: http://codepen.io/desandro/pen/wKpjs?editors=1010

As for your example, could you provide a **reduced test case** of your issue? The image is helpful, but not enough for this issue to be addressed. See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues).
