### ISSUE TITLE
Masonry Bootstrap Modal Issue

### ISSUE THREAD

**Issue by erishv** [desandro/masonry#935]
Hello,
Can you help me with this please? I am running Masonry inside a modal, the masonry should load when the modal is clicked. 

Please suggest or modify the code on the test case. Thanks

Here is the test case: http://codepen.io/erishv/pen/BWQvrY

**Comment by desandro** [comment]
Similar to https://github.com/desandro/masonry/issues/217#issuecomment-6910871, you'll need to trigger layout after the content is displayed. In this case, you can use [Bootstraps's `shown.bs.modal` event](https://v4-alpha.getbootstrap.com/components/modal/#events). 

``` js
// layout masonry when visible
$('#exampleModal').on( 'shown.bs.modal', function() {
  $('.grid').masonry({
    itemSelector: '.grid-item',
    columnWidth: 160
  });
});
```

See demo http://codepen.io/desandro/pen/yMgyzR

**Comment by erishv** [comment]
Thank you Sir, this works.
But found the problem on my code, it is that I had multiple jQuery scripts en-queued for the other plugins (WordPress). And for somehow, the code 
`// layout masonry when visible
$('#exampleModal').on( 'shown.bs.modal', function() {
  $('.grid').masonry({
    itemSelector: '.grid-item',
    columnWidth: 160
  });
});`
only works when it is put before the closing tag of the body tag; when it is en-queued on another file, the code does not fired, but not displaying any error on the console.

Will try to work it out today, but your answer gave me light. Thank you so much
