### ISSUE TITLE
Still issues with Masonry + InfiniteScroll + ImagesLoaded

### ISSUE THREAD

**Issue by stabilimenta** [desandro/masonry#938]
Hello,
I'm having trouble with a WordPress use of Masonry + InfiniteScroll + ImagesLoaded.
The result is similar to the problems that are written about in other threads here, but the specifics are a little different. The page can be seen here:
https://evolutionarygraphics.com/asheville-web-design/
Sorry, I don't have a reduced version of it, but it's a rather complex layout, which might be part of the issue. 
My javascript looks like this:
```javascript
jQuery(document).ready(function($) {

	// Main content container
	var $container = $('.masonry-container');

	// Masonry + ImagesLoaded
	$container.imagesLoaded(function(){
		$container.masonry({
			// selector for entry content
			itemSelector: '.item',
			columnWidth: '.grid-sizer',
			percentPosition: true,
			gutter: '.gutter-sizer'
		});
	});

	// Infinite Scroll
	$container.infinitescroll({

		// selector for the paged navigation (it will be hidden)
		navSelector  : ".post-nav",
		// selector for the NEXT link (to page 2)
		nextSelector : ".next a",
		// selector for all items you'll retrieve
		itemSelector : ".item",

		// finished message
		loading: {
			msgText : 'Loading more items&hellip;',
			img : '/wp/wp-content/themes/evolutionarygraphics/images/wheel.svg',
			finishedMsg: "*********",
			}
		},

		// Trigger Masonry as a callback
		function( newElements ) {
			// hide new items while they are loading
			var $newElems = $( newElements ).css({ opacity: 0 });
			// ensure that images load before adding to masonry layout
			$newElems.imagesLoaded(function(){
				// show elems now they're ready
				$newElems.animate({ opacity: 1 });
				$container.masonry( 'appended', $newElems, true );
			})
		}
	);	

}); //end ready functions
```
It seems like imagesLoaded just isn't waiting until the images are loaded before displaying. Once the images are cached, the page loads perfectly.

Here is a screenshot of the issue, in case it happens to be working for you. 

![screen shot 2017-03-15 at 9 58 41 pm](https://cloud.githubusercontent.com/assets/10748861/23978525/da42a9d6-09ca-11e7-8a1b-d24958827b15.png)

I really appreciate any help you can offer. Masonry is really great.

**Comment by desandro** [comment]
Sorry to hear you're having trouble with Masonry. I just loaded up this page in Chrome and wasn't able to reproduce this issue. Your code looks good FWIW

**Comment by stabilimenta** [comment]
The issue is a bit erratic. Mostly, I'm using Firefox, and it happens in Firefox, but not all the time. In Safari (Mac, v9.1.13) it happens every time. No errors in the console though.

**Comment by stabilimenta** [comment]
I think I discovered my error... I was using calc() in my img srcset sizes, and was missing spaces around the math operators. 
calc(.88 * ((.31 * (100vw - 30px)) - 2px))
Safari really did not like that, and it was loading images that were far too big. Once I fixed that, the page size was cut by 3/4, and it is working now. 

Thanks for your awesome project, and for sharing your talents.
