### ISSUE TITLE
How do I centre my masonry grid?

### ISSUE THREAD

**Issue by Bekahlea** [desandro/masonry#939]
Hi,

I'm having a few issues with the masonry grid. I'm currently having to centre it on my [website](http://www.tinajarrett.com/music.html) using margin-left in the css. I was wondering if there was another way around it? I have tried margin: 0px auto 0px auto; but to no avail.

I'm also not entirely sure if I'm using the right version of masonry (I only found it yesterday) and any help or advice would be appreciated.

I have tried to use codepen [here](https://codepen.io/Bekahlea/pen/VpMREP) but it doesn't seem to be working the way it does in my previews on dreamweaver.

Thanks in advance.

**Comment by desandro** [comment]
Have you looked at using [fitWidth](http://masonry.desandro.com/options.html#fitwidth) and `margin: auto`? See demo http://codepen.io/desandro/pen/nGLvx

**Comment by Bekahlea** [comment]
I have yes, that worked on centring it, thank you. Though, the grid is no longer responsive when the page is resized. Is there anything that could be stopping that?

**Comment by desandro** [comment]
Sorry, but the behavior you're looking for is not possible. The container needs items to be a fixed width so it can measure for centering the container.  If the items are fluid width, then they need the container to have a fixed width. It's a chicken & the egg sort of situation.
