### ISSUE TITLE
Use masonryImagesReveal for initial items.

### ISSUE THREAD

**Issue by macmartine** [desandro/masonry#940]
How do you get Masonry to make two columns of 50% width?

When I set percentWidth, the image load on top of each other.

http://bootsnipp.com/user/snippets/K5onD

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues).

**Comment by macmartine** [comment]
Thanks! So, I am now using your exact demo, with different images, and it's better, but the photos are way down the page. Any ideas?

https://codepen.io/macmartine/pen/wJpOKG

**Comment by desandro** [comment]
Your demo has items being added again, hence the empty space on top. You can hack a fix by initializing Masonry with 0 items, using an `itemSelector: 'none'`. Then reset `itemSelector: '.item'`, then add items with `.masonryImagesReveal()`.  See demo https://codepen.io/desandro/pen/9f7ebbf5902acfde32140caa49e647bb

``` js
var $container = $('#images').masonry({
    itemSelector: 'none', // initialize with 0 items
    columnWidth: '.grid-sizer'
});

// set proper itemSelector
$container.masonry( 'option', { itemSelector: '.item ' });

// reveal initial images
$container.masonryImagesReveal($container.find('.item'));
```

**Comment by macmartine** [comment]
Thanks! But in that demo, when I first load the page, the image are all in one column, until I resize :(

**Comment by macmartine** [comment]
Any thoughts on this? Can't seem to get it.

**Comment by desandro** [comment]
Sorry, I'm not able to reproduce that bug with the single column. I feel like I've provided enough guidance on how to use `.masonryImagesReveal()`, I'll leave the rest up to you.

**Comment by macmartine** [comment]
That's unfortunate. Happens 100% of the time in Chrome when the browser window is below a certain width (Mine is currently at 1000px wide and it happens every time). When it's wide it seems much better. Using your demo: https://codepen.io/desandro/pen/9f7ebbf5902acfde32140caa49e647bb

Thanks for your help though.

**Comment by opetznick** [comment]
@desandro i can reproduce that bug too. using chrome 59 on osx sierra.
