### ISSUE TITLE
Animate Images *UP* instead of scaling into view. 

### ISSUE THREAD

**Issue by patrickbjohnson** [desandro/masonry#941]
This is more of a question as I cannot find any documentation necessary to solve from the issues or site. 

Is there a way to slide *UP* and into view when Masonry is initialized and the masonry items are loaded? 

I've attempted to tweak `top` position using the `hiddenStyle` and `visibleStyle` but adjusting the `top` value ruins the scripts attempt to calculate the position an item is supposed to actually have.

**Comment by desandro** [comment]
So close! You can do this with using `transform` within `hiddenStyle` and `visibleStyle`. See demo http://codepen.io/desandro/pen/bqvLaZ/

``` js
$('.grid').masonry({
    itemSelector: '.grid-item',
    columnWidth: 200,
    hiddenStyle: {
      transform: 'translateY(100px)',
      opacity: 0
    },
    visibleStyle: {
      transform: 'translateY(0px)',
      opacity: 1
    }
  });
```
