### ISSUE TITLE
Can masonry elements wrap around stamp (specifically above)?

### ISSUE THREAD

**Issue by OneTimeUser** [desandro/masonry#942]
I read in the docs that stamps clear all masonry elements above it, but is there a way for that not to happen, as in the elemnts just wrap around it?   I was trying to maybe fix the stamp in place so that when scrolling occurs, the masonry elements shift around it.   Currently in the codepen below, the elements shift but not above, as is how the stamp currently works.   Just curious. Thanks,
**Working Example** http://codepen.io/onetimeuser/pen/LWrBOe

**Comment by desandro** [comment]
Masonry can only stamp an element above items. However, [Packery](http://packeryjs.com) can stamp an element completely around items — below and above. See demo http://codepen.io/desandro/pen/60810567813640e4d4f6895431b53eeb/

**Comment by OneTimeUser** [comment]
Ah brilliant.  I figured I may have been in the wrong library.  Thanks so much man.
