### ISSUE TITLE
grid customizations

### ISSUE THREAD

**Issue by 12557** [desandro/masonry#943]
hey volks,

sorry for disturbing you i see you rolling with your eyes about my stupid questions.
i am totally new to masonry and jquery but i have to solve a challenge but i dont know
how to start 

i bought a wordpress template where masonry is implemented and installed the template. Thats the link to my site:

http://panm.formkoalition.de

i want to do 2 things:

1 edit the distance between the thumbnails
2 put the grid on a bottom line as you can see in that very nice example site i want to have my page look the same:

http://cargocollective.com/titusandronicus

This cargo site grid is absolutely beautiful and uses also masonry. I want now to change my wordpress grid as you can see in cargo. I tried it with css but this doesn't work. 

I found a div called:
`portfolio-entry post-19 jetpack-portfolio type-jetpack-portfolio status-publish has-post-thumbnail hentry masonry-brick`

but i cant find any css where i can edit it or where it is generated.

So guys many many thanks
hope to hear form you soon

greets 

12557

**Comment by desandro** [comment]
Sorry, I won't be able to provide support with this issue.  See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues).
