### ISSUE TITLE
Mobile fluid-width grid items are not rearranged nicely

### ISSUE THREAD

**Issue by timboozle** [desandro/masonry#944]
Not sure if this is expected behavior but I have a grid that has a fluid width on mobile (width:50vw). On this grid, banners are inserted at random positions that are 2 by 1 (width:100vw). If the banner is inserted at an odd number position the grid doesn't rearrange nicely and leaves an empty spot before the banner. 

I recreated the issue here: http://codepen.io/timboozle/pen/oWvYVN
It leaves an empty spot before the red banner which I would like to see filled.

Here is the issue in the real world: http://timboozle.nl/masonry/ (Pink banner)
As you can see the other breakpoints rearrange the grid nicely

**Comment by desandro** [comment]
Thanks for reporting this issue. Masonry's layout algorithm cannot fill gaps like these. [Packery, however, was built to fill gaps exactly like this.](http://packeryjs.com). Give it a try!
