### ISSUE TITLE
Diffrent display grind in Chrome and Safari

### ISSUE THREAD

**Issue by piotr-muszkiewicz** [desandro/masonry#945]
Hey.

https://evonails.pl/lakiery-hybrydowe-gellack-uv-pro/lakiery-hybrydowe-kolorowe/kolekcja-this-girl-is-on-fire.html

Large chrome image is displayed on the left and ff on the right. Why?

http://prntscr.com/evifst

**Comment by desandro** [comment]
This is likely a 1px rounding error issue. Sorry, I won't be able to fix this one with a hack. It could be likely resolved by #811
