### ISSUE TITLE
You script at unpkg is hacked!

### ISSUE THREAD

**Issue by lekhko** [desandro/masonry#947]
https://unpkg.com/masonry-layout@4.1/dist/masonry.pkgd.js

This file now redirects to malware script, and all sites alerts: 'Your computer is infected. You have to check it with antivirus.'

**Comment by sierracircle** [comment]
Yep..brings up a malware link on any websites using that link..

**Comment by desandro** [comment]
Thanks for reporting this issue. The [bug was with unpkg, which has since been resolved](https://twitter.com/unpkg/status/852669269103869952).
