### ISSUE TITLE
Expose method to use in filterFindElements for Shadow DOM compatibility

### ISSUE THREAD

**Issue by web-padawan** [desandro/masonry#949]
As of now, [this line](https://github.com/metafizzy/fizzy-ui-utils/blob/56445300f00ae9656da804af7143d451af2f8fee/utils.js#L139) collects elements using `querySelectorAll` with passed `itemSelector`. 

This doesn't work if we initialize grid on a web component with distributed children.

Say we have a `masonry-grid` component whose template looks like this:
```html
<template>
  <div id="grid">
    <slot></slot>
  </div>
</template>
```

Then, we pass pass children from outside, so they go to that `<slot>`, e. g. like this:

```html
<masonry-grid>
  <div class="grid-item"></div>
  <div class="grid-item"></div>
  <div class="grid-item"></div>
</masonry-grid>
```

And here we should replace call to `querySelector` by `HTMLSlotElement.assignedNodes({ flatten: true})` like it is described [here](https://www.polymer-project.org/2.0/docs/devguide/shadow-dom#slot-apis).

I could fork your awesome library and modify that code. But this would require maintaining forks for `masonry`, `outlayer` and `fizzy-ui-utils`, and I'd like to avoid this.

So I suggest modifying `filterFindElements` so it could accept an optional callback which could be passed into masonry options object. This would still require multiple changes, though.

Any suggestions about how to implement this better?

**Comment by desandro** [comment]
Thanks for looking into this! I haven't done any work to make Masonry a Polymer-compatible web component. If you can put together a [**reduced test case**](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues) demonstrating how Masonry is broken as a web component, I can better understand the issue with `filterFindElements`

**Comment by web-padawan** [comment]
Here is a **[reduced test case](http://codepen.io/web-padawan/pen/ybezdN/)**.
Please check it in Chrome 55+ because I haven't include polyfill. Safari 10.1 should be fine too.

As you can see, there are two places where items could be placed:
1. inside of the shadow DOM (they have green background) - those are rendered correctly
2. outside (injected to `<slot>`) - those are ignored, because `querySelectorAll` doesn't catch them.

**Comment by daKmoR** [comment]
hmmm just curious
changeing
`this._masonry = new Masonry(this.$.grid, {`
to 
`this._masonry = new Masonry(this, {`

will capture your red boxes but not your green boxes...
so it's the mixing of shadow dom and light dom elements that seems to be the problem right?
so maybe collect them properly yourself and give them to masonry later?

I do have a much simpler Masonry Custom Element (without automatic slot change - I use appendChild and insertBefore) which only uses slotted element so I never had this problem...
you can take a look at it here
https://gist.github.com/daKmoR/30c80f388a0109046fa67bb323c29d8d

**Comment by desandro** [comment]
@daKmoR Thanks so much for chiming in here. Given that this solution does not require modifying Masonry's source, I'd prefer to use it.

**Comment by web-padawan** [comment]
Well, this makes sense. Mixing shadow and light DOM might be a reasonable limitation here. Will close for now, until we have more browsers with native Shadow DOM support.

**Comment by xugao** [comment]
@daKmoR - would you mind sharing the full code for your implementation?
@web-padawan - if you have a working version, would you mind share your code/implementation?
