### ISSUE TITLE
Insert item to the items

### ISSUE THREAD

**Issue by pinclub** [desandro/masonry#950]
I try to insert a new item to the items, could not find any method, so I add an method like 

```javascript
proto.insertItems = function(index, elems ) {
    var items = this._itemize( elems );
    // add items to collection
    if ( items.length ) {
      this.items.splice(index, 0 , items[0]);
      //this.items = this.items.concat( items );
    }
    // layout and reveal just the new items
    this.layoutItems( items, true );
    this.reveal( items );
  };
```

Usage is:
```javascript
gridMasonry.append(jpicelements).masonry('insertItems', <index>, <item>);
```

Is there any better method to do this thing?

**Comment by desandro** [comment]
**Add a 👍  reaction** to this issue if you would like to see this feature better documented.

---

You can do it by adding this code (most of which [comes from Isotope](https://github.com/metafizzy/isotope/blob/v3.0.4/js/isotope.js#L532))

``` js
/**
 * @param {Array or NodeList or Element} elems
 * @param {Number} index
 */
Masonry.prototype.insert = function( elems, index ) {
  var items = this._itemize( elems );
  if ( !items.length ) {
    return;
  }
  // append item elements
  var i, item;
  var len = items.length;
  var fragment = document.createDocumentFragment();
  for ( i=0; i < len; i++ ) {
    item = items[i];
    fragment.appendChild( item.element );
  }
  var beforeElem = this.items[ index + 1 ].element;
  this.element.insertBefore( fragment, beforeElem );
  // insert items
  var spliceArgs = [ index, 0 ].concat( items );
  this.items.splice.apply( this.items, spliceArgs );
  // set flag
  for ( i=0; i < len; i++ ) {
    items[i].isLayoutInstant = true;
  }
  this.layout();
  // reset flag
  for ( i=0; i < len; i++ ) {
    delete items[i].isLayoutInstant;
  }
  this.reveal( items );
};
```

Then use it like

``` js
$grid.masonry( 'insert', $elems, 2 )
```

See demo http://codepen.io/desandro/pen/NjRwKM

**Comment by infinnie** [comment]
What about pinning this issue to the Masonry FAQs, since the need to insert items at random positions are common during development?

**Comment by desandro** [comment]
@infinnie Not a bad idea, but — looking this issue's engagement — I don't think there's enough interest just yet. I've updated my comment above to encourage people responding so I can get a better sense of its popularity.

**Comment by infinnie** [comment]
But then if we really wanted to insert items at a random position, maybe we could just use the DOM method to insert it and then call `.layout()`.
