### ISSUE TITLE
Memory leak ....

### ISSUE THREAD

**Issue by oddjobz** [desandro/masonry#951]
I've been struggling with a dynamic grid that's been crashing overnight when it's hit > 6000 items and eventually came to the conclusion "remove" wasn't actually cleaning the DOM. (max items should be 50) After adding a $().remove() of the item following the masonry remove, the problem seems to have resolved itself. I've managed to reproduce what seems to be the issue with the test-case below. (I'm using packaged 4.1.1)

**Test case:** http://codepen.io/oddjobz/pen/jmqdvX?editors=1111

**Comment by desandro** [comment]
Thank you for reporting this issue. Masonry's `remove` method does remove elements from the DOM, but only after its hide transition has been completed. See demo http://codepen.io/desandro/pen/c7039e55dfe7179e826c9b79505864b5/

**Comment by oddjobz** [comment]
I understand, however if the grid is not visible when the item is removed, this transition does take place and the item is left in the dom. So I have a grid on a tabbed screen, if I leave my application overnight with the grid on a hidden tab, come the morning it's either creaking with many thousands of invisible items in the grid, or it's completely locked up. (adding the manual 'remove' seems to fix the issue)
