### ISSUE TITLE
Masonry for js code

### ISSUE THREAD

**Issue by Kiko51** [desandro/masonry#952]
Hello,

I want to put 2 columns with several rows of news taken from a feed of a blog. This is the code of how lame 8 blog news:

$(document).ready(function()
{
	$.ajax(
	{
        	url: 'blog.blogspot.com',
		type: 'get',
        	dataType: "jsonp",
        	success: function(data) 
        	{
            		var posturl = "";
            		var htmlcode = '<ul>';
            		var newhtmlcode = '';
            		var tamano_imagen = 700;
            		var i = 0;
            		var count= 0;
			var fecha="";
            		while ((i < data.feed.entry.length) && (count<8))
            		{
	            		for (var j=0; j < data.feed.entry[i].link.length; j++)
	            		{
	                		if (data.feed.entry[i].link[j].rel == "alternate")
	                		{
	                    			posturl = data.feed.entry[i].link[j].href;
	                    			break;
	                		}
	            		}
				 
	            		if("content" in data.feed.entry[i])
	            		{
	                		var postcontent = data.feed.entry[i].content.$t;
					if(typeof(data.feed.entry[i].media$thumbnail) != "undefined")
					{
	                			var miniatura = data.feed.entry[i].media$thumbnail.url;
						var miniatura = miniatura.replace('s72-c', 's'+ tamano_imagen);
					}
					else
					{
						var miniatura = "complementos/js/escudo.jpg";
					}
				}
				if("published" in data.feed.entry[i])
				{
					var date_published = data.feed.entry[i].published.$t;
					var fecha = date_published.split('T');
					var yyyy_mm_dd = fecha[0].split('-');
			
					var year = yyyy_mm_dd[0];
					var month = yyyy_mm_dd[1];
					var day = yyyy_mm_dd[2];
					
					switch (month) 
					{

						case "01": 
							mes="Enero";
							break;
						case "02": 
							mes="Febrero";
							break;
						case "03": 
							mes="Marzo";
							break;
						case "04": 
							mes="Abril";
							break;
						case "05": 
							mes="Mayo";
							break;
						case "06": 
							mes="Junio";
							break;
						case "07": 
							mes="Julio";
							break;
						case "08": 
							mes="Agosto";
							break;
						case "09": 
							mes="Septiembre";
							break;
						case "10": 
							mes="Octubre";
							break;
						case "11": 
							mes="Noviembre";
							break;
						case "12": 
							var mes="Diciembre";
							break;
					}

					fecha = day + " de " + mes + " de " + year;                    
		  		}
	            		else if("summary" in data.feed.entry[i])
	            		{
	                		var postcontent = data.feed.entry[i].summary.$t;
	            		}
	            		else
	            		{
	                		var postcontent = "";
	            		}
	            		var re = /<\S[^>]*>/g;
	            		postcontent = postcontent.replace(re,"");
		    		var posttitle = data.feed.entry[i].title.$t;
	            		//reduce postcontent to 300 characters
	            		if(postcontent.length > 300)
	            		{
	                		postcontent = postcontent.substring(0,300);
					postcontent = postcontent+' ...';
	            		}
	            
		    		htmlcode += '</ul>';
	
				newhtmlcode += 	"<div class='cuadro_noticia'>" +	
							"<div class='foto_noticia'><img src='"+miniatura+"'></div>" +
							"<div class='titular'><h1><a target='_blank' href='"+posturl+"'>"+posttitle+"</a></h1></div>"+
							"<div class='fecha'>"+fecha+"</div>" +
							"<div class='contenido_noticia'><span>"+postcontent+"</span></div>"+	
							"<div class='leer_mas'><a target='_blank' class='icono_leer_mas' href='"+posturl+"'>>>Leer más</a></div>"+
						"</div>";

				i++;
				count++;
			}					
			$('.noticias_blog').append(newhtmlcode);
        	}
    	});	
});

I try to apply masonry for each news but it does not work. How should I? The css for cuadro_noticia is:

float:left;
width:45%;
margin-right:5%;

The html code would look like this:
<head>
<script src="complementos/js/jquery.masonry.min.js"></script>
<script src="complementos/js/jquery.masonry.min.js"></script>
<script>
$(document).ready(function(){
	$('#noticias_blog').masonry();
});
</script>

</head>

<body>
<div class="noticias_blog" id="noticias_blog"></div>
</div>

How could I apply masonry ??

Thank you very much.

**Comment by desandro** [comment]
Sorry, but I will not be able to provide personal support for this issue. See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues).
