### ISSUE TITLE
Layout breaks with 60% & 40% widths.

### ISSUE THREAD

**Issue by timothyachumba** [desandro/masonry#954]
Not able to create a grid with a 60% / 40% split? It works well with 50% / 50%.

![2017-04-24 10_18_46 pm](https://cloud.githubusercontent.com/assets/2601332/25359606/bc6ec1a0-293d-11e7-9278-13bfea6b80f8.gif)

http://codepen.io/anon/pen/jmMvPO

**Comment by desandro** [comment]
For 60%/40%, you'll need a columnWidth that's a divisor of both: 20%.

``` css
.grid-sizer { width: 20%; }
```

See demo http://codepen.io/desandro/pen/61964b61c10fcf86b569b446a3781ed3/

**Comment by stevepiron** [comment]
@desandro That means you can mix grid items that have a common divisor such as 20%, 40%, 60%, 80%, 100%... divisor is 10%.

For the OP, the common divisor for 1/2 grid items, 2/5 grid items and 3/5 grid items would be 1/10.

How can you mix grid items that are for example 1/3 and grid items that are 1/2 ? 🤔

**Comment by Goldenis** [comment]
@desandro gutter is not working on the above example.
Also, I wanna place 50%/50% blocks as well but with the above example, only 60%/40% is feasible.

```
.grid-sizer { width: 20%; }
.grid-item--width-40 {
  width: 40%;
}
.grid-item--width-50 {
  width: 50%;
}
.grid-item--width-60 {
  width: 60%;
}
```

**Comment by desandro** [comment]
> @desandro gutter is not working on the above example.

That's because a gutter is not enabled in that demo. See [fluid gutter demo](http://codepen.io/desandro/pen/BAJKn)

> 

Fo 60%/50%/40%, you'll need a divisor of all three: 10%.
