### ISSUE TITLE
destroy method is not working properly

### ISSUE THREAD

**Issue by FlorianBrinkmann** [desandro/masonry#956]
Hi!

I am trying to get the following working: The Masonry grid should only be active above a specific viewport width. If the viewport gets narrower that the specific width, the masonry instance should be destroyed.

But it seems that the `destroy()` method is not working. This is my code:

```javascript
(function () {
    var smallWindow;

    /**
     * Get the gallery grids.
     *
     * @type {Element}
     */
    var gridElem = document.querySelector(".gallery-grid");

    /**
     * Check if we have grid elements.
     */
    if (gridElem !== null) {
        /**
         * Function for creating and destroying the masonry grids.
         */
        function masonryGrid() {
            var w = Math.max(
                document.documentElement.clientWidth,
                window.innerWidth || 0
            );

            /**
             * Only init a grid if the window is greater or equal 730
             */
            if (w >= 730) {
                new Masonry(gridElem, {
                    itemSelector: ".gallery-grid-item",
                    columnWidth: 1,
                    gutter: 10,
                    transitionDuration: 0,
                    resize: true,
                    fitWidth: true
                });
                smallWindow = false;
            } else {
                if (smallWindow === false) {
                    var msnry = Masonry.data(gridElem);
                    msnry.destroy();
                }
                smallWindow = true;
            }
        }

        document.addEventListener("DOMContentLoaded", masonryGrid);
        window.addEventListener("resize", masonryGrid);
    }
})();
```

Here is a pen where you can see it in action: https://codepen.io/florianbrinkmann/pen/NjjbBq (sorry for including the library code in the JS field, but I do not get it working with external referencing it…)

The `position: absolute` gets removed on smaller viewports, but the script continues to set the grid wrapper width and height, et cetera.

Is it maybe a problem that I try to do it with vanilla JS? I have done this with Packery and jQuery on another site, and there it works like a charm. This is the code that does it there for me:

```javascript
(function ($) {
    var smallWindow;
    masonry = function(){
        var w = Math.max(document.documentElement.clientWidth, window.innerWidth || 0);
        if ( w <= 695 ) {
            $('#grid').packery('destroy');
            smallWindow = true;
        } else {
            if ( smallWindow == true || smallWindow == undefined ) {
                $('#grid').packery({
                    // options
                    columnWidth: 90,
                    itemSelector: 'article',
                    gutter: 20,
                    transitionDuration: 0
                });
            }
        }
    };

    masonry();

    $(window).resize(function(){
        masonry();
    });
})(jQuery);
```

But it would be cool if I could get it working without jQuery :)

Thanks in advance!

**Comment by desandro** [comment]
Thanks for reporting this issue. There looks to an issue with how you're saving state

``` js
if (w >= 730) {
  new Masonry(gridElem, {
    // ...
  });
}
```

This code reads *if true, initialize Masonry*. This initializes a new instance of Masonry every time the window is resized. You can resolve this by only handling one instance of Masonry at a time, by holding on to the `msnry` variable.  See demo https://codepen.io/desandro/pen/c7be06b460c5ed5eb9c06e8a56286830/

``` js
var msnry;

if (w >= 730 && !msnry) {
  msnry = new Masonry(gridElem, {
    itemSelector: ".gallery-grid-item",
    columnWidth: 1,
    gutter: 10,
    transitionDuration: 0,
    resize: true,
    fitWidth: true
  });
} else if (w < 730 && msnry ) {
  msnry.destroy();
  msnry = null;
}
```

**Comment by FlorianBrinkmann** [comment]
Great, thank you — that works perfectly, and the code looks better, too! :)

**Comment by ilonikso** [comment]
Maan, I try a bunch of methods, read a lot of posts, and finally you me. Thank you
