### ISSUE TITLE
add transition effect to masonry items

### ISSUE THREAD

**Issue by mosijava** [desandro/masonry#959]
Hi
you [can see here ](https://codepen.io/mosijava/pen/vmJEjX)that when I add a hover transition effect to my masonry Items, then they seems to reload twice!

but if I withdraw the transition effect it works great!

**Comment by mosijava** [comment]
I found out an event named "transitionend" cause this problem?
can you help me with this?

**Comment by desandro** [comment]
Masonry uses CSS transitions for updating layout. If your own CSS has transitions for `opacity`, `top/left` or `transform`, they could conflict with Masonry. One solution to use separate element for transition effects

``` js
<div class="masonry-item">
  <div class="hover-card">
```

See demo https://codepen.io/desandro/pen/f2843303281532ebecf86031d57fd63b/

**Comment by mosijava** [comment]
thank you sir
It now works great
