### ISSUE TITLE
Masonry don't work on IE9

### ISSUE THREAD

**Issue by resimovic** [desandro/masonry#960]
Hi, submiting issue 'coz even Your web page (with masonry) don't work on IE9. 
Test case: http://codepen.io/desandro/pen/osFxj is not supported by IE9 so this is only way.
I am in the middle of developing theme for wordpress everything work on chrome, FireFox, IE 11, IE 10, Edge but IE9 not.
Is there any solution for support IE9

**Comment by desandro** [comment]
[Masonry v4 does not support IE9](https://masonry.desandro.com/extras.html#browser-support). You can use [Masonry v3](https://masonry.desandro.com/v3)

**Comment by SgtOddball** [comment]
It's also worth noting that not even Microsoft support IE9/IE10 anymore (As of April 11th 2017). Might be time to move on.
