### ISSUE TITLE
Avoid the 1 col stack when using imagesLoaded ( slower connections )

### ISSUE THREAD

**Issue by MinumWeb** [desandro/masonry#961]
Hey there,

Absolutely love the plugin. I'm wondering if there is something I'm doing wrong. 
When I call in masonry like so..

`var $grid = $('.view--card-grid .view-content').masonry({`
`itemSelector: '.card',`
`percentPosition: true`
`});`
`// layout Isotope after each image loads`
`$grid.imagesLoaded().progress( function() {`
	`$grid.masonry();`
`});  `

It results in an unwanted 1 columns stacking event before it **JUMPS** into its masonry position. 
See below 

![example-grid](https://cloud.githubusercontent.com/assets/8870893/25882577/5a078a08-3598-11e7-9aba-253b4be0c137.jpg)

I'm just wondering if there is another method that I'm missing to avoid this effect on slower connections? 

Please excuse the lack of a test case, I didn't feel it would benefit this question.

**Comment by desandro** [comment]
Looks like you need to set columnWidth https://masonry.desandro.com/faq.html#the-first-item-breaks-the-grid

**Comment by MinumWeb** [comment]
Hi desandro!

Thank you for the quick response, unfortunately - I thought the problem was solved. 
But I resolved this issue by adding the css `float: left;` 

For safe measure I also added in the columnWidth!

However, throttled connection shows the below result. I've shown two different results.

![example2](https://cloud.githubusercontent.com/assets/8870893/25923026/b69f9a8e-362f-11e7-963d-1f2c53210fbf.jpg)
------------------------------------------------------------------------------------------------
![example1](https://cloud.githubusercontent.com/assets/8870893/25923028/b93d466a-362f-11e7-87c9-7d76b54aa78c.jpg)

Thank you again for your response - greatly appreciate it!

Cheers!

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues).
