### ISSUE TITLE
Appended children not updating layout

### ISSUE THREAD

**Issue by alexandervalencia** [desandro/masonry#962]
Hi,

First, thanks for creating such a useful tool, it really is quite amazing!

For the project I'm working on I am unable to use jQuery so I'm trying to do this in vanillajs. The issue I'm running into is that we plan to dynamically load images from our server and we need the layout to update when the pictures get loaded (~20 at a time). As a test case I included a codepen to show the issue.: 
The layout is not being updated when neither .appended() nor .layout() is called.

To simulate items being added dynamically you can click the "add 20 divs" button. To simulate a call to msnry.layout() you can click the "reset layout" button.

Adding one div at a time causes the divs to be inserted into the layout properly.

**Test case:** http://codepen.io/alexandervalencia/pen/qmoBMN

My feeling is that this is not really a "bug" but if there's a proper way to make it work please let me know.

**Comment by desandro** [comment]
Thanks for submitting this issue and providing a reduced test case. Sorry you ran into this snag.

Your demo almost works! Unfortunately, [the `appended` method](https://masonry.desandro.com/methods.html#appended) will not work with a just-appended document fragment. It requires the item elements themselves — either as a single element, array of elements, or jQuery object.

We can resolve the issue by changing `gridItems` to array of elements, and using that within `appended`.

``` js
gridItems = gridItems.map(
	function (item) {
		var gridItem = document.createElement('div');
		gridItem.className = 'grid-item blue';
		gridItem.innerHTML = item;

		fragment.appendChild(gridItem);
    return gridItem;
	}
);

document.querySelector('.grid').appendChild(fragment);

msnry.appended( gridItems );
```

See demo http://codepen.io/desandro/pen/5f064b93c7a82df45d1ebaa315336618/

**Comment by alexandervalencia** [comment]
Wow, thank you SO MUCH! You reminded me why the open source community is so awesome!

I was confused about how to append an array of elements without using jQuery and your explanation cleared that up. Again, really thankful for your quick comment!

**Comment by desandro** [comment]
Glad I could help! Please consider supporting my work by purchasing a license [for one of Metafizzy's commercial libraries](https://metafizzy.co)
