### ISSUE TITLE
Should I use Isotope or Masonry?

### ISSUE THREAD

**Issue by AbrahamHalil** [desandro/masonry#963]
Hi,

i want to use masonry for a personal Project. I need no filter like isotope. Do you think is "masonry.desandro.com" enough for this or is the "masonry system of isotope" better?

thanks
J

**Comment by desandro** [comment]
Hello! Thank you for this question.

If you do not need filtering or sorting, then I recommend you use Masonry. It's smaller and less complex than Isotope.
