### ISSUE TITLE
Embedded video causes overlap/gap issues

### ISSUE THREAD

**Issue by dashkevych** [desandro/masonry#964]
Hi,

Is there a way to fix overlap and gap issue when an embedded video is added to the item selector? Here is an example: https://cloudup.com/c3Es2Sp2odv

**Comment by dashkevych** [comment]
I've found a solution by using **setTimeout** method.
If somebody needs the solution:
`
var refreshGrid = function() {
  setTimeout( function() {
     grid.masonry( 'layout' );
  }, 1000 );
}

jQuery( window ).on( 'load resize', function() {
  refreshGrid();
});
`

I wonder if there is more elegant solution to fix it.

**Comment by desandro** [comment]
You'll need to trigger `layout` after the video has loaded. Is this HTML5 video? Try using the [`loadeddata` event](https://developer.mozilla.org/en-US/docs/Web/Events/loadeddata)

``` js
grid.on( 'load loadeddata', function() {
  grid.masonry('layout');
});
```

Do not trigger `layout` on window `resize`. Masonry already includes this behavior.
