### ISSUE TITLE
Masonry delay before trigger 

### ISSUE THREAD

**Issue by robbisy** [desandro/masonry#965]
Hi
 I've noticed that Masonry delays always before trigger. It doesn't last long just few seconds.
[codepen link](https://codepen.io/anon/pen/jwOwbo)

**Comment by desandro** [comment]
Thanks for submitting this issue. It's currently set up to wait until all images have been loaded before initializing Masonry.  You may want to try initializing Masonry first, then triggering `layout` as images load. See demo https://codepen.io/desandro/pen/066eab43b0121c7c724c334e0a532654/
