### ISSUE TITLE
Window is not defined error

### ISSUE THREAD

**Issue by pierinocipolloni** [desandro/masonry#966]
Having trouble initializing Masonry. I ran npm install masonry-layout --save. Added masonry = require('masonry-layout') in gulpfile (I am using Gulp). Get a "window is not defined" error. Thoughts?
Thank you!

**Comment by desandro** [comment]
Thanks for reporting this issue. Masonry was designed to work in a browser. What kind of environment are you trying to run Masonry in?

**Comment by pierinocipolloni** [comment]
Indeed, in a browser. It is a simple website really. I am using Gulp as a
build tool. In the gulpfile.js After the npm install, I am putting require
statement but it doesn't seem too happy about it.

**Comment by desandro** [comment]
> In the gulpfile.js After the npm install, I am putting require
statement but it doesn't seem too happy about it.

``` js
require('masonry-layout')
```

Requiring will work if you are using are module loader like Webpack or Browserify. These module loaders then produce output/build files that can be used in browsers. But `require('masonry-layout')` won't work if you're directly requiring it in `gulpfile.js`, because that's loading it a node environment, not a browser.

Most likely, you need to point to `masonry/masonry.js` in your Gulp JS task.

I'm kind of in the dark with how your build process works, but that's what I think the issue is.

**Comment by TeodorKolev** [comment]
Why this is closed? I am getting same error. React isomorphic rendering - webpack

**Comment by khalid-halo** [comment]
Getting the same error with server side rendering

**Comment by Feaman** [comment]
I fixed it by making 
`const Masonry = require('masonry-layout')
new Masonry(grid)`
after the component is loading, not in the top of file. In the place where you init Masonry object.

So, if you use Vue.js - make `require` in `mounted` method.

**Comment by mamadOuologuem** [comment]
A quick workaround in React can b

1. Declare a `useDynamicImport` hook to handle dynamic import 
```JS
export function useDynamicImport(importPromise) {
  const [imported, setImported] = useState({});

  useEffect(() => {
    let cancelled = false;
    const awaitImport = async () => {
      const result = await importPromise;
      if (!cancelled && result && Object.keys(imported).length === 0) {
        setImported(() => result);
      }
    };
    awaitImport();
    return () => {
      cancelled = true;
    };
  }, [importPromise, imported]);

  return imported;
}
```

2. Use it like that
```JS
import React, { useState, useEffect } from 'react';
import { useDynamicImport } from '#hooks/useDynamicImport';

const MasonryUI = () => {
  const IS_STATIC = typeof window === 'undefined';
  
  const { default: Masonry } = useDynamicImport(
    !IS_STATIC && import('masonry-layout'),
  );
  const [masonry, setMasonry] = useState(undefined);

  useEffect(() => {
    if (Masonry) {
      setMasonry(
        new Masonry('#grid', {
          itemSelector: '.grid-item',
          columnWidth: 200,
        }),
      );
    }
  }, [Masonry]);

  useEffect(() => {
    masonry?.layout();
  }, [masonry]);

  return (
    // Render your grid and grid-items
  );
};
```
