### ISSUE TITLE
Masonry: How to vertically align items?

### ISSUE THREAD

**Issue by viteresa** [desandro/masonry#967]
I am using Masonry to arrange items on a 4-column layout, however I would like to order/stack the items vertically and not horizontally... is it possible?

My (currently horizontaly-aligned items ) example: https://codepen.io/viteresa/pen/YQXoqW

thank you so much for any help!

**Comment by desandro** [comment]
Thank you for this question. Could you be looking for the [masonryHorizontal layout mode for Isotope](https://isotope.metafizzy.co/layout-modes/masonryhorizontal.html)?
