### ISSUE TITLE
Images Flying around the page...

### ISSUE THREAD

**Issue by bigthinkery** [desandro/masonry#968]
The first time my images load, they are flying around the page while they place. I have the preloader installed, but can't figure out how to fix this. Please help!

**Comment by NoahWilcox** [comment]
Hey @bigthinkery 
Would you happen to have an example you could show us?

**Comment by bigthinkery** [comment]
Thanks for the response! Sure: http://bt-staging.com/work

**Comment by desandro** [comment]
Thanks for that! It looks like you're using the [imagesLoaded progress behavior](https://masonry.desandro.com/layout.html#imagesloaded)

``` js
// init Masonry
var $grid = $('.grid').masonry({
  // options...
});
// layout Masonry after each image loads
$grid.imagesLoaded().progress( function() {
  $grid.masonry('layout');
});
```

So what's happening is that with each image that is loaded, Masonry has to position it again. That is what is causing the items to move around. 

There are several ways to address this. One way to resolve this is to  imagesLoaded after all images have loaded, instead of for each image.

``` js
var $grid = $('.grid').masonry({
  // options...
});
// layout Masonry after all images loaded
$grid.imagesLoaded( function() {
  $grid.masonry('layout');
});
```

**Comment by bigthinkery** [comment]
So I've added the code to the footer: 
`var $grid = $('.grid').masonry({
  // options...
});
// layout Masonry after all images loaded
$grid.imagesLoaded( function() {
  $grid.masonry('layout');
});`

And it's still responding the same way...what might I be doing wrong?

**Comment by desandro** [comment]
remove this:

``` html
        <script>
        var $grid = $('.grid').masonry({
          // options...
        });
        // layout Masonry after all images loaded
        $grid.imagesLoaded( function() {
          $grid.masonry('layout');
        });
		</script>
```

Change this code in `js/grid.js`

``` js

// init Masonry
var $grid = $('.grid').masonry({
  itemSelector: '.grid-item',
  percentPosition: true,
  columnWidth: '.grid-sizer'
});
// layout Isotope after each image loads
$grid.imagesLoaded().progress( function() {
  $grid.masonry();
});
```

to this:

``` js

// init Masonry
var $grid = $('.grid').masonry({
  itemSelector: '.grid-item',
  percentPosition: true,
  columnWidth: '.grid-sizer'
});
// layout Isotope after all images loaded
$grid.imagesLoaded( function() {
  $grid.masonry();
});
```

**Comment by bigthinkery** [comment]
That did the trick! Thank you!
