### ISSUE TITLE
Masonry not working properly in IE 11 again with Bootstrap 4

### ISSUE THREAD

**Issue by weilinzung** [desandro/masonry#969]
On IE the paddings and margins are removed.

`<div class="col-md-6 grid-item"></div>`

here is the screenshot: http://oi65.tinypic.com/10dzbr8.jpg

please give some helps, thanks!

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues). Try [forking the Bootstrap 3 demo](https://masonry.desandro.com/extras.html#bootstrap)

**Comment by weilinzung** [comment]
ok. I created a CodePen which is fine, so I do a debug for other elements. I found out it is one of my sidebar element use `bootstrap-select` cause issue.  I would see what I can do to fix that.

https://codepen.io/weilinzung/pen/gRwOaJ


thanks!

**Comment by weilinzung** [comment]
ok. Found it.

`$('.gallery').masonry({...});`  need to be initialized before ' $('.selectpicker').selectpicker({...});' which help me fix it.
