### ISSUE TITLE
Height problem but images with attr width and height

### ISSUE THREAD

**Issue by benoitwimart** [desandro/masonry#970]
Hi,

I have this issue on http://jenseign.com/html/hypertextmarkuplanguage/ressources/ first load on Firefox is not OK, second is OK. Any idea, srcset works with Masonry ? 

Sorry for the non-reduce, my code is based on this nice https://tympanus.net/codrops/2013/07/02/loading-effects-for-grid-items-with-css-animations/

**Comment by desandro** [comment]
Thanks for reporting this issue. Sorry, imagesLoaded does not work with srcset. See desandro/imagesloaded#175
