### ISSUE TITLE
Masonry: Are we able to increase the height of the div?

### ISSUE THREAD

**Issue by lg134** [desandro/masonry#974]
Hi Desandro, 

Thank you for the awesome apps!

Is there a way to increase the height of the Masonry div? At the moment it is being auto populated based on the photos received, but my pagination div's height is not included so  it is being populated on top of the photo div (.container div). I can't set the fixed height. Please see the printscreen attached. 

Thanks for your time :). 

[
![screen shot 2017-07-10 at 5 01 10 pm](https://user-images.githubusercontent.com/30041808/28010477-aa6d5756-6591-11e7-8b84-27c2d173e532.png)
](url)

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues).

**Comment by lg134** [comment]
Hi Desandro, 

Thank you for the reply. 
Mine is an Ajax filtering and pagination from a data source, so I don't know how to do the reduced test case :(.
