### ISSUE TITLE
Combining 4 column and 3 column grid

### ISSUE THREAD

**Issue by SamiAssasi** [desandro/masonry#977]
I've currently been testing this masonry images grid.

Currently the problem is that certain image widths don't align correctly and this leaves me with unnecessary empty space, as you can see here:

https://codepen.io/anon/pen/zdqXqN

As you can see the combo 25% + 75% width, and 50% width seem to be working perfectly, but for some reason I can't get the last row to work correctly (w33 & w66).

**Comment by desandro** [comment]
Hello! Thanks for reporting this issue. If you want to support 4-column 25% grids and 3 column 33.33% grids, then you'll have to use a common denominator: a 12-column 8.33% grid.

``` css
.grid-sizer {
  width: 8.33%
}
```

See demo https://codepen.io/desandro/pen/ae894985f80ce71694f8d245e657e51e/
