### ISSUE TITLE
Adding jquery masonry object breaks the grid

### ISSUE THREAD

**Issue by omarel1** [desandro/masonry#978]
The last image falls down on the next line and does not fill the empty space, but when I comment out the jquery masonry object, the image works properly.

I need the masonry object for the other options.

Anyone know what's happening here?

I have a codepen here to demonstrate:
https://codepen.io/omarel/pen/GvqZqR

hide the JS masonry object and you will see that the last item fits the grid.

without masonry
<img width="1386" alt="01" src="https://user-images.githubusercontent.com/6363878/28881706-01003524-7777-11e7-87e8-a9bb2b9ca729.png">

with masonry
<img width="1373" alt="02" src="https://user-images.githubusercontent.com/6363878/28881711-06a3499e-7777-11e7-8d21-13d36e8b4ba7.png">

**Comment by desandro** [comment]
[Looks like you need to add `columnWidth` ](https://masonry.desandro.com/faq.html#the-first-item-breaks-the-grid)

> You most likely need to set the columnWidth option. Without columnWidth set, Masonry will use the width of the first item for the size of its columns.

See demo https://codepen.io/desandro/pen/9f4323a3f545c3f2aae5d9ddc83dab55/

**Comment by omarel1** [comment]
But the docs say that sizing should be done with your CSS styling. I dont want to hard code size values because each photo may have a different size.

"All sizing of items is handled by your CSS."

Also, in your demo it doesnt look to fill in the space either?
