### ISSUE TITLE
Problem with new added items - not in masonry style

### ISSUE THREAD

**Issue by plusPlus91** [desandro/masonry#979]
Hello,

I've created a simple test file with the following code and everything is working very fine. But in another case I have a problem with new appended items. It is no new page-site which must be loaded, the items will be added by javascript if I click a "view more button". These new added items are not updated with the style-parameters (position, left, top). Do you have a idea what I must do to update the new added items? I'm a programmer newbie, already read the documentation. Thank you

$(document).ready(function() {
	var $grid = $('.masonry').masonry({
	  itemSelector: 'none',
	  columnWidth: '.grid-sizer',
	  gutter: '.gutter-sizer',
	  percentPosition: true,
	});

	var msnry = $grid.data('masonry');

	$grid.imagesLoaded( function() {
	  $grid.removeClass('unloaded');
	  $grid.masonry( 'option', { itemSelector: '.custom-list-item' });
	  var $items = $grid.find('.custom-list-item');
	  $grid.masonry( 'appended', $items );
	});
});

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues).
