### ISSUE TITLE
Bad examples

### ISSUE THREAD

**Issue by TeodorKolev** [desandro/masonry#980]
Really bad examples. 
When we have this:

```
<div class="grid" data-masonry='{ "itemSelector": ".grid-item", "columnWidth": 200 }'>
  <div class="grid-item"></div>
  <div class="grid-item"></div>
</div>
```
Why do we need this:
```
var msnry = new Masonry( '.grid', {
  // options...
});
```
Why these both are in same block. It misleading user:
```
// vanilla JS
// init with element
var grid = document.querySelector('.grid');
var msnry = new Masonry( grid, {
  // options...
  itemSelector: '.grid-item',
  columnWidth: 200
});

// init with selector
var msnry = new Masonry( '.grid', {
  // options...
});
```
What is the html needed for this:
```
var msnry = new Masonry( '.grid', {
  // options...
});
```
???

**Comment by dashengz** [comment]
The guide is trying to say that there are three **ways** to initialize the grid layout. You are not supposed to use them all together. You can choose any one of the three options.

The html would look similar to this:
```
<div class="grid">
  <div class="grid-item"></div>
  <div class="grid-item"></div>
  ...
</div>
```

They also have a [website](https://masonry.desandro.com/layout.html) that documents the usage in more details.
