### ISSUE TITLE
React compatability

### ISSUE THREAD

**Issue by TeodorKolev** [desandro/masonry#981]
I am using react with isomorphic rendering.
```
 {
        test: /masonry-layout/,
        loader: 'imports?define=>false&this=>window',
      }
```
`npm install masonry-layout --save`
```
 render() {
    const Masonry = require('masonry-layout');
    return (
          <div className="grid" data-masonry='{ "itemSelector": ".grid-item", "columnWidth": 200 }'></div>
    );
  }
```
When I load component all views are messed up. If I change resolution to mobile and back again. It is fixed. No errors in console. Is there any remedy for this one?

**Comment by desandro** [comment]
I recommend you try [react-masonry-component](https://github.com/eiriklv/react-masonry-component)
