### ISSUE TITLE
Responsive handling

### ISSUE THREAD

**Issue by TeodorKolev** [desandro/masonry#982]
Is there a way to set percents for items width for different resolutions instead of static pixels? If it is please provide some example or guides, because this is very important. Thank you

**Comment by desandro** [comment]
Yes! Use [element sizing](https://masonry.desandro.com/options.html#element-sizing) for [columnWidth](https://masonry.desandro.com/options.html#columnwidth)

See demo https://codepen.io/desandro/pen/JFpeg
