### ISSUE TITLE
Any way to keep all items on a single screen without scrolling?

### ISSUE THREAD

**Issue by kmgsoftware** [desandro/masonry#983]
We're using masonry for a page that will be displayed on an iPad kiosk. The photos should auto-arrange (which masonry is great at), but I'd also like to be able to control the height so no matter how many photos are in the grid, there will never be a scroll bar (i.e. all the images must fit one one screen, and must automatically become smaller to accommodate this)

Does anyone have any ideas for how this could be accomplished?

**Comment by desandro** [comment]
Hello! Thanks for reporting this issue. Sorry, Masonry does not work with a set height. Masonry sets height with its layout algorithm. You may want to look at CSS Grid, which may be able to pull off this solution.
