### ISSUE TITLE
Using Masonry and need support with panels expanding and collapsing

### ISSUE THREAD

**Issue by batfink76** [desandro/masonry#984]
Hi I am attempting to build a web page which will utilise the masonry.js.

However, each of my blocks will have a container of hidden content which will display when the user clicks on a expand arrow. The content will then collapse when the user clicks on the switched expand arrow.

I have created a full example of the issue here - https://tinyurl.com/ya4uktxz

What I would like this to be doing is when the panel is expanded it does not run behind the panel below, but pushed the panel below down. So it retains its height and visibility.

Sorry to ask, but I cannot figure this out.

**Test case:** http://codepen.io/desandro/pen/osFxj

**Comment by desandro** [comment]
Hello! Thanks for reporting this issue. 

> What I would like this to be doing is when the panel is expanded it does not run behind the panel below, but pushed the panel below down. So it retains its height and visibility.

Masonry does not support this behavior. But Packery does. Use [shiftLayout](https://packery.metafizzy.co/methods.html#shiftlayout) to layout items so that they maintain horizontal position but change vertical position.

**Comment by batfink76** [comment]
thanks. I did in fact figure it out a different way which used an accompanying script to control the expand / collapse which also ensured to reload masonry and take into account the expanded cell. Worked out fine with the use of Packery.

Thanks for responding though.
