### ISSUE TITLE
Layout not right until i resize the window #694

### ISSUE THREAD

**Issue by Cedcomps** [desandro/masonry#985]
Hi, I have an issue with this plugin when i load a new page, (I use Materialize css) I have to resize the window until masonry manage to work. But if I don't resize the windows I got this => Posts stack on top of each other
![test1](https://user-images.githubusercontent.com/19873078/29518773-fdbad5fa-867a-11e7-97ff-519c495f710d.jpg)
And when I resize it's work
![test2](https://user-images.githubusercontent.com/19873078/29518782-09127930-867b-11e7-9f24-b612736118f7.jpg)

I tried to have a look at #694 with css `html { overflow-y: scroll; }` but nothing change

**Comment by desandro** [comment]
Are you using [imagesLoaded](https://masonry.desandro.com/layout.html#imagesloaded) ?

I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues).

**Comment by Cedcomps** [comment]
Oh I haven't thought of using imagesLoaded. And I tried with and it's work perfectly! 
Thanks for your support, it's an awesome plugin.
