### ISSUE TITLE
Problem with the gutter and columnWidth

### ISSUE THREAD

**Issue by QuentinSalais** [desandro/masonry#986]
Hi,

I don't really understand what to make with this two options. I need a gutter of 26 px but I totally randomize the columnWidth, I've tried with different numbers but I can't get the result I want.

I have 4 different sizes for my images that are in the masonry container. Those 4 different sizes are made to be completely perfect to match with the gutters (26px) and do this result : 

![result](https://user-images.githubusercontent.com/17829266/29615658-04a15bf6-880f-11e7-9f8b-a0ef7938c0cb.png)

Unfortunately it doesn't work and after a bit of changing the options I've got what you can see in the fork I'm linking below.
The gutters doesn't correspond at all, it's not 26px everywhere and it does not fill the container as it should.

Here's the fork on github who match the website I currently am working on : 
[https://codepen.io/MrCyrdan/pen/yoEoLz](https://codepen.io/MrCyrdan/pen/yoEoLz)

I'm working with bootstrap on my website, and the masonry grid is in a ul which is working with the plugin "Slick" (So the result is a slider of masonry grid of images).

My problem is I can't get the masonry to work properly as it seems the gutter option doesn't work like it should. And in the meantime I don't know what number I should write for ColumnWidth. The result should put all my block aligned at the right and at the left of the container.

I hope you can help me, I have run out of ideas... :/

Thanks in advance,
Quentin.

**Comment by desandro** [comment]
> I need a gutter of 26

Okay! so you can set `gutter: 26`. you do not need to use element sizing because the value is not dynamic or proportional.

Looks like your smallest items are `170px`, so that will be `columnWidth`. Your grid would then be

```
1 column  = 170*1 + 26*0 = 170
2 columns = 170*2 + 26*1 = 366
3 columns = 170*3 + 26*2 = 562
4 columns = 170*4 + 26*3 = 758
5 columns = 170*5 + 26*4 = 954
```

See demo https://codepen.io/desandro/pen/3d1fac81ee3f6c4315f6b177c20b04c6/

**Comment by QuentinSalais** [comment]
Okay so I totally messed up the width of the container, it was 945px not 954px but it's okay, thanks to your calculations I managed to succeed !

Thanks a lot for your help !!
I am used to Slick but thanks for the link, I'll try it some time :)
