### ISSUE TITLE
Cannot read property apply

### ISSUE THREAD

**Issue by jbonpland** [desandro/masonry#987]
Hi All, i'm getting the following error and masonry is not working, it just displays the first photo in full size:

jquery.masonry.min.js:10 Uncaught TypeError: Cannot read property 'apply' of undefined
    at jquery.masonry.min.js:10
(anonymous) @ jquery.masonry.min.js:10
setTimeout (async)
handler @ jquery.masonry.min.js:10
dispatch @ jquery.min.js:3
r.handle @ jquery.min.js:3

Cheers!

**Comment by desandro** [comment]
`jquery.masonry.min.js` is an old version of Masonry. Have you looked at [updating to the latest v4](http://masonry.desandro.com)?
