### ISSUE TITLE
Hole in this masonry

### ISSUE THREAD

**Issue by jpyrat** [desandro/masonry#989]
Hi,

As you can see on this test case that should produce 4 columns masonry with no hole inside (because there is enough 1 column items to fill them), there is a gap between the first 2 items and the third.

![image](https://user-images.githubusercontent.com/763100/29881619-641e7ffe-8dab-11e7-8f50-e216254e7ae2.png)

**Test case:** https://codepen.io/jpyrat/pen/vJvERr forked from https://codepen.io/desandro/pen/BAJKn

**Comment by jpyrat** [comment]
Someone with the same problem : https://stackoverflow.com/questions/25913154/masonry-leaving-empty-gap
His solution : switch to Packery.

**Comment by jpyrat** [comment]
Duplicate with #866

**Comment by jpyrat** [comment]
And #228

**Comment by desandro** [comment]
Hello! Yes, gaps like this can happen with Masonry's layout algorithm. But [Packery was specifically designed](https://packery.metafizzy.co) to fill these kind of gaps. Use Packery.
