### ISSUE TITLE
Maintain horizontal gutters

### ISSUE THREAD

**Issue by CHEWX** [desandro/masonry#990]
Hi,

I've looked through the options, but I cannot see what I am looking for.

All the examples look to maintain perfect vertical lines, but is it possible to maintain perfect horizontal lines?

Thanks

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues).

**Comment by CHEWX** [comment]
Hi @desandro ,

I'm not having an issue, I am just seeing whether it's possible.

All your demos show vertical lines, but none match horizontally.

I'm thinking that you wouldn't do the layout I am thinking about in Masonry.

Thanks,
Tom

**Comment by desandro** [comment]
If you're using set pixel sizes, then yes its possible. Otherwise, if you're using percent sizes for gutter, no Masonry does not support it. However, [Packery](https://packery.metafizzy.co/options.html#gutter) does, as it uses the same size its vertical and horizontal gutter.
