### ISSUE TITLE
How to tie Masonry and List.js?

### ISSUE THREAD

**Issue by evstun** [desandro/masonry#991]
Good day! First, I would like to thank you for your work, for your code! Your code is a miracle, thank you!

I had a small problem and I'm asking for your help. I initially used [List.js](http://listjs.com/) to search on the page, made it to div and it works great. Now I am using your code [Masonry](https://masonry.desandro.com/) and I really like how the blocks line up when you resize the browser window. But I encountered the following problem is how to combine work [List.js](http://listjs.com/) and your miracle code [Masonry](https://masonry.desandro.com/). Now when I start to search for unnecessary div are hidden, and those that I'm looking for with the help of the search box remain but do not rise to the top of the list, they freeze at the bottom of the list and sometimes not visible! Help to make so that when you hide don't need the div, you need climbed to the top of the list, and not remain in its place?!

I will be very grateful and will buy you a Cup of strong coffee!

**Comment by desandro** [comment]
Hello! Thanks for opening this issue. List.js and Masonry look to be in conflict with one another. They both layout items. I don't think you can use them together. If you are interested in filtering a list of items with Masonry layout, I recommend looking at [Isotope](https://isotope.metafizzy.co) with a [quicksearch behavior](https://codepen.io/desandro/pen/wfaGu).

**Comment by evstun** [comment]
Thank you! That's what I needed! You saved me!

**Comment by evstun** [comment]
Good day! And you can combine filter and search at the same time? What you could first filter, and then to use search?

I did, but maybe something is not right! If I press the sort button and then use the search field, nothing happens. Refreshes the page, use the search and the search works!

Conversely, if I first use the search box, and then click the sort button, the sorting comes from just the content and not the filtered search!

Tell me, is there any way to fix it?

sincerely, Alexander

**Comment by desandro** [comment]
See [Search & filter buttons demo](https://codepen.io/desandro/pen/mCdbD)
