### ISSUE TITLE
Firefox: images overlapping.

### ISSUE THREAD

**Issue by kimaldis** [desandro/masonry#993]
I am using imagesLoaded but I'm still having a problem with overlapping images. It seems to be specific to Firefox; I've tested on Chrome & OS X Safari without trouble. A refresh seems to fix it and once refreshed the issue won't repeat. I can reproduce consistently by opening the page in a new private window.

An example can be found at https://www.kim-aldis.co.uk/kids-shoot-1/

Anything you can suggest would be appreciated. Thanks.

``` javascript
( function($) {

     $(document).ready(function() {

	     var $container = $('.grid').first();
		
	     $container.imagesLoaded( function() {

		     $container.masonry({

			     // set itemSelector so .grid-sizer is not used in layout
			     itemSelector: '.grid-item',
			     // use element for option
			     columnWidth: '.grid-sizer',
			     percentPosition: true,
			     gutter: '.gutter-sizer'

		     })
	     });
     });

})(jQuery )
```

**Comment by desandro** [comment]
Thanks for reporting this issue. Have you looked at using progress 

``` js
// init masonry
$container.masonry({...})

$container.imagesLoaded().progress( function() {
  $container.masonry();
});
```

triggering Masonry first, then again after all imagesLoaded?

``` js
// init masonry
$container.masonry({...})

$container.imagesLoaded( function() {
  $container.masonry();
});
```

**Comment by kimaldis** [comment]
I've just tried it, it didn't help. Do I have this correct?:

``` javascript

(function($) {

    $(document).ready(function() {

        var $container = $('.grid').first();

        $container.masonry({

            // set itemSelector so .grid-sizer is not used in layout
            itemSelector: '.grid-item',
            // use element for option
            columnWidth: '.grid-sizer',
            percentPosition: true,
            gutter: '.gutter-sizer'

        })

        $container.imagesLoaded(function() {
            $container.masonry();
        });

    });


})(jQuery)
```

**Comment by desandro** [comment]
Your code looks okay. I would check with `console.log` if imagesLoaded is triggering when you expect. FWIW I was able to see overlapping images on the initial load with Chrome as well.

**Comment by kimaldis** [comment]
Just occured to me, I'm not using <img src="">, I'm using <input type='image' ... > in a form, for some reason I can't remember for now. You think maybe that could be the problem?

**Comment by kimaldis** [comment]
I __think__ I've sovled this by using `$(window).on("load", function() {}` instead of `$(document).ready(function() {}` I can't, offhand, think of a bullet-proof way to test this but so far it seems to be working.

**Comment by baidoct** [comment]
Had the same problem, the `$(window).on("load", function() { << your masonry load code >> }` did the trick. Thank you!

**Comment by desandro** [comment]
I recommend trigging `layout` again after on window load, rather than initializing.

``` js
var $grid = $('.grid').masonry({
  // options
});
// layout on imagesLoaded
$grid.imagesLoaded( function() {
  $grid.masonry();
});
// layout after everything loaded
$(window).on( 'load', function() {
  $grid.masonry();
});

``` 

[`$(window).load` is a last resort](https://metafizzy.co/blog/window-load-last-resort/).
