### ISSUE TITLE
Init masonry after ajax call

### ISSUE THREAD

**Issue by MathieuJJ** [desandro/masonry#997]
Hi,

Thank you for your great plugin!

I need to use it in Magento 2 and I have an issue when I want to init the plugin after ajax call. When I init the plugin without ajax call it works perfectly.

Please find below my code:

```
require([
	"require",
    "jquery",
	"imagesloaded",
	"masonry"
], function(require, $, Masonry) {
	 
	$('.team-social-wall-content .loader').fadeIn("fast");
	
	var masonryOptions = {
	 	itemSelector: '.social-wall-item',
		horizontalOrder: true,
		columnWidth:'.social-wall-grid-sizer',
		percentPosition: true,
		gutter: 10
	};

	$.ajax({
			type: 'post',
			url: '/team/index/socialmediaajax',
			data: {
				f: "getSocialMediaWall",
				ti : $('.team-detail').data('team-id')
			},
			dataType: 'json'
			
		}).done(function (data) {
			
			$('.julboteam-social-wall-content .loader').fadeOut("fast");
			
			if(data.success){
				var html = $(data.results);
				$('.social-wall-row').html(html).promise().done(function(){
				
					$('.team-social-wall-content').imagesLoaded( function() {
						require( [ 'jquery-bridget/jquery-bridget' ],
							function( jQueryBridget ) {
								jQueryBridget( 'masonry', Masonry, $ );
								$('.social-wall-row').masonry(masonryOptions);
							}
						);	
					});
				});
			}
		});
});
```

The value of "data.results" is html content.

There is not any error but it looks like the plugin is not initialized because there is not any masonry custom css attributes added in the DOM.

Is someone has an idea about this issue ?

Thank you,
Mathieu

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues).

**Comment by MathieuJJ** [comment]
I had read the contributing guidelines before to post my issue but I do not know how to simulate the ajax call on codepen.
