### ISSUE TITLE
tiles overlap vertically when you resize the window

### ISSUE THREAD

**Issue by JunctionDesign** [desandro/masonry#998]
hey just having an issue i can't seem to solve, everytime i resize the window my tiles sometimes leave gaps between each other or tiles just disappear or they overlap on top of each other vertically. everything is fine when you initially load the browser, its just when playing with the window size manually i see these issues. and sometimes gaps appear between tiles as well.

thanks a lot for your help!!

**Test case:** https://codepen.io/ajmcmorris/pen/KXmRZL

**Comment by desandro** [comment]
Thanks for providing a demo! Looks like the transition on the grid and items is throwing off the layout.  See demo

https://codepen.io/desandro/pen/3474de50a2106e693d139e43b982bca3/

Any remaining gaps are caused by the h2 margin. You can fix that with your CSS.

**Comment by JunctionDesign** [comment]
Thanks for your help
